### ISSUE TITLE
Audio streaming on Android

### ISSUE THREAD

**Issue by yasirrose** [feross/simple-peer#103]
Hi,

I have implemented SimplePeerJs with pusher in electron app and now i'm working on phonegap app. On desktop app audio video streaming is functioning properly. But on android Audio/Video streaming is not working . Connection established properly and local+remote blob files added to audio tag as well. there seems be no issue while debugging but audio stream is not working somehow. 

Can you please tell me is there any other way to implement stream indifferent way for mobile ?? 

Thanks,

**Comment by feross** [comment]
Nothing needs to be different on mobile. This is probably due to a bug in the PhoneGap library you're using.
