### ISSUE TITLE
peer.on('stream', function(stream) is calling two times.

### ISSUE THREAD

**Issue by techleadz333** [feross/simple-peer#106]
Hi, I am new in this field and i have developed an audio video calling functionality .
Mozilla console gave me this warning
onaddstream is deprecated! Use peerConnection.ontrack instead
i was using simplepeer.js but after this warning i tried simplepeer.min.js .Now the warning is not displaying but my video is showing me two times(means two screens) have been showing and the event 
peer.on('stream', function(stream) is calling two times.I have put console.log('testing') in this function and it is showing two times.Any idea why this is happening??

![screenshot_1](https://cloud.githubusercontent.com/assets/22686142/20678584/180e6cac-b5b9-11e6-8421-bde9d1c4ba08.png)

**Comment by feross** [comment]
This could be caused by any number of things. Without seeing your complete code, there's no way to know.
