### ISSUE TITLE
 navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by techleadz333** [feross/simple-peer#107]
Mozilla firefox console is giving me the following warning
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia
I have changed the code like 

```
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia ||navigator.mozGetUserMedia; 

  navigator.getUserMedia(
    {
      audio: true,
      video:true
    },
changed the above code to

navigator.mediaDevices.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia ||navigator.mozGetUserMedia||navigator.mediaDevices.getUserMedia; 

  navigator.mediaDevices.getUserMedia(
    {
      audio: true,
      video:true
    },


```
but it is showing more errors.
I have tried so many things but still no success.
Kindly help me.

**Comment by feross** [comment]
Sorry, this is not a support forum. This library does not implement `getUserMedia`. Consider using StackOverflow for questions like this in the future.
