### ISSUE TITLE
can't stream when initiator = false

### ISSUE THREAD

**Issue by Flamenco** [feross/simple-peer#112]
When a peer is set to {initiator:false, stream:myServerStream}, the stream is never triggered on the connecting peer with config {initiator:true}.

However, when the connecting peer also provides a stream {initiator:true, stream:myClientStream} it works as expected.

Data connections work in both cases.

**Comment by feross** [comment]
This is a bug in Chrome. See this duplicate issue: https://github.com/feross/simple-peer/issues/95

**Comment by Flamenco** [comment]
I am not using chrome.  I am using wrtc in node and onAddSteam is getting called BTW

Also, I don't want the initiator firing signals first.

Please consider reopening.

**Comment by feross** [comment]
`wrtc` in node is based on the same codebase that Chrome uses, from https://webrtc.org/ This is a webrtc.org issue, as far as I can tell. If you have a PR that fixes this issue for you, I'm happy to accept it.

**Comment by RationalCoding** [comment]
@Flamenco You do not need to change your signalling order. Just specify the constraints option.

**Comment by Flamenco** [comment]
@RationalCoding 
> constraints - custom webrtc video/voice constraints (used by RTCPeerConnection constructor)

What specific constraints parameters you are referring to?

**Comment by RationalCoding** [comment]
@Flamenco 

The initiator should offer to receive:

```javascript
new SimplePeer({
    initiator: true, 
    offerConstraints: { 
        mandatory: { 
            OfferToReceiveAudio: true, 
            OfferToReceiveVideo: true 
        } 
    }
})
```
The non-initiator should not offer to receive:

```javascript
new SimplePeer({
    initiator: false, 
    stream:myServerStream
    answerConstraints: { 
        mandatory: { 
            OfferToReceiveAudio: false, 
            OfferToReceiveVideo: false 
        } 
    }
})
```
