### ISSUE TITLE
Dynamic switching of streams

### ISSUE THREAD

**Issue by matikbird** [feross/simple-peer#114]
I have my phone, right in front of me, streaming every move I make.

I have two cameras in my phone, one in the front, one in the back.
Would it be possible to change which camera can stream without refreshing the page (using `mediaDevices.enumerateDevices` to get a list of cameras and then provide a way to change the stream)

Is this possible?
Thanks!

**Comment by feross** [comment]
Yeah, it's possible to do this with WebRTC. We may need to make API changes to `simple-peer` to make this easier to do. Ideas welcome for how to do this!

**Comment by matikbird** [comment]
But don't close it!
It's still unsolved :(

**Comment by feross** [comment]
I'm not so sure this is the job of `simple-peer`. I suggest creating a new simple-peer object with the back camera when the user switches to it in your app.

**Comment by matikbird** [comment]
According to @jeremija 

> jeremija commented on 7 Dec 2016
IIRC firefox mobile lets you choose which camera to use. You'd need to use mediaDevices.enumerateDevices to get a list of cameras and then provide a way to change the stream. The library that's used for establishing the peer connection did not support dynamic switching of streams, meaning the user would have to reconnect (or refresh the page). I don't currently have the time to implement that but you're welcome to implement it and create a pull request. Check the CONTRIBUTING.md file if you're interested.

would be nice if simple-peer supports dynamic switch of streams to not refesh the whole app/web

**Comment by feross** [comment]
Refreshing the whole app is not necessary. As I said in my last comment, you can just create a new simple-peer object.

**Comment by salwa1234** [comment]
@feross  that means we have to initiate a new call every time when we need to toggle camera and what if we want to do an audio call first and then a video track to it ? i will also be a similar process as of toggling 
the camera ?

**Comment by jeremija** [comment]
@salwa1234 you should be able to use the `replaceTrack` function for this.

**Comment by salwa1234** [comment]
@jeremija i have tried all these, it didn't work. the problem is i am developing a group video chat and i want to toggle the camera on android or ios but nothing works. can you help me out in this ?

**Comment by salwa1234** [comment]
const handleCameraSwitch = (e) => {
    e.stopPropagation();
    console.log('camera');

    navigator
      .mediaDevices
      .getUserMedia({
        video: {
          width: { exact: 640 },
          height: { exact: 400 },
          facingMode: {
            exact: 'environment'
          }
        },
        audio: true
      })
      .then(stream => {
        toast.success('yeeeeeeee');

        peersRef.current.forEach((peer) => {
          if (peer) {
            peer
              .peer
              .replaceTrack &&
              peer
                .peer
                .replaceTrack(
                  peer.peer.streams[0].getVideoTracks()[0],
                  stream.getVideoTracks()[0],
                  peer.peer.streams[0]
                )

            // console.log(localVideo.current.srcObject.getVideoTracks()[0].getConstraints())
          }
        });
      }).catch(err => {
        toast.error(err)
      });
  }

@jeremija i have written this code for toggling the camera and i have noticed that the navigator do not fire on any android or ios phone but on a laptop or computer it does, i do not know where is the problem,
 according to me this piece of code is fine but it only works on laptop browsers

**Comment by jeremija** [comment]
@salwa1234 the promise will fail without any prompt when the browser has not been given permissions to access the camera and microphone.

Also, requesting camera access should be done in response to user actions (i.e. in a click event handler), otherwise it might also fail.

The errors that the browser API returns are usually quite descriptive.

**Comment by jeremija** [comment]
Also, I'd recommend you not to use the `exact` constraints since the `getUserMedia` promise will fail if the exact resolution cannot be provided.

**Comment by salwa1234** [comment]
@jeremija thanks, the code that i have written is inside and event handler as you can see the name (i.e handleCameraSwicth)
the problem is the navigator part of the code is not executing on android chrome browser even its not rejecting or resolving the promise the mobile (android ) browser is completely ignoring that part of the code like a comment :D event when i omit the facingMode constraint

**Comment by salwa1234** [comment]
and secondly i have already used navigator when user jumps inside the video call component it gets executed first but it is not working second time on camera switch handler

**Comment by jeremija** [comment]
If it works the first time, perhaps you need to stop the existing audio/video tracks before requesting new ones. I'm not 100% about this, but I can't reproduce this issue using Chrome or Firefox for Android on peercalls.com, which uses `simple-peer` under the hood and supports dynamic track switching.

**Comment by salwa1234** [comment]
@jeremija thanks for your help i have just stopped video and audio tracks of previous stream before executing navigator   and it worked 
localVideo.current.srcObject.getTracks().forEach(track => track.stop())

**Comment by salwa1234** [comment]
hi @feross @jeremija ,
Is there any way to listen if peer is connecting if we have a poor internet connection
currently if i close my internet connection all the peers closes without even try to reconnect 
i have tested this by toggling my wifi but once an internet connection goes down peer destroys 
and one thing more, peers are not connecting when i try to call from one mobile device to an other but from laptop to mobile or mobile to laptop it works fine (any idea what is going wrong here)

**Comment by salwa1234** [comment]
@jeremija , @feross 
i have noticed that peers are connecting only when both are on the same network 
how would i able to connect them when they are on different networks ?

**Comment by jeremija** [comment]
If you'd like to reuse existing connections, you'd need to wait for ICE restarts to be supported by `simple-peer`, see #579.

To add support for different networks, you need to add a STUN or a TURN server. See the `config.iceServers` parameter: https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration/iceServers
