### ISSUE TITLE
Mozilla deprecated "moz" prefix

### ISSUE THREAD

**Issue by DCtheTall** [feross/simple-peer#115]
Simple Peer causes client-side JavaScript to show the following warning:

WebRTC interfaces with the “moz” prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.

**Comment by feross** [comment]
Update your `simple-peer` or `get-browser-rtc` dependency. This was fixed a year ago: https://github.com/substack/get-browser-rtc/commit/6fd8d44233cd75f6e5fd0c31e37ba4e9e5a3501c
