### ISSUE TITLE
Support react-native-webrtc getStats

### ISSUE THREAD

**Issue by bkonkle** [feross/simple-peer#116]
In the `getStats` call, here:

https://github.com/feross/simple-peer/blob/master/index.js#L413-L438

In React Native using `react-native-webrtc`, the logic falls back to the Chrome implementation with the first two arguments inverted (#lolchrome) rather than following the standard method signature. `react-native-webrtc` is a good citizen and implemented it the [right way](https://github.com/oney/react-native-webrtc/blob/master/RTCPeerConnection.js#L158), but since the logic falls back to the Chrome block it doesn't work (and consequently 'connect' is never emitted).

Since Chrome is the known non-standard API here, I think a better approach would be to look for a Chrome-specific marker and then fall back to the standard signature that Mozilla uses.

I'll prepare a pull request, but I'd love any initial feedback you have in the meantime. 😄 

Thanks!

**Comment by bkonkle** [comment]
caniuse.com says Chrome still uses the `webkit` prefix, so I'll do a quick fork inverting the logic and looking for webkitRTCPeerConnection.

**Comment by feross** [comment]
I did what you suggested and we fallback to the standard behavior now. However, to fix a warning in Firefox, I changed that same standard behavior to use the promise-based version of `getStats`, since the callback version has been deprecated. So I'm guessing this won't work for you now.

**Comment by feross** [comment]
Okay, third times the charm. Published a version that falls back to the callback version for `react-native-webrtc`.

6.1.3.
