### ISSUE TITLE
Default STUN server not available

### ISSUE THREAD

**Issue by ekr** [feross/simple-peer#120]
index.js specifies the following default STUN server, which was formerly operated by Mozilla
```stun:23.21.150.121```. 

However, Mozilla has disabled this server.

A potential alternative is: ```stun.l.google.com:19302```, though I don't know if Google is OK with people using that one. @juberti?

**Comment by ekr** [comment]
You are definitely going to want to do something here because having a broken default causes serious connectivity issues for most users.

**Comment by feross** [comment]
@ekr Thanks for the tip, updated and released as v6.1.5. I've seen it written somewhere that Google doesn't mind if people use their STUN server, but a confirmation from @juberti or @samdutton would be great 🙏 ☺️

**Comment by feross** [comment]
@ekr When did Mozilla shut down their STUN server? Was this documented anywhere?

**Comment by ekr** [comment]
December. Not sure if it was announced.
