### ISSUE TITLE
Can't connect from host A to host B. Connection from B to A works fine.

### ISSUE THREAD

**Issue by vkulov** [feross/simple-peer#124]
Hello,

I'm using SimplePeer and ICE servers to negotiate a connection between 2 peers. We have a weird issue where it works in one direction but doesn't work in the other direction. We get an error "Error: Ice connection failed."

So connecting from A to B succeeds. 
But connecting from B to A ends up with an error - Error: Ice connection failed.

We are using 
```
trickle: true,
config: {
   iceServers: iceServers
}
```

Can you help us?

Also when using ice servers is it needed to initialize SimplePeer with the iceServers config option on both sides. We are initializing SimplePeer with the iceServers config option on the server-side. Do we need to do the same on the reciever side?

Whet I mean is that on the server we are using:
```
        var peer = new SimplePeer({
            initiator: true,
            stream: stream,
            trickle: true,
            config: {
                iceServers: iceServers
            }});
```

but on the receiver side we are simply using
`        var peer = new SimplePeer();
`

**Comment by feross** [comment]
Yes, it is necessary to specify the `iceServers` on both sides to maximize the likelihood of the connection succeeding. The iceServers option allow the peer to discover more possible routes to the remote peer. I bet this solves your connectivity problem.
