### ISSUE TITLE
Stream buffer full?

### ISSUE THREAD

**Issue by SourceBoy** [feross/simple-peer#130]
I'm observing a weird behavior under Node 6.9.4:

```
const peer1 = new SimplePeer(/* configured */)

peer1.on('connect', () => {
  const stream = fs.createReadStream('Some large file (1GB would do)')
  //stream.pipe(peer1) // Only sends about 3 to 4MB of file
  stream.on('data', (chunk) => {
    peer1.write(chunk) // Returns false after about 3MB
    // Adding if false stream.pause() and stream.resume() on peer1.on('drain') doesn't work either
  })
})
```

```
const peer2 = new SimplePeer(/* configured */)
let size = 0

peer2.on('data', (chunk) => {
  // Only receives about 2 to 3MB of file no matter what
  console.log(size += chunk.length) // Does NOT receive the whole file regardless using peer1.write(chunk) or stream.pipe(peer1) from peer1
})
```

It'd seem that `self._channel.bufferedAmount is > self._maxBufferedAmount`; doesn't the channel buffer get flushed upon send()?

**Comment by SourceBoy** [comment]
Test result indicates that the **drain** event from peer1 never fired:
```
peer1.on('connect', () => {
  stream.on('data', (chunk) => {
    if (peer1.write(chunk) === false) {
      stream.pause()
    }
  })

  // Doesn't fire
  peer1.on('drain', () => {
    stream.resume()
  })
})
```

**Comment by feross** [comment]
Which webrtc implementation are you using in Node.js? `wrtc`?

**Comment by SourceBoy** [comment]
@feross electron-webrtc

**Comment by SourceBoy** [comment]
Looks like [this RTCDataChannel.send()](https://github.com/mappum/electron-webrtc/blob/v0.3.0/src/RTCDataChannel.js#L177) implementation is currently broken.

Switching to [wrtc](https://www.npmjs.com/package/wrtc) with [this binary on Linux](https://webrtc-libraries-and-headers.s3.amazonaws.com/wrtc/v0.0.60/Release/node-v48-linux-x64.tar.gz) worked.

![](https://i.imgur.com/yXG9mXM.png)

The memory usage is however, rather high. Do you have any recommendations on lowering the mem usage? I was under the assumption that once a chunk of stream is written, that memory would be freed?

This seems like the RAM ate the whole 1GB file
![Memory usage](https://i.imgur.com/soBkNPs.png)

**Comment by feross** [comment]
@SourceBoy glad you got your issue figured out. thanks for opening an issue on the electron-webrtc repo.
