### ISSUE TITLE
[question] Error: Invalid key provided

### ISSUE THREAD

**Issue by jessevdp** [feross/simple-peer#132]
**using simplepeer.min.js** client side.

Hi, while testing simple-peer using the minified version I immediately ran into this issue, this did **not** happen when testing out with the browserify version. 

I was trying out the [example from the readme](https://github.com/feross/simple-peer#usage), basically only running this code: 
```js
var p = new Peer({ initiator: location.hash === '#1', trickle: false })
p.on('error', function (err) { console.log('error', err) })
```

It generated (and logged thanks to the second line) this error: 
```
error Error: Invalid key provided
    at c.emitError (peer.min.js:1)
    at c._abort (peer.min.js:1)
    at c._handleMessage (peer.min.js:1)
    at c.<anonymous> (peer.min.js:1)
    at c.d.emit (peer.min.js:1)
    at WebSocket._socket._socket.onmessage (peer.min.js:1)
```

Unfortunately I could not find a way to resolve this issue in the documentation. (I tried 😬 )

**Comment by feross** [comment]
The error originates in a file called `peer.min.js`. Is this actually the same file as `simplepeer.min.js`? It appears this file is related to WebSockets, so it has nothing to do with `simple-peer`. Let me know if this is not the case.

**Comment by jessevdp** [comment]
You're absolutely right, I had forgotten to delete the previous p2p library I was using, the js kinda overwrote....

Guess stupid things like that happen when you've been coding for too many hours in a row. 😬
