### ISSUE TITLE
possible missing error event? 

### ISSUE THREAD

**Issue by jessevdp** [feross/simple-peer#133]
I came across this possible issue while testing, I already figured out what was going wrong but  thought I should report this.

I had some connectivity issues to clients on a different network and decided to add a TURN server. I found a list of possible (free) STUN and TURN servers and decided to use these to setup. 

Now what I think happend is that the logins for the TURN servers where invalid, I can't confirm this or anything but that's my best guess. When not using the TURN servers the `signal` event was triggered just fine by the initiation client and establishing a connection (locally) wasn't a problem. However when adding these TURN servers (with login) to the `iceServers` `array` nothing happened, the `signal` event wasn't triggered nor was the `error` event. (I did wait like 5 min for it to make sure)

I started looking trough the various issues in this repository and noticed #69 -> there this free turn server http://numb.viagenie.ca/ was suggested. 
I signed up for a free account, setup the `iceServers` and everything worked fine. (only specifying their TURN server for testing).

## synopsis 
Possibly an error event should be triggered when a TURN (or any) server fails, but then again... I have no clue if that's exactly what happened.

I hope this report is helpful, if you need any more information on how to recreate this situation, just ask for it 👍

**Comment by feross** [comment]
Thanks for the detailed report. Can you share the invalid TURN server you used? If I can reproduce this, I'll see if there's some way to emit and 'error' in this case.

**Comment by jessevdp** [comment]
https://gist.github.com/yetithefoot/7592580

Think I just copied this list of ice servers. Hope this is all the info you need! 

Really awesome library btw, simplifies the webRTC API and makes it way more understandable. 😇

**Comment by feross** [comment]
I just tried with that list of servers and could not reproduce the issue.
