### ISSUE TITLE
[possibly weird]

### ISSUE THREAD

**Issue by jessevdp** [feross/simple-peer#134]
I came across this possible issue while testing, I'll try my best to give enough information for you to reconstruct this scenario and you can see for yourself weather or not you want to do something with this.

I wanted to test out if you could use the answer to a different offer (by the same client) to complete the connection between two peers. Now the answer to that question is (probably) **nope** but that's not the subject of this issue...

#### What did I do? 
* I created a `new SimplePeer()` A and set initiator to `true`. I took the `offer` and used it to generate an `answer` at the remote end. 
* I created a `new SimplePeer()` B also with initiator set to true but ignored its `offer`
* I took the `answer` generated at the remote end and passed it into the second peer (B)'s signal method. 

**Result**: Nothing happened **at all**. 
I even left the page open for a couple of minutes, but nothing happened.  

## my code
```js
function P2P () {
  var p = new SimplePeer({
    initiator: true,
    config: {
      iceServers: iceServers
    },
    trickle: false
  })

  p.on('error', function (err) { console.log('error', err) })
  p.on('signal', function (data) {
    console.log('SIGNAL', JSON.stringify(data))
  })

  p.on('connect', function () {
    console.log('CONNECT')
  })

  p.on('data', function (data) {
    console.log('data: ' + data)
  })
  return p;
}
```
As you can see I do have an event listener specified for the error events, and it was not fired.

## screenshot

In the screenshot below the first `SimplePeer` was named B and the second was named C. This does not match the earlier description. So that's just something to note!

<img width="70%" alt="screen shot 2017-01-28 at 22 30 58" src="https://cloud.githubusercontent.com/assets/15139826/22400053/57382392-e5ab-11e6-97fb-31b1e3a89baf.png">

## suggestion
Possibly some event should be triggered in this situation since right now the client receives no feedback whatsoever. 

I'm not sure if this event should be an error event since I noticed the following: 

I tried to take the offer generated by B (c in the screenshot) and go over to (the same) remote end to try and create another answer. This just to see if B could still be used. 

When I used `.signal(offer)` on the remote end the connect event fired (between the remote end and B).
**I gave B the answer before giving the remote end the offer and it still worked!**

## Synopsis
I noticed something. Here's the report... you decide what you do with it. 

PS. I think it would be really cool if you could setup peers like I tried in my example. This would allow for way easier setup (between multiple peers). But this is probably impossible due to how the webRTC protocol works.

**Comment by feross** [comment]
This is impossible due to how WebRTC works. Agreed, this could be pretty useful (i.e. one way peer connections). I don't know if it's possible to detect this scenario, but if you (or someone else) feels strongly this should be detected, I'll accept a PR to do that.
