### ISSUE TITLE
Support depracated RTCIceServers config url param

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/simple-peer#136]
From a small research I performed with 20 manual tests, while having the url field in rtcConfig, webtorrent performed much more better.

I suggest keeping it around, for whatever reason it improves performance to connect to peers.

**Comment by feross** [comment]
Which browser did you test with? How did you test? I want to confirm this myself so we can file a bug on the relevant browser if this is actually happening.

**Comment by DiegoRBaquero** [comment]
Chrome 55. MacOS Sierra.

I first deleted BTorrent's rtcConfig to use default and noticed it didn't connect as fast and as to many peers as before.

I then put it back and confirmed.

I created a mirror version, one with url and urls and one with urls only.

I manually ran 10 tests in each and the one with url performed better, more peers, faster initial connections.

**Comment by DiegoRBaquero** [comment]
I JUST got updated to Chrome 56. Could have been fixed already. Want me to re-do the test?

Imo is a small change that helps older browsers anyways.

**Comment by feross** [comment]
@DiegoRBaquero It prints a deprecation warning for Firefox users, so I'd rather avoid it if there's no advantage. Could you redo the test?

**Comment by DiegoRBaquero** [comment]
Just tested with Chrome 56. No issue.

Let's keep it as it is and wait for clients to update.

**Comment by feross** [comment]
That's great to hear. I just checked and it looks like `urls` has been supported since Firefox 38. It's been in Chrome for so long that the adapter.js project doesn't even shim it anymore. Weird that Chrome 55 was slower with it...
