### ISSUE TITLE
optionalDependency on wrtc is unwanted for web projects

### ISSUE THREAD

**Issue by guymguym** [feross/simple-peer#14]
Hi @feross 

Continuing the discussion in https://github.com/js-platform/node-webrtc/issues/194 (and the clutter of trying to solve it with --no-optional) - I see another downside of defining wrtc as an optionalDependency of simple-peer.

I have several projects that depends on simple-peer, because it's awesome :) These projects only use it in web pages, but have no interest for the webrtc stack for nodejs, and they get installed on cloud platforms only to serve those pages to users.

Now wrtc is always attempted to install along with simple-peer, and since wrtc is not yet providing binaries for all platforms, this also starts to build from source... and fails on occasion. So I think wrtc is still not yet in a stable status, but even if it was it is definitely not a small nifty library that can be dragged along anyplace with simple-peer (which is a small and nifty library).

Maybe use [peerDependency](https://docs.npmjs.com/all#peerdependencies) instead so that if anyone wants to use simple-peer with wrtc it will simple depend on both?

Thanks!

**Comment by substack** [comment]
Agreed here. This is an unwanted feature except when I want node support. What about a separate package for node support?

**Comment by feross** [comment]
Version 5.0.0 removes the `wrtc` dependency. Instead, you must now pass it in like:

```js
var SimplePeer = require('simple-peer')
var wrtc = require('wrtc')

var peer1 = new SimplePeer({ initiator: true, wrtc: wrtc })
var peer2 = new SimplePeer({ wrtc: wrtc })
```

**Comment by guymguym** [comment]
:+1:
