### ISSUE TITLE
Add Twilio's free STUN?

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/simple-peer#144]
Adds a redundancy layer and allows STUN where Google is banned.

I can PR if needed

**Comment by feross** [comment]
I think Firefox shows a console warning when there are multiple STUN servers specified. It claims this makes the connection take longer. But you raise a good point about the Google STUN server being blocked in countries like China.

It's not clear to me what the right tradeoff is here.

**Comment by DiegoRBaquero** [comment]
It seems that the first response is used: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by feross** [comment]
@DiegoRBaquero Okay, I'm convinced. Let's add it. Want to send a PR?

**Comment by RationalCoding** [comment]
I'm not getting any warning in Firefox with multiple urls, so maybe it's been fixed/muted.
