### ISSUE TITLE
Browser differences in constraint objects

### ISSUE THREAD

**Issue by RationalCoding** [feross/simple-peer#145]
There are currently two ways to specify answer/offer constraints:

The new format:
```javascript
{
  offerToReceiveVideo: true,
  offerToReceiveAudio: true
}
```

The old format:
```javascript
{
  mandatory: {
    OfferToReceiveVideo: true,
    OfferToReceiveAudio: true
  }
}
```

Chrome doesn't support the new spec as of v56, throwing a "malformed constraints object error".

Firefox supposedly supports both formats, but there are a number of issues with using the old format (like onaddstream not firing in certain situations).

It would be great if simple-peer could abstract this away.

**Comment by feross** [comment]
Agreed!
