### ISSUE TITLE
TypeError: Cannot set property 'binaryType' of undefined

### ISSUE THREAD

**Issue by doganmurat** [feross/simple-peer#155]
Hi,

I am trying to use simple-peer with node.
Here is my sample code;
```
'use strict';

const SimplePeer = require('simple-peer');
const wrtc = require('wrtc');

const peer = new SimplePeer({
    initiator: true,
    wrtc: wrtc
});
```
Here is output;

```
murat@linux-m ~/js/p2p $ DEBUG=* node peer1.js 
  simple-peer [d2d71d7] new peer { initiator: true, wrtc: { RTCIceCandidate: [Function: RTCIceCandidate], RTCPeerConnection: [Function: RTCPeerConnection], RTCSessionDescription: [Function: RTCSessionDescription] } } +0ms
/home/murat/js/p2p/node_modules/simple-peer/index.js:305
  self._channel.binaryType = 'arraybuffer'
                           ^

TypeError: Cannot set property 'binaryType' of undefined
    at Peer._setupData (/home/murat/js/p2p/node_modules/simple-peer/index.js:305:28)
    at new Peer (/home/murat/js/p2p/node_modules/simple-peer/index.js:105:10)
    at Object.<anonymous> (/home/murat/js/p2p/peer1.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

I tried with node version 4.8 and also 6.10 nothing changed.
If I  call with initiator: false as options than everything seems OK.

Please note that ;
I am using Ubuntu 16.04 and had an issue https://github.com/js-platform/node-webrtc/issues/281.

I successfully solved the issue but now I have this issue.

Any help would be appreciated.

Best regards,

**Comment by doganmurat** [comment]
Also please note that all tests with node-webrtc passes successfully.

**Comment by feross** [comment]
Works for me. Closing this issue until the following information is provided.

Can you provide the following information:

- What version of `simple-peer` are you using?
- What version of `wrtc` are you using?

**Comment by doganmurat** [comment]
simple-peer version :6.4.3
wrtc version : 0.0.62

I found the problem.
Problem was simple-peer default config about iceServers.
I called like this and it worked.

```
const peerConfig = {
  initiator: true,
  wrtc: wrtc,
  config: {
    iceServers: [{
        url: 'stun:stun.l.google.com:19302'
      },
      {
        url: 'stun:stun1.l.google.com:19302'
      },
      {
        url: 'stun:stun2.l.google.com:19302'
      },
      {
        url: 'stun:stun3.l.google.com:19302'
      },
      {
        url: 'stun:stun4.l.google.com:19302'
      },
    ]

  }
};

....

this.__peerObj = new SimplePeer(peerConfig);
```

**Comment by feross** [comment]
@doganmurat Can you explain a bit more? Why does this fix the issue? Is there a bug in `simple-peer`?

**Comment by doganmurat** [comment]
@feross I tested in win-7 all worked no problem.
In linux I got error above with default ice-server config.

What happens if all ice-servers are down?
Could that be the situation?

**Comment by feross** [comment]
@doganmurat It sounds to me like you might be running a different version of `wrtc` in windows 7 versus linux. Can you confirm that you're running the latest version in both places?

**Comment by doganmurat** [comment]
@feross In windows I have wrtc version 0.0.61.
In Linux I had an issue with wrtc same as [this-wrtc-issue-281](https://github.com/js-platform/node-webrtc/issues/281)

I built wrtc from source.
In linux wrtc version is 0.0.62.

What is the min required version of wrtc for simple-peer?

**Comment by feross** [comment]
I recommend using the latest version of `wrtc`, but I don't use `wrtc` anymore so I can't say whether it's a good library to continue using. `simple-peer` works great with Chrome/Firefox.

**Comment by doganmurat** [comment]
I am using simple-peer for a nodejs project so I have to use wrtc.
Thanks anyway.
