### ISSUE TITLE
broadcast video stream to all connected clients

### ISSUE THREAD

**Issue by go4devguy** [feross/simple-peer#160]
How can I create a video broadcasting app (star topology) where video stream from one client machine needs to be broadcasted on all other client's machine? Could you point me to any working example or just give some pointers in this direction ?

**Comment by RationalCoding** [comment]
Make a new peer object for every connection and only pass a stream into the host. Other than that, it's just a regular connection.

Set offer and answer constraints on all peers or the "stream" event might not fire.
