### ISSUE TITLE
Can not create peer with initiator: true.

### ISSUE THREAD

**Issue by Xazzzi** [feross/simple-peer#163]
Following code fails:
```
let pc = new Peer({wrtc, initiator: true})

TypeError: Cannot set property 'binaryType' of undefined
    at Peer._setupData (/home/azzi/gdtime/rtcserver/node_modules/simple-peer/index.js:307:28)
    at new Peer (/home/azzi/gdtime/rtcserver/node_modules/simple-peer/index.js:106:10)
    at repl:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
```
Some research given, it turns out that `Peer._setupData` receives event that is `{channel: undefined}` and tries to work with it as if `channel` was a thing:
```
// index.js:307
self._channel.binaryType = 'arraybuffer'
```
Call that causes it:
```
// index.js:106
self._setupData({
  channel: self._pc.createDataChannel(self.channelName, self.channelConfig)
})
```
I also found this [commit](https://github.com/js-platform/node-webrtc/commit/39ee525361eedb784ad8210b9dcdad6150a83af8) in `node-webrtc` repo, that seems relevant. Seems like `simple-peer` is just missing undefined check.

Would be nice to have it fixed somehow.

I'm using Node 7.8.0 and wrtc 0.0.62 built from github, if that is important.

**Comment by feross** [comment]
This sounds like a bug in `wrtc` because calling `pc.createDataChannel()` should not return `undefined`. It's not even clear what we should do about it, since it's undefined behavior.

**Comment by feross** [comment]
Decided to just kill the whole peer connection if this happens, since this should never happen (to my knowledge) in a spec-compliant implementation.

Also, according to the commit you linked, it only happens when `wrtc` has already closed the underlying peer connection, so there's no way to salvage this situation. It's best to just error gracefully instead of throwing an exception.

Fixed in 7.0.1.

**Comment by Xazzzi** [comment]
I'm looking at wrtc source now, it really looks like their bug.
Not sure why all tests their pass though.

Seems like `PeerConnection.createDataChannel` won't give return value unless connected already.
But you still can make it better: since stream is actually being created, just not returned immediately as function result in some conditions, you can replace:
```
// index.js:99
if (self.initiator) {
    ...
    // index.js:106
    self._setupData({
      channel: self._pc.createDataChannel(self.channelName, self.channelConfig)
    })
  } else {
    self._pc.ondatachannel = function (event) {
      self._setupData(event)
    }
  }
```
With:
```
if (self.initiator) {
    ...
}
self._pc.ondatachannel = function (event) {
  self._setupData(event)
}
```

I just checked in node's repl, event is being triggered correctly this way.
```
pc2 = new rtc.RTCPeerConnection()
pc2.ondatachannel = evt => console.log(evt)
pc2.createDataChannel('name')

RTCDataChannel {
  addEventListener: [Function],
  dispatchEvent: [Function],
  removeEventListener: [Function],
  send: [Function: send],
  close: [Function: close] }
```

**Comment by Xazzzi** [comment]
Actually, i was wrong, it seems to be a return value. I'm so confused right now, node webrtc works from repl, but when used with simple-peer, underlying PeerConnection seems to be closed instantly after creation.

**Comment by feross** [comment]
Thanks for digging, sounds like we should keep calling `_setupData` the same way? Thanks.

**Comment by Xazzzi** [comment]
Yep, it was my mistake.
