### ISSUE TITLE
Error: Ice connection failed.

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#164]
The test suite is failing with `Error: Ice connection failed.`. I've also noticed this error in the WebTorrent Desktop telemetry logs, and it's now one of the top errors.

We should figure out what's going on.

**Comment by RationalCoding** [comment]
Is it possible that these are network related? I know ICE can fail for quite a few external reasons.

**Comment by feross** [comment]
Yep, this is network related. Happens when I have my firewall enabled and don't allow the connections through.

**Comment by RationalCoding** [comment]
We could specify a default TURN server.

**Comment by feross** [comment]
@RationalCoding TURN servers are expensive. Who would pay for it?

**Comment by RationalCoding** [comment]
True. Anyways, I'd prefer to trust a 3rd-party TURN server by default. It's good the way it is.

**Comment by RationalCoding** [comment]
I've noticed that the ICE status will briefly change to "disconnected" on Chrome. Adding a short reconnect timer (~100ms) has significantly reduced these errors for me.

**Comment by surprisetalk** [comment]
@RationalCoding I'm being inundated with ICE connection errors on `webtorrent-hybrid`. Would you be willing to share your reconnection code? Thanks!

**Comment by RationalCoding** [comment]
@surprisetalk Please see the investigation into this error I did in #202. There are multiple reasons for this error (mostly network related.)

The reconnectTimer option was removed in a past PR since we changed how we handle ice timeouts. You shouldn't have the issue I'm talking about here in a new version of simple-peer.
