### ISSUE TITLE
Breaking changes to readable-stream

### ISSUE THREAD

**Issue by Right2Drive** [feross/simple-peer#169]
When using simple-peer with readable-stream 2.2.8, receiving the following exception upon peer creation:
```
Uncaught TypeError: this.once is not a function
    at Peer.Duplex (eval at <anonymous> (bundle.js:131), <anonymous>:53:8)
    at new Peer (eval at <anonymous> (bundle.js:1521), <anonymous>:29:17)
```

**Comment by feross** [comment]
That's odd. This is probably something in your program, since our test suite passes just fine with `readable-stream` 2.2.8. Can you provide more details?

**Comment by Right2Drive** [comment]
Hi, 

Thanks for the speedy reply! I'll do some more investigation, but I pushed some minor changes to my application on bluemix, and upon rebuilding starting receiving this error. It was working downstream on my local machine, and for some reason `once` was no longer found on the prototype chain of the simple peer instance when calling `stream.Duplex.call(self, opts)`

Updated the dependencies of simple-peer and the issue started happening locally as well, after looking at it a little closer I don't believe it would be related to readable-stream though, jumped the gun a bit

**Comment by feross** [comment]
Which version of `simple-peer` are you using? Can you run `npm ls simple-peer` and paste the output here?

**Comment by Right2Drive** [comment]
You inherit from the prototype of readable-stream Duplex, which on my app seems to no longer have the prototype from `Stream` available to it on the chain, it seems downgrading to readable-stream 2.0.5 did resolve this again.

I upgraded to the latest version of simple-peer hoping to resolve this, still no luck. Output of `npm ls simple-peer`:
```
<root>\ease-web>npm ls simple-peer
ease-web@1.0.0 <root>\ease-web
`-- simple-peer@7.0.1
```

**Comment by Right2Drive** [comment]
If you want to see what I'm talking about, the application is hosted at `https://ease-web.mybluemix.net/`, and a temp uuid to use is `4f99ced9-e9a7-1ab4-74f8-e79cae4e2b87`

**Comment by RationalCoding** [comment]
Just ran the test suite with an updated `readable-stream`, and everything's ok.

Am I right in thinking you are trying to access `Peer.Duplex`? SimplePeer doesn't expose the `readable-stream` API like that, it just inherits from it.

**Comment by Right2Drive** [comment]
No, just creating a SimplePeer instance

**Comment by RationalCoding** [comment]
Strange. Well I wouldn't advise updating `readable-stream` if the old version works for you. We run the test suite on the current dependency level and update when neccesary, anything out that is unsafe.

**Comment by Right2Drive** [comment]
I am thinking if the tests are passing then it must be an issue with one of my other dependencies interfering with simple-peer. I noticed there are some issues open with readable-stream regarding webpack

**Comment by RationalCoding** [comment]
That's probably the cause. We build with Browserify and not webpack

**Comment by Right2Drive** [comment]
Correct me if I'm wrong @RationalCoding but the dependency for readable-stream is set with `^`, so it will continue to pull changes from downstream until a major version change

**Comment by feross** [comment]
Looks like readable-stream is aware of the issue: https://github.com/nodejs/readable-stream/issues/277

**Comment by Right2Drive** [comment]
Thanks! I will force the version of readable-stream until it is resolved! I greatly appreciate the help!
