### ISSUE TITLE
Simplepeer.min.js raising security error in Firefox.

### ISSUE THREAD

**Issue by Lastalas** [feross/simple-peer#17]
Unable to load the page.  The exception and html are below:

This is the error:
*Security wrapper denied access to property valueOf on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.*

HTML: https://gist.github.com/Lastalas/e3a157244877a9d7aa65

I'm not quite sure what else I can add.  Does this sound in any way familiar?

Firefox 35.0.1
Ubuntu 64bit

**Comment by feross** [comment]
You're using the constructor wrong. Take a look at [the docs](https://github.com/feross/simple-peer#peer--new-simplepeeropts).

This is your code:

```js
 var peer = new SimplePeer({
          constraints:{
            mandatory: {
                OfferToReceiveAudio: false,
                OfferToReceiveVideo: true
            },
            optional: [
                {DtlsSrtpKeyAgreement: true}
            ]
        },
        iceServers:[{urls: 'stun:stun.l.google.com:19302'}]
    });
```

The `iceServers` key is supposed to be inside a `config` object. Example:

```js
 var peer = new SimplePeer({
          constraints:{
            mandatory: {
                OfferToReceiveAudio: false,
                OfferToReceiveVideo: true
            },
            optional: [
                {DtlsSrtpKeyAgreement: true}
            ]
        },
        config: { iceServers:[{urls: 'stun:stun.l.google.com:19302'}] }
    });
```

Try fixing that and seeing if the error goes away.
