### ISSUE TITLE
piping with {end: false} still closes the stream

### ISSUE THREAD

**Issue by RationalCoding** [feross/simple-peer#171]
```javascript
stream.pipe(peer, { end: false} )
```
will still close the peer when the readable stream ends.

**Comment by feross** [comment]
No idea off the top of my head why this would happen.

Note that we do set `allowHalfOpen` to `false`. Documented here: https://nodejs.org/api/stream.html#stream_new_stream_duplex_options But I don't think that would cause an issue here.

**Comment by RationalCoding** [comment]
Setting allowHalfOpen to true doesn't fix it. Going to see if it's a `readable-stream` issue.

**Comment by RationalCoding** [comment]
Ah, I see my mistake now. The pipe was ending from the other side.

This works fine:

```javascript
stream.pipe(peer1, { end: false} )
```

But you need to keep the other side open too.

```
peer2.pipe(outputStream, { end: false} )
```
