### ISSUE TITLE
Connection failure in Firefox does not fire the error event

### ISSUE THREAD

**Issue by onel** [feross/simple-peer#175]
This might be a Firefox issue so sorry in advance.
I've tested with two computers, one of them connected with Firefox.
If I close the WIFI the `_destroy` method is called on the peer as expected but the `err` argument is undefined. This only happens in Firefox.

In Chrome the argument is an error with the message `Ice connection failed.`
Because of this the `error` event is not fired in Firefox.
Is there a way to make Firefox fire the event?

**Comment by feross** [comment]
There's no way to get these events to be reliable, as far as I know. The implementations vary in how they behave. The most reliable way is to use the signaling channel to send a heartbeat to the server and then the server can communicate the status to the different peers over a websocket.

If anyone else has ideas, feel free to chime in.
