### ISSUE TITLE
Error processing ICE candidate

### ISSUE THREAD

**Issue by gnazarkin** [feross/simple-peer#176]
I can establish successful connections but the receiver gets a lot of errors during the process and before a connection is established. No errors for the initiator.

The error is - `DOMException: Error processing ICE candidate`

**Comment by feross** [comment]
Without more information like the actual code you're using, the version of `simple-peer`, the browser, the browser version, etc. it's impossible to help you.

Nonetheless, here's a StackOverflow answer that might help: http://stackoverflow.com/a/40205727
