### ISSUE TITLE
Slow Connection

### ISSUE THREAD

**Issue by doganmurat** [feross/simple-peer#177]
Hi,
I am trying to connect 2 peer on same LAN. 
simple-peer find outs local ip addresses as expected but connection speed is very low.
For file transfer it is about 100 KByte/s
Please note that one end is nodejs app. (I am using node-wrtc)

Any idea how to improve speed?

simple-peer version:6.4.4
node version : 6.9.10
node-wrtc version: 0.0.61

**Comment by feross** [comment]
The speed will depend a lot on how you implement the file transfer. How are you splitting the file up? How is the receiving peer requesting pieces from the sender?

Closing as this is not a `simple-peer` issue, but discussion can continue.

**Comment by vblagomir** [comment]
So, to continue the discussion here. And this is also related to #195 and #393, but with a clear test.

Two computers (macOS, Safari 12.1+) are within WLAN network with realistic speed of ~250Mb/s (~30MB/s) are connected with RTCDataChannel/simple-peer. A file (50MB) is sliced/processed with FileReader and is sent with chunks of 16Kb over from one computer to another using the RTCDataChannel/simple-peer.

The slicing/sending takes ~5s, receiving takes ~14s, giving real speed of the sending of 10MB/s (3 times slower than the realistic potential of the network) and receiving ~3.6MB/s (~8 times slower).

**The main question:**
Is this the maximum that can be achieved with RTCDataChannel/simple-peer? Is there anything that can be optimized/configured to make it faster?

I am not talking about optimization of processing/slicing the file for now, but about the buffering and backpressure of RTCDataChannel, as if receiving peer could get the data at the same speed as the sending peer is sending, it would be already not bad. So far the whole concept seem to be rather slow.

By the way, to send the same file to a local NAS over the same network would take ~2s (~25MB/s). And using the WebRTC example: https://webrtc.github.io/samples/src/content/datachannel/filetransfer/ while transferring the same file 'Average bitrate' is shown 44000 Kb/s (~6MB/s), though I did not dig into what exactly is happening on this demo.

**Comment by t-mullen** [comment]
It'd definitely be interesting to do some speed comparisons of simple-peer, vanilla RTCDataChannel, and alternatives like websockets.

I wouldn't compare to the raw WLAN bandwidth, the extra overhead of IP/UDP/DTLS/SCTP makes it an unrealistic baseline, not to mention initial signalling time. I think some mininet tests comparing websockets with SSL would be more accurate.

I'm not sure about config options to improve performance. Maybe increasing maxMessageSize through the SDP could work in some situations.

**Comment by jimmywarting** [comment]
I have created a simple raw WebRTC transferering test
http://jsfiddle.net/v4umxgn2/1/

Reason was that i used some rtc library that had other overhead stuff and the speed of wish it transfered a file to another tab was slow.

I considered the fiddle as "under the best conditions" and made it my personal goal to try and reach the same speed in my other project
