### ISSUE TITLE
Not working when implementing together with adapter.js

### ISSUE THREAD

**Issue by olastor** [feross/simple-peer#179]
As soon as I add https://webrtc.github.io/adapter/adapter-latest.js (or v3.3.3/4) to my code using `simple-peer`, the error "Unhandled Promise rejection: Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack." is thrown in console (it's working fine without adapter.js). Are these 2 packages not supposed to be used in the same project?

Complete error message:
![bildschirmfoto_2017-04-30_17-41-34](https://cloud.githubusercontent.com/assets/7479641/25565755/a444084e-2dcd-11e7-9d5d-05202768fba5.png)

**Comment by etienne-martin** [comment]
I think that's because Microsoft Edge doesn't support the `MediaStreamTrack` metric.

See: https://www.callstats.io/2015/10/02/microsoft-edge-ortc-support-added/

> Currently, the getStats() API in Microsoft Edge (Build 13.10547) returns quite rudimentary statistics: the round-trip time (RTT), the packets sent and received. However, several important metrics are missing, for example, jitter, and bytes sent or received.

**Comment by RationalCoding** [comment]
Adapter.js shouldn't remove MediaStreamTrack support for Chrome and Firefox though. Seems like an issue with their polyfill.

**Comment by RationalCoding** [comment]
Closing as this cannot be fixed in simple-peer. Recommend you open an issue in adapter.js for MediaStreamTrack support in getStats.
