### ISSUE TITLE
Ice connection failed when connecting from Chrome to Firefox or Chrome to Chrome 

### ISSUE THREAD

**Issue by akhilstanis** [feross/simple-peer#181]
I am trying out the simple example given in the README and it fails when initiating the connection from chrome. I get the following error in console.

    error Error: Ice connection failed.
        at u._onIceStateChange (simplepeer.min.js:3)
        at RTCPeerConnection.t._pc.oniceconnectionstatechange (simplepeer.min.js:3)

Chrome version: 58.0.3029.110 (64-bit)
Firefox version: 53.0.3 (64-bit)

The example works fine when initiating the connection from Firefox though. I checked few combinations and here are the results.

**Chrome to Firefox: Fail**
**Firefox to Chrome: Success**
**Chrome to Chrome: Fail**
**Firefox to Firefox: Success**

Is there incompatibility with the latest version of chrome?

**Comment by kifhan** [comment]
Could you trace ``` chrome://webrtc-internals/ ``` for what's going on?
I got same error once, but some reason, it doesn't came back.

**Comment by akhilstanis** [comment]
@kifhan It turns out I had my firewall configured to block incoming connections to chrome. Fixed that it is working fine now. Thanks!
