### ISSUE TITLE
Custom iceServers config setting seems to be ignored, and google and twilio STUN servers are used instead

### ISSUE THREAD

**Issue by weijiekoh** [feross/simple-peer#182]
I'm trying to make simple-peer connect via TURN, so I changed the `iceServers` config option to my own custom TURN servers:

```
iceServers: [ 
    { url: 'turn:<custom TURN server IP>:3478' },
    { url: "turn:numb.viagenie.ca:3478",
      username: "xxx",
      credential: "xxx" },
 ]
```

However, the P2P connection fails with Firefox 53.0.3 giving this error:

```
peer error [28]</</Peer.prototype._onIceConnectionStateChange@http://<ipaddress>:3000/js/bundle.js:5654:19
Peer/self._pc.oniceconnectionstatechange@http://<ipaddress>:3000/js/bundle.js:5302:5
  bundle.js:6431:5
[websocket send] {"type":"end"}  bundle.js:6588:5
ICE failed, add a TURN server and see about:webrtc for more details
```

Upon inspecting the logs in `about:webrtc`, Firefox states that simple-peer attempts to make a STUN connection through `global.stun.twilio.com:3478` and `stun.l.google.com:19302`, but makes no mention of the custom TURN servers I set.

To reproduce this, deploy [lxjs-chat](https://github.com/feross/lxjs-chat) on an AWS EC2 instance, upgrade simple-peer to the latest version (`6.4.4`), edit the `CONFIG` variable in `public/js/peer.js`, and then connect using devices located behind different NAT firewalls. I used Firefox 53.02 on Android on a mobile data network, and Firefox 53.0.3 on Ubuntu Linux connected to a Wifi network.

This problem doesn't happen if both peers are connected to the same Wifi network.

**Comment by cdvv7788** [comment]
Latest version is not 6.4.4. It seems to be working for me with 8.1.0

**Comment by feross** [comment]
The `lxjs-chat` example was very out-of-date. The `peer.js` file in that repo was actually a super-early version of `simple-peer`, before it was published separately as it's own module.

I just went through that codebase and updated it to use the latest version of `simple-peer`. Go ahead and give that a try now and feel free to open a new issue if you have troubles.
