### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by bromoapp** [feross/simple-peer#183]
Hi,

I'm researching WebRTC right now, and if you check my projects here are mostly about WebRTC.
In all of my projects here, I use browser's standard JS for invoking webrtc, and after finding [this](https://github.com/jeregrine/phoenix_webrtc) project, I'm interested on using **simple-peer.js** library.

I know this might not be an appropriate place to ask regarding simple-peer.js, But I just wonder why that library doesn't run in my project. What I do in this project are:

1. Installing simple-peer.js by calling **npm install simple-peer --save**
2. I called from my app.js: **import Peer from "simple-peer"**

But it throws error in by browser console, it shows:

Uncaught ReferenceError: process is not defined
at index.js:7
at index.js:48
at initModule (app.js:43)
at require (app.js:60)
at expanded (app.js:34)
at app.js:148
at _stream_readable.js:11
at _stream_readable.js:940
at initModule (app.js:43)
at require (app.js:60)

And when I click on debug console, it shows below script that caused error:

![capture](https://user-images.githubusercontent.com/21073705/27004780-c980e6c2-4e39-11e7-9324-308bdba817ac.PNG)

And I cannot make any instance of Peer in my page.

Thanks

**Comment by RationalCoding** [comment]
simple-peer only works in the browser using a bundler like Browserify or WebPack. 

I'm not sure if it's possible to add ES6 module support, but it's not there now.

**Comment by RationalCoding** [comment]
You could try it with the standalone bundle of simple-peer: https://wzrd.in/standalone/simple-peer

**Comment by bromoapp** [comment]
Ok I'll try ... I close this issue ... thanks, and great project :)

**Comment by RationalCoding** [comment]
If that doesn't work for you, you can always include the standalone simple-peer in a script tag and SimplePeer will be a global variable.

**Comment by indatawetrust** [comment]
this solution work for me

```js
var app = express();
// ...
const browserify = require('browserify-middleware');
// ...
app.get('/js/simple-peer.js', browserify(['simple-peer']));
```

```html
<script src="/js/simple-peer.js"></script>
<script>
var Peer = require('simple-peer');
</script>
<script src="/bundle.js"></script>
```

**Comment by arayatnetspidotcom** [comment]
> Hi,
> 
> I'm researching WebRTC right now, and if you check my projects here are mostly about WebRTC.
> In all of my projects here, I use browser's standard JS for invoking webrtc, and after finding [this](https://github.com/jeregrine/phoenix_webrtc) project, I'm interested on using **simple-peer.js** library.
> 
> I know this might not be an appropriate place to ask regarding simple-peer.js, But I just wonder why that library doesn't run in my project. What I do in this project are:
> 
> 1. Installing simple-peer.js by calling **npm install simple-peer --save**
> 2. I called from my app.js: **import Peer from "simple-peer"**
> 
> But it throws error in by browser console, it shows:
> 
> Uncaught ReferenceError: process is not defined
> at index.js:7
> at index.js:48
> at initModule (app.js:43)
> at require (app.js:60)
> at expanded (app.js:34)
> at app.js:148
> at _stream_readable.js:11
> at _stream_readable.js:940
> at initModule (app.js:43)
> at require (app.js:60)
> 
> And when I click on debug console, it shows below script that caused error:
> 
> ![capture](https://user-images.githubusercontent.com/21073705/27004780-c980e6c2-4e39-11e7-9324-308bdba817ac.PNG)
> 
> And I cannot make any instance of Peer in my page.
> 
> Thanks



> Hi,
> 
> I'm researching WebRTC right now, and if you check my projects here are mostly about WebRTC.
> In all of my projects here, I use browser's standard JS for invoking webrtc, and after finding [this](https://github.com/jeregrine/phoenix_webrtc) project, I'm interested on using **simple-peer.js** library.
> 
> I know this might not be an appropriate place to ask regarding simple-peer.js, But I just wonder why that library doesn't run in my project. What I do in this project are:
> 
> 1. Installing simple-peer.js by calling **npm install simple-peer --save**
> 2. I called from my app.js: **import Peer from "simple-peer"**
> 
> But it throws error in by browser console, it shows:
> 
> Uncaught ReferenceError: process is not defined
> at index.js:7
> at index.js:48
> at initModule (app.js:43)
> at require (app.js:60)
> at expanded (app.js:34)
> at app.js:148
> at _stream_readable.js:11
> at _stream_readable.js:940
> at initModule (app.js:43)
> at require (app.js:60)
> 
> And when I click on debug console, it shows below script that caused error:
> 
> ![capture](https://user-images.githubusercontent.com/21073705/27004780-c980e6c2-4e39-11e7-9324-308bdba817ac.PNG)
> 
> And I cannot make any instance of Peer in my page.
> 
> Thanks

Hey did you find a solution to your problem? coz i am also facing the same issue.

**Comment by mlujan476** [comment]
same same

**Comment by Samrj12** [comment]
If it was an error with simple peers, this solved it for me: https://stackoverflow.com/questions/74421952/uncaught-referenceerror-process-not-defined-simple-peer-javascript
