### ISSUE TITLE
Simple peer in ionic 2

### ISSUE THREAD

**Issue by coolvasanth** [feross/simple-peer#184]
Hi, Can we user Simple peer in ionic 2 for creating a video chatting application. If so please share some materials on same.

**Comment by RationalCoding** [comment]
As far as I know, there's no standards-compliant WebRTC for Ionic. You'll have to use something lime [PhoneRTC](https://github.com/alongubkin/phonertc), which isn't compatible with simple-peer. You could make some sort of wrapper around it and use the same simple-peer interface, but that would be a lot of work.
