### ISSUE TITLE
Revert PR #180 once Chrome 61 is released

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#186]
Revert this PR once Chrome 61 is released: https://github.com/feross/simple-peer/pull/180

Context: https://github.com/feross/simple-peer/issues/178#issuecomment-309941181

**Comment by carloslfu** [comment]
Chrome 61 is now [relased](https://chromereleases.googleblog.com/2017/09/stable-channel-update-for-desktop_14.html)

**Comment by feross** [comment]
This will be released in the next version of simple-peer, 8.5.0
