### ISSUE TITLE
Promise syntax for RTCPeerConnection#createOffer

### ISSUE THREAD

**Issue by jeremija** [feross/simple-peer#190]
Hi there,

I've been experimenting with Safari Technology Preview R34 and I'm getting an error:

```Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary```

Looks like the [currently used][1] `pc.createOffer(successCallback, failureCallback, [options])` is [deprecated][2], and the `pc.createOffer([options])` should be used instead:

> In older code and documentation, you may see a callback-based version of this function. This has been deprecated and its use is strongly discouraged. You should update any existing code to use the Promise-based version of createOffer() instead.

What are the plans for supporting this new syntax? I could make a new pull request with the fix, but I'm worried it would cause issues with older browsers.

[1]: https://github.com/feross/simple-peer/blob/795370d607e6d6744774ba33723d2ba5b410a51f/index.js#L406
[2]: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer#RTCOfferOptions_dictionary

**Comment by jeremija** [comment]
I've had some success with modifying this library to establish a successful connection between Firefox 54 and Safari Technology Preview R34. I found Firefox to have more descriptive error messages than Chromium.

I had to:

1. Change the calls of following `RTCPeerConnection` methods to promise syntax:
    - `createOffer`
    - `createAnswer`
    - `setRemoteDescription`
    - `setLocalDescription`
    - `addIceCandidate` (would probably work without this)

    jeremija/simple-peer@8062544a4f6d87df5a822faabfd8ed1cc791b035
    jeremija/simple-peer@69db11876659f37ebfcae58a1448f0631f912eb5

2. Add a hack for Safari. I kept getting the following error in Firefox when connection was initiated from Safari:

    > Mismatch between mid and level - "video" is not the mid for level 0; "audio" is)

    The `icecandidate` events generated by Safari always had the `sdpMLineIndex = 0`, so I had to count them and increase them manually

    jeremija/simple-peer@3be31eac590a6e404685c6c2d86c457eebe7f2e9

I can now get establish a connection by using Google's STUN servers. Using TURN or TURNS doesn't work, but this is most likely a bug in Safari.

**Comment by RationalCoding** [comment]
This seems to be an issue about Safari support. I suggest waiting for the actual release, as technology previews are extremely likely to change.

Hopefully Safari implements callbacks, else many existing applications are going to break.

**Comment by NekR** [comment]
I highly doubt that. Latest Tech Preview was released couple of days ago and Apple is going to host its conf on September 12 where iOS 11 has to be released.

**Comment by NekR** [comment]
Also, has anyone testing this in Edge?

**Comment by feross** [comment]
@NekR Edge lacks DataChannels at the moment. You can vote for the feature here: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17929639-rtc-data-channels

**Comment by saranrapjs** [comment]
Hey @jeremija your commits with the Promise-based syntax look good to me! This syntax now reflects what's been shipped in Safari 11.X, works in Chrome and Firefox. It also looks like the callback syntax [is called out specifically as deprecated](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer).

You should make a PR for your code! And this could just be versioned as a breaking change?

**Comment by jeremija** [comment]
@saranrapjs I merged my fork with upstream/master: jeremija/simple-peer@cc05c7d (brach name: jeremija-safari-merge). I can create a pull request if @feross agrees, however there are two more issues to resolve:

a) Should this be rewritten with promise syntax, and using callbacks as a fallback? Right now promises are wrapped as callbacks, which makes the code convoluted.

b) The tests fail:

```
node_modules/electron-webrtc/src/RTCPeerConnection.js:189
          cb(offer)
          ^

TypeError: cb is not a function
```

My first guess is because electron-webrtc does not support promise-like syntax, but I don't have the time to investigate further at the moment.

**Comment by feross** [comment]
@jeremija Let's try to change as little code as possible, ideally. So, let's maintain the callback-style of this library. We can consider migrating to Promises in a future issue/PR, but that should be a separate discussion.

We need to maintain support for `electron-webrtc`, so that means we need to support browsers that only have the callback version of the method.

**Comment by phiresky** [comment]
Just want to say that this issue apparently persists in the stable version of Safari which makes everything that uses webtorrent not work at all in Safari. See https://github.com/phiresky/tv-show-ratings/issues/3

**Comment by t-mullen** [comment]
This was resolved in #337 and we support Promise-only Safari now.

**Comment by phiresky** [comment]
Nice, thank you. It hasn't trickled down into a release though, right?

**Comment by t-mullen** [comment]
That’s right.

**Comment by perguth** [comment]
Even on `9.11.1` I get that error when running tests via https://github.com/mafintosh/webrtc-swarm/:

```
node_modules/electron-webrtc/src/RTCPeerConnection.js:189
          cb(offer)
          ^

TypeError: cb is not a function
```
