### ISSUE TITLE
More docs, more examples

### ISSUE THREAD

**Issue by nkittsteiner** [feross/simple-peer#191]
First. ¿There is any example ```one-to-many``` connection using Simple-Peer? Docs could be expanded using some signaling (more real life) examples IMHO.
Another thing to mention is that when I tried to quick start without using browserify, in the examples initialization of the library appear as a ```Peer``` (instead of ```SimplePeer```) object so when you are just importing the 'simplepeer.min.js' file as a static js you get an error 'Peer is not defined'. I know that it may sound silly and noobish but for newcomers this could be a problem.

Keep it up! This is a fantastic library!

**Comment by RationalCoding** [comment]
Hi @nkittsteiner.

To create a one-to-many network, you need to create a new connection for every peer to the central peer. Just repeat the signaling example for each connection. You can using a signaling library like [signalhub](https://github.com/mafintosh/signalhub) or [simple-signal](https://github.com/RationalCoding/simple-signal) to make things easier.

Browserify decides what the module is called when the standalone module is built. I assume you're using one from a CDN that may have been built with the name `SimplePeer`. I agree that's confusing, but I'm not sure how to solve that :/

Good luck!
