### ISSUE TITLE
Running on Meteor: ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by vblagomir** [feross/simple-peer#193]
Can not launch it in Meteor. Getting the error 'ReferenceError: Can't find variable: Buffer'
and while trying to trace it it goes back into:
node_modules/core-util-is/lib/util.js 
exports.isBuffer = Buffer.isBuffer;                                                                                    // 103

**Comment by vblagomir** [comment]
Managed to run the minified version without browserify, so it is not an issue.

**Comment by NgKhanh** [comment]
Hello @vblagomir I have the same problem, how did you fix it ?

**Comment by vblagomir** [comment]
Hi @NgKhanh, I have imported the minified version directly
`import SimplePeer from 'simple-peer/simplepeer.min.js'`

**Comment by RationalCoding** [comment]
This error is because you are trying to load the module in a browser environment without browserifying it first. Buffer is a Node.js builtin. The minified version is already browserified.

**Comment by vblagomir** [comment]
I am running it in Meteor, and have finally managed to import non-minified version following this thread https://github.com/meteor/meteor/issues/8645#issuecomment-298349964 

```
global.Buffer = global.Buffer || require('buffer').Buffer
const SimplePeer = require('simple-peer')
```
..yet it is far from the expected `import SimplePeer from 'simple-peer'` which does not work even without the `global.Buffer` declaration (even though it is considered to be equivalent to 'require'/'browserify'
