### ISSUE TITLE
Data channel backpressure

### ISSUE THREAD

**Issue by vblagomir** [feross/simple-peer#195]
I am trying to send large binary files over data channel and had the same issue as in the closed #170, so now trying to do this with `peer.write()` instead of `peer.send()`..

However, I am still noticing that the sender sends data faster than the receiver receives.. Is this a normal behaviour? That would require me to not to rely on sending progress, but rather somehow get receiving progress.. is there a hidden method probably to get that, or should I get this info over other channels?

**Comment by RationalCoding** [comment]
Data is buffered before being sent, so writing to the stream doesn't necessarily send it immediately.

You could override the send method to intercept data before it is sent.

'''
Peer.prototype.oldSend = Peer.prototype.send

Peer.prototype.send = function (chunk) {
   // chunk is data being truly sent
   this.oldSend(chunk) 
}
'''

The channel has its own internal buffer, but it's small enough that you shouldn't notice it.

**Comment by RationalCoding** [comment]
I would think tracking progress on the receiving peer would be more appropriate, but you might not see much of a difference.

**Comment by vblagomir** [comment]
Thank you for the quick feedback. After investigation I also considered that the data is buffered. And instead I have managed to send back data from receiving peer back to the sender about the progress. So far it works ok. :-)
