### ISSUE TITLE
Question: Is it possible to save a media stream on NodeJS using SimplePeer?

### ISSUE THREAD

**Issue by nkittsteiner** [feross/simple-peer#197]
Any comments would be highly appreciated

**Comment by RationalCoding** [comment]
I don't know of any Node.js WebRTC implementations that support MediaStreams. 

If one peer is a browser, you could use media-record-stream on the browser and send that over the data channel. You can write that data to a file and you'll end up with a webm recording of your MediaStream.

If both peers are Node, you might be out of luck until a decent MediaStream implementation is available.

**Comment by nkittsteiner** [comment]
Thanks @RationalCoding  👍
