### ISSUE TITLE
Error: No WebRTC support: Specify `opts.wrtc` option in this environment

### ISSUE THREAD

**Issue by simkieu** [feross/simple-peer#198]
This won't happen if I use budo package and has "start": "budo index.js:bundle.js" in my package.json. But if I change it to "start": "node index.js", then it has this error: 
"Error: No WebRTC support: Specify `opts.wrtc` option in this environment"
Please help explain how I can get it running without budo. Thank you so much!

<img width="728" alt="screen shot 2017-08-20 at 5 02 12 pm" src="https://user-images.githubusercontent.com/11154795/29499582-81f22f10-85c9-11e7-9c88-a918100d71a6.png">

**Comment by RationalCoding** [comment]
Please read the documentation. You must specify a WebRTC implementation in Node.js.

---
### in node

To use this library in node, pass in `opts.wrtc` as a parameter:

```js
var SimplePeer = require('simple-peer')
var wrtc = require('wrtc')

var peer1 = new SimplePeer({ initiator: true, wrtc: wrtc })
var peer2 = new SimplePeer({ wrtc: wrtc })
```
---

https://github.com/js-platform/node-webrtc
https://github.com/mappum/electron-webrtc
