### ISSUE TITLE
Offer a way to munge the "local" offer

### ISSUE THREAD

**Issue by jraoult** [feross/simple-peer#20]
Would be great to give a way to patch the offer's SDP before setting it as a local description (like it is done for the "speed hack"). May be a function passed as an option to the constructor like:
```javascript
new SimplePeer({
  sdpMunger: function(sdp) {
    // transform the SDP
    return sdp;
  }
})
```

I would need it to change to configuration of the audio codec (set it in stereo mode and change the `ptime`).

**Comment by feross** [comment]
Yep, I see the use case for this. Let's name the property `sdpTransform` though. PR welcome!

**Comment by jraoult** [comment]
@feross got you ;-) I'll see what I can do.

**Comment by contra** [comment]
Can you link to the "speed hack" for reference?

**Comment by feross** [comment]
This is the "speed hack": https://github.com/feross/simple-peer/blob/4bec667b979e5f6baa2e15d3ba09d82890047584/index.js#L490-L493

**Comment by feross** [comment]
This is supported as as of 5.8.0.
