### ISSUE TITLE
Peer.send is a null property ?

### ISSUE THREAD

**Issue by andreGarvin** [feross/simple-peer#201]
I justed tried out simple peer today and tried sending a message
```js
document.getElementById('connect').addEventListener('click', () => {
    const recip = JSON.parse(document.getElementById('recip').value)
    Peer.signal(recip)
})
```
```js
Peer.send(message)
```

I keep getting this error
```bundle.js:15006 Uncaught TypeError: Cannot read property 'send' of null```

**Comment by andreGarvin** [comment]
I checked the property and the `Peer` object instance is not null and the `__proto` also has the connect method on it, could this be  bad prototype chaining the class or inheritance problem

**Comment by xemasiv** [comment]
@andreGarvin how did you solve this?

**Comment by xemasiv** [comment]
@andreGarvin how did you solve this?

**Comment by owenauch** [comment]
I'm also wondering how you solved this...

**Comment by RationalCoding** [comment]
You cannot use `peer.send()` before the connect event.

Use `peer.write()` to take advantage of the buffer.

**Comment by owenauch** [comment]
That's not my issue @RationalCoding. I'm trying to send to a peer that I've already sent to before, but for some reason in a specific case it is failing with `TypeError: Cannot read property 'send' of null`. The object instance exists and seems normal when I log it. Do you have any ideas?

**Comment by owenauch** [comment]
For example, this code is failing:
```
if (p) {
    p.send(JSON.stringify(message));
}
```

**Comment by RationalCoding** [comment]
Can you try logging `peer.connected` and `peer.destroyed` before that call to send?

**Comment by xemasiv** [comment]
In my case it was making the mistake of adding multiple `peer.on(..)` handlers (took me a lot of re-reading my code).

@owenauch if your peer1 has `._channel` property and peer2 does not, this might also be the case.

**Comment by owenauch** [comment]
What is the difference between `write` and `send`?

**Comment by nazar-pc** [comment]
`write` is a part of streaming interface, can be buffered, while `send` sends data immediately and directly through data channel: https://github.com/feross/simple-peer#memory-usage

**Comment by andreGarvin** [comment]
I am soooooo sorry I did not see earlier
