### ISSUE TITLE
Stream event fires before connect

### ISSUE THREAD

**Issue by gurupras** [feross/simple-peer#203]
Maybe this is how it's meant to work, but intuitively, one expects the `connect` event to fire before a `stream` is available. If I call `new SimplePeer` with a stream object passed in, the `stream` event fires before `connect` on the remote. 

I'm using `socket.io` as the signalling mechanism.
Should I be writing my state management logic in the `stream` event handler?

**Comment by RationalCoding** [comment]
Could you post browser and OS versions?

If I remember correctly, `connect` should fire before `stream`.

**Comment by gurupras** [comment]
OS: Windows 10 
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

I'll update this issue with some code snippets in a few hours to help test easily

**Comment by gurupras** [comment]
There's too much code across too many files. I'll work on aggregating all of it into a couple of files to paste, but for you, you should be able to test it out at: http://108.20.166.116:21949/

**Comment by gurupras** [comment]
If it helps in any way, this is essentially where I got my code from. All I did was add some (ugly) wrappers and vue components for the webcam part
https://gist.github.com/adammw/d9bf021c395835427aa0

**Comment by RationalCoding** [comment]
It seems the internal `onTrack` event is firing while the `getStats` call is waiting. There's nothing wrong with that, but I agree it is confusing...

The API doesn't guarantee that `stream` fires before `connect` and the examples don't show any sort of nesting, so I would consider this working-as-intended.

I would suggest buffering the events (ie [node-delayed-stream](https://github.com/felixge/node-delayed-stream)) or changing your logic to be more aligned with the examples (no nesting).
