### ISSUE TITLE
How to Run simple-peer on NodeJS?

### ISSUE THREAD

**Issue by peppoS37** [feross/simple-peer#204]
Hello,
I claim that I am a beginner programmer of javascript and nodeJS, but how can I run a file index that uses simple-peer libraries on NodeJS? I can only do it with npm start. Sorry for my ignorance.
G.C.

**Comment by RationalCoding** [comment]
Node.js does not implement WebRTC natively like browsers do. You will need a module. 

From the README:

To use this library in node, pass in opts.wrtc as a parameter:

```javascript
var SimplePeer = require('simple-peer')
var wrtc = require('wrtc')

var peer1 = new SimplePeer({ initiator: true, wrtc: wrtc })
var peer2 = new SimplePeer({ wrtc: wrtc })
```

**Comment by peppoS37** [comment]
Thanks!
