### ISSUE TITLE
SimplePeer ignore the iceServer config

### ISSUE THREAD

**Issue by GrenardAntoine** [feross/simple-peer#213]
I've used SimplePeer with my local network and everything work fine. I want now to connect using my stun server but no matter what address I enter for the stun server it doesn't change. The config of the iceServers seems to be ignored.

Here is my code :
   
```
let p = new SimplePeer({
    initiator: initiator,
    stream: stream, 
    trickle: false,
    config: { iceServers: [ { url: 'stun:123.123.123.123:19302' } ] }
})
```

**Comment by RationalCoding** [comment]
Can you try the standard `urls` instead:

```
let p = new SimplePeer({
    initiator: initiator,
    stream: stream, 
    trickle: false,
    config: { iceServers: [ { url: 'stun:123.123.123.123:19302' } ] }
})
```

How can you tell that the config is being ignored?

**Comment by GrenardAntoine** [comment]
I don't see the difference between your code and mine. 
Because even if their is no iceServer behind the address i still go a signal with no error. Or maybe is it normal ?

**Comment by RationalCoding** [comment]
`iceServers: [ { >>>>> urls <<<<<: 'stun:123.123.123.123:19302' } ]`
vs
`iceServers: [ { url: 'stun:123.123.123.123:19302' } ]`

**Comment by RationalCoding** [comment]
What is the error you are seeing?

**Comment by GrenardAntoine** [comment]
I don't see any errors. It is like if it was working but their is no stun server at the adress i'm pointing so i don't really understand.

**Comment by RationalCoding** [comment]
STUN isn't always required to make a connection.

**Comment by RationalCoding** [comment]
https://stackoverflow.com/a/23716086/5329546

**Comment by GrenardAntoine** [comment]
Ok i see ! The stun server will only be called if the connection can't be made without it ? Am i right ?

**Comment by RationalCoding** [comment]
Actually it seems an invalid STUN server causes the `signal` event to never fire. It's probably trying to connect and failing: https://codepen.io/RationalCoding/pen/dZWega?editors=1010

**Comment by RationalCoding** [comment]
Yes, it should only be used when a normal connection can't be made.

It seems to make the `signal` event hang, but this is expected. https://codepen.io/RationalCoding/pen/dZWega?editors=1010

**Comment by RationalCoding** [comment]
Closing as expected behaviour.
