### ISSUE TITLE
Test Windows with AppVeyor?

### ISSUE THREAD

**Issue by markandrus** [feross/simple-peer#223]
I think it would be good to have AppVeyor testing that simple-peer continues to work in Windows. I mostly worry about, e.g., wrtc continuing to work as expected when consumed by simple-peer in a Windows environment.

**Comment by feross** [comment]
I'm not sure this is worth the trouble to set up as well as dealing with the added test flakiness...

`wrtc` already has AppVeyor set up. We don't do anything platform-specific in `simple-peer` (to my knowledge. So, assuming that our `wrtc` tests pass on Linux they should pass on Windows. If that's not the case, then that is going to be a `wrtc` bug and not a `simple-peer` one and there's not really anything for `simple-peer` to do.
