### ISSUE TITLE
#215 breaks Safari

### ISSUE THREAD

**Issue by johanholmerin** [feross/simple-peer#224]
`RTCPeerConnection.getStats` in Safari does not return any item of the type `transport`, which causes a setTimeout-loop at [index.js#L644](https://github.com/feross/simple-peer/blob/cf951202d1fb94d54d34bde60eb115d843dd58fb/index.js#L644). This seems to be related to #221.

Safari also does not expose IP or port, remote or local, which causes the test `ensure remote address and port are available right after connection` to fail.

**Comment by andrefilimono** [comment]
Simple workaround:
https://github.com/andrefilimono/simple-peer/commit/e8e87c0f2b0295b2870094b4187c15d5a21aec83

It isn`t good solution, but it works :)

**Comment by RationalCoding** [comment]
Is this resolved by #228? @nazar-pc

**Comment by nazar-pc** [comment]
Yes, it is.

**Comment by RationalCoding** [comment]
Great. Thanks.
