### ISSUE TITLE
simple-peer does not work on shared hosting (https) and signaling server (https)

### ISSUE THREAD

**Issue by 2n2n** [feross/simple-peer#225]
Just want to know if simple-peer works on a shared hosting? while the signaling server is hosted on a linux VPS?

**Comment by RationalCoding** [comment]
simple-peer is agnostic to how you signal. You simply need to get the JSON object to the other peer in some way. So yes, it will work with a VPS.

**Comment by RationalCoding** [comment]
Closing as there doesn't appear to be an issue with signalling on VPSs. Feel free to comment if you've found something.
