### ISSUE TITLE
Make `signal` itself a stream?

### ISSUE THREAD

**Issue by tlrobinson** [feross/simple-peer#226]
Instead of having a special `signal` event and `signal` method, why not just have a `signal` stream, which would let you easily pipe it somewhere?

e.x. a contrived example based on https://github.com/feross/simple-peer#data-channels

```javascript
var peer1 = new SimplePeer({ initiator: true })
var peer2 = new SimplePeer()

peer1.signal.pipe(peer2.signal).pipe(peer1.signal)

peer1.on('connect', function () {
  // wait for 'connect' event before using the data channel
  peer1.send('hey peer2, how is it going?')
})

peer2.on('data', function (data) {
  // got a data channel message
  console.log('got a message from peer1: ' + data)
})
```

You could still do `peer.signal.on("data", ...)` (instead of `peer.on("signal", ...)`) and `peer.signal.write(...)` (instead of `peer.signal(...)`), of course.

**Comment by feross** [comment]
Yeah, this is an interesting idea. But the thing is that signal messages are discrete, they're not a byte stream. Node.js streams support an "object mode" for this, but I don't think W3C streams have such a mode, so I'm worried about adopting an API that will later require us to write a parser (as @RationalCoding mentioned).

Closing this for now.
