### ISSUE TITLE
Very long time to execute

### ISSUE THREAD

**Issue by Ciao121** [feross/simple-peer#229]
HI,
using this in webtorrent, adding about 100 torrents i get this:
```
[Violation] 'negotiationneeded' handler took 2851ms
[Violation] 'icecandidate' handler took 8131ms
```
This occours every time the seeder is sending update announces (every 2 min to a ws tracker)
Is that normal?

**Comment by RationalCoding** [comment]
Those are just debug warnings. 2.8 seconds isn't an unusual time to wait on an ice candidate. I'd say this is normal.

Those warnings are disabled by default under Devtools > Console > Default levels > Verbose. You must have turned them on at some point.

**Comment by Ciao121** [comment]
Thank you @RationalCoding,
I know it's just a 'info' warning. Do you think also the other value (8.1 sec) can be an expected value?

**Comment by RationalCoding** [comment]
It's a pretty long time, but not anything alarming.

**Comment by RationalCoding** [comment]
If you can, combining all of those torrents into one would help performance significantly.

**Comment by Ciao121** [comment]
Thanks you very much!
