### ISSUE TITLE
capture LIVE stream in opencv4nodejs

### ISSUE THREAD

**Issue by vijaysagi1** [feross/simple-peer#246]
Hi,

my requirement is i need to do face detection on client side (browser) and stream the object to opencv4nodejs which will do face recognition.

Q1)
While am trying to run simple-peer  the following is the error encountered: 

code: 
var SimplePeer = require('simple-peer')
// get video/voice stream
navigator.getUserMedia({ video: true, audio: true }, gotMedia, function () {})

**ReferenceError: navigator is not defined**

Q2)  pls suggest how i stream the object to opencv4nodejs

Thanks
vijay

**Comment by RationalCoding** [comment]
navigator is undefined because Node does not have access to the browser APIs for video capture. wrtc does not support MediaStreams anyways.

You could capture with FFMPEG, stream into Node, then send the video of a datachannel. That might be difficult though.

**Comment by RationalCoding** [comment]
Closing since video capture in Node is out-of-scope for simple-peer

**Comment by RationalCoding** [comment]
Or spawn a headless browser like puppeteer.
