### ISSUE TITLE
destroy() not working

### ISSUE THREAD

**Issue by dnish** [feross/simple-peer#254]
Hey,
when I call the .destroy() method on the receiver side, the connection between both peers doesn't get closed. I'm having the following callback:

```
  this.peer.on('close',() => {
            console.log("Closed");
        });
```

If the initiator calls <code>.destroy()</code>, the event is fired on both sides. If the receiver calls the method, the event is only fired on receivers side. I've tested in on Chrome for Mac v64

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. What browser? What version? Please share a complete code example that reproduces the issue.

**Comment by dnish** [comment]
It was an issue on our side, we fixed it and everything is working fine now.

**Comment by phamanhduy** [comment]
> It was an issue on our side, we've fixed it and everything is working fine now.

what is issue?
