### ISSUE TITLE
react/react native

### ISSUE THREAD

**Issue by filipef101** [feross/simple-peer#256]
Can I use this on a react native app and on a react app?

**Comment by nazar-pc** [comment]
Yes, you can with `react-native-webrtc`.
However, there are some caveats you need to be aware of until they are fixed in `react-native-webrtc`: https://github.com/feross/simple-peer/issues/221 and https://github.com/oney/react-native-webrtc/pull/415

**Comment by filipef101** [comment]
Thank you so much
