### ISSUE TITLE
self._wrtc.RTCPeerConnection is not a constructor

### ISSUE THREAD

**Issue by d3b00** [feross/simple-peer#274]

**Comment by nazar-pc** [comment]
Impossible to help without code example or any other details

**Comment by d3b00** [comment]
Using [RTC-Everywhere](https://github.com/contra/rtc-everywhere).

Code: 
```
const Peer = require('simple-peer');
const rtc = require('rtc-everywhere')();

let p1 = new Peer({ initiator: true, wrtc: rtc, trickle: false });
p1.on('signal', (data) => {
    console.log(data);
});
```

Error:
/data/data/com.desipixels.chat/files/nodejs-project/node_modules/simple-peer/index.js:82
self._pc = new (self._wrtc.RTCPeerConnection)(self.config, self.constraints)
               ^
TypeError: self._wrtc.RTCPeerConnection is not a constructor

Works fine on Windows but I get the error on Android

**Comment by nazar-pc** [comment]
This is an issue in `rtc-everywhere`, not `simpe-peer`. Open upstream issue instead, `simple-peer` can't do anything if `rtc` object doesn't contain `RTCPeerConnection` property.

**Comment by d3b00** [comment]
do you know a way through which I can run simple-peer in node?
wrtc only supports x64 bit machines :(
is there another way to run simple-peer in node without wrtc?

**Comment by nazar-pc** [comment]
There is also `electron-webrtc`, but it is older and looks like not maintained anymore and I'm not sure if it works on arm. Yet another option might be `react-native-webrtc` if you have react native app.

`simple-peer` is just a wrapper library, it needs a WebRTC implementation anyway.

**Comment by nazar-pc** [comment]
You should better ask this question in corresponding project, I personally don't know the answer: https://github.com/js-platform/node-webrtc/issues

**Comment by d3b00** [comment]
alright. thanks!
