### ISSUE TITLE
Can not send buffer in Safari

### ISSUE THREAD

**Issue by snowinszu** [feross/simple-peer#275]
When I use simplePeer.send() to send a buffer in Safari, it throws a error that "SyntaxError (DOM Exception 12): The string did not match the expected pattern.".  Btw, it works in Chrome.

**Comment by nazar-pc** [comment]
What kind of buffer are you sending?
Do you have a demo (preferably reduced) available somewhere?
Does it happen when you send data from Safari, to Safari or both?

**Comment by snowinszu** [comment]
1. Buffer from https://github.com/feross/buffer.
2. I don't have a reduced demo now.
3. I send data from Safari to Chrome.

**Comment by nazar-pc** [comment]
Mentioned buffer is just polyfill, it uses `Uint8Array` under the hood.
Can you try this demo in Safari?: https://jsfiddle.net/6h0t466p/
It will test Safari<->Safari, which is different from what you've described, but still might give useful details.

**Comment by snowinszu** [comment]
This bug happened in Safari 11.0.3, when I update it to latest, the bug disappeared!

**Comment by nazar-pc** [comment]
Safari implementation still maturing, not everything works as expected, etc.
So if this was a bug in Safari, which is already fixed, I'm closing the issue, nothing should be done in `simple-peer` in this case.
