### ISSUE TITLE
Default example unexpected token e in JSON

### ISSUE THREAD

**Issue by Jakobud** [feross/simple-peer#276]
I'm looking at the basic, default example:

```
<html>
  <body>
    <style>
      #outgoing {
        width: 600px;
        word-wrap: break-word;
      }
    </style>
    <form>
      <textarea id="incoming"></textarea>
      <button type="submit">submit</button>
    </form>
    <pre id="outgoing"></pre>
    <script src="bundle.js"></script>
  </body>
</html>
```

```
var Peer = require('simple-peer')
var p = new Peer({ initiator: location.hash === '#1', trickle: false })

p.on('error', function (err) { console.log('error', err) })

p.on('signal', function (data) {
  console.log('SIGNAL', JSON.stringify(data))
  document.querySelector('#outgoing').textContent = JSON.stringify(data)
})

document.querySelector('form').addEventListener('submit', function (ev) {
  ev.preventDefault()
  p.signal(JSON.parse(document.querySelector('#incoming').value))
})

p.on('connect', function () {
  console.log('CONNECT')
  p.send('whatever' + Math.random())
})

p.on('data', function (data) {
  console.log('data: ' + data)
})
```

I have take the JavaScript and combiled it to `bundle.js` using Browserify (also I have tried the same with webpack). I get the following error when running the example and attempting to submit anything into the input text box:

```
VM139:1 Uncaught SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at HTMLFormElement.<anonymous> (bundle.js:2688)
(anonymous) @ bundle.js:2688
```

What am I doing wrong?

**Comment by nazar-pc** [comment]
Works for me. From stack trace you've provided execution doesn't even reach `simple-peer` when you submit the form, so there is an issue in signal transmission. Make sure you've copied the whole string if you do that manually.

Would be easier if you could provide a sample of bad JSON.

Closing for now, since this doesn't appear to be an issue in `simple-peer`, but feel free to continue conversation.

**Comment by Jakobud** [comment]
I'm not sure what you mean. I create an index.html and paste in the above code. I create an app.js and paste in the JavaScript above. Then I run `browserify app.js -o bundle.js`. Then I open the webpage in a browser and attempt to submit something to the form. Then I get the error. What step(s) am I missing here?

**Comment by Jakobud** [comment]
Also what bad JSON are you talking about? Maybe I'm misunderstand what I'm supposed to be doing with this form...

**Comment by nazar-pc** [comment]
Your error is about malformed JSON. So somewhere in the process between `textContent = JSON.stringify(data)` and `querySelector('#incoming').value` JSON string gets corrupted and browser complains about this. The error you've quoted literally says just that.

What about sample of your JSON?

**Comment by Jakobud** [comment]
Okay maybe I'm misunderstanding something. Does the form only support a JSON value?

I'm pretty sure I have initiated a connection already. Here is the JSON from `index.html#1`:
```
{"type":"offer","sdp":"v=0\r\no=- 3589177446502491562 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 54860 DTLS/SCTP 5000\r\nc=IN IP4 71.211.174.252\r\na=candidate:2138393493 1 udp 2113937151 192.168.0.4 54860 typ host generation 0 network-cost 50\r\na=candidate:842163049 1 udp 1677729535 71.211.174.252 54860 typ srflx raddr 192.168.0.4 rport 54860 generation 0 network-cost 50\r\na=ice-ufrag:gXT7\r\na=ice-pwd:6XEG2RXJV2y/88SHmKq2j+on\r\na=ice-options:trickle\r\na=fingerprint:sha-256 E1:A9:97:EF:E0:6A:E2:30:68:DB:6A:1F:34:C9:4B:39:0C:A3:93:CC:81:F3:10:6D:9F:F2:42:81:C1:77:4D:8D\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}
```

And then in the other window (`index.html) after I paste in the above I get this:
```
{"type":"answer","sdp":"v=0\r\no=- 2983521192943979422 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 54573 DTLS/SCTP 5000\r\nc=IN IP4 192.168.0.4\r\nb=AS:30\r\na=candidate:2138393493 1 udp 2113937151 192.168.0.4 54573 typ host generation 0 network-cost 50\r\na=ice-ufrag:VDBr\r\na=ice-pwd:YJml1Bdq37LzYlsQAp193RpQ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 EE:F8:63:B7:38:8D:6F:37:BB:69:4A:F2:B5:60:9A:D3:7E:26:DD:67:8E:45:D6:6F:B8:50:EE:CB:06:11:00:95\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}
```

Then I paste this back again into the first window (`index.html#1`).  Then in the consoles for each window I see the connection being made (`CONNECT data: whatever0.5188351964861451`).

But then what do I do? The instructions I guess aren't clear to me. I tried typing in `hello world` into one of the forms and expected it to show up in the other but then I get the error. Am I supposed to type in a JSON value instead? What is the form of this JSON value I am to be submitting to the form? I feel like I'm  missing a step in the instructions.

**Comment by nazar-pc** [comment]
What your form supports depends on you. For signaling `simple-peer` supports both plain object and JSON strings:
https://github.com/feross/simple-peer/blob/f2cba134ae5dfc7127008ea96ceb543b93f7b06b/index.js#L179-L188

Once you get `CONNECT data: whatever0.5188351964861451`, it means that:
* you're connected
* you've already sent a useful piece of data with `p.send()` method

No need to call `p.signal()` anymore. Create a separate field and button in your form and use that for sending data. Data and signals are separate things here, don't mix them.

**Comment by Jakobud** [comment]
Oh! Okay I totally misunderstood the example then. Thank you. I thought the example was illustrating how to connect and then you could use the form to send data back and forth. I understand now. Thank you.

So in an actual production application, there would be some sort of database-driven server or something in the middle of all of this to facilitate passing the signals back and forth in order for peers to create connections, right?

Thank you again,

**Comment by nazar-pc** [comment]
Exactly. Some kind of server is needed to exchange signals and then peers can talk directly.

**Comment by Jakobud** [comment]
Great thanks. What would a server like this look like? Are there already WebRTC Signal Server libraries (Node.js) out there? Or is this something where you gotta roll your own using a database + websockets?

**Comment by nazar-pc** [comment]
It heavily depends on use case. Usually you create some kind of chat room or something. Then room ID is shared with both users so that server knows how to connect them to each other. Take a look at this: https://simplewebrtc.com/

**Comment by RationalCoding** [comment]
socket.io or signalhub are great for this. If you want something easier to setup, look at my repo simple-signal (handles calls to signal on simple-peer objects for you, and spits out fully connected peer objects!)

Manual signalling like you’re doing now technically works, but there can be ICE problems if the user is too slow.

**Comment by haidoan** [comment]
@RationalCoding thanks for useful info, btw what do you mean by 'user is too slow' in your comment?

**Comment by nazar-pc** [comment]
AFAIK there is a 30 seconds time frame during which you need to exchange signals. If you don't manage to do that in time, signals will expire.

**Comment by haidoan** [comment]
@nazar-pc thanks for your reply, btw is this rule apply for offer peer as well? coz if i set 'trickle: false' in the constructor of initial peer, it take more than 30 seconds to generate peer id as this issue [.](https://github.com/feross/simple-peer/issues/248) thanks

**Comment by haidoan** [comment]
@nazar-pc thanks for you response, i got it.
