### ISSUE TITLE
(Info) addStream API not available

### ISSUE THREAD

**Issue by folkvir** [feross/simple-peer#281]
I'm using the 9.0.0 (latest), the #250  seems to be merged but the release is not done for the moment.
Is a release planned?

**Comment by RationalCoding** [comment]
Yes, a release is planned.

@feross

**Comment by feross** [comment]
Closing in favor of https://github.com/feross/simple-peer/issues/286

**Comment by RationalCoding** [comment]
@folkvir The addStream API is available in 9.1.0
