### ISSUE TITLE
Publish new minor version

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#286]
Following on my comment here: https://github.com/feross/simple-peer/pull/250#issuecomment-380977158

Usually, whenever I make a breaking change, I make the commit message start with `BREAKING: ` so that users upgrading to the new major version can quickly scan for the breaking commit. In that commit, I write what is breaking and what (if anything) the user can do to migrate.

@RationalCoding Can you write up a description and rationale for the breakage?

Once this is documented here, I can release a new major version and include the message in the version commit, which will be fine for this release.

**Comment by feross** [comment]
Sidenote: this might cause serious issues for WebTorrent clients since I can't force update the hundreds of websites that already have WebTorrent on them.

**Comment by RationalCoding** [comment]
This renegotiate signal event is only sent if renegotiation is used. It is disabled by default and shouldn't cause issues for WebTorrent if the option is never enabled for any WebTorrent peers.

**Comment by RationalCoding** [comment]
Just never use `peer.negotiate()`, `peer.addTrack()`, or `peer.addStream()` and everything will work fine. If a peer DOES use one of those events, remote peers will crash.

**Comment by feross** [comment]
Nice, thanks for the explanation. I'll release this as a minor version then.

**Comment by feross** [comment]
Will publish when `master` is passing on CI

**Comment by feross** [comment]
Not passing, still blocked on https://github.com/feross/simple-peer/issues/283

**Comment by feross** [comment]
Published 9.1.0! Thanks @RationalCoding!
