### ISSUE TITLE
Implement renegotiation of constraints

### ISSUE THREAD

**Issue by RationalCoding** [feross/simple-peer#287]
Currently only renegotiation of media lines is supported. Due to an existing bug (see #95), it's impossible to upgrade a datachannel-only connection to a connection with mediastreams on the non-initiator side. (The initiator can upgrade it's side with no problems.)

Renegotiation of media constraints should be added for this reason and it's generally a good feature to have.

**Comment by feross** [comment]
@RationalCoding Did you link to the wrong issue. I don't think #94 is related, right?

**Comment by RationalCoding** [comment]
Yes, #95.
