### ISSUE TITLE
Remove "speed hack"

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#29]
So, I knew that the "speed hack" shouldn't be necessary with SCTP data channels, but Chrome was still including the bandwidth line in the SDPs and so I figured I'd leave the speed hack in there.

But @fippo was making fun of me at the WebRTC meetup after Google I/O for still using it, so let's get rid of it :-)

**Comment by fippo** [comment]
:+1: :-p

**Comment by feross** [comment]
Released as 5.11.0.
