### ISSUE TITLE
master's simplepeer.min.js has no removeStream() function

### ISSUE THREAD

**Issue by natotech** [feross/simple-peer#293]
Hi,

I'm trying to use simple-peer in a non-node application and I'm using simplepeer.min.js directly. The README mentions about removeStream() and addStream() but this function is not actually in simplepeer.min.js.

I don't use node so I am clueless as to whether the lack of removeStream() function in simplepeer.min.js is an issue or not. Can anybody direct me to steps if I need to do some command lines for simplepeer.min.js to be complete as described in the README.md?

**Comment by RationalCoding** [comment]
addStream and removeStream haven't been release yet. Sorry for the premature documentation update.

#286

**Comment by feross** [comment]
This feature is not part of a release yet because we still need to get the tests to pass :)

You can produce your own updated `simplepeer.min.js` file by running `npm install && npm run build` on your own git checkout of the `simple-peer` code.

**Comment by natotech** [comment]
Thanks guys for the quick responses. You rock!

**Comment by RationalCoding** [comment]
@natotech The addStream API is available in 9.1.0
