### ISSUE TITLE
addStream is not a function

### ISSUE THREAD

**Issue by Craigzyc** [feross/simple-peer#296]
I'm getting the error addStream is not a function using 9.0.0 from npm.

The github readme describes that function but the npm one doesnt.

Obviously its not included in my version. 

Is this a feature going out or a feature coming in?

If going out what version do I need to use it?

**Comment by Craigzyc** [comment]
Sorry, just noticed #281 

When is 9.1.0 being release ?

**Comment by nazar-pc** [comment]
It should have been released earlier today, but there is no git tag and 9.1.0 is not available on npm. @feross, was it pulled back or what?

**Comment by feross** [comment]
Sorry, I did an incomplete publish. Just fixed it.

**Comment by Craigzyc** [comment]
Awesome thank you. I pulled it straight from git to test. 

I'm no longer getting any errors on addStream but I'm not getting anything on the other end with 
`p.on('stream', function(stream){console.log("Received Stream")})
`
Any Ideas what to look for?

The connect event is firing on both ends.

**Comment by Craigzyc** [comment]
Ok well at first I didn't have the stream right. 
Now that I have the stream right I'm getting 

> Uncaught (in promise) TypeError: self._pc.addTrack is not a function

**Comment by nazar-pc** [comment]
What OS/Browser/environment, can you share code you're using?

**Comment by nazar-pc** [comment]
If `addTrack` is not a function in your environment, that means it doesn't support reasonably modern version of WebRTC spec. You might try to add https://github.com/webrtc/adapter

**Comment by feross** [comment]
Closing this since it doesn't seem like a simple-peer issue, but feel free to continue discussion.

**Comment by Craigzyc** [comment]
How would I use webrtc-adapter?
I tried 
`var wrtc = require('webrtc-adapter'); `
`p = new Peer({ initiator: true, wrtc: wrtc, config:config});`


and got:

> Uncaught TypeError: self._wrtc.RTCPeerConnection is not a constructor

at line 90 of index.js from simple-peer which is:
`  self._pc = new (self._wrtc.RTCPeerConnection)(self.config, self.constraints)
`

Thanks for your help

**Comment by nazar-pc** [comment]
It patches existing implementation.
So you'd do something like this (not necessarily works, but should give you an idea how to approach this):
```javascript
var wrtc = your_wrtc_implementation;
var chromeShim = require('webrtc-adapter/src/chrome/chrome_shim');
chromeShim.shimOnTrack(wrtc);
chromeShim.shimAddTrackRemoveTrack(wrtc);
```

Look at https://github.com/webrtc/adapter/blob/master/src/js/adapter_factory.js for more details on what shims can be used.
