### ISSUE TITLE
Cannot send stream from non-initiator peer to initiator peer

### ISSUE THREAD

**Issue by coderkd10** [feross/simple-peer#303]
I'm new to simple-peer and was playing with the demos listed in the readme.

As in the demo I was able send a media stream from the initiator peer to the other peer.
But when I try to do the reverse, i.e, send stream from the other peer to the initiator, the stream never arrives, i.e., `peer.on('stream', cb)` is never trigged.

I have created a simple demo to illustrate this issue - 
1. [working demo - initiator to other](https://l2lkwyzlwm.codesandbox.io/) ([src](https://codesandbox.io/s/l2lkwyzlwm))
2. [not working demo - other to initiator](https://2nx22nmqp.codesandbox.io/) ([src](https://codesandbox.io/s/2nx22nmqp))

**Comment by nazar-pc** [comment]
It looks like `peer.negotiate()` method is not documented, but apparently needs to be called.
@RationalCoding, I remember there was some limitation concerning streams from non-initiator, can you clarify?

**Comment by RationalCoding** [comment]
I would probably just wait for #287 to be implemented. I plan to do it fairly soon.

**Comment by t-mullen** [comment]
WebRTC constraints are deprecated and transceivers are the new way to do this, so my answer above it a little dated.

But yes, passing the same number of streams on both sides (empty or otherwise) will bypass this issue.
