### ISSUE TITLE
p.on stream event not calling

### ISSUE THREAD

**Issue by rubenperezpro** [feross/simple-peer#305]
hi , (sorry for my bad english).

I am trying to record on a node server a video stream from a browser. i get offer and answer and get status connected, but i dont get event p.('stream') on node ..... 

thx for your help

**Comment by nazar-pc** [comment]
Media streams are not supported on Node.js yet, but expect it to be available relatively soon.
The primary issue here is that underlying node-webrtc doesn't support media streams yet, so there is nothing simple-peer can do about it.
You can follow this issue to track progress: https://github.com/js-platform/node-webrtc/issues/396
