### ISSUE TITLE
self._pc.addStream is not a function

### ISSUE THREAD

**Issue by DuckerMan** [feross/simple-peer#309]
peer1.addStream(stream);

I get stream from getUserMedia.

Node.js LTS 8.11.1
Electron 2.0.0
Chrome 61

**Comment by nazar-pc** [comment]
There is no `self._pc.addStream` code in current version.
Make sure to install latest release of simple-peer from NPM.

**Comment by nazar-pc** [comment]
Also see #302 that is related to Electron

**Comment by DuckerMan** [comment]
Ok, now i got error:

self._pc.addTrack is not function

**Comment by DuckerMan** [comment]
My version of Simple Peer is 9.1.1

**Comment by nazar-pc** [comment]
This is Electron's issue, modern browsers including Chrome will work fine.
Electron has strange WebRTC implementation that doesn't necessary follow Chromium despite using it as foundation.
See #296 and #302 for details and possible workarounds. You can also vote/comment on relevant issue in Electron repository.
