### ISSUE TITLE
error while attempting to run on React Native 0.55

### ISSUE THREAD

**Issue by nervouscat** [feross/simple-peer#316]
Hello Feross,

Hope all is well,

I was attempting to use simple-peer with the latest version of React-Native and got the following error: 

**error: bundling failed: Error: Unable to resolve module `buffer` from `.../node_modules/safe-buffer/index.js`: Module `buffer` does not exist in the Haste module map**

and this is my package.json file:

```
{
  "name": "dstest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "simple-peer": "^9.1.2"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.0.1",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Please let me know if there is anyway I can help in debugging this as well.

Thank you in advance!

**Comment by nazar-pc** [comment]
This is something crazy with React Native. I've seen similar errors when tried it last time, but after project re-creation I've got it working somehow. There is nothing simple-peer can or should do about this, you'll have better luck asking in React Native community about this.

**Comment by D1plo1d** [comment]
This previously posted solution worked for React Native `0.56.0` for me: https://github.com/feross/simple-peer/issues/109#issuecomment-271428446

**Comment by aleritty** [comment]
I'm experiencing the same error but not using react-native, but standard npm install in a nodejs project.

The error about Buffer isn't present if I npm uninstall simple-peer and reoccurs when I npm install it
