### ISSUE TITLE
Removing an on.("event") handler

### ISSUE THREAD

**Issue by owenauch** [feross/simple-peer#325]
Is there any way to remove an `on.("event")` handler? Like if I add `on.("data", function() {})` but decide that later I want to use a different behavior when the peer receives data. Can I somehow remove the `.on("data")` handler and define a new one? Right now, if you define `on.("event")` twice, it will execute the behavior of both handlers.

**Comment by nazar-pc** [comment]
There is `off` and some other methods, you can see all of them in Node.js API documentation: https://nodejs.org/api/events.html#events_class_eventemitter

**Comment by owenauch** [comment]
Thanks!
