### ISSUE TITLE
data undefined in signal when called in creation of initiator peer

### ISSUE THREAD

**Issue by owenauch** [feross/simple-peer#326]
I'm creating a new peer with option `initiator: true`, which should immediately trigger `peer.on('signal')`. However, I'm getting an error in `simple-peer/index.js` on `Peer.prototype.signal` saying that data is undefined. Here is the code for that part that is failing:
```
Peer.prototype.signal = function (data) {
  var self = this
  if (self.destroyed) throw makeError('cannot signal after peer is destroyed', 'ERR_SIGNALING')
  if (typeof data === 'string') {
    try {
      data = JSON.parse(data)
    } catch (err) {
      data = {}
    }
  }
  self._debug('signal()')

  if (data.renegotiate) {
    self._debug('got request to renegotiate')
    self._needsNegotiation()
  }
```
`data` is undefined, so when it runs `if(data.renegotiate)`, it responds with `TypeError: Cannot read property 'renegotiate' of undefined`.

My code looks like this: 
```
const peer = new Peer({
      initiator: true,
      wrtc: wrtc,
      trickle: false,
      reconnectTimer: 300
});

peer.on("signal", function(SDP) {
    console.log("made it into peer signal")
}
```

**Comment by nazar-pc** [comment]
Make sure to pass an object or JSON string when calling `peer.signal()`. Error suggests that you're calling it with `undefined`.

**Comment by RationalCoding** [comment]
Is the signal event ever emitting undefined, or are you passing undefined into Peer.signal?

**Comment by owenauch** [comment]
Wait, there was an errant `peer.signal()` call below it that was running before that event could fire with `undefined` for data. Thank you both for the help.
