### ISSUE TITLE
Error signal in Firefox and Chrome

### ISSUE THREAD

**Issue by webivan1** [feross/simple-peer#327]
http://prntscr.com/juuz4q
Hi. I used example yours code on github.
Error: InvalidStateError: Cannot set remote offer in state have-local-offer.
Example: var p = new Peer({ initiator: location.hash === '#1', trickle: false }) p.on('error', function (err) { console.log('error', err) }) ...

**Comment by nazar-pc** [comment]
You need to create initiator on one side and responder on the other side. Looks like you have 2 initiators right now.

**Comment by webivan1** [comment]
Sorry! I was not understand you.
```
const p = new Peer({
  initiator: true,
  trickle: false
});
// ...
this.$refs.form.addEventListener('submit', function (ev) {
  ev.preventDefault()
  // Error: InvalidStateError: Cannot set remote offer in state have-local-offer
  p.signal(JSON.parse(document.querySelector('#incoming').value))
});
```
When I do p.signal(data) shown error

**Comment by nazar-pc** [comment]
You need to create an instance with `initiator: true` in for one side and with `initiator: false` on the other side.

**Comment by webivan1** [comment]
Thanks!
It is work.
