### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data

### ISSUE THREAD

**Issue by ilDon** [feross/simple-peer#330]
I'm trying to send data through a slow network, but it's failing. 

Initially I was doing it with `peer.send(data)`, but it was failing even with very small amounts of data (few KBs) with error: `DOMException: Failed to execute 'send' on 'RTCDataChannel': Could not send data`.

I then replaced `.send` with `.write`as explained in issue #170 . Now I'm able to send small amounts of data, but when trying to send ~500KB I get the error "NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data".

**Comment by RationalCoding** [comment]
Your chunks are too large and don't fit inside a single call to `send`. simple-peer doesn't chunk your stream for you.

https://www.npmjs.com/package/chunk-stream
