### ISSUE TITLE
Error: cannot signal after peer is destroyed

### ISSUE THREAD

**Issue by olgeorge** [feross/simple-peer#338]
What is the proper way to tear down the connection?

I establish a WebRTC connection using a `SimplePeer` object, but then I need to drop the connection and reconnect. I call the `simplePeer.destroy()`, create a new `SimplePeer` object and do the signalling part, but I get the following error:

```
Error: cannot signal after peer is destroyed
```

What am I doing wrong? Same issue as this one: https://github.com/feross/simple-peer/issues/101

**Comment by RationalCoding** [comment]
Do you create new Peer objects on both sides of the connection? Destroying a peer locally will destroy the remote peer it’s connected to.

**Comment by RationalCoding** [comment]
Also, please post your console logs with debugging enabled.

`peer._debug = console.log`

**Comment by phamthecuong** [comment]
I also have the same problem, please show me the solution to this error.

**Comment by nazar-pc** [comment]
@phamthecuong it is impossible to help you without any details. It is typically caused by wrong order of methods calls, but where exactly depends on your code.

**Comment by olgeorge** [comment]
@RationalCoding was right after all. I did call a simple peer object after it was destroyed due to the fact that I didn't remove the event listener on the signalling source, so I would signal the old peers with offers intended for new peers

@phamthecuong you can check out my implementation below. It's a client-server wrapper around simple-peer with auto reconnect with signalling performed over websockets, but you can easily replace the latter with whatever means of exchanging offers you use
https://github.com/olgeorge/react-electron-webrtc-phaser/blob/master/app/services/peerConnection.js

**Comment by chetanpandey1266** [comment]
```js

        const connectionRef = useRef();

    const callUser = (id) => {
        setCallEnded(false);
        setReceivingCall(true);
        setCallAccepted(false);
        console.log(id)
        const peer = new Peer({
            initiator:true, 
            trickle:false, 
            stream: stream
        })
        // debugger;
        peer.on("signal", (data) => {
            socket.emit("callUser", {
                usedToCall: id,
                signalData: data,
                from: me,
                name: name 
            })
        })

        // Received a remote video stream, which can be displayed in a video tag
        peer.on("stream", (stream) => {
            userVideo.current.srcObject = stream;
        })

        socket.on("callAccepted", (signal) => {
            setCallAccepted(true); 
            peer.signal(signal); 
        })

        connectionRef.current = peer;
    }

    const answerCall = () => {
        setCallAccepted(true); 
        const peer = new Peer({
            initiator: false,
            trickle: false,
            stream: stream 
        })

        peer.on("signal", (data)=> {
            socket.emit("answerCall", {signal:data, to:caller});
        })

        peer.on("stream", (stream) => {
            userVideo.current.srcObject = stream;
        })

        peer.signal(callerSignal)
        connectionRef.current = peer;
    }

    const leaveCall = () => {
        setCallEnded(true);
        connectionRef.current.destroy();
    }

```

I am also doing the same thing but getting error. @olgeorge  can you suggest where  I am doing wrong. I don't have much knowledge of class components so your code was not so helpful to me.

**Comment by chetanpandey1266** [comment]
I had 9.11.0 version and I switched to 9.6.2 but for this version also its giving the same error on the third consecutive call

**Comment by Mihai-github** [comment]
Any updates on this? How can we destroy both peers' connections for example when reloading the page because event if I call connectionRef.current.destroy() i get the following error.

`Uncaught TypeError: connectionRef.current.destroy is not a function`

**Comment by ahmdsdk** [comment]
> ```js
>         const connectionRef = useRef();
> 
>     const callUser = (id) => {
>         setCallEnded(false);
>         setReceivingCall(true);
>         setCallAccepted(false);
>         console.log(id)
>         const peer = new Peer({
>             initiator:true, 
>             trickle:false, 
>             stream: stream
>         })
>         // debugger;
>         peer.on("signal", (data) => {
>             socket.emit("callUser", {
>                 usedToCall: id,
>                 signalData: data,
>                 from: me,
>                 name: name 
>             })
>         })
> 
>         // Received a remote video stream, which can be displayed in a video tag
>         peer.on("stream", (stream) => {
>             userVideo.current.srcObject = stream;
>         })
> 
>         socket.on("callAccepted", (signal) => {
>             setCallAccepted(true); 
>             peer.signal(signal); 
>         })
> 
>         connectionRef.current = peer;
>     }
> 
>     const answerCall = () => {
>         setCallAccepted(true); 
>         const peer = new Peer({
>             initiator: false,
>             trickle: false,
>             stream: stream 
>         })
> 
>         peer.on("signal", (data)=> {
>             socket.emit("answerCall", {signal:data, to:caller});
>         })
> 
>         peer.on("stream", (stream) => {
>             userVideo.current.srcObject = stream;
>         })
> 
>         peer.signal(callerSignal)
>         connectionRef.current = peer;
>     }
> 
>     const leaveCall = () => {
>         setCallEnded(true);
>         connectionRef.current.destroy();
>     }
> ```
> 
> I am also doing the same thing but getting error. @olgeorge can you suggest where I am doing wrong. I don't have much knowledge of class components so your code was not so helpful to me.

I faced the same issue you have to unsubscribe to the socket.io callAccepted listener when peer is closed:

`
peer.on('close', () => {
    console.log('peer closed');
    socket.off("callAccepted");
});
`

**Comment by Ankur800** [comment]
> `peer.on('close', () => { console.log('peer closed'); socket.off("callAccepted"); });`

@ahmdsdk Working perfectly fine!
