### ISSUE TITLE
instanceof ArrayBuffer returning false when it should return true

### ISSUE THREAD

**Issue by MacroChip** [feross/simple-peer#339]
https://github.com/feross/simple-peer/blob/13b56be752fb8d5c8bfc0835e6bde489ef1d9845/index.js#L816

This check is not passing for me. I am using node v8.10.0, simple-peer 9.1.2, and webtrc 0.1.5. Does this line need to switch to the fix used in https://github.com/feross/buffer/pull/170/files ? Right now I am using Buffer.from in my application code.

**Comment by RationalCoding** [comment]
So you're getting an ArrayBuffer out of the stream instead of a Buffer?

**Comment by MacroChip** [comment]
No, sorry. I made a mistake. The actual problem was that I read the documentation incorrectly. I didn't realize that the Buffer I'm getting in my app shares memory with the originating ArrayBuffer from the WebRTC implementation. I was getting errors due to this. Should this line change to `if (data instanceof ArrayBuffer) data = Buffer.from(Buffer.from(data))` or is this obvious to more experienced developers?

**Comment by RationalCoding** [comment]
I'm not entirely sure how two calls to `Buffer.from` is different from one, but it seems you've solved the issue you were having. 👍

**Comment by RationalCoding** [comment]
Interesting. How/why did you modify that ArrayBuffer? Cloning every buffer seems it would have a performance impact.
