### ISSUE TITLE
Restart an existing SimplePeer connection

### ISSUE THREAD

**Issue by ilDon** [feross/simple-peer#341]
I'm trying to "restart" an existing connection.

Assuming connection `const peer = { first: new Peer(... args) }`, I can't recreate a new connection between the same two peers on `peer.first` without reloading the page (when reloading the page the connection is (re)established without any issue).

I have tried to the following:

    // "first" connection - [displaying only the code of the initiator]
    const peer = { userA: new Peer({ initiator: true, trickle: false }) };
    
    // [omitted code up to `.connected = true`]
    
    peer.userA.destroy(); // with and without the optional `error message`
    destroy peer.userA; // both after calling `destroy()` and without calling `destroy()`

    // "second" connection - [displaying only the code of the initiator]  
    peer.userA = new Peer({ initiator: true, trickle: false });

Unfortunately the "second" connection won't connect, both when the "first" connected, and when it did not.

The "first" connection in the console appears like this:

    allowHalfOpen:false
    answerConstraints:{}
    channelConfig:{}
    channelName:"7127337a05636fb1ba616871719788627bd22941"
    config:{iceServers: Array(2)}
    connected:true
    constraints:{}
    initiator:true
    localAddress:"XXX.XXX.XXX.XXX" // correct IP
    localPort:58308
    offerConstraints:{}
    readable:true
    remoteAddress:"XXX.XXX.XXX.XXX" // correct IP
    remoteFamily:"IPv4"
    remotePort:61205
    sdpTransform:ƒ (e)
    streams:[]
    trickle:false
    writable:true
    ...

The "second" connection, however, is missing some crucial data (e.g. IP), both in the `initiator` and in the `receiver`. The initiator appears like this in the console:

    allowHalfOpen:false
    answerConstraints:{}
    channelConfig:{}
    channelName:"dfe7107551bf3ebf4e812b463882b5b52f6715ed"
    config:{iceServers: Array(2)}
    connected:false
    constraints:{}
    initiator:true
    localAddress:undefined
    localPort:undefined
    offerConstraints:{}
    readable:true
    remoteAddress:undefined
    remoteFamily:undefined
    remotePort:undefined
    sdpTransform:ƒ (e)
    streams:[]
    trickle:false
    writable:true
    ...

The second receiver has also `channelName:null`.

Is it a but, am I missing something, or is it forbidden to reinitiate a connection between the same two peers without reloading the page?

**Comment by RationalCoding** [comment]
When either peer object taking part in a connection is destroyed, the connection and both peers are no longer valid and should be discarded. You can’t reuse either peer object and need to create new peer objects for both sides.

Please post your peer debug logs with `peer._debug = console.log` for all Peer objects.

**Comment by RationalCoding** [comment]
I've noticed that both of your peers have `initiator:true`. This is incorrect, only one should be the initiator.

**Comment by nazar-pc** [comment]
You need to re-create connections on both ends from scratch as @RationalCoding already said.

**Comment by RationalCoding** [comment]
Here is the issue:
```
SimplePeer debugger:  signal() <--- What is this signaling data? Which peer (first or second), is it called on?
SimplePeer debugger:  destroy (error: %s) InvalidStateError: Failed to set remote answer sdp: Called in wrong state: kStable
```
You are calling `.signal()` on the userA side after the first peer object was destroyed but before the second even sends an offer. 

The `Error: Ice connection failed.` is just because the `userA` side failed to connect.

It seems there's quite a few problems with how you are signalling. Try to keep messages intended for a connection completely separate, so they don't accidentally go to the wrong peer object. Signalling can go wrong in a lot of places when using multiple peers, especially if you are trying to use the same signalling channel.

I do have a signalling module that can give you basic channel separation and a connection model if you're interested in using it or reading the code: https://github.com/RationalCoding/simple-signal

Closing as this doesn't appear to be an issue in simple-peer, but feel free to continue discussion.

**Comment by ilDon** [comment]
I am doing that. I am recreating from scratch the connection. As you can see from the logs, both the `initiator` and the `receiver` objects are even set to undefined (after calling `destroy()`

**Comment by ilDon** [comment]
@RationalCoding thanks for pointing out that, I was indeed having the issue you described.

No I've fixed that part, but I'm still unable to re-create a new connection after the original has been destroyed.

Now the console shows on both ends the correct flow, but for some reason the second time I try to connect the same peers (without reloading the page), the connection fails.

The logs for the `initiator`:

    Initiator starts connection procedure
    SimplePeer debugger:  starting batched negotiation
    SimplePeer debugger:  start negotiation
    SimplePeer debugger:  signalingStateChange %s have-local-offer
    SimplePeer debugger:  createOffer success
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) new gathering
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) new complete
    SimplePeer debugger:  signal
    Initiator has received the response code from the receiver
    SimplePeer debugger:  signal()
    SimplePeer debugger:  flushing sender queue []
    SimplePeer debugger:  negotiate
    SimplePeer debugger:  signalingStateChange %s stable
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking complete
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) connected complete
    SimplePeer debugger:  maybeReady pc %s channel %s true false
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) completed complete
    SimplePeer debugger:  maybeReady pc %s channel %s true false
    SimplePeer debugger:  on channel open
    SimplePeer debugger:  maybeReady pc %s channel %s true true
    SimplePeer debugger:  connect local: %s:%s remote: %s:%s XXX.XXX.XXX.XXX 55569 XXX.XXX.XXX.XXX 59593
    SimplePeer debugger:  connect
    Peers are communicating
    Initiator has called destroy()
    Peer object: undefined
    Initiator starts connection procedure
    SimplePeer debugger:  starting batched negotiation
    SimplePeer debugger:  start negotiation
    SimplePeer debugger:  signalingStateChange %s have-local-offer
    SimplePeer debugger:  createOffer success
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) new gathering
    Initiator has received the response code from the receiver
    SimplePeer debugger:  signal()
    SimplePeer debugger:  flushing sender queue []
    SimplePeer debugger:  negotiate
    SimplePeer debugger:  signalingStateChange %s stable
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking gathering  <-- from here the second connection process of the initiator looks different
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking complete
    SimplePeer debugger:  signal
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) failed complete
    SimplePeer debugger:  destroy (error: %s) Ice connection failed.
    SimplePeer onError: Error: Ice connection failed.
    at o (simplepeer.min.js:1)
    at r._onIceStateChange (simplepeer.min.js:1)
    at RTCPeerConnection.t._pc.oniceconnectionstatechange (simplepeer.min.js:1)
    (anonymous) @ simple-peer.service.ts:96
    d @ simplepeer.min.js:1
    n.emit @ simplepeer.min.js:1
    r._destroy @ simplepeer.min.js:1
    r.destroy @ simplepeer.min.js:1
    r._onIceStateChange @ simplepeer.min.js:1
    t._pc.oniceconnectionstatechange @ simplepeer.min.js:1

The logs for the `receiver`:

    Receiver has received the offer code
    SimplePeer debugger:  signal()
    SimplePeer debugger:  signalingStateChange %s have-remote-offer
    SimplePeer debugger:  flushing sender queue []
    SimplePeer debugger:  negotiate
    SimplePeer debugger:  signalingStateChange %s stable
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking new
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking gathering
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking complete
    SimplePeer debugger:  signal
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) connected complete
    SimplePeer debugger:  maybeReady pc %s channel %s true false
    SimplePeer debugger:  on channel open
    SimplePeer debugger:  maybeReady pc %s channel %s true true
    SimplePeer debugger:  connect local: %s:%s remote: %s:%s XXX.XXX.XXX.XXX 59593 XXX.XXX.XXX.XXX 55569
    SimplePeer debugger:  connect
    Peers are communicating
    SimplePeer debugger:  on channel close
    SimplePeer debugger:  destroy (error: %s) undefined
    Receiver has received the destroy request and has emitted the onClose event
    Peer object: {}
    Receiver has received the offer code
    SimplePeer debugger:  signal()
    SimplePeer debugger:  signalingStateChange %s have-remote-offer
    SimplePeer debugger:  flushing sender queue []
    SimplePeer debugger:  negotiate
    SimplePeer debugger:  signalingStateChange %s stable
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking new
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking gathering
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) checking complete
    SimplePeer debugger:  signal
    SimplePeer debugger:  iceStateChange (connection: %s) (gathering: %s) failed complete  <-- from here the second connection process of the receiver looks different
    SimplePeer debugger:  destroy (error: %s) Ice connection failed.
    SimplePeer connection error: Error: Ice connection failed.
    at o (simplepeer.min.js:1)
    at r._onIceStateChange (simplepeer.min.js:1)
    at RTCPeerConnection.t._pc.oniceconnectionstatechange (simplepeer.min.js:1)
     (anonymous) @ simple-peer.service.ts:96
    d @ simplepeer.min.js:1
    n.emit @ simplepeer.min.js:1
    r._destroy @ simplepeer.min.js:1
    r.destroy @ simplepeer.min.js:1
    r._onIceStateChange @ simplepeer.min.js:1
    t._pc.oniceconnectionstatechange @ simplepeer.min.js:1

I've checked the status of WebRTC connections at `chrome://webrtc-internals/` (Google Chrome 67.0.3396.99), and everything looks fine. When the first connection is established, it does appear in the connections list, and after `destroy()` has been called by the initiator the connection is removed (after few seconds).

**Comment by iranagame** [comment]
Have you found a solution for this? I have a exact issue like this.
@ilDon
