### ISSUE TITLE
min.js doesn't parse correctly in Edge

### ISSUE THREAD

**Issue by didlie** [feross/simple-peer#344]
min.js doesn't parse correctly in Edge... ?!?

**Comment by nazar-pc** [comment]
Could you provide any details like what error you're getting exactly?

**Comment by didlie** [comment]
HTML1506: Unexpected token.
simple.html (17,1)

 SCRIPT57345: SCRIPT57345: Could not complete the operation due to error c004e001.
simple-peer.js (1,71626)

("undefined"==typeof window)throw o("No WebRTC support: Specify `opts.wrtc` option in this environment","ERR_WEBRTC_SUPPORT");else throw o("No WebRTC support: Not a supported browser","ERR_WEBRTC_SUPPORT");

**Comment by nazar-pc** [comment]
Looks like your browser doesn't support WebRTC just like error says. What browser is it?

**Comment by didlie** [comment]
It supports initiation of WebRTC throgh my own scripts, it just doesn't accept some syntax in min.js, near where simple-peer does the error check... the error is never thrown. The script gets a parse error with Unexpected Token "."

**Comment by nazar-pc** [comment]
From what I see unexpected token is in your HTML code. In addition to this quoted snippet doesn't contain `.`.

**Comment by didlie** [comment]
make a little html file and include min.js as an src='' and check it out in Edge... thanks in advance

**Comment by RationalCoding** [comment]
error c004e001 is a WebRTC error relating to badly formed STUN or TURN urls. Specifically, STUN urls aren't supported in Edge.

I'm guessing the script you're using is adapter.js? Either way, you need to filter out STUN urls from your config. https://github.com/webrtc/adapter/issues/446

**Comment by didlie** [comment]
thank you, it is a transient error, so yes filtering. ... also trying to adapt this to a non-None methodolgy. I'm very frustrated by the lack of an option to delay the destroy() and page-refresh events without hacking/digging/long hours and then recompiling the min.js.... I'm going to cut out the good parts and start a new repository. There are many good parts of this code and the browser version is more important than the Node version, because this is WebRTC, not a Node chat!
