### ISSUE TITLE
Support for "Unified Plan"

### ISSUE THREAD

**Issue by ilDon** [feross/simple-peer#351]
As reported at [https://webrtc.org/web-apis/chrome/unified-plan/](https://webrtc.org/web-apis/chrome/unified-plan/),

> Google is planning to transition Chrome’s WebRTC implementation from the current SDP format (called “Plan B”) to a standards conformant format (“Unified Plan”, draft-ietf-rtcweb-jsep)

[WebRTC M68 branch (cut at r23360)](https://groups.google.com/forum/#!msg/discuss-webrtc/nDdDqIBtFBM/bf_0eknmAwAJ) has taken the transition into phase 2 (`Make the API feature generally available`), so now:

> Web developers can experiment with the new format by specifying {sdpSemantics: "unified-plan"} in the RTCPeerConnection constructor

In phase 3 (in ~3 months) the `Unified Plan` format will be the default standard, and in phase 4 (in ~ 7 months) it will be the only choice available.

Will simple-peer still work with the new standard?

**Comment by nazar-pc** [comment]
Unified Plan is already used in Firefox and other browsers with Chrome being a notable exception.
I don't see why it wouldn't work in Chrome after this change.

**Comment by fippo** [comment]
the timeline for that has changed. In particular this is currently leading to [interop issues](https://bugs.chromium.org/p/chromium/issues/detail?id=872431)

**Comment by t-mullen** [comment]
I think with #440, we support Unified Plan. The interop issues mentioned seem to be resolved in Firefox source, Chrome 73.0.3683.86 and Safari Technology Preview Release 78.

Please reopen this issue if I have missed anything.
