### ISSUE TITLE
MediaStream issue when not on same network

### ISSUE THREAD

**Issue by tgoldenberg** [feross/simple-peer#36]
Hi, I am new to WebRTC but used this library to build an app with video chat. When I used it locally (with an Incognito browser) it worked fine, and when I tested with two computers on Heroku it worked fine as well. Now I am finding that when I have a chat between two users on different networks (or different states, countries, etc.), it doesn't work. Why might this be? I plugged in a bunch of console.logs and saved the incoming MediaStream as a global var to see if I could get the video to come in by playing around in the browser console, but no luck. Is this an issue with SimplePeer or a glitch in my code? It must be one or the other. Here is a Gist. https://gist.github.com/tgoldenberg/80ba89f193b99724ff26

It may be somewhat confusing. The example I based off of, the PusheRTC repo (on Github), uses a 'presence-chat', while I used a private 1-1 chat with Pusher. I was finding difficulties negotiating who would be the initiator:true peer, so I create an event that triggers the initiator:true. Everything else should seem fairly straightforward. 

I really hope someone will be able to tell me what is going wrong, and how I can fix it. Thank you!

**Comment by tgoldenberg** [comment]
So as I mentioned, being new to webRTC I neglected the fact that STUN servers don't always work due to firewalls, and it is necessary to fall back to TURN servers. I eventually found this out, and ended up using a service (Xirsys), which solved the issue. I might recommend adding a sidenote in the docs, though. It would have prevented my own freaking out ;).

**Comment by feross** [comment]
Thanks for the suggestion. I'll add a note to the readme.
