### ISSUE TITLE
How can I get a non minified version of simplepeer.min.js?

### ISSUE THREAD

**Issue by PokerCurve** [feross/simple-peer#37]

**Comment by feross** [comment]
Clone the github repo and then run:

```
npm install
browserify -s SimplePeer -r ./ > simplepeer.js
```

**Comment by feross** [comment]
Also, you can inspect the source code here: https://github.com/feross/simple-peer/blob/master/index.js

**Comment by PokerCurve** [comment]
Thanks! This repository should have more stars.

**Comment by feross** [comment]
Thanks!

**Comment by PokerCurve** [comment]
Hey @feross 

I'm not able to establish a p2p connection on my LAN without the use of a STUN server. Using your example where the peers exchange signalling data on the same page doesn't work without an internet connection. 

I am working on a project where a peer can stream video to a few others. When streaming video to more than 1 peer my CPU usage shoots through the roof. Is p2p video chat using WebRTC limited to one connection? My understanding is that in cases where there are say >5 participants in a video chat you will instead have to relay the video via a server.  

Another thing I have noticed is that in the signalling data the number of ICE candidates generated fluctuates a lot, especially when streaming video. Is this something I should be concerned about?

**Comment by feross** [comment]
@PokerCurve You need a STUN server even when you're trying to connect to peers on your local LAN or in the same page. This is required by the WebRTC spec, for a reason that I don't fully understand. Maybe @fippo could give an explanation?

**Comment by feross** [comment]
@PokerCurve 

> Is p2p video chat using WebRTC limited to one connection?

Each peer connection object represents a connection to one peer. You can make as many as you like to connect all peers, but you'll have performance issues when you get too many.

 >  in the signalling data the number of ICE candidates generated fluctuates a lot, especially when streaming video. Is this something I should be concerned about?

This is normal and dependent on the interfaces available on your machine and which networks you are connected to. I would not worry about it.

**Comment by fippo** [comment]
@feross no you don't need a stun server on the local network. Where does the spec say that?
Even though with recent modifications from https://groups.google.com/forum/#!topic/discuss-webrtc/bMOsMFx7PFc you might have to in the future.
