### ISSUE TITLE
addStream on non-initiator with peers mesh

### ISSUE THREAD

**Issue by igorcouto** [feross/simple-peer#370]
Hi, 

I'm facing problems adding stream on non initiator side.

I have followed #287 , #303  (setting contraints before addStream) and adding offers and answers contraints, but the non initiator cannot add stream after initial connection.

Is there some clarifying material or docs of what I need to to to add Stream on non initiator side in a peer mesh?

**Comment by t-mullen** [comment]
This can be tricky as it sometimes requires an out-of-band signal to change constraints. It could probably benefit from being included in an "advanced usage" guide, but I'd be happy to clear up what needs to be done here.

I'm assuming you are starting with both peers refusing to receive?

```javascript
var p1 = new Peer({initiator:true, offerConstraints: {
      offerToReceiveVideo: false,
      offerToReceiveAudio: false
    })
var p2 = new Peer({initiator:false, answerConstraints: {
      offerToReceiveVideo: false,
      offerToReceiveAudio: false
    })
```

**Comment by igorcouto** [comment]
I wasn't, but now i was passing as that. Same behaviour.

Then, on the non-initiator side, i was setting constraints, but now I'm in doubt.
```
if (this.peer.initiator){
          this.peer.setConstraints(offerConstraints);
          
        } else {
          this.peer.setConstraints(answerConstraints);
        }
```

As I'm passing answerContraints to false on non-initiator, I have to pass true now? Or pass on the offer contraints ?

**Comment by t-mullen** [comment]
I wouldn't use the `setConstraints` method to set initial constraints. It's called after the offer is generated.

**Comment by igorcouto** [comment]
Sorry, my fault. I was calling just before the non-initiator gets media stream.
        
```
        if (!this.peer.initiator){
          this.peer.setConstraints(offerConstraints);
          
        } else {
          this.peer.setConstraints(answerConstraints);
        }
        this.peer.addStream(stream);
```

**Comment by t-mullen** [comment]
Ah ok. When you're ready to add a stream to the non-initiator, you need to change the *initiator's* offerConstraints to true.

So, you need to change the OTHER peer's constraints. This requires some kind of signaling message.

```
newConstraints = { offerToReceiveAudio: true, offerToReceiveVideo: true }
signalingChannel.send('requestToChangeConstraints', newConstraints)
this.peer.addStream(stream);
```

```
signalingChannel.on('requestToChangeConstraints', (newConstraints) {
  this.peer.setConstraints(newConstraints);
})
```

**Comment by t-mullen** [comment]
When renegotiation completes due to the call to `addStream`, the new constraints will be used.

**Comment by igorcouto** [comment]
Nice. with signalling it works.
The only observation is that I need to addStream to all peers on mesh, but that's not a problem.

It's time to work on the case where a new peer enter on a room with something already streaming, but I think is a matter of just to test if there's a stream and then building the peer standard way (with stream and no contraints, right)?

**Comment by t-mullen** [comment]
The mesh won't change anything, connections are just one peer to one peer.

If you want to add a stream on first connection, just do it without renegotiation (by providing streams in the constructor).

```
var p1 = new Peer({initiator:true, offerConstraints: {
      offerToReceiveVideo: true, // these must be true if the other peer is providing streams
      offerToReceiveAudio: true
    })
var p2 = new Peer({initiator:false, answerConstraints: {
      streams: [ /* all your MediaStreams */],
      offerToReceiveVideo: false, // these must be false if the other peer is not providing streams
      offerToReceiveAudio: false
    })
```

**Comment by Bernard-Murphy** [comment]
setConstraints is undefined, also I don't see the offerConstraints/answerConstraints when I console log my peers. Have they been renamed to something else since this post?
