### ISSUE TITLE
Firefox 63 - peer.destroy() -> InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

### ISSUE THREAD

**Issue by schirrmie** [feross/simple-peer#375]
Hi,

with Firefox 63.0 i will get the following error by peer.destroy()

`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

In Chrome all is fine. I can't catch the error or anything else. I don't know how to solve this. Any help?

Regards
schirrmie

**Comment by t-mullen** [comment]
Can you make sure the error is in the call to `peer.destroy()` by wrapping it in a try block?

```javascript
try {
  peer.destroy()
} catch (err) {
  console.log('error was thrown in peer.destroy')
}
```

**Comment by schirrmie** [comment]
Hi,

I tried with try/catch but it does not work. I always get the error
`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`
but not the catch console.log. Only if I remove the peer.destroy the error is gone.
I don't know if this firefox related. I searched a little bit but don't find anything about it.

Regards
schirrmie

**Comment by t-mullen** [comment]
The only thing I could find on this issue is that it might occur with a video element that is trying to use a destroyed video source. Is it possible some part of your application is attempting to display a mediastream from the destroyed peer inside a video element?

**Comment by schirrmie** [comment]
Hi,

yeah maybe something with the video src object. I tested the following before peer.destroy and the error is gone.

`localVideo.srcObject = null;`

Thank You for the help!

Regards
schirrmie
