### ISSUE TITLE
Would be nice to get more information from getStats

### ISSUE THREAD

**Issue by jeregrine** [feross/simple-peer#38]
Right now getStats() is handled internally and sets local/remote host/port. Would be nice if I we had an event to allow users to hook into the stats.

I'm thinking something like

peer.getStats(function(stats){})

and in internally it would do this https://github.com/feross/simple-peer/blob/master/index.js#L375-L395 and then pass it to our callback. 

Currently my I'd like to know if the peer needed a TURN server or not, its kind of tricky currently to figure out which ice candidate was selected/successful especially since the last ice candidate always seems to be the TURN server I have configured.

**Comment by jeregrine** [comment]
I suppose to solve my issue I could iterate over the candidates in the SRP from top to bottom and compare the host/port and if its the relay candidate I've figured it out.

**Comment by feross** [comment]
Do calls to `getStats` change over time? If not, we can just emit a 'stats' event with the results from the internal `getStats` call.

**Comment by jeregrine** [comment]
They do change over time.

**Comment by jeregrine** [comment]
@feross I mean if I do a peer._pc.getStats kind of like the code llinked it works. Here are some things I need it for:

- Checking volume from an input peer, impossible to maths on audio streams in chrome. This lets me see if a user is talking or not. 
- Getting more accurate information on connection quality.

**Comment by contra** [comment]
@jeregrine Would exporting the function be enough to solve the problem for you? Or do you see it being a `stats` event that gets emitted on changes

**Comment by jeregrine** [comment]
You can only really query it. So an exported function is all I would need. 



—

**Comment by contra** [comment]
@jeregrine Want to send a PR that adds getStats to the Peer prototype?

**Comment by jeregrine** [comment]
Its been a while since I have looked at it but I can give it a shot. 



—

**Comment by feross** [comment]
We should keep the browser normalization logic that's in the current getStats call in the exposed function, so you might want to put that in it's own function.

**Comment by feross** [comment]
Fixed by #51
