### ISSUE TITLE
Get the media stream

### ISSUE THREAD

**Issue by StepToTop** [feross/simple-peer#381]
Hey guys, thanks for the amazing project.
May I ask a question about how to get the media stream and get it written on the disk from the browser client on my nodejs server.

**Comment by t-mullen** [comment]
Not currently possible on Node: https://github.com/js-platform/node-webrtc/issues/421

Possible on browser: https://github.com/streamproc/MediaStreamRecorder

**Comment by t-mullen** [comment]
You could also use an external media server like Kurento.

**Comment by mmcc** [comment]
Based on the linked node-webrtc issue, they added a non-standard way to get access to the raw video frames. However, I'm not ever seeing the `stream` event fired on the server end of things. Is there additional work that needs to be done in this lib before we can start experimenting there?
