### ISSUE TITLE
Backpressure: Use new "onbufferedamountlow" event instead of setTimeout hack

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#39]
Hooray – the event we wanted was added to the WebRTC data channel spec and implemented by Chrome! See: https://code.google.com/p/chromium/issues/detail?id=496700

Now, let's support it in `simple-peer`!

Ideally, we can eliminate the hack for Firefox too, but we need to check if they've implemented the new event yet, or not.

**Comment by feross** [comment]
This is now supported in Firefox too – we should really support it now!

https://bugzilla.mozilla.org/show_bug.cgi?id=1178091

**Comment by feross** [comment]
cc @mafintosh

**Comment by mafintosh** [comment]
Wow. I feel like we made an impact here :) We should definitely add that to simple-peer.

**Comment by feross** [comment]
Yeah! When the activity on the mailing list is super low, I think one email can make a big difference!

**Comment by du5t** [comment]
Just checking up; do you think this is the cause of [my issue with swarmlog](https://github.com/substack/swarmlog/issues/3)? @substack sent me here lol

**Comment by feross** [comment]
@du5t It's possible. Not sure, though. PR welcome!
