### ISSUE TITLE
How to create a one to many connection?

### ISSUE THREAD

**Issue by hkmsadek** [feross/simple-peer#391]
This is not an issue just some questions i couldn't find. 

1. Is it possible to create a one to many stream for a live broadcasting? 
2. How can I implement screen sharing? 

Any suggestion will be helpful. Thank you.

**Comment by nazar-pc** [comment]
You can find example of connecting more that 2 nodes in readme here: https://github.com/feross/simple-peer#connecting-more-than-2-peers
It shows full-mesh, but you will likely want to have something like star topology instead. Beware, it will probably not scale beyond 10 people or thereabout depending on your network conditions.

For screen sharing you need to specify proper constraints. There should be nothing simple-peer specific here, it just acts as convenient wrapper and handles some edge cases for you. Here is the article I stumbled upon, it can be your starting point: https://medium.com/@chris_82106/implementing-webrtc-screen-sharing-in-a-web-app-late-2016-51c1a2642e4

**Comment by hkmsadek** [comment]
Thank you. Could you please clear me about scaling? You mean 10 connections will slow down?

**Comment by nazar-pc** [comment]
I mean if you have 10 people connected to you your network should be able to handle that. since you'll be sending 10 copies of the same data.
For large number of clients this is not viable and some server-based solution is needed (potentially with transcoding functionality), where you can send video once and then clients can connect and receive it without extra load on your machine.

**Comment by JacobSamro** [comment]
> For large number of clients this is not viable and some server-based solution is needed (potentially with transcoding functionality), where you can send video once and then clients can connect and receive it without extra load on your machine.

@nazar-pc Do you have any resources for this ?

**Comment by nazar-pc** [comment]
Not really, didn't setup such a thing myself yet.
