### ISSUE TITLE
React Native: Can't find variable: Buffer

### ISSUE THREAD

**Issue by stephane-r** [feross/simple-peer#394]
Hi every body !

I would like use this library in React Native App. I've see many issue that it is possible to run this module on React Native with react-native-webrtc.

But i've an error with Buffer module : `Can't find variable: Buffer`. So, i've install all dependencies with `rn-nodify` : 

`./node_modules/.bin/rn-nodeify --install buffer,events,crypto,stream,util,process,vm --hack`

But no result.

I've try to import minified version : 

```
import Peer from 'simple-peer/simplepeer.min.js';
import wrtc from 'react-native-webrtc';

const peer1 = new Peer({ initiator: true, wrtc: wrtc });
```

That not work : `Use Chrome, Firefox or Internet Explorer 11`.

![image](https://user-images.githubusercontent.com/4712791/49096202-61703980-f26a-11e8-933e-78f1cec05225.png)

Anyone have already use this library on React Native ? (in my case, v0.57.5)

**Comment by t-mullen** [comment]
Did you import the `rn-nodeify` shim that is generated by that command?

```javascript
import './shim'
```

https://github.com/mvayngrib/rn-nodeify#examples
