### ISSUE TITLE
Not Compatible with MS Edge and Safari?

### ISSUE THREAD

**Issue by riddle28** [feross/simple-peer#400]
I am developing a chat application with simple-peer and I have tested the sample on your index page. It works fine with browsers except from MS Edge and Apple Safari because it consoles the error with error code c004e001, but chrome and firefox works fine with simple-peer. What was the reason for it? Due to unable to support them?

**Comment by t-mullen** [comment]
We don't currently support MS Edge because they do not support data channels, and the WebRTC implementation is questionable in general (Microsoft prefers ORTC).

Safari should work in the latest source code and bundle.

**Comment by jimmywarting** [comment]
> and the WebRTC implementation is questionable in general (Microsoft prefers ORTC).

Well, [Edge is ditching EdgeHTML and changing to use the Blink engine soon](https://hub.packtpub.com/microsoft-reportedly-ditching-edgehtml-for-chromium-in-the-windows-10-default-browser/) so 👍 
Means we will have one less annoying engine to worry about.

**Comment by t-mullen** [comment]
Closing since there's no plans to support Edge until datachannels are supported.

Feel free to open another issue if you have Safari bugs.
