### ISSUE TITLE
Websocket connection closed after streaming

### ISSUE THREAD

**Issue by mnicolas80** [feross/simple-peer#401]
I am using a -almost custom- nodejs websocket server (in Total.js) which is responsible to transfer the offer/answer messages between two browsers.
Currently the signaling is using STUN servers and it works as expected, because any text message can be exchanged between the two clients.

When I initialize streaming data, the existing websocket connection closes. I tried to bind the streaming data to the constructor `new Peer([opts])` or later `peer.addStream(stream)` , but still the websocket connection gets closed.
Also I monitored before and after the websocket termination, the console logs the video signals:
```
p.on('signal', function (data) {
  console.log('SIGNAL', data);
}
```

Any idea?
Thank you

**Comment by mnicolas80** [comment]
Some progress...
Issue (of closed websocket connection) solved by not setting the stream on initiator's side:
```
p1 = new SimplePeer({
  stream: initiator ? false : window.stream
}
```
On the other hand, it seems the invited user does not send the stream to the initiator or vise versa, because the event `p1.on('stream', function (stream) {` never get called.

**Comment by t-mullen** [comment]
`stream`, `addStream()` and the `stream` event are all related to `MediaStreams` from `getUserMedia`, not Node.js streams or any kind of data stream.

**Comment by yaplusplus** [comment]
I have the same problem.

The initiator's WebSocket connection breaks halfway (can receive messages from the server, but can't send) right after receiving "{ renegotiate: true }" message from another WebRTC peer. In my case the WebSocket connection doesn't close (`readyState === 1`), but it doesn't work correctly.

As @mnicolas80 wrote, removing `stream` from the initiator's side helps, but this approach doesn't solve the problem in general.

I'm curious how WebRTC connection may affect WebSocket connection?
