### ISSUE TITLE
I do not understand how to start!?

### ISSUE THREAD

**Issue by frogeraie** [feross/simple-peer#404]
I do not understand what is "bundle.js"!?

**Comment by t-mullen** [comment]
It's just your code. In this case, it's called `bundle.js` since it's bundled with browserify. But you don't need that, and can just use `simplepeer.min.js`.

```html
<script src="simplepeer.min.js"></script>
<script>
  var peer = new SimplePeer()
  // write your code as normal
</script>
```

**Comment by frogeraie** [comment]
Thanks!!!
