### ISSUE TITLE
electron-webrtc tests stalling

### ISSUE THREAD

**Issue by t-mullen** [feross/simple-peer#406]
The following tests stall intermittently on electron-webrtc:
- `duplex stream: send data one-way`
- `duplex stream: send data before "connect" event`
- `backpressure`

We should investigate why.

**Comment by t-mullen** [comment]
We might want to consider dropping support for electron-webrtc, as it seems to no longer be maintained.

**Comment by nazar-pc** [comment]
I would be in favor of that, almost 2 years without commits in master branch
