### ISSUE TITLE
Sauce tests hanging

### ISSUE THREAD

**Issue by jessetane** [feross/simple-peer#41]
Somewhere around September 4th the browser tests started hanging for me, I think due to a change at Sauce. Peer connections from Sauce's network to the outside world continue to work, so TURN can be used to work around the issue, but I don't think this is a real solution. I've sent an email to Sauce but haven't gotten a reply yet - can anyone else confirm / deny this problem?

**Comment by feross** [comment]
Yeah, I've noticed the same thing.

If adding TURN makes the tests work on Sauce that seems like a workable solution. The most important thing is that we have tests that run for every PR and that they exercise as much functionality as possible.

**Comment by jessetane** [comment]
It works, but testing a p2p module exclusively through a relay feels sort of funny to me... also, now every module that wants to test webrtc things needs a twilio account? Imo we should try to get Sauce to fix their network or explain why it's not behaving the way we would expect.

Any of you nice folks at @saucelabs have any idea what changed? (sorry for the spam)
/CC @christian-bromann @filmaj @imurchie @jlipps @santiycr @sebv

**Comment by feross** [comment]
> testing a p2p module exclusively through a relay feels sort of funny to me

Fair point. But we would still have the node tests which run on travis. Obviously, I agree that getting Sauce to fix this is the right solution.

**Comment by feross** [comment]
@saucelabs Whatever you changed recently makes it much harder/impossible to use Sauce for testing WebRTC apps. This may affect your business, as this is a large and fast growing market.

**Comment by feross** [comment]
I just pushed a change to use a TURN server to improve the situation a bit. I expect tests to be flaky still until https://github.com/feross/simple-peer/issues/35 is fixed.

**Comment by jlipps** [comment]
I don't personally know what's going on but I've started an internal thread at Sauce to see if we can get an explanation for this.

**Comment by jessetane** [comment]
@jlipps that's awesome, thanks! Curious to hear what you find out.

**Comment by jlipps** [comment]
@jessetane it would be helpful for our investigation if you could send us links to the last test you know that passed and the first test you think failed because of this issue. Are you able to find that?

**Comment by jessetane** [comment]
A pass: https://saucelabs.com/tests/d294cc4c26524cdcb946e5e95a5230fa
A hang: https://saucelabs.com/tests/b07f86ff2cd342f789e23cf7bcd34d75

I first noticed the issue on September 4th on another repo that depends on this module. From experimenting in manual testing mode (chrome, mac os), I think all the appropriate ice candidates are still being generated, connections just are never established.

**Comment by jlipps** [comment]
@jessetane, from our ops team:

> Network issue can be easily determined if the user can provide their prefix and allow me to probe that prefix to see if theres any issue with that route.
> are they having packet loss or unable to connect to sauce connect as well?

Mind sharing that info? Happy to move this to e-mail if that's better.

**Comment by jessetane** [comment]
This issue is about WebRTC connectivity inside Sauce's network, so knowing my IP won't help here. The easiest way for ops to reproduce the issue would be to have them spin up a box for manual testing and to run the connectivity test provided by webrtc.org:

https://test.webrtc.org/?turnURI=stun%3A23.21.150.121

**Comment by jessetane** [comment]
For example: https://saucelabs.com/beta/tests/edfec8789f154275a5e6a5da8e0aa71a/watch

**Comment by bdgscotland** [comment]
Hi @jessetane - should I be able to successfully run this from a non-Sauce IP?

**Comment by jessetane** [comment]
@bdgscotland that depends on your network configuration - it works for me, I'm currently behind a netgear wifi router doing stock NAT.

**Comment by bdgscotland** [comment]
I'm at home today and using Webpass ISP behind a Juniper SRX210H (does not support UPNP; Xbox Live reports me as 'Strict NAT') - the webrtc.org test fails.

From a Sauce perspective; we're not 100% sure why it worked one day and stopped the next. The Sauce VMs are behind NAT, but haven't made any changes on or around that date. We're investigating..

Did you get TURN to work?
Does this test now fail 100% of the time with STUN?

**Comment by jessetane** [comment]
@bdgscotland I just ran the test again and it failed for me, so I must have made a mistake in the link to run it. So sorry about that - trying to figure out what I did differently the first time!

Either way, yes, TURN works, and I do see that even the webrtc.org test only runs through a relay by default, so perhaps we're just stuck doing things that way, however I'm still fairly sure that this used to work with STUN on Sauce's network before September...

**Comment by bdgscotland** [comment]
It seemed to work for me, on Sauce, using this:
https://test.webrtc.org/?turnURI=stun%3A23.21.150.121

Using the other URL you posted of https://test.webrtc.org/?turnURI=stun%3A23.21.150.121 fails with the reason "Malformed URL".

**Comment by jessetane** [comment]
Aren't those urls the same?

**Comment by bdgscotland** [comment]
I just updated it. ;) The difference is ?stunURI vs ?turnURI

**Comment by jessetane** [comment]
stunURI is not a param handled by the test, so in that case you're just getting the default TURN servers, which is why it works.

When I tested this the first time, I used the inspector to replace the url manually, which I believe is why it worked for me. It appears that the way turnURI is parsed prevents passing a stun uri, looking now to see if there is another way to do this without the inspector...

**Comment by bdgscotland** [comment]
Ah.. the ?turnURI fails with the "Malformed URL" when I click to expand on the failed lines. Let me know what you find.

**Comment by jessetane** [comment]
Ok, some progress: in an effort to try replacing the url with the inspector on Sauce I had to use Windows since keyboard shortcut overlap prevented me from opening the Sauce machine inspector's "find" - low and behold, it worked!

After that I tried running simple-peer's tests on a Windows machine instead of a Mac (the default?), and they went through just fine. So could it be something related to the Mac image? The network Mac images run on?

**Comment by jessetane** [comment]
@bdgscotland any update on this? Are you able to reproduce the difference on your end between the mac / win vms?

**Comment by bdgscotland** [comment]
@jessetane I'm not sure, I won't be able to help you now.. feel free to reach out to @jlipps for more info.

**Comment by jessetane** [comment]
@bdgscotland thanks for letting me know. @jlipps if you're interested I believe this is still an issue for os x vms - a new version of https://test.webrtc.org just shipped that shows the difference clearly:

win 10: https://saucelabs.com/beta/tests/8778de035c3648c1b403b68e91ebf601
os x el capitan: https://saucelabs.com/beta/tests/8457d9ec790e47d0967bb680ca8e9b88

Note that host connectivity is not working on os x! My understanding is that for two peers running on the same machine, host connectivity should basically always work since packets would not even need to hit the network.

**Comment by holyoption79** [comment]
Dear folks! 

I'm Network engineer from Saucelabs and was wondering if theres anything I can help,

I think on network route troubleshooting perspective,

Is there any traceroute packet loss?

Is ping(icmp) failing? loss? 

Please provide your public ip address if anything above and see if your upstream provider has any issues with ours and we'll dig in from response  above. 

Thank you!

**Comment by jessetane** [comment]
@holyoption79 did you read my previous comment? Can you confirm?
