### ISSUE TITLE
Isometric Peer initiation

### ISSUE THREAD

**Issue by ccorcos** [feross/simple-peer#410]
I'm writing a program that tries to connect to other peers and there's a race condition where both peers try to initiate a connection at the same time. It would be nice if this race condition could be solved within this library.

```js
var Peer = require("simple-peer")
var wrtc = require("wrtc")

// Two peers initiating at the same time.
var peer1 = new Peer({ initiator: true, wrtc: wrtc })
var peer2 = new Peer({ initiator: true, wrtc: wrtc })

peer1.on("signal", function(data) {
	console.log("peer1 signal")
	peer2.signal(data)
})

peer2.on("signal", function(data) {
	console.log("peer2 signal")
	peer1.signal(data)
})

peer1.on("connect", function() {
	console.log("peer1 connect")
	peer1.send("peer1->peer2")
})

peer2.on("connect", function() {
	console.log("peer2 connect")
	peer1.send("peer2->peer1")
})

peer1.on("data", function(data) {
	console.log("peer1 data: " + data)
})

peer2.on("data", function(data) {
	console.log("peer2 data: " + data)
})
```

**Comment by nazar-pc** [comment]
This library is only a wrapper for native WebRTC API. I have implemented race conditions handling for this library a few times already, usually I have some kind of ID and I just kept connection with `offer` from node with higher ID and dropped the other connection.
Such things are typically application-specific and not something simple-peer should handle on its own.

**Comment by ccorcos** [comment]
Sounds good. I did just what you said. Thanks
