### ISSUE TITLE
Anyone successfully using data channels on iOS?

### ISSUE THREAD

**Issue by anderspitman** [feross/simple-peer#414]
I'm currently using raw WebRTC. My use case is pretty specific. I'm trying to get Firefox/Chrome/iOS Safari all talking to each other over data channels on a LAN (for games). One nice thing about this is it doesn't require any STUN/ICE servers. Unfortunately, iOS apparently [doesn't allow local candidates](https://github.com/webrtc/samples/issues/1123) unless the user has granted permissions. I'm wondering if simple-peer has anything built in to handle this so I don't have to refix the wheel from scratch?

**Comment by t-mullen** [comment]
I don’t believe you’ll be able to connect over LAN without a stun server or access to local candidates.

You’ll need to disable ice candidate restrictions in iOS and OSX Safari if you want to do that. There’s nothing to be done at the JavaScript level.

**Comment by anderspitman** [comment]
Thanks @t-mullen, from my further investigation I believe you are correct.
