### ISSUE TITLE
Firefox-to-Chrome addStream with renegotiation breaks streams

### ISSUE THREAD

**Issue by schirrmie** [feross/simple-peer#415]
Hi,

I have a button to pause/unpause sending video to the remote peer.
I use removeStream and addStream for this.
I have a call between Chrome and Firefox browser. If I pause and unpause the video from Chrome browser to Firefox all is fine.
But if I pause and unpause from Firefox browser the receiving video on Chrome site is just black.
After removeStream I have a freeze frame (thats fine) and after addStream the freeze frame change to black.

This is my simplified source

```
    if( pause ) {
      this.RTCPeer.removeStream(this.localStream);
    } else {
      this.RTCPeer.addStream(this.localStream);
  }

```

Between 2 Chrome or 2 Firefox all is ok only from Firefox to Chrome I have this issue.

Any suggestions for this issue?

Regards
schirrmie

**Comment by schirrmie** [comment]
Thanks for the example. I will try this!

**Comment by schirrmie** [comment]
Hi,

enable and disable track works fine. But if I disable the track the local video is black too.
This is bad. The local user needs to see his local video. I will stay with this workaround until Firefox fix this issue.
If You open an issue in the bug forum please post a link here so I can track the progress.
Thank You!

Regards
schirrmie

**Comment by t-mullen** [comment]
In Unified Plan, adding a stream after you've removed it is not supported. The recommended way is to enable/disable the stream as I mentioned above. `removeTrack` permanently removes tracks. 

If you want to keep tracks enabled to play them locally (in a video element for example), you'll need to clone the MediaStream.

```javascript
originalStream // <- your local MediaStream
clonedStream = stream.clone()
peer.addStream(clonedStream)
```
```javascript
videoElement.srcObject = originalStream
```
```javascript
if( pause ) {
  this.localStream.getTracks().forEach(track => { track.enabled=false })
} else {
  this.localStream.getTracks().forEach(track => { track.enabled=true })
}
```
