### ISSUE TITLE
this peer connection is relying on the default sdpSemantics

### ISSUE THREAD

**Issue by jarretttaylor** [feross/simple-peer#430]
Not sure if this is related to #351, but I thought I would post it separately in the event that it is not.
simple-peer version: latest from github (bafe6e5  on Dec 13, 2018)
Clients:
non-initiator: ChromeOS v71.0.3578.127
initiator: Windows 10 - Chrome v72.0.3626.81 (Official Build) (64-bit)

Connection is successfully established between the two peers and video is flowing in both directions.
I then attempt to add an additional video stream on the ChromeOS side via addStream(stream).
Signaling takes place and the error below occurs on the Windows 10 side.
This worked previously.

10:30:04.954 simplepeer.min.js:11 [Deprecation] "Complex" Plan B SDP detected! Chrome will switch the default sdpSemantics in M72, around January 2019 from 'plan-b' to the standardized 'unified-plan' format and this peer connection is relying on the default sdpSemantics. This SDP is not compatible with Unified Plan and will be rejected by clients expecting Unified Plan. For more information about how to prepare for the switch, see https://webrtc.org/web-apis/chrome/unified-plan/.
Promise @ simplepeer.min.js:11
t.setRemoteDescription @ simplepeer.min.js:11
r.signal @ simplepeer.min.js:11
app.signalWebSocketMessageListener @ ampqc.html:829
app.signalWebSocket.onmessage @ app.js:1493

10:30:05.003 ampqc.html:340 error:  Error: InvalidAccessError: Failed to set remote answer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan.
    at i (simplepeer.min.js:11)
    at simplepeer.min.js:11
handleError @ ampqc.html:340
s @ simplepeer.min.js:6
n.emit @ simplepeer.min.js:6
r._destroy @ simplepeer.min.js:11
r.destroy @ simplepeer.min.js:11
(anonymous) @ simplepeer.min.js:11
Promise.catch (async)
r.signal @ simplepeer.min.js:11
app.signalWebSocketMessageListener @ ampqc.html:829
app.signalWebSocket.onmessage @ app.js:1493

Due to my shallow understanding of all that simple-peer does, it isn't clear (to me) if the offending message format is being generated by simple-peer or if it is ChromeOS. If it is ChromeOS, this might just be a release synchronization issue on Google's part since v72 is not yet available for that platform. Any direction you can provide is greatly appreciated. Also, thank you for creating and maintaining this library.

**Comment by t-mullen** [comment]
Try forcing unified plan in your peer options with:
```javascript
new Peer({
  config: 
    sdpSemantics: 'unified-plan'
})
```

**Comment by jarretttaylor** [comment]
@t-mullen That removed the error; however, addStream is not firing. Please remind me how to turn on debug logging in simple-peer. I know I have seen it in other tickets, but can't seem to locate it now.

**Comment by t-mullen** [comment]
```javascript
peer._debug = console.log
```

Unified Plan support in Chrome is still relatively new and we haven't had the chance to fully test it. You may have some issues.

**Comment by t-mullen** [comment]
It's probably an issue with how we're using Unified Plan. I'm taking a look at these problems this week.

**Comment by jarretttaylor** [comment]
Excellent. If there is anything I can do to assist in testing, please let me know.

**Comment by t-mullen** [comment]
Unified plan doesn't support adding new media lines from the non-initiator. We'll need to switch to using transceivers to re-implement `addStream/addTrack` on the non-initiator.

> Offering to Receive Media

> The answerer is not allowed to add new m= sections in the answer SDP. This means that if the offerer is not offering to send anything, there’s typically no “sendrecv” m= sections that the answerer can use to send media on. Renegotiation is needed on the answerer’s side, adding more round trip times before sending is possible. This section describes how to offer to receive media, making it possible to receive Early Media in the initial offer/answer cycle.
> 
> In Plan B, the legacy createOffer()-constraints offerToReceiveAudio/offerToReceiveVideo would create m= sections for it to be possible to receive any number of tracks. In Unified Plan this constraint only works for a single track per kind as it only creates one audio and/or video transceiver; the spec advises using addTransceiver() instead. Chrome only partially supports this constraint; it works for offering but the createOffer()-transceiver is not immediately visible, leading to some unexpected behavior.
> 
> The Unified Plan way of offering to receive media is to use addTransceiver() to create as many “recvonly”-transceiver as you are willing to receive.

**Comment by t-mullen** [comment]
I've opened a new issue to track this, since it seems the initial ChromeOS issue was solved.
