### ISSUE TITLE
Stream two audio sources from non-initiator

### ISSUE THREAD

**Issue by CiscoKidxx** [feross/simple-peer#439]
Hello!

Is it possible to stream two audio sources, say one from an `<audio>` element and another from the local microphone to the initiator? Both streams are ready when the initiator begins this connection. I have tried doing something like the below code and can only get one audio stream to  the initiator.

**initiator:**
```
let local_stream = await navigator.mediaDevices.getUserMedia({
  video: false,
  audio: true
});

const initiator = new Peer({
  initiator: true,
  trickle: false,
  streams: [local_stream]
});
```
**peer:**
```
// this is referencing an <audio> element
let remote_stream = window.mediaTech.stream; 

let local_stream = await navigator.mediaDevices.getUserMedia({
  video: false,
  audio: true
});

const peer = new Peer({
  trickle: false,
  streams: [local_stream, remote_stream]
});
```

**Comment by nazar-pc** [comment]
What is the code on the side were you expect to receive 2 audio streams?

**Comment by t-mullen** [comment]
Sending more tracks on the non-initiator than the initiator is currently broken until we add transceiver support. #433

**Comment by CiscoKidxx** [comment]
@t-mullen Thanks for the info. For now, as a workaround I mixed the two streams into one before sending it back to the initiator.

**peer:**
```
let remote_stream = window.mediaTech.stream;

let local_stream = await navigator.mediaDevices.getUserMedia({
  video: false,
  audio: true
});

let remote_stream_source = ac.createMediaStreamSource(remote_stream);
let local_stream_source = ac.createMediaStreamSource(local_stream);

const dest = ac.createMediaStreamDestination();

remote_stream_source.connect(dest);
local_stream_source.connect(dest);

console.log("dest", dest);

const peer = new Peer({
  trickle: false,
  streams: [dest.stream]
});
```

**Comment by t-mullen** [comment]
Should be resolved with transceiver support.
