### ISSUE TITLE
stream display media after streaming user video

### ISSUE THREAD

**Issue by igorcouto** [feross/simple-peer#446]
Hi,

I'm sucessfully displaying user media, and then, when user chooses to strem display (capturing screen), calling again addStream method does not fires peer.on('stream') on another side. I have also tried addTrack with no sucess.

Anyone have a direction on how can send another stream using same peer?

Thanks!

**Comment by jarretttaylor** [comment]
@igorcouto Check out #433 as it is likely related to your issue.

**Comment by igorcouto** [comment]
Hi @jarretttaylor . I think this is the situation. Do you have an idea about some workaround? Or we need just to wait until the transceiver get implement?

Perhaps switching video and screensharing using the same stream? Is it possible?

**Comment by igorcouto** [comment]
Hi @jarretttaylor , I was able to make it using replaceTrack. Like that:

peer.replaceTrack(oldTrack,newTrack,stream);
