### ISSUE TITLE
Fallback to addStream when addTrack is not supported

### ISSUE THREAD

**Issue by owodunni** [feross/simple-peer#447]
Hi,

Using Simple Peer together with older webrtc API such as https://github.com/oney/react-native-webrtc where addTrack is not supported. Results in stream not being created in the Peer constructor, it also results in a chrash if addStream is used directly.

On line 139 in index.js:

``` javascript
  if ('addTrack' in self._pc) {
    if (self.streams) {
      self.streams.forEach(function (stream) {
        self.addStream(stream)
      })
    }
    self._pc.ontrack = function (event) {
      self._onTrack(event)
    }
  }
```

This makes it so that the stream is not added and no feedback is given to the user of Simple Peer.

Using the peer.addStream method doesn't have the same check.

On line 275 in index.js:

``` javascript
var sender = self._pc.addTrack(track, stream)
```

Here addTrack is used without checking if addTrack exists.

I have made a workaround that enables me to send stream from android app to a chrome browser. I will make a PR shortly.

**Comment by t-mullen** [comment]
Latest version will throw an error when attempting to use `addTrack` on unsupported browsers.

**Comment by petermercy** [comment]
@t-mullen I'm still having this error when I pass a react-native-webrtc stream into Simple Peer. I see that react-native-webrtc [updated to M75](https://github.com/react-native-webrtc/react-native-webrtc/releases) in 8/2019. Do you know if they're still incompatible with Simple Peer?

**Comment by stanwolverine** [comment]
hello @owodunni, how did you end up solving your issue? I am stuck with this same issue, and can't figure out what to do. please help.

**Comment by BabakYaghoobi** [comment]
Hi guys,
If you want to use simple-peer in React Native need some changes:

1) change somthing in addTrack func:

```
addTrack(track, stream) {
    this._debug('addTrack()')

    const submap = this._senderMap.get(track) || new Map() // nested Maps map [track, stream] to sender
    let sender = submap.get(stream)
    if (!sender) {

      //Added by Babak <-------- need changes
      if (this._pc.addTrack) {
        sender = this._pc.addTrack(track, stream)
      } else {
        sender = this._pc.addStream(stream)
      }

      submap.set(stream, sender)
      this._senderMap.set(track, submap)
      this._needsNegotiation()
    } else if (sender.removed) {
      throw errCode(new Error('Track has been removed. You should enable/disable tracks that you want to re-add.'), 'ERR_SENDER_REMOVED')
    } else {
      throw errCode(new Error('Track has already been added to that stream.'), 'ERR_SENDER_ALREADY_ADDED')
    }
  }

```

2) add this func after: this._pc.ontrack
   
```
    // Added by Babak
    this._pc.onaddstream = event => {
      queueMicrotask(() => {
        this._debug('on stream')
        this.emit('stream', event.stream) // ensure all tracks have been added
      })
    }

```

now the other side for using this stream use like this:

```
peer.on('stream', (stream) => {
      // console.log('----------------- stream -------------------------------');
      if (stream.currentTarget && stream.currentTarget._remoteStreams) {
        stream = stream.currentTarget._remoteStreams[0];
      }
      //console.log('Got peer stream!!!', peerId, stream);

      peer.stream = stream;
      that.setPeerState(peerId, peer);
    });

```

tested on version 9.7.2 and work fine on react native,
Regrads
