### ISSUE TITLE
cannot remove track and add stream

### ISSUE THREAD

**Issue by igorcouto** [feross/simple-peer#450]
Related to #407 

The scenario works fine when my peer is the initiator of connection. I can remove and add streams many times.

```
export const endStream = () => {
	Object.keys(realtime.peers).forEach((peerId) => {
		try {
			const peer = realtime.peers[peerId];
			peer.removeStream(realtime.streams.me);
		} catch (err) {
			console.log(err);
		} // eslint-disable-line no-empty
	});

	realtime.streams.me.getTracks().forEach(track => track.stop());
	realtime.streams.me = null;
}

export const streamVideo = (stream) => {
	Object.keys(realtime.peers).forEach((peer) => {
		try {
			realtime.peers[peer].addStream(stream);
		} catch (err) {
			console.log(err);
		 } // eslint-disable-line no-empty
	});
};

```
When the other peer is the initiator, and initiates the connection with a stream, I can remove the stream from the nonInitiator side, but _remoteMediaStreams does not remove the values on the initiator side, with null sender map (I already tried to removeStream on remote side, but the null sender map blocks me to do this). The effect of this is that the event 'onStream' is never fired after the addStream.

I'm using the last version.

Some thoughts?

**Comment by t-mullen** [comment]
You can't modify the number of tracks from the non-initiator until transceivers are implemented. #440

**Comment by igorcouto** [comment]
This makes a lot of sense on the scenarios I'm facing. I will try to use signaling to addStream/remove on the initiator side.
