### ISSUE TITLE
Incorporating Selective Forwarding Unit (SFU)

### ISSUE THREAD

**Issue by gurupras** [feross/simple-peer#451]
I really like the API exposed by simple-peer and have been using it for some of my webRTC apps.

A new requirement of mine is to try and set up something akin to large-scale video conferencing. A P2P network wouldn't work for this due to the connection blowup already discussed. 

To that end, are there any examples of how to integrate an SFU with simple-peer?

**Comment by t-mullen** [comment]
It depends on the SFU you want to use. I've had success with Kurento+simple-peer. You just need to pass signalling messages between the SFU's WebRTC endpoint and the simple-peer RTCPeerConnection. Take care not to use renegotiation and and make sure your browser peer is the initiator.

If you want to implement an SFU using simple-peer, it's possible with node-webrtc, but expect to have to deal with threading issues yourself.

**Comment by t-mullen** [comment]
As for examples, I would look at examples for the specific SFU you want to use. simple-peer doesn't really do anything special in terms of signalling (aside from renegotiation and transceiver requests, which are not required).

**Comment by ahmetozalp** [comment]
> Kullanmak istediğiniz SFU'ya bağlıdır. Kurento + akranıyla başarılı oldum. Sinyal mesajlarını SFU'nun WebRTC uç noktası ile basit eş RTCPeerConnection arasında iletmeniz yeterlidir. Yeniden pazarlamayı kullanmamaya dikkat edin ve tarayıcı eşinizin başlatıcı olduğundan emin olun.
> 
> Basit eş kullanarak bir SFU uygulamak istiyorsanız, düğüm webrtc ile mümkündür, ancak diş çekme sorunlarıyla başa çıkmak zorunda kalmayı bekleyebilirsiniz. Bir yönlendirme birimi olarak bir tarayıcı eşiniz bile olabilir, ancak bunu tavsiye etmem.

How can I do this? I have a connection with "simple-peer" installed I want to save the videos to the server kurento server is also installed but I could not connect them

**Comment by vpanichkin** [comment]
> Take care not to use renegotiation and and make sure your browser peer is the initiator.

Could you explain, why should the browser peer be an initiator? 

I also got stuck during gathering candidates on Kurento as I can get play **typ host candidate**. 
Did you succeed in getting srflx candidate on Kurento?

P.S. The logs after successful connections between Kurento and Simple-peer from chrome://webrtc-internals would be really appreciated
