### ISSUE TITLE
self._channel is null

### ISSUE THREAD

**Issue by stevemk14ebr** [feross/simple-peer#452]
After establishing a bi-directional stream between two clients in node (wrtc), the peer.send function cannot send as there is no channel. The video stream works fine. Code:

Line 76 the error appears: 'Unhandled promise rejection TypeError: "self._channel is null"'
https://pastebin.com/QeumsLKL

**Comment by stevemk14ebr** [comment]
I think this is a race-condition between the peer being created. If i move the send to a button, and wait a sec, then manually send it works fine.

**Comment by t-mullen** [comment]
Can you try using `.write()` instead of `.send()`?

**Comment by stevemk14ebr** [comment]
This is on the receiving side, not the sending side, i'm accepting not connecting . It works with peer.write(). Doesn't work with peer.send. If the peer.send call is delayed by at least 100ms after creation of the peer object from accept, it works: 

Changes to work:
```
const delay = ms => new Promise(_ => setTimeout(_, ms));

async onRequest(request){
	// we're receiving, get video stream (before accepting connection)
	this.stream = await this.b_getMedia();

	// pass stream to webrtc
	const { peer } = await request.accept(undefined, {wrtc: wrtc, stream: this.stream});
	this.b_initPeer(peer);
	await delay(100);
	this.peer.send('I got your stream man!');
}
```

this suggests a race condition exists.

**Comment by t-mullen** [comment]
You still need to listen for the connect event before calling `.send()`. Or use `.write()` instead to buffer your data.

`simple-signal` doesn't wait for the connect event before resolving the accept promise - you need to do this. 

```javascript
const { peer } = await request.accept(undefined, {wrtc: wrtc, stream: this.stream});
this.b_initPeer(peer);
this.peer.on('connect', () => {
  this.peer.send('I got your stream man!');
})
```
or
```javascript
const { peer } = await request.accept(undefined, {wrtc: wrtc, stream: this.stream});
this.b_initPeer(peer);
this.peer.write('I got your stream man!'); // write is safer for many reasons
```

If it still doesn't work, try opening this issue in the `simple-signal` repository.
