### ISSUE TITLE
[Safari only] "transceiverRequest" sent in a loop when the non initiator ".addStream"  

### ISSUE THREAD

**Issue by XavM** [feross/simple-peer#456]
Using the last build with "unified plan" on Safari, and adding a stream from a non initiator peer, the signal "transceiverRequest" is sent in a loop from the non initiator to the initiator, resulting in an infinity of signals being exchanged between peers (until tab is closed)

Expected behaviour : 

".addStream" > "renegotiate" > "offer" > "answer" > "transceiverRequest" > "offer" > "answer" > "on('stream')" triggered on the initiator peer 

Current behaviour on Safari : 

".addStream" > "renegotiate" > "offer" > "answer" > "transceiverRequest" > "offer" > "answer" > "transceiverRequest" > "offer" > "answer" > "transceiverRequest" >  ... etc in a loop ...  

Tested on OSX 10.14.4 + Safari 12.1  + simplepeer.min.js commit c5f8a8ded50ef354d5a0f8a3700f8817565ed032

Works fine when ".addStream"  is triggered from the initiator
Seems to work fine on Chrome/Firefox both ways 

Ex to reproduce : https://gist.github.com/XavM/78bac54fd17a1870016342df7894ed64

**Comment by t-mullen** [comment]
Seems like a new bug in latest Safari. I’ll try to get a fix this weekend.

**Comment by cbikar** [comment]
I noticed a similar issue on iOS 12.2. I open a session between Chrome (desktop, initiator) and Safari (iOS, non-initiator). After adding a stream, simple-peer is emitting signaling data in a loop.

**Comment by t-mullen** [comment]
Can you try the latest build in this repo?

**Comment by XavM** [comment]
No more endless signaling on "OSX 10.14.4 / Safari 12.1" and "iOS 12.2/Safari" with commit 3ed91bf631c4bf9c3b4bf5a85d004bb70d621707

Good job !!

Must not be related to #456, but on "iOS 12.2/Safari", the video never shows up when the stream event is fired (Opening a dedicated issue for this one : #465)

Works fine on "OSX 10.14.4 / Safari 12.1 and 12.2"
