### ISSUE TITLE
Add simple way to capture first signal emitted

### ISSUE THREAD

**Issue by guysv** [feross/simple-peer#458]
Docs state that the `on('signal')` should be installed right after initializing the SimplePeer object so the initial signal won't be missed in the case that this is the initiator side of the connection.

I ran into a situation where the moment I initialize the object, and the moment I start to actually move around signals, are in two pretty separate places.

I still need to get that initial signal event somehow, so my workaround is:
1. install an event listener right after initialization to capture any signal event, which adds the signal obj to some cache (array)
2. when time comes, empty cache into the signaling mechanism
3. install a real signal event handler which sends the signal through the signaling mechanism
4. remove initial signal-to-cache event handler

That's a hassle I would love to eliminate.
The way I see it, if SimplePeer could expose a `getFirstSignal` API, and guarantee that no more signals will be created until first signal is sent to peer, that will make things simpler. 

I would love to share my actual situation and workaround, but I didn't get it to work yet.
Please nag me about it if it is relevant to the discussion.

What is your take on this? Maybe there is an easier workaround on my side that I missed?

**Comment by t-mullen** [comment]
EventEmitters typically don't cache events. If we did add caching of the `signal` event, we should be consistent for all events (ie you might not want to miss an important `stream` or `data` event, which can fire before you attach a listener).

Taking an action that will fire an event before you're listening for that event is unusual in event-driven programming. I'd be interested to hear why you need to instantiate peer objects before setting up your signalling channel.

It's really easy to do this caching yourself (but I don't recommend it):
```javascript
var cache = []
const peer = new Peer()
peer.on('signal', (data) => { // immediately after instantiating peer
  if (signalChannel.ready) { // ideally, your signaling channel should be ready before ever creating the peer
    signalChannel.write(data)
  } else {
    cache.push(data)
  }
})
signalChannel.on('ready', ()=>{
  cache.forEach(data => signalChannel.write(data))
  cache = []
})
```

**Comment by guysv** [comment]
After reviewing, I found that after all I could setup the peer obj and the handlers at the same routine, so no need to patch simple-peer. thank you for your attention to my subject!
