### ISSUE TITLE
Throttling signaling messages

### ISSUE THREAD

**Issue by stevenmusumeche** [feross/simple-peer#46]
Is there a way to throttle signaling messages?  I'm trying to do the connection negotiation over Pusher client events, but it only allows 10 per second which is not enough.

**Comment by feross** [comment]
You can set the `trickle` option to `false` and you'll get only one 'signal' event.

```js
var p = new Peer({ trickle: false })
```

**Comment by stevenmusumeche** [comment]
Hello @feross and thank you so much for your reply and work on this project. I did see the trickle setting but I had a problem with it.  For example, this code works and I get the console output seen below:

```
        var peer1 = new SimplePeer({initiator: true});
        var peer2 = new SimplePeer({});

        peer1.on('signal', function (data) {
            // when peer1 has signaling data, give it to peer2 somehow
            peer2.signal(data);
            console.log('peer1 received signal');
        });

        peer2.on('signal', function (data) {
            // when peer2 has signaling data, give it to peer1 somehow
            peer1.signal(data);
            console.log('peer2 received signal');
        });

        peer1.on('connect', function () {
            // wait for 'connect' event before using the data channel
            peer1.send('hey peer2, how is it going?')
        });

        peer2.on('data', function (data) {
            // got a data channel message
            console.log('got a message from peer1: ' + data)
        })
```

```
peer1 received signal
7temp.php:22 peer1 received signal
temp.php:28 peer2 received signal
7temp.php:28 peer2 received signal
temp.php:22 peer1 received signal
temp.php:28 peer2 received signal
temp.php:38 got a message from peer1: hey peer2, how is it going?
```

However if I set trickle to false in this simple example, like this:

```
        var peer1 = new SimplePeer({initiator: true, trickle: false});
        var peer2 = new SimplePeer({trickle: false});
        // .... same code
```

It takes over 20 seconds for the final message to display.  Is this expected behavior? Is there something I can do in between these two extremes?

**Comment by feross** [comment]
The `trickle: false` setting will wait for all candidate gathering to finish. It's a core option of the webrtc peer connection object. If you want to come up with some middle ground, you'll have to do that in your code. `simple-peer` is a low-level library. You can do that by using a debounce function that batches up all the candidates that have been found when none come for 500ms, or something like that.
