### ISSUE TITLE
[iOS only] The video never shows up when the stream event is fired 

### ISSUE THREAD

**Issue by XavM** [feross/simple-peer#465]
Using iOS/Safari, the video never shows up after the stream event is fired

Tested on iOS 12.2 + Safari + simplepeer.min.js commit 3ed91bf631c4bf9c3b4bf5a85d004bb70d621707

Ex to reproduce : https://gist.github.com/XavM/5f1c1dd781bb9dfac5306efb65fe9392

Works fine on "OSX 10.14.4 / Safari 12.1"

**Comment by t-mullen** [comment]
Probably related to the new test failures on latest iOS Safari. Apple is on a roll with these updates 😄

**Comment by XavM** [comment]
In case any one is having the same issue with "iOS 12.2/Safari" : 

SDP Unified Plan is turned off by default in "iOS 12.2/Safari" 
This can be turned on using the Safari settings on iOS : "Settings > Safari > Advanced >Experimental Features > WebRTC Unified Plan"

Once activated, every thing works as expected

**Comment by t-mullen** [comment]
If Unified Plan has been moved behind a flag in iOS Safari, I'm not sure there's anything we can do in simple-peer.

**Comment by t-mullen** [comment]
Unified Plan appears to be the default in latest Safari.
