### ISSUE TITLE
Unhandled Promise rejection in firefox

### ISSUE THREAD

**Issue by Dealerpriest** [feross/simple-peer#470]
I'm developing an ionic application where I use simple peer. It works fine in chrome. But I get the following error in firefox (66.0.5):
```
Unhandled Promise rejection: Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack. ; Zone: <root> ; Task: Promise.then ; Value: TypeError: "Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack."
    getStats firefox_shim.js:78
    getStats index.js:668
    findCandidatePair index.js:704
    _maybeReady index.js:823
    _onChannelOpen index.js:907
    onopen index.js:471
 shimPeerConnection/window.RTCPeerConnection.prototype.getStats@http://localhost:8100/build/vendor.js:152449:12
Peer.prototype.getStats@http://localhost:8100/build/vendor.js:86848:5
findCandidatePair@http://localhost:8100/build/vendor.js:86884:5
Peer.prototype._maybeReady@http://localhost:8100/build/vendor.js:87003:3
Peer.prototype._onChannelOpen@http://localhost:8100/build/vendor.js:87087:3
Peer.prototype._setupData/self._channel.onopen@http://localhost:8100/build/vendor.js:86651:5
polyfills.js:3:20715
    onUnhandledError http://localhost:8100/build/polyfills.js:3
    r http://localhost:8100/build/polyfills.js:3
    microtaskDrainDone http://localhost:8100/build/polyfills.js:3
    microtaskDrainDone http://localhost:8100/build/polyfills.js:3
    o http://localhost:8100/build/polyfills.js:3
```

What could be the reason for this error? I have a feeling it's related to shims for firefox or something similar. Any advice would be much appreciated!

**Comment by Dealerpriest** [comment]
I removed all occurences of `import "webrtc-adapter"` in my code base and the issue seems to be resolved. Maybe it should be mentioned in the documentation that one shouldn't use adapter with simple peer?

**Comment by t-mullen** [comment]
Could you log:
```javascript
console.log(peer. _isReactNativeWebrtc)
console.log(peer._pc.getStats.length)
```

**Comment by t-mullen** [comment]
Also please check if this throws an error:
```javascript
peer._pc.getStats().then(function (res) {})
```

**Comment by D1plo1d** [comment]
I've ran into the same issue. Adding your code @t-mullen gives:

peer._isReactNativeWebrtc = false
peer._pc.getStats.length = 3

and no errors are thrown in the getStats promise.

The error message is:
`TypeError: Argument 1 of RTCPeerConnection.getStats does not implement interface MediaStreamTrack.`

And it's comming from firefox_shim.js:174 in webrtc-adapter version 6.4.8 which looks like this:

```js
return nativeGetStats.apply(this, [selector || null])
```

**Comment by D1plo1d** [comment]
Appears to be related to https://github.com/webrtcHacks/adapter/issues/683

**Comment by D1plo1d** [comment]
There's definitely a mismatch here but I don't know which project needs patching.

webrtc-adapter always uses the first argument as the selector. If it's falsey it treats it as null:
https://github.com/webrtcHacks/adapter/blob/2e7e49dd8a212db67dc4a9c119d787f6c4efedfa/src/js/firefox/firefox_shim.js#L75

simple-peer passes a callback as the first agument if getStats accepts arguments (which it does for webrtc-adapter). So the callback is being misinterpreted as the selector:
https://github.com/feross/simple-peer/blob/8bf4f675a99d0aa3fc243a88e2f6e097742df3b5/index.js#L713

**Comment by D1plo1d** [comment]
There's definitely a mismatch here but I don't know which project needs patching. My best guess at the moment is that webrtc-adapter's getStats function should have zero args so they need to use reflection to get the arguments passed in instead of declaring arguments.

webrtc-adapter always uses the first argument as the selector. If it's falsey it treats it as null:
https://github.com/webrtcHacks/adapter/blob/2e7e49dd8a212db67dc4a9c119d787f6c4efedfa/src/js/firefox/firefox_shim.js#L75

simple-peer passes a callback as the first agument if getStats accepts arguments (which it does for webrtc-adapter). So the callback is being misinterpreted as the selector:
https://github.com/feross/simple-peer/blob/8bf4f675a99d0aa3fc243a88e2f6e097742df3b5/index.js#L713

**Comment by t-mullen** [comment]
Adapter doesn't set the default arguments for their shim, so `RTCPeerConnection.prototype.getStats.length` is not `3`, not `0`. 

This makes simple-peer think the browser only supports the old callback API, so it calls that. Unfortunately Adapter doesn't properly shim the callback form either (it just exposes the native `getStats`), so we call the native getStats with a callback argument. 

Firefox doesn't support passing a callback into it's native getStats so it errors.

Opened an issue for adapter to fix: https://github.com/webrtcHacks/adapter/issues/981
I'm going to PR a more robust way to detect promise API support.

**Comment by D1plo1d** [comment]
Oh, I already filed a PR with adapter. This was enough to resolved the issue for me:  https://github.com/D1plo1d/adapter/pull/1

**Comment by t-mullen** [comment]
Cool, let's get that merged!

**Comment by D1plo1d** [comment]
On it! New PR: https://github.com/webrtcHacks/adapter/pull/982

**Comment by feross** [comment]
Looks like the PR was merged in `webrtc-adapter`, so this issue can be closed?
