### ISSUE TITLE
change codec and bandwidth on the fly

### ISSUE THREAD

**Issue by startupgurukul** [feross/simple-peer#471]
hello folks, thank you for the library, we are trying to change the codec to vp9 if available 

https://developers.google.com/web/updates/2016/01/vp9-webrtc do you think the library can implement it along with it, dynamic bandwidth setting would also be awesome to have, below is a sample to do that https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/bandwidth/js/main.js

**Comment by startupgurukul** [comment]
Closing comment, found sdpTransform will reopen if it doesn't work

**Comment by t-mullen** [comment]
Change `peer.sdpTransform` (or it's behaviour), then call `peer.negotiate()`.
