### ISSUE TITLE
Crashing on iPhone

### ISSUE THREAD

**Issue by dnish** [feross/simple-peer#473]
Hey guys,
I don't know if I'm the only one with this issue, but since iOS 12.3 I'm having several issues when I try to call a person. Most of the time, the page crashes and Safari reloads, especially when I try to do a renegotiation (switch camera). Sometimes, the page crashes after the video conversation was stopped. Am I the only one with this issues?

**Comment by t-mullen** [comment]
I've noticed occasional iOS crashes during renegotiation. It's almost definitely a browser bug - we should try and reproduce this outside of simple-peer.

**Comment by dnish** [comment]
@t-mullen Any idea how we can find the problem? I've already submitted a log to Apple, but they seem not to get it. Just tried several times the renegotiation (camera change) and Safari crashes about every third time.

**Comment by dnish** [comment]
@t-mullen Is it possible that the issue is related to https://github.com/twilio/twilio-video.js/issues/294 ? On the latest iOS version, it's still crashing.

**Comment by feross** [comment]
Supposedly iOS 13.5 has fixed some crashes. @dnish Can you retest and see if this has been fixed for you?

**Comment by t-mullen** [comment]
I haven't experienced any of these iOS crashes in a long time. I believe this issue is fixed.
