### ISSUE TITLE
Connection between Firefox PC and Chrome Android doesn't establish

### ISSUE THREAD

**Issue by ucentrix** [feross/simple-peer#475]
I've been having troubles successfully establishing connection between Firefox on PC and Chrome on Android. Ice connection fails after about 10 seconds. If I use Chrome on PC and Chrome on Android the connection succeeds.

I'm using paid Twilio TURN (and STUN) servers and I also tried xirsys servers and with both the same problem persits.
I am 100% sure it is not a problem with the TURN servers, because I created my own very truncated implementation of simple-peer and the connection establishes without a problem.

I am also using the latest simple-peer (9.3.0) and went through the pinned troubleshooting for when ice connection fails (https://github.com/feross/simple-peer/issues/202#issue-262008686).
- I can successfully connect with the provided tool
- I receive more than one relay candidate
- I am using urls in config for iceServers
- I am using private STUN and TURN servers
- The latency on signalling messages is basically non existant and both sides receive all of the signal messages
- Firewall isn't blocking the connection since twilio is already using a TURN server with port 443 and transport tcp

Last debug message that simple-peer outputs (before ice connection fails) is "iceComplete timeout completed".

How would I even go about debugging this further?

**Comment by t-mullen** [comment]
We don't have Chrome on Android tests. I'll look into changing that.

**Comment by rgawenda** [comment]
It happens to me with streams from ios to firefox.
In the same setup (browsers stream to a server, with own turnserver). ios and chrome work both ways, firefox and chrome work both ways.
firefox from IOS results in this message after between 5 and 10 seconds (while firefox reveives from a chrome source near instantly)

**Comment by t-mullen** [comment]
We run tests on Android now with no unusual connection failures - do you still have this issue?

**Comment by feross** [comment]
Closing due to no response.
