### ISSUE TITLE
default example is having issue.

### ISSUE THREAD

**Issue by thewebdevelopment** [feross/simple-peer#476]
I am not sure creator or owner didn't tested the default example.

The issue:
After submitting form I am getting.
"Uncaught SyntaxError: Unexpected token q in JSON at position 0"

**Comment by t-mullen** [comment]
Could you log what you're passing into `peer.signal()`?

**Comment by thewebdevelopment** [comment]
```
document.querySelector('form').addEventListener('submit', ev => {
  ev.preventDefault()
  p.signal(JSON.parse(document.querySelector('#incoming').value))
})

```

Line is causing the issue
`p.signal(JSON.parse(document.querySelector('#incoming').value))`

**Comment by t-mullen** [comment]
What is the value of `document.querySelector('#incoming').value`?

**Comment by thewebdevelopment** [comment]
> What is the string value of `document.querySelector('#incoming').value`?

whenever I enter anything in text box and press submit it says.
Unexpected token < in JSON at position 0

**Comment by t-mullen** [comment]
Sorry, I'm asking you to run this code and tell me what it prints in the developer console:
```javascript
document.querySelector('form').addEventListener('submit', ev => {
  ev.preventDefault()
  console.log(document.querySelector('#incoming').value) // <- what does this print to console?
  p.signal(JSON.parse(document.querySelector('#incoming').value))
})

```

**Comment by t-mullen** [comment]
Feel free to reopen if you have more information. It looks like the string you are passing into the test field is not valid JSON.

**Comment by OsirisFrik** [comment]
> Sorry, I'm asking you to run this code and tell me what it prints in the developer console:
> 
> ```js
> document.querySelector('form').addEventListener('submit', ev => {
>   ev.preventDefault()
>   console.log(document.querySelector('#incoming').value) // <- what does this print to console?
>   p.signal(JSON.parse(document.querySelector('#incoming').value))
> })
> ```

Hi, i try the example, and i have a error on send data to `p.signal`, i try send object or JSON data, but any time return same error
```
error Error: signal() called with invalid signal data
    at makeError (index.js:17)
    at Peer.signal (index.js:220)
    at HTMLFormElement.eval (index.js:21)
```
my value in `#incoming` is `{"msg": true}` and log `{msg: true}` when pass to submit event

and, if you try a second time send the message, log error
```
index.js:17 Uncaught Error: cannot signal after peer is destroyed
    at makeError (index.js:17)
    at Peer.signal (index.js:178)
    at HTMLFormElement.eval (index.js:21)
```

**Comment by t-mullen** [comment]
`{msg: true}` is not valid signalling data.

**Comment by OsirisFrik** [comment]
@t-mullen check this example
[https://jsfiddle.net/osirisfrik/hyzqpgru/3](https://jsfiddle.net/osirisfrik/hyzqpgru/3)

**Comment by HyperClockUp** [comment]
same error in my demo, which use the code in README.
