### ISSUE TITLE
InvalidStateError: RTCDataChannel.readyState is not 'open'

### ISSUE THREAD

**Issue by lacker** [feross/simple-peer#480]
I'm calling `send` on a `simple-peer` and getting this error. It's happening in Node.js, when `peer.connected` is true. I can avoid it by checking `peer._channel.readyState` myself, but shouldn't the `simple-peer` library already be doing that for me?

Here's a stack trace:

```
InvalidStateError: RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (/home/lacker/go/src/github.com/axiom-org/axiom/ts/node_modules/wrtc/lib/index.js:48:8)
    at Peer.Object.<anonymous>.Peer.send (/home/lacker/go/src/github.com/axiom-org/axiom/ts/node_modules/simple-peer/index.js:243:17)
```

**Comment by t-mullen** [comment]
The channel should be ready after `connect` has fired. Are you waiting for this event before attempting to send?

**Comment by lacker** [comment]
Yeah the channel has been connected for a while. It seems like the RTCDataChannel may be in the middle of closing - this is typically happening during the cleanup phase of unit tests, where a lot of channels are being shut down.

What's the right way to make sure I'm not calling send after the RTCDataChannel has shut down? I was hoping that checking `peer.connected` would be good enough, but it isn't working in this case.

**Comment by lacker** [comment]
More info:

`peer.connected` is true
`peer.destroyed` is false
`peer._channel.readyState` is "closed"

**Comment by t-mullen** [comment]
We are polling the `readyState` in an interval, so it's likely your application is checking `peer.connected` right before that interval fires.

`peer.connected` needs a getter function that checks the `peer._channel.readyState`.
