### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'unref' of undefined

### ISSUE THREAD

**Issue by lacker** [feross/simple-peer#481]
I'm getting this error in node.js during the cleanup while the program is shutting down. I can narrow down the problem to these two lines of code:

https://github.com/feross/simple-peer/blob/master/index.js#L876

```
self._interval = setInterval(function () { self._onInterval() }, 150)
if (self._interval.unref) self._interval.unref()
```

It seems that in Node the return value of `setInterval` can sometimes be undefined, perhaps during some post-event-loop cleanup or something like that. I think the second line here should be changed to

```
if (self._interval && self._interval.unref) self._interval.unref()
```

**Comment by lacker** [comment]
Inserting this code to modify `global.setInterval` works as a workaround:

```
let oldSetInterval = global.setInterval;
global.setInterval = function(...args): any {
  let answer = oldSetInterval(...args);
  if (!answer) {
    return {};
  }
  return answer;
};
```

**Comment by lacker** [comment]
I submitted a one line pull request to fix this bug in https://github.com/feross/simple-peer/pull/482 - if someone could take a look that would be great!

**Comment by nazar-pc** [comment]
To me PR doesn't make any sense (not claiming it is necessary wrong though, everything can happen from my experience unfortunately). `.unref()` is called synchronously after `setInterval()`, nothing in Node.js should happen between those 2 points in time that clears `self._interval`.

Can you try to post reduce as bug report in Node.js first? If this is an upstream issue, we may accept a workaround until it is fixed, but currently it looks very suspicious.

If you can provide reduced example here and exact Node.js version, that would be useful as well.

**Comment by lacker** [comment]
AFAICT `self._interval` is not getting cleared, `setInterval` is just returning undefined. That is how the workaround fixes the problem.

I'll see if I can provide a reduced example. It doesn't seem to fail on every shutdown, unfortunately.

**Comment by lacker** [comment]
I figured out the problem is an interaction with the `jsdom` library. In my unit testing setup using jest, `jsdom` is providing a browser-like environment, but it replaces Node's `setInterval` with a different `setInterval` function that returns undefined when it's called during the cleanup phase. (After all tests complete, but while Node still isn't exiting because it's waiting for the various timers created by simple-timer.)

see: https://github.com/jsdom/jsdom/blob/865ad590454dd345521722184bc298b32fa40810/lib/jsdom/browser/Window.js#L659

IMO it would be great to merge this PR so that simple-peer plays nicely with jsdom and thus with writing unit tests using Jest. I can understand if you were to make the case that the problem is on jsdom's end, though.

To reproduce this, roughly, write a test using the Jest defaults (which use jsdom) and just open a bunch of simple-peers and close them. If you're opening and closing enough you'll run into it. I could make an example if it helps but it's pretty clear from the code that the jsdom setInterval sometimes returns undefined.

**Comment by nazar-pc** [comment]
Can you report to jsdom developers that this is wrong and breaks applications, please?

**Comment by lacker** [comment]
Yeah, I opened issue https://github.com/jsdom/jsdom/issues/2617
