### ISSUE TITLE
Needs an npm publish? - I think a bugfix is in master but not on npm

### ISSUE THREAD

**Issue by lacker** [feross/simple-peer#483]
In 9.3.0, sometimes this error, `TypeError: Cannot read property 'signalingState' of null` is thrown when destroying a simple-peer. It is coming from this section of code:

```
Peer.prototype._addIceCandidate = function (candidate) {
  var self = this
  self._pc.addIceCandidate(new self._wrtc.RTCIceCandidate(candidate)).catch(func
tion (err) {
    // HACK: node-webrtc throws an incorrect error https://github.com/node-webrt
c/node-webrtc/issues/498
    if (self._pc.signalingState !== 'closed' && err.message === 'Failed to set ICE candidate; RTCPeerConnection is closed.') {
      return self._debug('ignoring incorrect wrtc error')
    }
    self.destroy(makeError(err, 'ERR_ADD_ICE_CANDIDATE'))
  })
}
```

It looks to me like there is a bug here. If the Peer has been destroyed by the time this callback runs, it will try to access `self._pc.signalingState`, but `self._pc` has already been nulled out.

However! - it also looks like this bug has been fixed in master, since this line of code was removed in https://github.com/feross/simple-peer/commit/8c3b22c901d75f49b551407a6d543b8eee647815

That bugfix doesn't appear to have gotten to npm, though. The most recent version of simple-peer on npm is this one which still contains the old code:

https://unpkg.com/simple-peer@9.3.0/index.js

Could someone push a 9.3.1 that includes this bugfix?

**Comment by t-mullen** [comment]
Yes! https://github.com/feross/simple-peer/pull/485

Thanks for catching this - I've been a bit distracted by work.
