### ISSUE TITLE
Created peer connection failed using lib wrtc

### ISSUE THREAD

**Issue by ximenchuigao** [feross/simple-peer#484]
I tried to create peer using [wrtc](https://npmjs.com/package/wrtc) config, but get failed.
````
var wrtc = require('wrtc')    
var peer2 = new Peer({ wrtc: wrtc })
````
The code stopped working here:
````
self._pc = new (self._wrtc.RTCPeerConnection)(self.config)
````
The wrtc version is 0.4.1 and simple peer version is 9.3.0

No error or exception threw out...

**Comment by t-mullen** [comment]
What do you mean by "the code stopped working"? Does the Node process terminate?

**Comment by t-mullen** [comment]
The npm version was slightly out of date and contained a `wrtc` fix. Please install and try simple-peer `3.4.0`.

**Comment by ximenchuigao** [comment]
> What do you mean by "the code stopped working" if no exception was thrown? Does the Node process terminate?

Yes, the node process terminated without any exceptions or logs

**Comment by t-mullen** [comment]
Do you have anything else in your Node.js file that will keep the process alive? Your Node process may be just running your code and terminating normally.

**Comment by markandrus** [comment]
@ximenchuigao what version of Node were you using? Since wrtc 0.4.x, we're using N-API, and I noticed a slight behavior change in later Node 12 and now Node 13 builds. I have a change slated for release that may fix this.

**Comment by ximenchuigao** [comment]
@markandrus I got this problem in Node 12, and I can't  remember the exact sub-version.  I used a workaround to resolve peer connection issue in my project, so i didn't do any further investigation on it....

**Comment by t-mullen** [comment]
Closing because it seems you've found a workaround for your issue.
