### ISSUE TITLE
"incremental multistream" test failing on iOS

### ISSUE THREAD

**Issue by t-mullen** [feross/simple-peer#486]
The receiving peer is getting too many stream events. We should investigate this.

**Comment by feross** [comment]
Odd issue.

**Comment by t-mullen** [comment]
I should have added some more details about this issue, but as of yet I've been unable to reproduce this test failure locally - so all I know is the Saucelabs test is failing.

All tests consistently pass on a physical iPhone running iOS 12.2. Going to try 12.3.

**Comment by t-mullen** [comment]
12.3 also passes consistently. I ran a fresh XCode iPhone simulator (12.1, 12.2 and 12.3) for 50 runs each and all tests pass 100% of the time on all versions.

I thought it might be because the Travis tests connect via TURN - but even forcing TURN by filtering everything but relay candidates couldn't reproduce the issue.

I'm at a loss - unless someone has ideas about this, we can probably just disable this test for iOS.

**Comment by t-mullen** [comment]
I've managed to get a hold of a saucelabs account. It seems like this issue only occurs in the virtual iOS environment they have.

Sometimes tracks events for on the same MediaStream have a different MediaStream ID, meaning a stream event is being emitted for each track (double the stream events expected). It's not clear why this only occurs sometimes, but it doesn't happen in real iOS.

**Comment by feross** [comment]
Nice debugging!
