### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#489]
FYI, I'm removing `package-lock.json`. Module users will always get the latest version of our dependencies, so we should not trick ourselves into thinking things work by locking down our versions with a `package-lock.json` which will apply when we are developing this module.

IMO, `package-lock.json` only makes sense for apps, not modules.

**Comment by nazar-pc** [comment]
Removing it will cause installation of random package versions in CI for instance. This is the primary reason I prefer to keep it even for libraries. `package-lock.json` is not published to NPM anyway, so nothing to worry about in that regard.

**Comment by feross** [comment]
> Removing it will cause installation of random package versions in CI for instance

This is desirable. We want CI to install the same versions that a real user would install if they were to run `npm install simple-peer`.
