### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by pwFoo** [feross/simple-peer#490]
Simple-peer looks good and easy to use, but what is about encryption? e2e / p2p? Is there an example how it could be done?

**Comment by nazar-pc** [comment]
What kind of encryption are you talking about?
WebRTC transport itself is encrypted out of the box and for signaling data HTTPS is highly recommended.

**Comment by pwFoo** [comment]
And how to verify the peers identity? Sorry, I'm new with webrtc and don't know how it works. But it sounds really interesting to do some tests. But would be important how secure it is for data / chat texts. Thanks!

**Comment by nazar-pc** [comment]
You can use something like signatures or AEAD for signaling data and verify identify that way.
I've built a few things for Node.js that may be relevant to this use case:
* https://github.com/nazar-pc/supercop.wasm - digital signatures
* https://github.com/nazar-pc/noise-c.wasm - transport protocol framework with encryption

It heavily depends on specific use case you have.

**Comment by pwFoo** [comment]
Thanks, I take a look. 

At the moment I would start with e2e chat messages. Backend (signaling, users db) preferred php.
But it should be extendable if it works well and is fun to develop to add for example video support.

**Comment by pwFoo** [comment]
Tried your first simple examples and looks good.

> An "offer" will be generated by the initiator. Paste this into the receiver's form and hit submit. The receiver generates an "answer". Paste this into the initiator's form and hit submit.

The offer / answers can't be used for persistent peers / users, because it's ip / port dependent, right?
So I would need a way to have the initiater server side php and the client get the offer and send the answer back...

**Comment by pwFoo** [comment]
I think I can start with initiator / answer exchange via backend server. 

Like manual exchange via form send code to the server, verify user session and forward to peers. Same with answers of peers back to the initiator.

**Comment by nazar-pc** [comment]
You can't store answer/offer since they are one-time use and yes, you need some kind of server to exchange them before peers can establish direct connection. PHP will work fine for that. Also manual exchange is tricky, since AFAIK you only have about 30 seconds before answer/offer expire.

**Comment by pwFoo** [comment]
So offer / answer need to be generated just in time. Also if two peers connected (with an old offer+answer) and a third peer would need a new "server" / initiator offer to join?
And a disconnect handling for example because of ip address chang (reconnect with offer + answer) is needed?

So first peer is the initiator and if the initiator leaves all others should be disconnected and need reconnect with a new initiator?

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Comment by pavlobu** [comment]
it seems like there will be a new feature in webrtc comming soon called: Insertable Streams API

the main purpose of which is to add another security layer and make a real end to end encryption of
video streaming data.

by the time I'm writing this, [Insertable Streams API ](https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/) is only experimental feature and is not added to all browsers yet

hope that simple peer will support it as soon as it becomes available in new versions of browsers

here is more info on that: 

https://webrtchacks.com/you-dont-have-end-to-end-encryption-e2ee/
https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/
https://jitsi.org/blog/e2ee/

**Comment by ElectricReality** [comment]
Heyoo! First of all thank you @feross for the wonderful package you have created. It made the code im working on way simple and beautiful. It would be great for e2ee to be added to simple-peer once Insertable Streams is on production and used in mainstream.

**Comment by BabakYaghoobi** [comment]
See here:
https://github.com/w3c/webrtc-insertable-streams/blob/master/explainer.md

**Comment by akhil-rana** [comment]
Anyone successful in using insertable streams with simple peer? 
@feross Any plan on integrating this into SP?

**Comment by vanevery** [comment]
+1 on support for insertable streams.  Would be happy to contribute to an effort to get it working in SP.
