### ISSUE TITLE
Adding stream to nodejs connection to browser closes connection.

### ISSUE THREAD

**Issue by mturnshek** [feross/simple-peer#491]
I've got a camera in node that I want to stream to the browser (using Firefox right now), but I can't figure out how to get a track added to the connection.

### Attempts
In the following code, `connection` is a remote peer connection object, referred to as `peer1`, `peer2` usually in the example code.

attempt 1:
```
// Create a track and an empty stream.
let vs = new wrtc.nonstandard.RTCVideoSource();
let t = vs.createTrack();
let m = new wrtc.MediaStream([]);
connection.addStream(m);
connection.addTrack(t, m);
```
result: everything happens on the node side, but the connection closes before the 'stream' event can be received by the browser.

attempt 2:
```
let vs = new wrtc.nonstandard.RTCVideoSource();
let t = vs.createTrack();
let m = new wrtc.MediaStream([t]);
connection.addStream(m);
```
result: everything happens on the node side, but the connection closes before the 'stream' event can be received by the browser. (same result)

I've tried attempt 1 and 2 both immediately after establishing a connection, and with a timeout of 5 seconds after the 'connect' event.

attempt 3:
```
let vs = new wrtc.nonstandard.RTCVideoSource();
let t = vs.createTrack();
let m = new wrtc.MediaStream([]); // or wrtc.MediaStream([t])
let connection = new SimplePeer({ wrtc: wrtc, initiator: initiator, streams: [m] });
```
result: if t is passed to MediaStream, the connection is established and immediately closes, if t is not passed, the connection is established, but no streams can be located and no 'stream' event fires on the browser-side.

I've tried all examples both with and without swapping the browser WebRTC to `wrtc` instead of the native support, and nothing different happens.

Though, I did notice that `wrtc` in my browser, and `wrtc` in node were different. `wrtc.nonstandard` is undefined in the browser.

### Questions

Is what I'm trying to do possible/supported? It seems to be covered by the tests, like here:

https://github.com/feross/simple-peer/blob/master/test/multistream.js

I cloned the repo to run tests, and it seems like they all work fine, but I suppose it's only testing inter-nodejs peer connections.

If this is not supported by simple-peer, is there a way to do what I'm trying to do? Any leads?

Is there a way to add this capability to simple-peer without using the wrtc dependency directly?

Am I missing something else obvious?

Please let me know if I can provide any more information to help out.

**Comment by t-mullen** [comment]
Can you establish a connection and send data over the data channel from Node.js to the browser without adding any media streams? Confirming this works would rule out a lot of other issues.

**Comment by mturnshek** [comment]
This capability work great. I’m currently sending compressed images directly over the data channel and it works okay, but I’m trying to optimize it.

**Comment by t-mullen** [comment]
Ok then, I believe this would be the correct syntax:
```javascript
let vs = new wrtc.nonstandard.RTCVideoSource();
let t = vs.createTrack();
let m = new wrtc.MediaStream([t]);
let connection = new SimplePeer({ wrtc: wrtc, initiator: initiator, streams: [m] });
```
or
```javascript
let vs = new wrtc.nonstandard.RTCVideoSource();
let t = vs.createTrack();
let m = new wrtc.MediaStream([t]);
connection.addStream(m);
```

But I'm not sure if you can pass an empty video source like that. You might need to call `source.onFrame` at least once before adding it to the peer. What do your signalling messages look like?

**Comment by mturnshek** [comment]
Okay, I don't know how to use source.onFrame yet. I'll have to find an example of that somewhere and get back to you with the results.

Here are what my signals look like from node to browser:
```
signal sent from node to browser:
{ type: 'answer',
  sdp:
   'v=0\r\no=- 3264420586356700866 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 50281 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 192.168.1.16\r\nb=AS:30\r\na=candidate:3596738868 1 udp 2122260223 192.168.1.16 50281 typ host generation 0 network-id 1 network-cost 50\r\na=ice-ufrag:87T9\r\na=ice-pwd:zlj9hv4lyN0P5wCbeXXXT2T4\r\na=ice-options:trickle\r\na=fingerprint:sha-256 F3:AE:5F:B9:04:0A:3F:5A:15:EE:57:1A:4A:BC:8A:68:B6:C9:A4:85:C5:ED:60:6C:89:1D:74:88:9A:EE:4C:9B\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\n' }

signal sent from node to browser:
{ transceiverRequest: { kind: 'video', init: undefined } }

signal sent from node to browser:

{ candidate:
   { candidate:
      'candidate:3596738868 1 udp 2122260223 192.168.1.16 50281 typ host generation 0 ufrag 87T9 network-id 1 network-cost 50',
     sdpMLineIndex: 0,
     sdpMid: '0' } }
```

**Comment by mturnshek** [comment]
Okay, I think I managed to put some frames into the source with the following:

```
function getNodeStream() {
    let source = new wrtc.nonstandard.RTCVideoSource();
    const track = source.createTrack();
    const sink = new wrtc.nonstandard.RTCVideoSink(track);
    const frameWidth = 320;
    const frameHeight = 240;
    let frame = {
        width: frameWidth,
        height: frameHeight,
        data: new Uint8Array(frameWidth * frameHeight * 1.5),
    }

    setInterval(() => {
        source.onFrame(frame);
    }, 1000);

    sink.onframe = ({ frame }) => {
        console.log(frame);
    }

    let mediaStream = new wrtc.MediaStream([track]);
    return mediaStream;
}
```

I call this in advance, so `source.onFrame` is definitely called at least once before the connection begins. However, the same thing as before is happening: the connection closes without the 'stream' event occuring in the browser.

**Comment by t-mullen** [comment]
Why are you using a RTCVideoSink at all? 

RTCVideoSource with simple-peer works fine for me when the video is valid. It's what I use for manual testing here: https://github.com/t-mullen/wrtc-to-ffmpeg/blob/master/test/index.html

I tried the latest versions of `wrtc` and `simple-peer`, and everything still works.

**Comment by t-mullen** [comment]
This doesn't seem to be a simple-peer issue. The people at [node-webrtc](https://github.com/node-webrtc/node-webrtc/issues) could probably help you better than me.
