### ISSUE TITLE
Compare to peerjs

### ISSUE THREAD

**Issue by pwFoo** [feross/simple-peer#492]
Hi @feross,

how compare / differ simple-peer to https://github.com/peers/peerjs?

Any additional / missing features or advantages to peerjs?

**Comment by jarretttaylor** [comment]
PeerJS is no longer maintained. Additionally, it does not work with modern browsers since it hasn't evolved with the WebRTC specification..

**Comment by pwFoo** [comment]
Oh, ok. Thanks. Never thought it could be out of maintenance because last commit is 10 days ago.
So simple-peer is better for modern browsers.

**Comment by jarretttaylor** [comment]
If PeerJS has a recent commit, then someone might have picked it back up. The client side stopped working in March of 2018. At that time, the last commit was from a couple of years back. I switched to simple-peer and have never looked back.

**Comment by pwFoo** [comment]
So simple-peer is a newer base with modern browser focus. No need to take a closer look at peerjs ;)

**Comment by feross** [comment]
@pwFoo Sounds like your question has been answered :) I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Comment by szcuipeng** [comment]
Is there the latest answer by 2023?

**Comment by fredericrous** [comment]
in 2024, peerjs looks active, mostly 1 contributor tho. I am currently looking at libp2p which is active and used by the eth and ipfs community https://github.com/libp2p/js-libp2p
