### ISSUE TITLE
Error with multiple offers per RTCPeerConnection setup

### ISSUE THREAD

**Issue by corwin-of-amber** [feross/simple-peer#494]
I have encountered several scenarios where `setRemoteDescription` has been called more than once. This can happen if the `sdp` message is delayed on its way from one client, to the signalhub, to the second client. This mostly happens in slow networks with a high packet drop rate (e.g. 4G).

This is what's printed when debug is turned on:
```
simple-peer [783e416] destroy (error: InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Called in wrong state: kHaveLocalOffer) +2ms
```

**Comment by nazar-pc** [comment]
Almost always such cases are result of incorrect handling of signaling events. So it would be really nice to have reproducible test case such that we can confirm fix and make sure it doesn't regress.

**Comment by corwin-of-amber** [comment]
Yes, that would be ideal. Unfortunately that only happens "sometimes".

Also, looking at the error message I pasted before, it does not seem that my fix is sufficient. The erroneous state is when the pc has a _local_ offer, I am not sure why this is an invalid state for `setRemoteDescription`.

**Comment by nazar-pc** [comment]
Hm... make sure you're setting it on the correct peer. At least some code sample would be useful, I saw similar issues many times in the past.

**Comment by corwin-of-amber** [comment]
Ok, I am using signalhub/signalhubws for the signaling, and https://github.com/mafintosh/webrtc-swarm for setting up the connections, so it is possible that the problem is caused by one of those. They have been pretty reliable so far but messages do tend to get stalled when the connection is bad.

I am attaching an example source and a trace of simple-peer leading to the error.

[swarm.js.txt](https://github.com/feross/simple-peer/files/3374736/swarm.js.txt)
[kHaveLocalOffer.log.txt](https://github.com/feross/simple-peer/files/3374742/kHaveLocalOffer.log.txt)

**Comment by corwin-of-amber** [comment]
#369 seems relevant to this, but AFAICT only one end is initiating; more careful study of webrtc-swarm is needed to confirm this though.

**Comment by nazar-pc** [comment]
So those are logs from one side. What the other side says?

**Comment by corwin-of-amber** [comment]
> So those are logs from one side. What the other side says?

It is rather unfortunate but I did not have debug enabled on the other side at that particular point 😩 
Will update if this comes up again when I can catch both ends.

**Comment by corwin-of-amber** [comment]
Ok, I managed to reproduce this more-or-less consistently by running two instances of `swarm.js` at the very same time like so:
```
node swarm.js & ; node swarm.js
```
Looking at the logs, it seems that indeed both RTCPeerConnections are created as initiators. So like you said originally, this is a signaling problem, probably caused by webrtc-swarm in this case. Thanks!

**Comment by nazar-pc** [comment]
I'm closing this issue then, but feel free to continue discussion if necessary
