### ISSUE TITLE
Does `trickle` work out of the box or do we need special config?

### ISSUE THREAD

**Issue by bohrapp** [feross/simple-peer#496]
I have correctly implemented a signalin mechanism and I'm able to connect tow peers with `trickle: false`.

Now I would like to speed up things, but simply setting `trickle` to `true` won't work, as the non-initiator does not seem to be connected. 

These are the debug logs for the non-initiator:

    P2P debugger - connect
    Peer info 
                            - _id: 805cb65;
                            - _readableState: {"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null};
                            - readable: true;
                            - _events: {};
                            - _eventsCount: 7;
                            - _maxListeners: undefined;
                            - _writableState: {"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}};
                            - writable: true;
                            - allowHalfOpen: false;
                            - channelName: null;
                            - initiator: false;
                            - channelConfig: {};
                            - config: {"iceServers":[{"urls":"stun:stun.l.google.com:19302"}],"sdpSemantics":"unified-plan"};
                            - offerOptions: {};
                            - answerOptions: {};
                            - sdpTransform: undefined;
                            - streams: [];
                            - trickle: true;
                            - allowHalfTrickle: false;
                            - iceCompleteTimeout: 5000;
                            - connected: false;
                            - remoteAddress: undefined;
                            - remoteFamily: undefined;
                            - remotePort: undefined;
                            - localAddress: undefined;
                            - localFamily: undefined;
                            - localPort: undefined;
                            - _wrtc: {};
                            - _pcReady: false;
                            - _channelReady: false;
                            - _iceComplete: false;
                            - _iceCompleteTimer: null;
                            - _channel: null;
                            - _pendingCandidates: [{"candidate":"candidate:842163049 1 udp 1677729535 79.30.254.235 59950 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag W87U network-cost 999","sdpMLineIndex":0,"sdpMid":"0"}];
                            - _isNegotiating: true;
                            - _batchedNegotiation: false;
                            - _queuedNegotiation: false;
                            - _sendersAwaitingStable: [];
                            - _senderMap: {};
                            - _firstStable: true;
                            - _closingInterval: null;
                            - _remoteTracks: [];
                            - _remoteStreams: [];
                            - _chunk: null;
                            - _cb: null;
                            - _interval: null;
                            - _pc: {};
                            - _isReactNativeWebrtc: false;
                            - _onFinishBound: undefined;
                            - _debug: undefined;
                            - address: undefined;
                            - signal: undefined;
                            - _addIceCandidate: undefined;
                            - send: undefined;
                            - addTransceiver: undefined;
                            - addStream: undefined;
                            - addTrack: undefined;
                            - replaceTrack: undefined;
                            - removeTrack: undefined;
                            - removeStream: undefined;
                            - _needsNegotiation: undefined;
                            - negotiate: undefined;
                            - destroy: undefined;
                            - _destroy: undefined;
                            - _setupData: undefined;
                            - _read: undefined;
                            - _write: undefined;
                            - _onFinish: undefined;
                            - _startIceCompleteTimeout: undefined;
                            - _createOffer: undefined;
                            - _requestMissingTransceivers: undefined;
                            - _createAnswer: undefined;
                            - _onIceStateChange: undefined;
                            - getStats: undefined;
                            - _maybeReady: undefined;
                            - _onInterval: undefined;
                            - _onSignalingStateChange: undefined;
                            - _onIceCandidate: undefined;
                            - _onChannelMessage: undefined;
                            - _onChannelBufferedAmountLow: undefined;
                            - _onChannelOpen: undefined;
                            - _onChannelClose: undefined;
                            - _onTrack: undefined;
                            - write: undefined;
                            - cork: undefined;
                            - uncork: undefined;
                            - setDefaultEncoding: undefined;
                            - _writev: null;
                            - end: undefined;
                            - _undestroy: undefined;
                            - push: undefined;
                            - unshift: undefined;
                            - isPaused: undefined;
                            - setEncoding: undefined;
                            - read: undefined;
                            - pipe: undefined;
                            - unpipe: undefined;
                            - on: undefined;
                            - addListener: undefined;
                            - resume: undefined;
                            - pause: undefined;
                            - wrap: undefined;
                            - setMaxListeners: undefined;
                            - getMaxListeners: undefined;
                            - emit: undefined;
                            - prependListener: undefined;
                            - once: undefined;
                            - prependOnceListener: undefined;
                            - removeListener: undefined;
                            - removeAllListeners: undefined;
                            - listeners: undefined;
                            - listenerCount: undefined;
                            - eventNames: undefined.

I'm using the latest npm release, and I've also tested this with the latest github `min.js` file.

Do we need to implement some specific behavior to use `trickle`, or is it a problem with SimplePeer?

**Comment by nazar-pc** [comment]
Trickle ICE involves multiple signaling roundtrips, not one like without trickle. Are you sure all of them are forwarded to the other side?

**Comment by bohrapp** [comment]
I have noticed that the initiator receives more than one connection code from the other peer (in my tests 3), and it would seem that the same goes on for the other peer. I will check more on this, do you know of an example using trickle I could look into?

**Comment by feross** [comment]
This readme example uses trickle: https://github.com/feross/simple-peer#data-channels

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
