### ISSUE TITLE
Please Create A Gitter

### ISSUE THREAD

**Issue by TensorTom** [feross/simple-peer#500]
This is the most stable abstraction library I can find. Please make a Gitter.

Thank you

**Comment by feross** [comment]
Thanks for the kind words.

I personally don't want yet another "inbox" to have to check. I think GitHub issues are just fine. I'll defer to the other contributors, though.

**Comment by TensorTom** [comment]
it's just for colab of users mostly. the devs don't even have to talk there if they don't want.

**Comment by t-mullen** [comment]
I imagine someone would need to moderate it?

**Comment by feross** [comment]
You might consider joining `#webrtc` on IRC (freenode) or joining the `discuss-webrtc` mailing list: https://groups.google.com/forum/#!forum/discuss-webrtc
