### ISSUE TITLE
Handle ICE end of candidate

### ISSUE THREAD

**Issue by samuelmaddock** [feross/simple-peer#503]
Firefox v68 shipped an update which sends an ICE end of candidates message ([bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1318167)). The offer looks like this:
```js
{candidate: {candidate: "", sdpMLineIndex: 0, sdpMid: "0"}}
```

This seems to introduce an incompatibility between the latest version of Firefox (68.0) and Chrome (75.0.3770.100). When the offer is received in Chrome, an `OperationError` is thrown.

In my own testing, this is what I'm seeing:
![chrome_2019-07-13_16-56-465FQg](https://user-images.githubusercontent.com/1656324/61176529-54515200-a590-11e9-9ee6-c77cd5e6e3ef.png)

~~I'm using `simple-peer@9.3.0` which isn't the latest so I'll upgrade and update this thread if it fixes the problem.~~ Error persists on `simple-peer@9.4.0`.

**Comment by samuelmaddock** [comment]
For now I'm overriding `Peer.prototype.destroy` to ignore the `ERR_ADD_ICE_CANDIDATE` error.
```js
peer.destroy = (err) => {
  if (typeof err === 'object' && err.code === 'ERR_ADD_ICE_CANDIDATE') return;
  peer._destroy(err, () => {});
};
```

**Comment by t-mullen** [comment]
So the new "end" candidate has `event.candidate.candidate: ''` instead of `event.candidate.candidate:null` and Chrome doesn't support this?

**Comment by samuelmaddock** [comment]
@t-mullen Correct. I suspect this is ultimately up to Chrome to support, but it might be nice for simple-peer to smooth over the differences in the meantime.

**Comment by t-mullen** [comment]
Relevant: https://github.com/webrtcHacks/adapter/issues/863

**Comment by corwin-of-amber** [comment]
> So the new "end" candidate has `event.candidate.candidate: ''` instead of `event.candidate.candidate:null` and Chrome doesn't support this?

In my Firefox (running on Mac) I observed `candidate: ""` as well as a `null` candidate to signify the end of the candidates list.
