### ISSUE TITLE
Problem With Signaling In Example

### ISSUE THREAD

**Issue by TensorTom** [feross/simple-peer#504]
I included the mesh examples (peer1, peer2, peer3) in 3 separate .html files. For signaling, I specified my coturn server in the config:

```
config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        }
```
I added that to every instance of `= new SimplePeer` for that 3 file example. The pages load without errors but nothing happens. I expect to see the messages such as `hi peer2, this is peer1` but there's nothing. What has gone wrong?

Thanks for al the hard work.

**peer1.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Peer1</title>
</head>
<body>
<script src="../../js/simplepeer.min.js"></script>
<script>
    // These are peer1's connections to peer2 and peer3
    var peer2 = new SimplePeer({ initiator: true, config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        } })
    var peer3 = new SimplePeer({ initiator: true, config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        } })

    peer2.on('signal', data => {
        console.log(data)
    })

    peer2.on('connect', () => {
        peer2.send('hi peer2, this is peer1')
    })

    peer2.on('data', data => {
        console.log('got a message from peer2: ' + data)
    })

    peer3.on('signal', data => {
        console.log(data)
    })

    peer3.on('connect', () => {
        peer3.send('hi peer3, this is peer1')
    })

    peer3.on('data', data => {
        console.log('got a message from peer3: ' + data)
    })
</script>
</body>
</html>```
```

**peer2.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Peer2</title>
</head>
<body>
<script src="../../js/simplepeer.min.js"></script>
<script>
    // These are peer2's connections to peer1 and peer3
    var peer1 = new SimplePeer({
        config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        }
    })
    var peer3 = new SimplePeer({ initiator: true, config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        } })

    peer1.on('signal', data => {
        console.log(data)
    })

    peer1.on('connect', () => {
        peer1.send('hi peer1, this is peer2')
    })

    peer1.on('data', data => {
        console.log('got a message from peer1: ' + data)
    })

    peer3.on('signal', data => {
        console.log(data)
    })

    peer3.on('connect', () => {
        peer3.send('hi peer3, this is peer2')
    })

    peer3.on('data', data => {
        console.log('got a message from peer3: ' + data)
    })
</script>
</body>
</html>
```

**peer3.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Peer3</title>
</head>
<body>
<script src="../../js/simplepeer.min.js"></script>
<script>
    // These are peer3's connections to peer1 and peer2
    var peer1 = new SimplePeer({
            config: {
                iceServers: [
                    {urls: 'stun:stun.a-mm.tv:3478'},
                    {urls: 'stun:167.88.117.196:3478'}
                ]
            }
        }
    )
    var peer2 = new SimplePeer({
        config: {
            iceServers: [
                {urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:167.88.117.196:3478'}
            ]
        }
    })

    peer1.on('signal', data => {
        console.log(data)
    })

    peer1.on('connect', () => {
        peer1.send('hi peer1, this is peer3')
    })

    peer1.on('data', data => {
        console.log('got a message from peer1: ' + data)
    })

    peer2.on('signal', data => {
        console.log(data)
    })

    peer2.on('connect', () => {
        peer2.send('hi peer2, this is peer3')
    })

    peer2.on('data', data => {
        console.log('got a message from peer2: ' + data)
    })
</script>
</body>
</html>
```

**Comment by TensorTom** [comment]
I added console.log to the `.on('signal'` callbacks. Here's the output:

peer1:
![peer1](https://i.imgur.com/5QF52dY.png)

peer2:
![peer2](https://i.imgur.com/JhsgafE.png)

peer3 has no console output.

**Comment by t-mullen** [comment]
Are you passing the signalling events between the peers, or just logging them?

**Comment by TensorTom** [comment]
okay so it doesn't implement any of that but I don't have to open a websocket connection to any server, right? it will only be browser2browser? An example of this would be very helpful.

**Comment by t-mullen** [comment]
Yup, simple-peer doesn't implement the signalling structure - it's application-specific and needs a server (but you could have users copy-paste the signalling data through instant messaging apps). 

There's plenty of examples of how to use websockets, socket.io, or even HTTP. There's also libraries dedicated to WebRTC signalling:
https://github.com/t-mullen/simple-signal (I'm the author)
https://github.com/mafintosh/signalhub

**Comment by t-mullen** [comment]
Closing because there's no issue here, but feel free to continue discussion.

**Comment by TensorTom** [comment]
Just one more thing, if that's okay. So then:

- STUN is used to supply SDP information to each browser client.
- simple-peer does not exchange this SDP information.
- Instead, a separate, centralized (client/server), signaling protocol must be used.
- Websockets would exchange the SDP data, simple-peer would connect the browsers via data-channels, and no more client/server would be necessary after that?

My misconception has been that, I thought that upon receiving the STUN signaling data, no other server communication would be required. That WebRTC was then capable of initiating a connection to another browser. Oh I get it. Because STUN only gives you your NAT traversal data. Is that right? It doesn't exchange multiple peers' SDP data?

**Comment by t-mullen** [comment]
I think you got it. STUN servers provide server reflexive (srflx) candidates that are used for NAT traversal. 

The SDP contains a lot of things, like the fingerprints that will be used for key negotiation (WebRTC connections are encrypted and you need a secure channel to make sure you are connecting to the right person), as well as media-related things like the number of video/audio tracks, their codecs, etc. Specifics about datachannel properties are passed through here too (is the channel reliable, maximum window size, etc).

The other peer's ICE candidates are sent through this signalling data too (simple-peer abstracts the difference between candidate and SDP messages). Knowing your own "IP" from the STUN server is great, but you also need the peer's "IP" to connect.

It can get pretty complicated (a big complaint when the ICE spec was being drafted), but all you need to know to use it is that `signal` events need to be passed between peers.

https://andrewjprokop.wordpress.com/2013/09/30/understanding-session-description-protocol-sdp/

**Comment by TensorTom** [comment]
If you have a moment, would you please tell me what I'm doing wrong? I feel like I'm so close. To do signaling, I have decided to use Gun.js because it seems perfect for this use-case. Gun is working perfectly, passing the SDP data between the two as far as I can tell (Logged to console). 

peer2 gives no errors. peer1 gives the following 2 errors:

`Error: InvalidStateError: Cannot set remote offer in state have-local-offer`

_and_

`Error: cannot signal after peer is destroyed`

Here are the links to my two pages and I will post the code below as well:

peer1: [https://tinyurl.com/yyocspo7](https://tinyurl.com/yyocspo7)
peer2: [https://tinyurl.com/y3o92tuo](https://tinyurl.com/y3o92tuo)

**peer1.html**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>peer1</title>
</head>
<body>
<script src="js/jquery.js"></script>
<script src="js/gun.js"></script>
<script src="js/sea.js"></script>

<script src="js/adapter.js"></script>
<script src="js/simplepeer.min.js"></script>
<script>
    let gun = Gun(['https://myserver.com:8443/gun'])
    var gpeer1 = gun.get('peer1')

    let peer2 = new SimplePeer({ initiator: true, config: {
            iceServers: [
                //{urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:myserver:3478'}
            ]
        } })

    gun.get('peer2').get('sdp').on(function(data){
        console.log("signal from peer2: " + data)
        peer2.signal(data)
    })

    peer2.on('signal', data => {
        gpeer1.put({sdp: JSON.stringify(data)})
    })

    peer2.on('connect', () => {
        peer2.send('hi peer2, this is peer1')
    })

    peer2.on('data', data => {
        console.log('got a message from peer2: ' + data)
    })
</script>
</body>
</html>
```

**peer2.html**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>peer2</title>
</head>
<body>
<script src="js/jquery.js"></script>
<script src="js/gun.js"></script>
<script src="js/sea.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/gun/lib/webrtc.js"></script>-->

<script src="js/adapter.js"></script>
<script src="js/simplepeer.min.js"></script>
<script>
    let gun = Gun(['https://myserver.com:8443/gun'])
    var gpeer2 = gun.get('peer2')

    //gun.get('orders').map().on(function(data){

    let peer1 = new SimplePeer({ initiator: true, config: {
            iceServers: [
                //{urls: 'stun:stun.a-mm.tv:3478'},
                {urls: 'stun:myserver.com:3478'}
            ]
        } })

    gun.get('peer1').get('sdp').on(function(data){
        console.log("signal from peer1: " + data)
        peer1.signal(data)
    })

    peer1.on('signal', data => {
        gpeer2.put({sdp: JSON.stringify(data)})
    })

    peer1.on('connect', () => {
        peer1.send('hi peer1, this is peer2')
    })

    peer1.on('data', data => {
        console.log('got a message from peer2: ' + data)
    })
</script>
</body>
</html>
```

**Comment by TensorTom** [comment]
@t-mullen Update: I added `initiator: false` to peer2 which got rid of those errors but still there is no data exchange over data-channel being logged. I still must have done something wrong.

**Comment by t-mullen** [comment]
Make sure all the signalling messages are getting to the other peer. I've no idea how "Gun" works.

Try logging everything that comes out of peer1's `signal` event and everything going into `peer2.signal()` and comparing them.

**Comment by t-mullen** [comment]
Are you getting the `connect` event?

**Comment by t-mullen** [comment]
Seems like you might still have some issues with the signalling channel:
<img width="719" alt="Screen Shot 2019-07-16 at 5 57 32 PM" src="https://user-images.githubusercontent.com/14932492/61332825-3f282d80-a7f3-11e9-9dd9-0dd42f98f5de.png">
