### ISSUE TITLE
[Question] Users online and received / read information?

### ISSUE THREAD

**Issue by pwFoo** [feross/simple-peer#508]
I searched and read some information about webrtc and maybe would start to play with webrtc (simple-peer, simple-signal)...

During think about it I stumbled over user online / offline presence and read by recipient information.
Is it possible to implement such features and how could it be done?

I think webrtc connection is started on demand (chat, audio call offer). Send+Receive text message could be verified by data channel of both others are online, but if one user is offline (or just not "active" in the chat session = no webrtc connection established) webrtc data channel isn't established, right?
So how could it done?

**Comment by t-mullen** [comment]
https://github.com/t-mullen/simple-signal/issues/22
