### ISSUE TITLE
Chrome throws InvalidAccessError when receiving incremental streams from Safari 

### ISSUE THREAD

**Issue by t-mullen** [feross/simple-peer#513]
When receiving 5 streams from Safari added in quick asynchronous succession, Chrome throws:
`
Uncaught (in promise) Error: InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
`

It looks like this happens when a stream is added during renegotiation.

Working on a fix.

**Comment by t-mullen** [comment]
The signalling channel I was using for interop testing was delivering messages out-of-order. There's no issue here.

**Comment by feross** [comment]
Nice :)

**Comment by Mihai-github** [comment]
Hi, I'm getting the same error message using chrome and firefox when adding a new MediaStream to the connection... any idea how can i solve this?
