### ISSUE TITLE
Track duplication errors should be non-fatal

### ISSUE THREAD

**Issue by corwin-of-amber** [feross/simple-peer#515]
`addTrack`, `replaceTrack`, and `removeTrack` call `destroy()` if the operation is rejected. Isn't this a bit harsh? It does not give the caller a chance to catch the error and handle it gracefully, and is also rather hard to debug when you have a long log.

Seems to me that these errors can just be `throw`n instead.

**Comment by t-mullen** [comment]
The `Track has been removed.` and `Track has already been added to that stream.` errors are non-fatal and should just emit an `error` event. If those are the errors you mean then I'm on board.

Errors from `pc. addTrack` itself are likely fatal and should destroy the peer.

**Comment by corwin-of-amber** [comment]
Those are basically the ones I meant. As for errors from `pc.addTrack`, it seems that `InvalidAccessError` is non-fatal but then again, should never happen due to the preceding check. `InvalidStateError` only occurs if the connection is closed so destroying the peer is probably ok.
