### ISSUE TITLE
How to work with older browser which doesn't support promised api?

### ISSUE THREAD

**Issue by sky0014** [feross/simple-peer#516]
Chrome52 support promised webrtc api. But how can I use it in older browser like chrome43?

it has error: `Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary`

**Comment by jimmywarting** [comment]
not many use chrome 43 as chrome do autoupdates

**Comment by sky0014** [comment]
> not many use chrome 43 as chrome do autoupdates
> v43 is 4+ years old

yes, but we have some users use chrome<52, and the boss don't want to abandon them :cry:

**Comment by nazar-pc** [comment]
You can try older version that supported callback-based API, but I'm pretty sure you'll have issues with other newer browsers.
If you really need to support browsers from 2015, your best bet is to fork simple-peer and implement necessary support yourself.

**Comment by t-mullen** [comment]
You could also try https://github.com/webrtcHacks/adapter
