### ISSUE TITLE
Help wanted.

### ISSUE THREAD

**Issue by je3f0o** [feross/simple-peer#520]
Hello I'm a newbie for WebRTC. I wanted to create a simple multi peers connected audio session. First I created a listening `MediaStreamAudioDestinationNode` for other peers audio streams.
```
// Step 1: Created a MediaStreamAudioDestinationNode
const listen_stream_node = audio_context.createMediaStreamDestination();
```
Then I connected this `listen_stream_node` into audio element.
```
// Step 2: Connect MediaStreamAudioDestinationNode into audio element and play it.
cosnt audio_el = document.createElement("audio");

audio_el.onloadedmetadata = () => {
    audio_el.play();
    console.log("Audio playing...");
};

if ("srcObject" in audio_el) {
    audio_el.srcObject = listen_stream_node.stream;
} else {
    audio_el.src = URL.createObjectURL(listen_stream_node.stream);
}
```
Reason why I created a `listen_stream_node` is I wanted to mix all incoming media streams into single media stream node and play mixed `listen_stream_node`.
```
// Step 3:
// Mix all other peers incoming MediaStreams and
// connect to destination MediaStreamNode.
peer.on("stream", stream => {
    const media_source = audio_ctx.createMediaStreamSource(stream);
    media_source.connect(listen_stream_node);
    console.log("Stream connected");
});
```
Streams connected and I do not listen anything...
But if I try my own local stream connect into `listen_stream_node` and i hear myself. Everything works fine. But I don't want to listen myself and I wanted to listen only other peers streams.
```
// Test code for AudioNode.prototype.connect() method
// Everything works fine if I connect my own local stream into listen_stream_node.
// Exact same code with above peer.on("stream", stream => {...}); event.
navigator.mediaDevices.getUserMedia({ audio : true }).then(stream => {
    const media_source = audio_ctx.createMediaStreamSource(stream);
    media_source.connect(listen_stream_node); // Now I can hear myself
});
```
Please help me what is wrong with this? I've been trying to figure it out myself for whole fucking night. xD
Thank you.

**Comment by t-mullen** [comment]
WebAudio nodes get garbage collected if you create them in a scope and don't keep a reference to them.

```javascript
{ 
  const myNode = audioContext.createMediaStreamSource(stream);
}
myNode // node will be invalid soon after leaving the scope
```

Fix this by keeping a reference on something that won't be garbage collected, like `window`.
```javascript
window.audioNodeRefs = []
{ 
  const myNode = audioContext.createMediaStreamSource(stream);
  window.audioNodeRefs.push([])
}
myNode // node will be invalid soon after leaving the scope
```

**Comment by t-mullen** [comment]
Closing since this seems to be about the WebAudio API than simple-peer, but feel free to continue discussion.

**Comment by je3f0o** [comment]
Hello t-mullen. It is not garbage collected problem. My original code was this:
```
peer.on("stream", stream => {
    peer.__stream       = stream;
    peer.__media_source = audio_ctx.createMediaStreamSource(stream);
    peer.__media_source.connect(this.listen_stream_node);
    console.log("Stream connected");
});
```
I keep it MediaStreamSource reference assigned into peer itself.
This is really weird. If play this stream directly into audio element it will play without any problem. But when I connect this remote stream into my destination `listen_stream_node` it wont play...
