### ISSUE TITLE
Peers more than 2 fail to connect eachother 

### ISSUE THREAD

**Issue by mestefanivanov** [feross/simple-peer#523]
when peer3 joins the room the connection between peer1 and peer 2 fails ...  I commented this line of code and now everything is okay but I do not think this is the best way to handle this. The error is that peer cannot signal after destroyed 
![image](https://user-images.githubusercontent.com/46354551/62307291-fecfdd00-b48b-11e9-83e8-66977129aed3.png)

github repository here  ()=> https://github.com/mestefanivanov/WEBRTCRUSE

**Comment by nazar-pc** [comment]
It is not possible to connect more than 2 peers directly, since WebRTC only supports 2 peers: initiator and responder.
If you need more than 2 - you'll want to create a mesh or do some other hackery around this limitation.

**Comment by t-mullen** [comment]
A SimplePeer object represents one side of a two-sided WebRTC connection. There's no such thing as a 3-sided connection.

You can connect 3 browsers together by creating a different connection between each one (each browser creates 2 SimplePeer objects). Just make sure that each connection has one initiator and one non-initiator and you aren't mixing signal events between connections.

**Comment by mestefanivanov** [comment]
> A SimplePeer object represents one side of a two-sided WebRTC connection. There's no such thing as a 3-sided connection.
> 
> You can connect 3 browsers together by creating a different connection between each one (each browser creates 2 SimplePeer objects). This is called a "mesh". Just make sure that each connection has one initiator and one non-initiator and you aren't mixing signal events between connections.

That is is exactly what I am doing. But if I dont comment this line in simple-peer node there is some kind of error and one of the peers destroys himself . As I said when I I comment line 537 everything works just fine and the mesh is alright. I am sure that each connection has initiator and non - initiator and they connect properly. Now I am connecting multiple peers without problem and everyone can hear and send messages to  everyone. I checked if they properly send offers and responses between each other .  I just dont think messing with the library is the best way to do it. I am just asking why when i comment this line everything works just fine

**Comment by t-mullen** [comment]
What error is it? You can catch errors in simple-peer by listening to the `error` event.

**Comment by mestefanivanov** [comment]
> What error is it? You can catch errors in simple-peer by listening to the `error` event.

![image](https://user-images.githubusercontent.com/46354551/62373436-719b8f80-b542-11e9-8658-1997e4bd9763.png)
okay so I console logged the error which caused me this peer_.destroy problem and its DOMException ...And my other question is it right on whatever error to call peer_.destroy ..I have no idea what caused this DOMException error in first place 
PS: Thank u for the quick reply

**Comment by t-mullen** [comment]
The error should have a property called `code` on it. Could you log `err.code`?

**Comment by mestefanivanov** [comment]
> The error should have a property called `code` on it. Could you log `error.code`?

![image](https://user-images.githubusercontent.com/46354551/62400289-61f26a00-b587-11e9-9322-1ff827ad8f87.png)
Yeah sure. Its 11

**Comment by t-mullen** [comment]
Can you try the latest simple-peer version on Github? All errors from simple-peer should have descriptive string codes and there was a few that didn't.

The latest version should tell us where this error is from (if it's from simple-peer at all).

**Comment by mestefanivanov** [comment]
> Can you try the latest simple-peer version on Github? All errors from simple-peer should have descriptive string codes and there was a few that didn't.
> 
> The latest version should tell us where this error is from (if it's from simple-peer at all).

![image](https://user-images.githubusercontent.com/46354551/62458830-96804480-b786-11e9-8223-e8f53028487a.png)

**Comment by t-mullen** [comment]
That's a completely different error. It looks like there's issues with how you are doing signalling. The wrong signalling data is being passed into peers.

Double-check that peers aren't receiving signalling data from the other connection, that every connection has one initiator and one non-initiator and that peers aren't being removed.

**Comment by mestefanivanov** [comment]
> That's a completely different error. It looks like there's issues with how you are doing signalling. The wrong signalling data is being passed into peers.
> 
> Double-check that peers aren't receiving signalling data from the other connection, that every connection has one initiator and one non-initiator and that peers aren't being reused for a new connection.

I could not find where is the mistake. I am posting my client side and server side for ideas. Everything is well appreciated 
client side ()=> https://pastebin.com/dMMmvbFL
server side ()=> https://pastebin.com/jBkdb1Ch

**Comment by t-mullen** [comment]
```
    //Get last joined user to emmit offers just to him
    var user= clients.pop();
```
Sending the offer to the last connected client isn't correct - this could be the same client!

**Comment by t-mullen** [comment]
Closing this issue since it's not related to simple-peer, but I'd still be happy to answer questions.

You might want to take a look at [simple-signal](https://github.com/t-mullen/simple-signal) if you want a reference for your signalling code.
