### ISSUE TITLE
addStream closes the peer connection

### ISSUE THREAD

**Issue by jiangts** [feross/simple-peer#528]
After establishing a peer connection, addStream calls the `peer.on('close'...)` event. Using data channels works perfectly fine.

Then, I get `Uncaught Error: cannot signal after peer is destroyed`

My guess is it has to do with the `_stream_readable` programmatically calling destroy...

**Comment by jiangts** [comment]
ok, I found that my issue was I was adding too many `peer.on` listeners, which seems unrelated but by changing it to `peer.once` the peer stopped closing on me

**Comment by t-mullen** [comment]
Closing since it seems like this issue was resolved. Feel free to reopen with reproduction steps if that's not the case.

**Comment by jiangts** [comment]
hmm, I think it's worth investigating if adding too many `peer.on` listeners causes the peer connection to close.  If it's desired behavior, I think it should be mentioned on the README.
