### ISSUE TITLE
peer.signal is not a function

### ISSUE THREAD

**Issue by measwel** [feross/simple-peer#537]
Good day,

I have two peers, A and B. 
A creates peer B with initiator TRUE. 
As I understand, this means that peer A is the initiator.

A sends the offer to B. B creates the peer for A with initiator FALSE. 
B then calls signal on peer A.
B sends the answer back to A. 
However, when I try to pass the answer to signal on peer B, I get the error: peer.signal is not a function

I do not understand why the function is missing (undefined) on this peer. Can somebody please point me in the right direction?

**Comment by ckcr4lyf** [comment]
Can you also link some code, so it may be possible to understand this a bit better? 

i.e. how you're creating the peers, how its signalling

**Comment by measwel** [comment]
Yes, I am using my own signalling server for that, implemented in nodejs websocket. I am also using uuids for peer identification.

self.$runFunction('Communicator', 'addChat', {chat: chatItem, initiator: true})

On A runs : self.addChat({chat: peerB, initiator: true})
addChat will also create the peer for B like so:

`        let peer = new window.SimplePeer({
          initiator: initiator,
          trickle: false
        })

        peer.on('error', err => console.log('error', err))

        peer.on('signal', data => {
          var signal = JSON.stringify(data)
          console.log('SIGNAL', signal)
          self.$socket.emit('signal', {fromuuid: self.$auth.token.uuid, touuid: uuid, signal: signal})
        })

        peer.on('connect', () => {
          console.log('PEER CONNECTED')
        })

        peer.on('close', () => {
          console.log('PEER CLOSED')
        })

        peer.on('data', data => {
          console.log('PEER DATA: ' + data)
        })`

Signals are sent to the socket server, where they are delivered to the other peer:

`    socket.on('signal', function (data) {
      if (io.sockets.connected[user_socket[data.touuid]] !== undefined) {
        io.sockets.connected[user_socket[data.touuid]].emit('signal', {fromuuid: socket.userUuid, touuid: data.touuid, signal: data.signal});
      } else {
        logger.log('info', 'User ' + socket.userName + ' wants to chat, but ' + data.touuid + ' is not connected');
      }
    });`

Sending the signal to the relevant peer works fine, both the offer and answer are delivered.
When the signal arrives at a peer, it is processed with:

`
      signal: function (data) {
        let self = this
        let signal = JSON.parse(data.signal)
        let fromuuid = data.fromuuid
        console.log('received signal', data) 

        // if first signal, add the chat with initiator 'false'
        if (signal.type === 'offer') {
          // get requesting user's data from server
          self.$rest.User.get(fromuuid).then(response => {
            var fullUser = response.data.data
            var userString = JSON.stringify(fullUser)

            // add chat to list. this also creates the peer for this chat
            // on peer B we create a peer for A with initiator false, as we are receiving the offer signal
            let chat = self.addChat({chat: fullUser, initiator: false})

            // process the signal to build a peer to peer connection
            chat.peer.signal(data.signal) <-- THIS WORKS FINE. THE OFFER IS PROCESSED ON PEER B AND AN ANSWER IS GENERATED AND SENT BACK TO PEER A

          }).catch(function (err) {
            self.$utils.checkResponse(err.response)
          })
        } else { // Here the signal is of type answer, so the chat and its peer already exists. 

          let chat = self.allChats[fromuuid] <---  WORKS. CHAT AND PEER B ARE FOUND.
          chat.peer.signal(data.signal) <--- THIS PRODUCES THE ERROR : chat.peer.signal is not a function (undefined)
        }
      }
`

**Comment by measwel** [comment]
I can add to that, that the peer B object seems to change between sending out the offer and receiving the answser.

After sending the offer it is:
allowHalfOpen: false
allowHalfTrickle: false
answerOptions: {}
channelConfig: {}
channelName: "bac622a7ce0945a649be43cd40151c6ee203c42e"
config: {iceServers: Array(2), sdpSemantics: "unified-plan"}
iceCompleteTimeout: 5000
initiator: true
localAddress: undefined
localFamily: undefined
localPort: undefined
offerOptions: {}
readable: true
remoteAddress: undefined
remoteFamily: undefined
remotePort: undefined
sdpTransform: ƒ (e)
streams: []
trickle: false
writable: true
_batchedNegotiation: false
_cb: null
_channel: RTCDataChannel {label: "bac622a7ce0945a649be43cd40151c6ee203c42e", ordered: true, maxRetransmitTime: 65535, maxRetransmits: 65535, protocol: "", …}
_channelReady: false
_chunk: null
_closingInterval: 314
_connected: false
_events: {end: ƒ, finish: ƒ, error: ƒ, signal: ƒ, connect: ƒ, …}
_eventsCount: 7
_firstStable: false
_iceComplete: true
_iceCompleteTimer: 322
_id: "863ffac"
_interval: null
_isNegotiating: true
_isReactNativeWebrtc: false
_maxListeners: undefined
_onFinishBound: ƒ ()
_pc: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: null, pendingLocalDescription: RTCSessionDescription, remoteDescription: null, currentRemoteDescription: null, …}
_pcReady: false
_pendingCandidates: []
_queuedNegotiation: false
_readableState: d {objectMode: false, highWaterMark: 16384, buffer: e, length: 0, pipes: null, …}
_remoteStreams: []
_remoteTracks: []
_senderMap: Map {_c: Map(0)}
_sendersAwaitingStable: []
_writableState: s {objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: false, …}
_wrtc: {RTCPeerConnection: ƒ, RTCSessionDescription: ƒ, RTCIceCandidate: ƒ}
bufferSize: (...)
connected: (...)
destroyed: (...)
readableBuffer: (...)
readableFlowing: (...)
readableHighWaterMark: (...)
readableLength: (...)
writableBuffer: (...)
writableHighWaterMark: (...)
writableLength: (...)
__proto__: r
addStream: ƒ (e)
addTrack: ƒ (e, t)
addTransceiver: ƒ (e, t)
address: ƒ ()
destroy: ƒ (e)
getStats: ƒ (e)
negotiate: ƒ ()
removeStream: ƒ (e)
removeTrack: ƒ (e, t)
replaceTrack: ƒ (e, t, n)
send: ƒ (e)
signal: ƒ (e)
_addIceCandidate: ƒ (e)
_createAnswer: ƒ ()
_createOffer: ƒ ()
_debug: ƒ ()
_destroy: ƒ (e, t)
_maybeReady: ƒ ()
_needsNegotiation: ƒ ()
_onChannelBufferedAmountLow: ƒ ()
_onChannelClose: ƒ ()
_onChannelMessage: ƒ (e)
_onChannelOpen: ƒ ()
_onFinish: ƒ ()
_onIceCandidate: ƒ (e)
_onIceStateChange: ƒ ()
_onInterval: ƒ ()
_onSignalingStateChange: ƒ ()
_onTrack: ƒ (e)
_read: ƒ ()
_requestMissingTransceivers: ƒ ()
_setupData: ƒ (e)
_startIceCompleteTimeout: ƒ ()
_write: ƒ (e, t, n)
bufferSize: (...)
connected: (...)
constructor: ƒ r(e)
destroyed: (...)
readableBuffer: (...)
readableFlowing: (...)
readableHighWaterMark: (...)
readableLength: (...)
writableBuffer: (...)
writableHighWaterMark: (...)
writableLength: (...)
get bufferSize: ƒ ()
get connected: ƒ ()
__proto__: s

But after receiving the answer it is:
allowHalfOpen: (...)
allowHalfTrickle: (...)
answerOptions: (...)
channelConfig: (...)
channelName: (...)
config: (...)
iceCompleteTimeout: (...)
initiator: (...)
offerOptions: (...)
readable: (...)
streams: (...)
trickle: (...)
writable: (...)
_batchedNegotiation: (...)
_cb: (...)
_channel: (...)
_channelReady: (...)
_chunk: (...)
_closingInterval: (...)
_connected: (...)
_events: (...)
_eventsCount: (...)
_firstStable: (...)
_iceComplete: (...)
_iceCompleteTimer: (...)
_id: "863ffac"
_interval: (...)
_isNegotiating: (...)
_isReactNativeWebrtc: (...)
_pc: (...)
_pcReady: (...)
_pendingCandidates: (...)
_queuedNegotiation: (...)
_readableState: (...)
_remoteStreams: (...)
_remoteTracks: (...)
_senderMap: (...)
_sendersAwaitingStable: (...)
_writableState: (...)
_wrtc: (...)
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
get allowHalfOpen: ƒ reactiveGetter()
set allowHalfOpen: ƒ reactiveSetter(newVal)
get allowHalfTrickle: ƒ reactiveGetter()
set allowHalfTrickle: ƒ reactiveSetter(newVal)
get answerOptions: ƒ reactiveGetter()
set answerOptions: ƒ reactiveSetter(newVal)
get channelConfig: ƒ reactiveGetter()
set channelConfig: ƒ reactiveSetter(newVal)
get channelName: ƒ reactiveGetter()
set channelName: ƒ reactiveSetter(newVal)
get config: ƒ reactiveGetter()
set config: ƒ reactiveSetter(newVal)
get iceCompleteTimeout: ƒ reactiveGetter()
set iceCompleteTimeout: ƒ reactiveSetter(newVal)
get initiator: ƒ reactiveGetter()
set initiator: ƒ reactiveSetter(newVal)
get offerOptions: ƒ reactiveGetter()
set offerOptions: ƒ reactiveSetter(newVal)
get readable: ƒ reactiveGetter()
set readable: ƒ reactiveSetter(newVal)
get streams: ƒ reactiveGetter()
set streams: ƒ reactiveSetter(newVal)
get trickle: ƒ reactiveGetter()
set trickle: ƒ reactiveSetter(newVal)
get writable: ƒ reactiveGetter()
set writable: ƒ reactiveSetter(newVal)
get _batchedNegotiation: ƒ reactiveGetter()
set _batchedNegotiation: ƒ reactiveSetter(newVal)
get _cb: ƒ reactiveGetter()
set _cb: ƒ reactiveSetter(newVal)
get _channel: ƒ reactiveGetter()
set _channel: ƒ reactiveSetter(newVal)
get _channelReady: ƒ reactiveGetter()
set _channelReady: ƒ reactiveSetter(newVal)
get _chunk: ƒ reactiveGetter()
set _chunk: ƒ reactiveSetter(newVal)
get _closingInterval: ƒ reactiveGetter()
set _closingInterval: ƒ reactiveSetter(newVal)
get _connected: ƒ reactiveGetter()
set _connected: ƒ reactiveSetter(newVal)
get _events: ƒ reactiveGetter()
set _events: ƒ reactiveSetter(newVal)
get _eventsCount: ƒ reactiveGetter()
set _eventsCount: ƒ reactiveSetter(newVal)
get _firstStable: ƒ reactiveGetter()
set _firstStable: ƒ reactiveSetter(newVal)
get _iceComplete: ƒ reactiveGetter()
set _iceComplete: ƒ reactiveSetter(newVal)
get _iceCompleteTimer: ƒ reactiveGetter()
set _iceCompleteTimer: ƒ reactiveSetter(newVal)
get _id: ƒ reactiveGetter()
set _id: ƒ reactiveSetter(newVal)
get _interval: ƒ reactiveGetter()
set _interval: ƒ reactiveSetter(newVal)
get _isNegotiating: ƒ reactiveGetter()
set _isNegotiating: ƒ reactiveSetter(newVal)
get _isReactNativeWebrtc: ƒ reactiveGetter()
set _isReactNativeWebrtc: ƒ reactiveSetter(newVal)
get _pc: ƒ reactiveGetter()
set _pc: ƒ reactiveSetter(newVal)
get _pcReady: ƒ reactiveGetter()
set _pcReady: ƒ reactiveSetter(newVal)
get _pendingCandidates: ƒ reactiveGetter()
set _pendingCandidates: ƒ reactiveSetter(newVal)
get _queuedNegotiation: ƒ reactiveGetter()
set _queuedNegotiation: ƒ reactiveSetter(newVal)
get _readableState: ƒ reactiveGetter()
set _readableState: ƒ reactiveSetter(newVal)
get _remoteStreams: ƒ reactiveGetter()
set _remoteStreams: ƒ reactiveSetter(newVal)
get _remoteTracks: ƒ reactiveGetter()
set _remoteTracks: ƒ reactiveSetter(newVal)
get _senderMap: ƒ reactiveGetter()
set _senderMap: ƒ reactiveSetter(newVal)
get _sendersAwaitingStable: ƒ reactiveGetter()
set _sendersAwaitingStable: ƒ reactiveSetter(newVal)
get _writableState: ƒ reactiveGetter()
set _writableState: ƒ reactiveSetter(newVal)
get _wrtc: ƒ reactiveGetter()
set _wrtc: ƒ reactiveSetter(newVal)
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()

It is the same peer, as can be seen by the ID. However, after receiving the answer the proto does not have the signal function anymore. I do not understand what causes the object definition to change.

**Comment by t-mullen** [comment]
Are you using VueJS?

**Comment by measwel** [comment]
Yes. I have imported the simplepeer.min.js library.

**Comment by t-mullen** [comment]
VueJS is modifying the peer object (notice all of the reactiveGetters etc). It's possible this is breaking the peer's prototypes (they are completely missing in the second log you posted).

I'm not too familiar with Vue - but try storing the peer objects in an object not watched by Vue so nothing is modified. You'll know you're successful when the peer has no reactiveGetters.

**Comment by measwel** [comment]
Thank you very much for the suggestion. I will try to find out what is going on.

**Comment by measwel** [comment]
t-mullen, you are right; 

When you pass a plain JavaScript object to a Vue instance as its data option, Vue will walk through all of its properties and convert them to getter/setters using Object.defineProperty. 

The peers where added to the chats object, which is a reactive data property. I need to keep the peers separated from my reactive data. Will update.

**Comment by t-mullen** [comment]
Closing since this seems solved. 👍
