### ISSUE TITLE
Connection racing condition

### ISSUE THREAD

**Issue by measwel** [feross/simple-peer#539]
If two peers come online and want to connect simultanously, then a racing condition can arise where they both send an offer as initiator to the other peer. I currently deal with that by storing an offer timestamp and if two offers cross eachother, I will discard the initiator with the older timestamp and create a non initiator peer instead.

I hope this is the right way to deal with this situation. After the peers are connected, I delete the timestamp, so all other signals are processed normally.

**Comment by t-mullen** [comment]
Sure, that's a reasonable way to resolve the conflict. 

simple-peer doesn't cover signalling - there's an endless number of behaviours your application might need here.
