### ISSUE TITLE
How to call other peers and respond to the call?

### ISSUE THREAD

**Issue by gopchi** [feross/simple-peer#540]
I've created a simple p2p video app but one thing that I cannot think of is how to set up the initiator to be a dynamic value? Here is what I would like to build - one client opens a link, another opens another link, they are both in the same room, because I'm exchanging their offers/answers with socket.io. I would like both parties to be able to call each other and be able to accept/reject the call (like in any other p2p app). Could you please suggest an idea how can it be achieved?

**Comment by feross** [comment]
Have you tried making the person who clicks "Make call" be the initiator?

**Comment by gopchi** [comment]
I have tried, but wouldn't be there a race condition if both parties try to call each other? Then I suppose I should track the timestamps and use sockets to exchange in between who was the first initiator, then destroy the other peer and recreate with initiator: false. Or maybe destroy both peers and recreate them both? Not sure, if the signaling would work OK if I destroy only one of them, since the other has signaled already.

Regarding accepting the call, I can only think of two possible scenarios:

1. Display a pop up with action buttons when you get an offer from another peer. Then if you want to reject the call just destroy the peer and send back a "rejected" event via socket, maybe.
2. The other option is when I got a stream from the other peer to do the same thing as in 1).

In your opinion which is a better approach?

Thanks!

**Comment by t-mullen** [comment]
There's a ton of ways to resolve this conflict.

[simple-signal](https://github.com/t-mullen/simple-signal) assigns unique IDs to every peer, tracks outgoing connections, and ignore conflicting connections from peers with lower IDs. It also attaches unique session IDs to each outgoing message to prevent signalling messages from being mixed between the conflicting connections.

You could also just create two connections and only keep the first one to fire the `connect` event.

You could also have your signalling server filter out conflicting messages.

I don't recommend using timestamps. Clocks between peers will not be synchronized.

**Comment by gopchi** [comment]
@t-mullen  Thank you for suggesting simple-signal! I didn't know about it and now life would get easier :) I am closing the issue since this provides answer to my question. Once again thank you!
