### ISSUE TITLE
peer.on('connect') is never called with firebase signaling.

### ISSUE THREAD

**Issue by deepakiitgcse** [feross/simple-peer#544]
Hi Folks, I am trying to use firebase realtime database to send the signaling data and make the peer connection work without any success. Below is the code snippet:

```
constructor() {
 const databaseRef = this.firebaseApp.database().ref('unique_id');
 this.selfPeer = new SimplePeer({initiator:true, trickle: false});
 this.selfPeer.on('signal', function(data) {
  databaseRef.set(data);
 });
}

connectTo(otherPersonUniqueId) {
    return new Promise((resolve, reject) => {
      const signalData = this.firebaseApp.database().get(otherPersonUniqueId);
      var peer = new SimplePeer({initiator: false});
      peer.signal(signalData);
      peer.on('connect', ()=> {
        resolve(peer);
      });
      peer.on('_connect_error', err => {
        reject(err);
      });
    });
}
```

However the peer.on('connect') is never called when I try to connect to other peers.

Thanks a bunch for helping with this.

**Comment by nazar-pc** [comment]
`signal` event is asynchronous and can happen multiple times.
So `const signalData = this.firebaseApp.database().get(otherPersonUniqueId);` doesn't look right at all.

You need some kind of even system that will be able to listen for events on one side and send them to the other side. And similarly in the opposite direction. Please look at readme for simple examples of that.

**Comment by t-mullen** [comment]
You're also not capturing the `signal` event of the non-initiator peer. Signalling messages go both ways.
