### ISSUE TITLE
SessionDescription is NULL

### ISSUE THREAD

**Issue by Lichwa** [feross/simple-peer#55]
I've used audio/video example from README file in my project and managed to get everything running, however when I rewrote everything to use my node.js + socket.io signaling server there started to be problems. What I'm trying to accomplish is streaming video directly to server, not to other clients.

After sending initial signal message from browser:
````javascript
socket.on('signal', function(data) {
    simplePeer.signal(data);
});
````
I'm getting this error on server:
````javascript
Error: SessionDescription is NULL.
````
After this, peer connection is closed and I can't go anywhere from there.
I'm using basic configuration on server side:
```javascript
var SimplePeer = require('simple-peer')
var wrtc = require('wrtc')
var peer = new SimplePeer({ wrtc: wrtc })
````
Am I doing something wrong in here?

**Comment by contra** [comment]
@Lichwa Can you provide a repo that recreates the issue + a full stack trace?

**Comment by feross** [comment]
@Lichwa I'm going to close this since it's been 18 days with no reply. If this is still an issue for you, feel free to leave a comment or open a new issue.
