### ISSUE TITLE
Restore peer connection

### ISSUE THREAD

**Issue by loustak** [feross/simple-peer#550]
Hello,

Is it possible to restore a peer to peer connection?
I would like to be able to store in the local storage the `offer` and the `answer` to restore connection on page refresh for exemple. 
But, I'm not currently sure if Webrtc allow this.

Thanks.

**Comment by nazar-pc** [comment]
No, offer and answer are only valid for about 30 seconds and are not reusable, you can only use them to establish that specific connection instance. As soon as you refresh the page, create new peer instance or 30 seconds passed, you need to start again.
