### ISSUE TITLE
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by otkelbay** [feross/simple-peer#552]
**Hello! I am having such kind of issue, i will be very grateful if anyone can help me!**
Error: OperationError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=max-message-size:262144 Invalid SDP line. 
Here is full SDP: 
"v=0
o=- 4367642876331182851 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=msid-semantic: WMS 9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t
m=audio 55727 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 37.99.48.167
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2999745851 1 udp 2122260223 192.168.56.1 1048 typ host generation 0 network-id 2
a=candidate:2131708102 1 udp 2122194687 192.168.0.100 1049 typ host generation 0 network-id 1 network-cost 10
a=candidate:4266086002 1 udp 1685987071 37.99.48.167 55727 typ srflx raddr 192.168.0.100 rport 1049 generation 0 network-id 1 network-cost 10
a=candidate:4233069003 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 network-id 2
a=candidate:831304758 1 tcp 1518214911 192.168.0.100 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:C5Zb
a=ice-pwd:3q4HuXTjVw+093LF4AfZVJmt
a=fingerprint:sha-256 D9:52:25:7E:93:A4:E5:D8:C2:57:56:CD:F6:57:B4:D1:D3:A2:0F:A5:C7:78:AD:36:A3:03:40:D4:16:73:F0:3F
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t b20a3472-7772-4285-8fd5-1e5f0114fa95
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1633076812 cname:FTGyI9TyIhW2G0q/
a=ssrc:1633076812 msid:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t b20a3472-7772-4285-8fd5-1e5f0114fa95
a=ssrc:1633076812 mslabel:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t
a=ssrc:1633076812 label:b20a3472-7772-4285-8fd5-1e5f0114fa95
m=video 10325 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116
c=IN IP4 37.99.48.167
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2999745851 1 udp 2122260223 192.168.56.1 1050 typ host generation 0 network-id 2
a=candidate:2131708102 1 udp 2122194687 192.168.0.100 1051 typ host generation 0 network-id 1 network-cost 10
a=candidate:4266086002 1 udp 1685987071 37.99.48.167 10325 typ srflx raddr 192.168.0.100 rport 1051 generation 0 network-id 1 network-cost 10
a=candidate:4233069003 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 network-id 2
a=candidate:831304758 1 tcp 1518214911 192.168.0.100 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:C5Zb
a=ice-pwd:3q4HuXTjVw+093LF4AfZVJmt
a=fingerprint:sha-256 D9:52:25:7E:93:A4:E5:D8:C2:57:56:CD:F6:57:B4:D1:D3:A2:0F:A5:C7:78:AD:36:A3:03:40:D4:16:73:F0:3F
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:12 urn:3gpp:video-orientation
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t 8e8851d0-024d-4d23-95c3-079610393475
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=123
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 3284123291 436202575
a=ssrc:3284123291 cname:FTGyI9TyIhW2G0q/
a=ssrc:3284123291 msid:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t 8e8851d0-024d-4d23-95c3-079610393475
a=ssrc:3284123291 mslabel:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t
a=ssrc:3284123291 label:8e8851d0-024d-4d23-95c3-079610393475
a=ssrc:436202575 cname:FTGyI9TyIhW2G0q/
a=ssrc:436202575 msid:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t 8e8851d0-024d-4d23-95c3-079610393475
a=ssrc:436202575 mslabel:9dG52MWfaPLGBCafgl3YQFczox9DSweMv30t
a=ssrc:436202575 label:8e8851d0-024d-4d23-95c3-079610393475
m=application 2087 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 37.99.48.167
a=candidate:2999745851 1 udp 2122260223 192.168.56.1 1052 typ host generation 0 network-id 2
a=candidate:2131708102 1 udp 2122194687 192.168.0.100 1053 typ host generation 0 network-id 1 network-cost 10
a=candidate:4266086002 1 udp 1685987071 37.99.48.167 2087 typ srflx raddr 192.168.0.100 rport 1053 generation 0 network-id 1 network-cost 10
a=candidate:4233069003 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 network-id 2
a=candidate:831304758 1 tcp 1518214911 192.168.0.100 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:C5Zb
a=ice-pwd:3q4HuXTjVw+093LF4AfZVJmt
a=fingerprint:sha-256 D9:52:25:7E:93:A4:E5:D8:C2:57:56:CD:F6:57:B4:D1:D3:A2:0F:A5:C7:78:AD:36:A3:03:40:D4:16:73:F0:3F
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:262144"

**Comment by otkelbay** [comment]
Just adding new line fixes bug: 
`signal.data.sdp += `\n`;`

**Comment by chocnut** [comment]
> Just adding new line fixes bug:
> `signal.data.sdp += `\n`;`

This works for me. @otkelbay do you know why need to add a \n?

**Comment by RewriteH** [comment]
> Just adding new line fixes bug:
> `signal.data.sdp += `\n`;`

lmao

**Comment by hypo-thesis** [comment]
Where did you add this line?

**Comment by hypo-thesis** [comment]
> Just adding new line fixes bug:
> `signal.data.sdp += `\n`;`

Where did you add this line?

**Comment by YonelaNuba** [comment]
> > Just adding new line fixes bug:
> > `signal.data.sdp += `\n`;`
> 
> Where did you add this line?



> > Just adding new line fixes bug:
> > `signal.data.sdp += `\n`;`
> 
> This works for me. @otkelbay do you know why need to add a \n?

Where did you guys add this line?

**Comment by FickXu** [comment]
> > > Just adding new line fixes bug:
> > > `signal.data.sdp += `\n`;`
> > 
> > 
> > Where did you add this line?
> 
> > > Just adding new line fixes bug:
> > > `signal.data.sdp += `\n`;`
> > 
> > 
> > This works for me. @otkelbay do you know why need to add a \n?
> 
> Where did you guys add this line?

I has a same problem, is you problem sloved?

**Comment by pesova** [comment]
> > > > Just adding new line fixes bug:
> > > > `signal.data.sdp += `\n`;`
> > > 
> > > 
> > > Where did you add this line?
> > 
> > 
> > > > Just adding new line fixes bug:
> > > > `signal.data.sdp += `\n`;`
> > > 
> > > 
> > > This works for me. @otkelbay do you know why need to add a \n?
> > 
> > 
> > Where did you guys add this line?
> 
> I has a same problem, is you problem sloved?

  const updatedSignal = {...data.signal, sdp: `${data.signal.sdp}\n`,};

**Comment by sids3083** [comment]
> Just adding new line fixes bug: `signal.data.sdp += `\n`;`

same issue i facing . can you please tell me where need to add this line. i m using vue

**Comment by slothentic** [comment]
Adding the the extra newline issue on the client side is the wrong solution, the payload contains a trailing newline, which gets trimmed by Laravel, possibly other frameworks.

Try editing this file: app/Http/Middleware/TrimStrings.php

Add the new key to exclude that parameter in the payload

```
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\TrimStrings as Middleware;

class TrimStrings extends Middleware
{
    protected $except = [
        'password',
        'password_confirmation',
        'signal.sdp', // <-- add this
    ];
}
```

Now you won't need to add the newline, the payload will already contain it

**Comment by shenfusheng** [comment]
你好，邮件已收到，谢谢！
