### ISSUE TITLE
RTCPeerConnection.addStream is deprecated

### ISSUE THREAD

**Issue by jzombie** [feross/simple-peer#556]
Just noticed that addStream is deprecated according to MDN (https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream).

I think that the README.md should be updated to reflect this.

**Comment by t-mullen** [comment]
We don’t use addStream internally. sinple-peer’s addStream is just a convenient wrapper around compliant addTrack 👍

**Comment by jzombie** [comment]
Nice!  I was hoping that would be the case.  Congrats then.
