### ISSUE TITLE
Adding streams after connection is made

### ISSUE THREAD

**Issue by omar94f** [feross/simple-peer#557]
Hi,
I am trying to dynamically add a stream after onConnect event has fired, this makes the peer fire another offer which I didnt know would happen. I tried to to signal this offer back to the receiving peer but that caused a crash. So what would be the proper way to handle dynamically adding a stream to an established connection. Im sure Im missing something which is not clear from the documentation.

var peer = new SimplePeer({
      initiator: true,
      trickle: false,
      
    })

this is how I am creating the initiating peer. On 'connect' I getUserMedia and call addStream().
Exactly how should I handle renegotiation for adding a stream?
Thanks

**Comment by t-mullen** [comment]
Your signalling code should be prepared for any number of signalling events from both peers. There’s more events than just the second offer that you may not be passing.

Also considering using a signalling library like signalhub or simple-signal.

**Comment by omar94f** [comment]
<img width="1049" alt="Screen Shot 2019-10-14 at 4 54 07 PM" src="https://user-images.githubusercontent.com/22911770/66749431-55ea2900-eea3-11e9-8e2d-5a0b0359dd7f.png">

This is the error I get when I signal back the new offer after the addStream. Any idea as to what can be wrong?

**Comment by t-mullen** [comment]
`data` is the object or JSON string you passed into `peer.signal()`. It’s undefined, which means you passed `undefined` to `peer.signal()`.

Make sure you’re passing signalling data and nothing else.

**Comment by omar94f** [comment]
Wow it was as simple as that cant believe I missed that, it did the job. Thanks for the help man really appreciate it.
