### ISSUE TITLE
Data channel crashing on sending Uint8Array

### ISSUE THREAD

**Issue by sahil-devzila** [feross/simple-peer#561]
Hi,
The library works very well for sharing voice/video over rtc connection.
I have a problem sharing Uint8Array when i do conn.send(data) the conn.on('close') get triggered automatically

what i tried is 
let c = document.getElementById("mySketcher");
let ctx = c.getContext("2d");
let imgData = ctx.getImageData(0, 0, c.width, c.height);
data = Buffer.from(imgData.data);
conn.send(data);
---- connection breaks here-------
<img width="1423" alt="Screenshot 2019-10-16 at 6 49 25 PM" src="https://user-images.githubusercontent.com/45587435/66922992-b87b2a80-f045-11e9-954b-02882931eec1.png">
The above shows what data i am trying to send.
i am using chrome Version 77.0.3865.120 (Official Build) (64-bit) 
Does the browser allow this big buffer size to transfer? this is something around 1549412 bytes as per me.

**Comment by t-mullen** [comment]
Module to chunk streams: https://www.npmjs.com/package/chunk-stream

Blog about maximum chunk size for RTCDataChannels (recommends 16kb chunks): http://viblast.com/blog/2015/2/5/webrtc-data-channel-message-size/


```javascript
var chunks = require('chunk-stream')
inputStream.pipe(chunks(16000)).pipe(peer)
```

or, with `write`:

```javascript
var chunks = require('chunk-stream')
var chunkStream = chunks(16000)
chunkStream.pipe(peer)

chunkStream.write(myData)
```

**Comment by sahil-devzila** [comment]
Thanks alot i will check this out. Looks like this is some webrtc guideline to follow. Closing this, not going to increase issue count of this awesome plugin.
