### ISSUE TITLE
SimplePeer is not a constructor

### ISSUE THREAD

**Issue by dirkk0** [feross/simple-peer#566]
Hi,

  when I try the example in the 'usage' paragraph, I get the error 'SimplePeer is not a constructor'.

Falling back to an older version of simplepeer.min.js (greenkeeper/bowser-2.7.0.), the example works.

Thanks,
  Dirk

**Comment by JinHengyu** [comment]
v9.3.1 works:
https://github.com/feross/simple-peer/releases/tag/v9.3.1

**Comment by feross** [comment]
How are you including the simple-peer code in your project?

**Comment by dirkk0** [comment]
I don't have a project yet. I am just trying out what works or not.
I followed the explanation here:
https://github.com/feross/simple-peer#usage
And it didn't work with master.
It did work with greenkeeper/bowser-2.7.0.

I didn't try v9.3.1 yet.
Should I?

**Comment by feross** [comment]
It turns out that I broke the minified build recently by switching `babel-minify` to `tinyify`. I just published a new version that fixes the issue. Give it a try.
