### ISSUE TITLE
Initial Signal takes long time for the initiator

### ISSUE THREAD

**Issue by gflores** [feross/simple-peer#568]
It takes me very long time (more than 40 seconds) for the initiator (initiator: true) to emit his initial signal.
Am I the only one in this situation ?

I'm Windows, running google chrome

**Comment by cracker0dks** [comment]
chrome takes a bit longer for me as well (Win10)
Win10+Chrome: ~3 Secs
Win10+FF: ~0.5 Secs
but 40 Seconds is somthing else....

**Comment by t-mullen** [comment]
Make sure you're not setting `trickle: false` in peer options and also try an alternative STUN server (the default STUN servers can be slow sometimes).

**Comment by t-mullen** [comment]
If the above steps don't improve performance for you, feel free to reopen.
