### ISSUE TITLE
Feature: Unreliable DataChannels

### ISSUE THREAD

**Issue by kumavis** [feross/simple-peer#57]
I'm looking to use webRTC to create a pair of RTCDataChannels per peer:
* tcp-like `{ reliable: true, ordered: true }` transport
* udp-like `{ reliable: false, ordered: false }` transport

This may be out of the scope of `simple-peer` but is there a simple way of creating additional dataChannels for a peer?

**Comment by kumavis** [comment]
reading through the source a bit more, seems like the data channel and the peer are closely coupled

**Comment by feross** [comment]
There's already an issue open for supporting creating additional data channels: https://github.com/feross/simple-peer/issues/19

For starters, we could support unreliable data channels.

**Comment by kumavis** [comment]
cool - i'll close this as a duplicate

**Comment by feross** [comment]
So you don't need unreliable channels?

**Comment by kumavis** [comment]
I do, but I feel like this issue falls cleanly under #19. I think you already support unreliable data channels via setting `channelConfig`.

**Comment by feross** [comment]
Yep, that's right.
