### ISSUE TITLE
how to send blob

### ISSUE THREAD

**Issue by m0ose** [feross/simple-peer#58]
I'm just curious how one would send a blob. It's hard for me to tell if the error is coming from chrome 47 or not.

the following code gives an error:

```javascript
    var b = new Blob(new Uint32Array(123))
    client.send(b) // this is a simple-peer
```

> Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': Blob support not implemented yet(…)

**Comment by feross** [comment]
Yes, this error is coming from Chrome. They don't support sending Blobs. WebSocket has the same issue too :(

You can convert it into a Buffer first. Here's a package to do that: https://github.com/feross/blob-to-buffer

**Comment by m0ose** [comment]
Thanks for the quick and informative reply.
How does one handle the data getting broken into chunks? I sent an image and it came in 2 seperate chunks.

**Comment by feross** [comment]
Are you calling `peer.send` or `peer.write`? If you call `peer.send` I think it should arrive in one chunk.

**Comment by m0ose** [comment]
I am using send. 
After playing around with it, I think that the max size for a send in chrome is 2^16 bytes. Firefox doesn't seem to have the same problem. 
I put a little test page at http://livetexture.com/firebase_webrtc_handshake/tests/testDataUtils.html

the code, after the handshake and stuff, looks a bit like 
```javascript
      var a = new ArrayBuffer(Math.pow(2,27)) 
      connection.send(a)
```
The actual test code lives at https://github.com/RedfishGroup/firebase_webrtc_handshake/blob/master/tests/testDataUtils.js#L74-L120
