### ISSUE TITLE
Use the Same Offer/SDP Multiple Times

### ISSUE THREAD

**Issue by JuliaBonita** [feross/simple-peer#582]
Hello,

I have a situation where I only want to exchange offer/SDP/ICE candidates _one time_ with one peer. Then the two peers should save their respective offer/answer and then re-use the same offer/answer again in the future to connect directly to each other without needing to re-connect to the signaling server every time they want to communicate. Can I use SimplePeer to accomplish this?

I have tried to do this myself by saving the offer and answer to a variable (`savedOffer` and `savedAnswer` respectively) and then skipping the `createOffer()` call and calling `peerConnection.setLocalDescription(savedOffer)` directly on the 2nd, 3rd . . . _nth_ session. But in Firefox I get a `Cannot set local offer when createOffer has not been called` error. 

Since `createOffer()` simply produces an SDP blob and there are no stateful integrity checks in any of the SDP fields that would prevent the same offer/SDP from being used multiple times, I don't see any reason why I can't re-use an offer multiple times, but I have not been able to figure out whether SimplePeer or some other approach will work.

Please help.

**Comment by nazar-pc** [comment]
This is not possible. Neither with Simple Peer nor without it, this is simply the way WebRTC API works. There were actually questions about this here already.
Just like Firefox said, you can only set local description that was just generated on the page. Moreover, SDP is only valid for short amount of time, so it doesn't make sense to store it anyway.
