### ISSUE TITLE
NotAllowedError: Invalid state

### ISSUE THREAD

**Issue by its-me-ilia** [feross/simple-peer#586]
Hey, I just used simple-peer and it works on computer but when i tried from samsung mobile, it showed error in title. what is problem?

**Comment by nazar-pc** [comment]
There is not enough information I'm afraid to figure out what is going on exactly.
Could you clarify where exactly error comes from? Like a stacktrace?

**Comment by its-me-ilia** [comment]
@nazar-pc as soon as website is opened this error occures, tutorial which lead me had exact same error and he solved it by clearing cache, so as long as i can't be sure if my user will need to clear cache i want to know if there is any possible way to solve this rather than clearing cache

**Comment by nazar-pc** [comment]
Well, this looks like an issue with website or browser and not with simple-peer unless there is a stacktrace pointing to simple-peer library specifically.

**Comment by its-me-ilia** [comment]
I think this is usual issue since the tutor had this issue as well by the way its chrome 79 and website is only dedicated to simple peer and no other logic is implemented which could cause error

**Comment by nazar-pc** [comment]
Well, even if that is the case (which I doubt, since I haven't experienced it myself even though I use simple-peer extensively), without concrete demo and reproduction steps it is next to impossible to figure out why.

**Comment by its-me-ilia** [comment]
Oh I am sorry, tutor had same TYPE of error with different message, my bad. I am going to close this issue
