### ISSUE TITLE
Connection does not initiate when using VPN

### ISSUE THREAD

**Issue by omar94f** [feross/simple-peer#589]
The connection works most of the time but not when a VPN is being used and in some random instances.

All signaling works fine, offer and answer are exchanged properly but nothing happens when offer peer calls signal() with the answer.

Any clarity on what might be the cause will be appreciated.

**Comment by nazar-pc** [comment]
If library works, then you'd have better chances getting help by creating post on StackOverflow or something similar.
Simple-peer is just a convenient wrapper and issues section in this repo is not a general support forum about WebRTC 🙃.

With that being said, your best friends are WebRTC developer tools in Chromium and Firefox, there you can see what browser does and why. Depending on networking conditions and VPN setup you may need to use TURN servers.

I'm closing this issue as there is nothing to be done in simple-peer on this topic.
