### ISSUE TITLE
iOS: Renegetation not working

### ISSUE THREAD

**Issue by dnish** [feross/simple-peer#592]
I have 2 peers connected to each other (Safari <-> Chrome). If the Safari user tries to change his camera, the connections stops on Chrome. I'm getting the following error message:

    destroy (error: InvalidAccessError: Failed to execute 'setRemoteDescription' on 
    'RTCPeerConnection': Failed to set remote offer sdp: Media section has more than one track 
    specified with a=ssrc lines which is not supported with Unified Plan.)

This is my function where I switch the camera:

    await this.getUserMedia(remoteRequest); // Setting this.localStream with new constraints
    this.peer.addStream(this.localStream);

If I add <code>this.peer.removeStream(this.localStream);</code> to the top, I don't get any error, but the connection stops on both sides.

**Comment by nazar-pc** [comment]
So Chrome wants to use Unified Plan, but your iOS Safari seems to still use Plan-B.
Which version of iOS is it, did you install latest updates available?

This is nothing wrong with simple-peer, but rather generic WebRTC question, so I'm closing this issue, but feel free to continue discussion.
