### ISSUE TITLE
Is it possible to send data like chat message and whiteboard canvas data with this?

### ISSUE THREAD

**Issue by joshbedo** [feross/simple-peer#594]
Just curious it hasn't been super clear and I haven't found any examples but is it possible to also have real-time chat next to the video and do things like send whiteboard data across the connection? TIA!

Wanted to build a 1-on-1 mentoring app and wondering if this would be a good fit or if i should look into other options like OpenTok.

**Comment by nazar-pc** [comment]
Yes, you can definitely build an app like that with WebRTC.
Simple-peer is just a library that makes your life of building apps like that easier.

**Comment by joshbedo** [comment]
Alright cool just wanted to make sure I wasn't in over my head. Thanks!

**Comment by joshbedo** [comment]
Have you seen any examples of how to handle screen sharing? @nazar-pc

**Comment by nazar-pc** [comment]
Many, just search online for WebRTC screen sharing, there is nothing special about simple-peer in this regard.

**Comment by joshbedo** [comment]
Alright thanks! Sorry for bugging you :)
