### ISSUE TITLE
A little demo? :)

### ISSUE THREAD

**Issue by diragb** [feross/simple-peer#595]
Hey guys, I've been going through the extensive documentation for the last few days now. I went through some of the issues and other examples, but I still can't figure out the mechanism behind P2P connection. I've made a few examples, but they all fail. It's not a syntax error, because everything works fine, I just don't conceptually understand how simple-peer works.

Can anyone please provide a small, lightweight example that can connect two peers by storing signalling data in Firebase Database, and send a media stream between them? **Even pseudo-code is welcome and actually preferrable**. I just want to wrap my head around this.

Thanks!

**Comment by nazar-pc** [comment]
Simple-peer is just a small abstraction on top of WebRTC, so to get the most out of it you may need to get familiar with WebRTC itself.

As to the demos, there are a few examples in the readme that you can copy-paste and those should just work. Have you tried those?
There are also tests in `test` directory for various features that should help you with more advanced use cases.
