### ISSUE TITLE
Video example outdated

### ISSUE THREAD

**Issue by holtwick** [feross/simple-peer#597]
The video sample is a bit outdated, because `navigator.getUserMedia` is deprecated.

Here is an example of a modern implementation: https://stackoverflow.com/questions/28991835/firefox-navigator-getusermedia-is-not-a-function/47958949#47958949

You might also want to mention, that the URL needs to be `https` in order to allow access to the API: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Security

Following both tips this will even work on iOS and macOS  ;)

**Comment by nazar-pc** [comment]
Would you mind preparing a PR with those changes? Seems like a really good thing to do indeed.

**Comment by holtwick** [comment]
Sorry, I didn't have the time yet to do it. Will look into it today hopefully.

For reference how urgent it seems to be for people: https://github.com/jitsi/jitsi-meet/issues/2000

**Comment by holtwick** [comment]
Sorry, didn't make it the other day. Finally I was able to make the pull request.
