### ISSUE TITLE
Connection doesn't establish with Opera 

### ISSUE THREAD

**Issue by michalzaq12** [feross/simple-peer#598]
SimplePeer works great in Chrome and Firefox but it doesn't with Opera browser, even if I try establish connection Opera <-> Opera.

Quick code snippet to reproduce bug: https://jsfiddle.net/qm876yjo/

If I add MediaStream to peer 1, the "stream" event is emitted in peer 2, but the connection
is not created. I mean 'connect' event is not emitted either in peer1 and in peer2 and stream is 'empty'

**OS:** Windows 10 64-bit
**Opera:** 67 Stable

**Comment by nazar-pc** [comment]
Does it work with plain WebRTC API? Simple-peer is just a library on top and there shouldn't be anything that it does that would cause issues.
Also make sure to try with extensions disabled, they may interfere with WebRTC sometimes.

**Comment by michalzaq12** [comment]
It works !
I had to change my browser settings under Settings > advance > privacy & security > WebRtC
![image](https://user-images.githubusercontent.com/28574933/77179699-1b775e80-6ac9-11ea-8bc3-932b00b35fdf.png)
to "Use any suitable network interface". 

Thanks
