### ISSUE TITLE
Get video feed when a peer requests the initiator

### ISSUE THREAD

**Issue by whimsicaldreamer** [feross/simple-peer#599]
The title may not be proper but I am having difficulty in understanding on how to get video feed in peer 2 if peer 1 is the initiator.  

 My current implementation issue:  
- Peer 1(Broadcaster) is loaded
- Peer 2(Viewer) is loaded but it doesnt receive any video feed from peer 1
- Refresh the Peer 1 page, video feed starts coming in on Peer 2  

**Peer1**  

```
componentDidMount() {
    navigator.mediaDevices.getUserMedia({
        video: true,
        audio: true,
    })
        .then(stream => {
            // Display own video
            if("srcObject" in this.localVideo.current) {
                this.localVideo.current.srcObject = stream;
            }
            else {
                this.localVideo.current.src = window.URL.createObjectURL(stream);
            }

            // Stream video to attendees
            this.gotMedia(stream);
        })
        .catch(error => {
            console.error(error);
        });
}

gotMedia = (stream) => {
    const broadcaster = new Peer({ initiator: true, stream: stream });

    broadcaster.on("signal", data => {
        this.socket.emit("signal", data);
    });

    this.socket.on("signal", data => {
        broadcaster.signal(data);
    });
};
```  

**Peer 2**  

```
componentDidMount() {
    const attendee = new Peer();
    attendee.on("signal", data => {
        this.socket.emit("signal", data);
    });

    this.socket.on("signal", data => {
        attendee.signal(data);
    });

    // Get remote video stream and display it
    attendee.on("stream", stream => {
        if("srcObject" in this.remoteVideo.current) {
            this.remoteVideo.current.srcObject = stream;
        }
        else {
            this.remoteVideo.current.src = window.URL.createObjectURL(stream);
        }
    });
}
```  

**Server**  

```
// Handle socket connections
io.on("connection", socket => {
   socket.on("signal", (data) => {
      socket.broadcast.emit("signal", data);
   });
});
```

**Comment by t-mullen** [comment]
It sounds like you're loading the page that Peer2 is on after the Peer1 signal events have been sent.

This would mean Peer2 is missing the first couple signalling events (so you're not getting a connection). When you reload Peer1, both peers are ready and everything works.

The initiator should wait for confirmation that the other peer has connected to the signalling server before starting to send signal messages.

**Comment by t-mullen** [comment]
Closing since this doesn't seem to be a bug with simple-peer, but feel free to continue discussion.

**Comment by whimsicaldreamer** [comment]
@t-mullen So what can be done for cases when, Peer2 is loaded after Peer1? I tried by setting both peers as initiators but it didn't work.

**Comment by nazar-pc** [comment]
This is responsibility of your app to know when and who is connecting to who and manage signaling accordingly. You can't set both peers to initiators, there must always be one initiator and one responder exactly in WebRTC connection.
