### ISSUE TITLE
Support for scaling topologies or server side solutions

### ISSUE THREAD

**Issue by pshah123** [feross/simple-peer#603]
I'm currently trying to scale a working full mesh topology by switching to some other method. So far the fastest I've found is to use a server in between. I'm wondering if simple peer has some compatibility with alternate topologies? I feel it would be a great addition as we have found many devices struggle with even 4 simultaneous connections.

**Comment by nazar-pc** [comment]
Simple-peer is just a library for WebRTC. WebRTC in turn is just P2P protocol.
If you need many connections you'd likely need an SFU on a server for a good experience.
4 devices mesh is where most practical applications stop.

**Comment by pshah123** [comment]
Does simple peer support any SFUs out of the box?  I was also wondering if there are any existing examples of this in use!

**Comment by nazar-pc** [comment]
There is no need for simple-peer to support any SFU specifically.
I believe SFUs look like a regular peers you connect to and have some magic inside of them. If there is a special WebSocket or data-channel-based communication protocol, simple-peer is compatible with that, but shouldn't support out of the box. Must be possible to write an adapter or maybe SFU already includes some kind of SDK for client applications.
