### ISSUE TITLE
Setting codec

### ISSUE THREAD

**Issue by litashg** [feross/simple-peer#607]
Hi @feross ! Do you have an option to set the codec? I need to use H264 instead of VH8. How can I do that?

**Comment by nazar-pc** [comment]
There is no option and most likely there will not be any.
Still what most people do is tweaking SDP manually.
Let's say you contains this in SDP:
```
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 125 127
...
a=rtpmap:96 VP8/90000
...
a=rtpmap:97 rtx/90000
...
a=rtpmap:98 VP9/90000
...
a=rtpmap:99 rtx/90000
...
a=rtpmap:100 VP9/90000
...
a=rtpmap:101 rtx/90000
...
a=rtpmap:102 red/90000
a=rtpmap:125 rtx/90000
...
a=rtpmap:127 ulpfec/90000
```

So in this case `96 97 98 99 100 101 102 125 127` contains `96` as the most desired codec configuration, which correcponds to `a=rtpmap:96 VP8/90000`.

If you change that to have `98` at the first position then VP9 will be preferred.

I haven't found a library in JS that processes modern SDP and allows to change this with a nice API unfortunately. But you can write a small hack that will achieve what you want with something like 10 lines of code.

P.S. Make sure you actually want H264, it is REALLY BAD at times with WebRTC. If you can at all, prefer VP8 or consider VP9.

**Comment by litashg** [comment]
Hi @nazar-pc . Thank you for a fast response. Let me explain why I want to set the preferred codec. I figure that when I use Firefox, my browser can render without lags 4-5 streams and just 3   in Chrome. I thought it's all because the default codec in Firefox is H264 and VP8 in Chrome. I will try to use your solution, and who knows, maybe it can help. 

PS. Дякую велике за те що відгукнулись.

**Comment by nazar-pc** [comment]
I'll close this since there is nothing to be done in simple-peer specifically, but feel free to continue conversation.
