### ISSUE TITLE
Uncaught Error: Connection failed

### ISSUE THREAD

**Issue by soubhikchatterjee** [feross/simple-peer#609]
I was trying the example listed at https://www.npmjs.com/package/simple-peer but getting Uncaught Error: Connection failed error (stack trace below). I then figured that my macos firewall was blocking the connection, it started working as soon as I turned the firewall off. How can I make it work even if the firewall is turned on? because it will not be a good experience if we tell our customers/clients to turn off the firewall. Just like when using zoom app it still works with firewall turned on. Pls, advise.

> "Uncaught Error: Connection failed.
>     at makeError (index.js:17)
>     at Peer._onConnectionStateChange (index.js:654)
>     at RTCPeerConnection.Peer._pc.onconnectionstatechange"

PS: I am using Chrome browser Version 80.0.3987.163 (Official Build) (64-bit) and node v12.4.0 and running the script locally.

**Comment by nazar-pc** [comment]
There are many examples there, so I have no idea to know which exactly you're talking about.
In either case you may need to use TURN server if you firewall blocks connections, but I have no idea why it does that. Either way this is nothing about simple-peer and just a generic WebRTC question, so I'm closing this issue, but feel free to continue conversation.

**Comment by soubhikchatterjee** [comment]
Please help me with a resource or steps to setup a TURN server.

Thanks

**Comment by nazar-pc** [comment]
You can start here: https://webrtc.org/getting-started/turn-server
This is the TURN server you can use to host it yourself or you can purchase it as a service from one of the providers: https://github.com/coturn/coturn

**Comment by soubhikchatterjee** [comment]
Thanks for the reply, but that link doesn't tell me how to install a TURN server.

**Comment by nazar-pc** [comment]
It does, just go to the wiki section of the repo. Please do you research, this is not a generic support forum for WebRTC.
