### ISSUE TITLE
Can't connect using different networks

### ISSUE THREAD

**Issue by diegogurgel** [feross/simple-peer#610]
On local networks I'm able to connect but when I switch one of the peers to a mobile network it doesn't work anymore. I'm using  `stun:stun4.l.google.com:19302` and `turn:numb.viagenie.ca`. Is this a problem with my free turn and turn servers os something changed? I notice that other webrtc examples are having the same problem. You can access my application using https://video-chat.dgurgel.now.sh/ and this is my peer config 
```javascript
new Peer({
            initiator: initiator,
            stream,
            trickle: false,
            reconnectTimer: 1000,
            iceTransportPolicy: 'relay',
            config: {
                iceServers: [
                    { urls: process.env.REACT_APP_STUN_SERVERS.split(',') },
                    {
                        urls: process.env.REACT_APP_TURN_SERVERS.split(','),
                        username: process.env.REACT_APP_TURN_USERNAME,
                        credential: process.env.REACT_APP_TURN_CREDENCIAL
                    },
                ]
            }
        })
```
And here is where I add the connection events
https://github.com/diegogurgel/react-webrtc/blob/master/src/components/video.js
Thank you

**Comment by nazar-pc** [comment]
If it doesn't work with other examples too, then this is not simple-peer's fault for sure, and this is simple-peer issue tracker, not generic WebRTC support forum.
There can be multiple issues with it including issue with TURN server. I would suggest you to try and set up your own somewhere with https://github.com/coturn/coturn and see if it works. You may need to set it up on both devices and not just one running on mobile phone.

Closing, since this is noting specific to simple-peer, but feel free to continue conversation.

**Comment by diegogurgel** [comment]
> If it doesn't work with other examples too, then this is not simple-peer's fault for sure, and this is simple-peer issue tracker, not generic WebRTC support forum.
> There can be multiple issues with it including issue with TURN server. I would suggest you to try and set up your own somewhere with https://github.com/coturn/coturn and see if it works. You may need to set it up on both devices and not just one running on mobile phone.
> 
> Closing, since this is noting specific to simple-peer, but feel free to continue conversation.

Sorry, my bad. Ok I'll investigate more. Thank you.

**Comment by diegogurgel** [comment]
I was able to solve it by testing my stun and turn servers here: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
in my case, I was getting unauthorized. I just created a new turn user 😅
