### ISSUE TITLE
Unable to destroy peer object

### ISSUE THREAD

**Issue by janesenaj** [feross/simple-peer#611]
I have a peer object defined as  `var peer = new Peer()`

Calling `peer.destroy()` leads to the error:

>ReferenceError:
>  process is not defined
>     at emitReadable (_stream_readable.js:529)
>     at onEofChunk (_stream_readable.js:506)
>     at readableAddChunk (_stream_readable.js:255)
>     at Peer.push../node_modules/simple-peer/node_modules/readable-stream/lib/_stream_readable.js.Readable.push (_stream_readable.js:241)
>     at Peer._destroy (index.js:408)
>     at Peer.destroy (index.js:398)
>     at Socket.<anonymous> (sender.component.ts:88)
>     at Socket.push../node_modules/ngx-socket-io/node_modules/component-emitter/index.js.Emitter.emit (index.js:133)
>     at Socket.push../node_modules/ngx-socket-io/node_modules/socket.io-client/lib/socket.js.Socket.onevent (socket.js:278)
>     at Socket.push../node_modules/ngx-socket-io/node_modules/socket.io-client/lib/socket.js.Socket.onpacket (socket.js:23).

What I'm trying to achieve is if a remote client refreshes the browser, I want all other clients to destroy the connection to that remote client.

**Comment by nazar-pc** [comment]
How do you get simple-peer on the page? I think there is something wrong the way bundling is configured in your app. You need to either use browserify or configure your bundles correctly or just use pre-built `simplepeer.min.js`.

**Comment by janesenaj** [comment]
I'm using Angular typescript,  hence:

`import * as Peer from 'simple-peer'`.

I'm able to get the connections and streams across peers,  but just unable to destroy them.

**Comment by izakgl** [comment]
For simple-peer to work correctly in angular you need some polyfills.
Add this to your `polyfills.ts` file:
```typescript
import * as process from 'process';

(window as any).global = window;
(window as any).process = process;
(window as any).Buffer = [];
```

And install this package: [https://www.npmjs.com/package/process](https://www.npmjs.com/package/process)

**Comment by janesenaj** [comment]
It works! Thank you.

> For simple-peer to work correctly in angular you need some polyfills.
> Add this to your `polyfills.ts` file:
> 
> ```ts
> import * as process from 'process';
> 
> (window as any).global = window;
> (window as any).process = process;
> (window as any).Buffer = [];
> ```
> 
> And install this package: https://www.npmjs.com/package/process

**Comment by janesenaj** [comment]
I thought the object was destroyed but came across #553 and realized that this was happening instead. I closed one client without destorying the peer object and 2 errors popped out after about 15s:

1. Uncaught Error: Connecton failed. 
2. Uncaught TypeError: Cannot read property '_readableState' of undefined.

**Comment by nazar-pc** [comment]
`_readableState` s a property on `this`, maybe you're storing `peer.destroy` and not `peer.destroy.bind(peer)` somewhere?

**Comment by janesenaj** [comment]
Turns out I didn't install `process` correctly... problem was resolved after installing the correct package.

**Comment by talksik** [comment]
this also solves it in React if anyone is wondering

**Comment by Mizan-Rifat** [comment]
@talksik I have the same problem. how do you solve this??

**Comment by talksik** [comment]
Yarn install process

Worked for me. Of course npm should work too

**Comment by aditya-subramanian7** [comment]
> For simple-peer to work correctly in angular you need some polyfills. Add this to your `polyfills.ts` file:
> 
> ```ts
> import * as process from 'process';
> 
> (window as any).global = window;
> (window as any).process = process;
> (window as any).Buffer = [];
> ```
> 
> And install this package: https://www.npmjs.com/package/process

Any idea about what would be the equivalent of this in react and I am not using typescript

**Comment by Tonybobo** [comment]
@aditya-subramanian7

import * as process from 'process';

window.global = window;
window.process = process;
window.Buffer = [];

It will work on react by adding the above codes to src/index.js

**Comment by krishnac0077** [comment]
thanks bro @Tonybobo 
Its working
