### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by yo-png** [feross/simple-peer#613]
Hey, 
I'm trying to implement webrtc & simple peer to my chat. Everything works but I would like to add screen sharing option. For that I tried that:
```javascript
$("#callScreenShare").click(async function(){
                if(captureStream != null){                
                    p.removeStream(captureStream)
                    p.addStream(videoStream)
                    captureStreamTrack.stop()
                    captureStreamTrack =captureStream= null
                    $("#callVideo")[0].srcObject = videoStream
                    $(this).text("screen_share")
                }else{
                    captureStream = await navigator.mediaDevices.getDisplayMedia({video:true, audio:true})
                    captureStreamTrack = captureStream.getTracks()[0]
                    $("#callVideo")[0].srcObject = captureStream
                    p.removeStream(videoStream)
                    console.log(p)
                    p.addStream(captureStream)
                    $(this).text("stop_screen_share")
                }
            })
```

But I stop the camera and after that doesn't do anything and my video stream on my peer's computer is blocked. No errors, nothing only that.

I've put a console.log when the event `stream` is fired. The first time it fires but when I call addStream method, it doesn't

If someone could help me it would be really helpful.

**Comment by nazar-pc** [comment]
Are you sure `captureStream` actually contains a media stream? If there is nothing in the `console.log` then it fails before that. Check with debugger in dev tools.

Doesn't seem to be an issue with simple-peer in any way, so I'm closing this, but feel free to continue conversation.

**Comment by amitmeghare** [comment]
Hi,

Facing issue while sharing a screen. It starts screen sharing & opens the camera properly after stop sharing on the first & second time, but when I trigger stop screen sharing event on the second time, it stops the signal/streaming on the other user's screen. Following are my two functions code startScreenShare & stopScreenShare in which I am removing and adding stream, and attached is the console screenshot, in which events log are shown. I am using Vuejs, Pusher, Simple-Peer with Laravel Framework.

startScreenShare: function() {

          console.log('Start Screen Share');
          try {
            this.$refs.myVideo.srcObject.getTracks().forEach(t => t.stop());
          } catch(e) {
            this.$refs.myVideo.src.getTracks().forEach(t => t.stop());
          }

          this.getScreenMediaPermissions()
              .then((stream) => {
                try {
                  this.$refs.myVideo.srcObject = stream;
                } catch(e) {
                  this.$refs.myVideo.src = window.URL.createObjectURL(stream);
                }

                this.$refs.myVideo.play();

                this.peer.removeStream(this.stream);
                this.peer.addStream(stream);
                this.stream = stream;
              })
              .catch((err) => {
                this.state.hasMedia = false;
              });
          this.isScreenShare = true;
        },

        stopScreenShare: function() {
          console.log('Stop Screen Share');
          try {
            this.$refs.myVideo.srcObject.getTracks().forEach(t => t.stop());
          } catch(e) {
            this.$refs.myVideo.src.getTracks().forEach(t => t.stop());
          }

          this.getMediaPermissions()
              .then((stream) => {
                try {
                  this.$refs.myVideo.srcObject = stream;
                } catch(e) {
                  this.$refs.myVideo.src = window.URL.createObjectURL(stream);
                }

                this.$refs.myVideo.play();

                this.peer.removeStream(this.stream);
                this.peer.addStream(stream);
                this.stream = stream;
              })
              .catch((err) => {
                this.state.hasMedia = false;
              });

          this.isScreenShare = false;
        }

![screenshot--2020 04 20-12_56_48](https://user-images.githubusercontent.com/25700375/79726137-f3695e00-8307-11ea-956c-48b71d8d4dc5.png)
