### ISSUE TITLE
Connection Failure Some times

### ISSUE THREAD

**Issue by saagarbethi** [feross/simple-peer#615]
Hi, 
I have installed simple peer node in my server that has public IP and I have developed one video chat application using this simple-peer, that application is also in same server. When 2 users are trying to connect in video chat and both are in different network , some times they are unable to connect and host gets connection Failure error. But they are in same network they are able to connect without any problem. Even though the node and application have also in public IP why can't they connect but it works as expected when two users are in same network to access my application. I just wondering what happens with simple peer can u please help in this. It's urgent

**Comment by nazar-pc** [comment]
This sounds like a typical issue with NAT and firewalls that prevent P2P connection from being established.
What probably need is TURN server or SFU if you want to scale number of participants.
Either way this is not an issue in simple-peer, but just a way WebRTC works. I would suggest to make more research and read even last few questions in this repo that were asked like within last week.
