### ISSUE TITLE
Issue with arrayBuffer

### ISSUE THREAD

**Issue by vj-abishek** [feross/simple-peer#617]
I'm trying to send a file. I'm Converting the file to arrayBuffer and I will send it to another peer. At the receiving end, the data get lost. The arrayBuffer becomes empty. I don't know is this is an issue. And I don't know how to parse arrayBuffer. Is there any way to send files using simple-peer...

**Comment by jarretttaylor** [comment]
Check out @t-mullen 's previous answer [here ](https://github.com/feross/simple-peer/issues/561#issuecomment-542774264)as it could provide more information about sending large amounts of data over the DataChannel.

**Comment by vj-abishek** [comment]
Thanks for your help!!
