### ISSUE TITLE
Missing error code in readme.md

### ISSUE THREAD

**Issue by davidcallanan** [feross/simple-peer#619]
Hi, thanks for your amazing package!

I noticed there is an error code missing from the `README.md` documentation, `"ERR_CONNECTION_FAILURE"` (as seen below when a connection is closed)

![image](https://user-images.githubusercontent.com/40340425/79072800-e67eb600-7cda-11ea-9ea5-d57475675ccc.png)

**Comment by t-mullen** [comment]
Good catch 👍
