### ISSUE TITLE
Reconnecting to peer results in InvalidModificationError in Firefox and erratic behavior in Chrome

### ISSUE THREAD

**Issue by dheera** [feross/simple-peer#620]
**Issue:**
When offerer (2nd peer) reloads the page, data can no longer be sent and results in InvalidModificationError despite Peer being re-instantiated.

**Minimal example to reproduce the bug:**
0. Paste this url into browser A. Open the console.
https://dheera.github.io/simple-peer-bug/
1. It will generate a hash in the URL. Cut and paste the new URL https://dheera.github.io/simple-peer-bug/#xxxxxx into browser B. Open the console.
2. You should see Hello world getting sent every 1 second in the console.
3. Reload browser B.
4. Firefox -- You get an error:
```
Error: InvalidModificationError: Cannot set local answer when createAnswer has not been called.
```
Chrome -- no error, p.on("close") is never called, peer appears connected, but data channel no longer receives

**Comment by nazar-pc** [comment]
There must be a bug in the logic in your code as error already states.

You can't cache and reuse answer or offer between peer connection instances or pages.
You need to start connections on both sides from scratch in order to establish a new one.

I'm closing since this is not an issue in simple-peer, but feel free to continue conversation.

**Comment by dheera** [comment]
Hi @nazar-pc I am indeed starting from scratch:
```
  p.on('close', data=> {
    console.log("peer.close");
    clearInterval(interval);
    p.destroy();
    startPeer();
  });
```

The issue in fact occurs only
- AFTER starting Peer() from scratch but without reloading the page
and ONLY
- with the data channel

**Comment by nazar-pc** [comment]
I didn't check the code in much details, I simply don't have time for that, sorry.
It seems that at least on one side you're calling `.signal()` incorrectly.
If there was an error in simple-peer then you'd get an error right away. But you only get it on next instance that shouldn't be connected to old one in any way.

I think 2 peers may not receive `close` at the same time or something similar happens.

Would be easier if you could make a simpler with 2 connections on the same page and without any websockets and things like that. Bare minimum. If it still fails, then there is something to be fixed, if not, then you'll be able to find an issue on the way of simplifying things.
