### ISSUE TITLE
replaceTrack() does not update stream in Peer.Streams[]

### ISSUE THREAD

**Issue by thedavidscherer** [feross/simple-peer#621]
Calling Peer.replaceTrack(old, new, stream) works so far as replacing the track and updating the stream for the clients. But when you try to get the device ID from peer.streams[0].getTracks()[0].getSettings().deviceId, it returns null or the old device ID.

**Comment by nazar-pc** [comment]
`peer.streams` is not a public API so it is not supposed to be used by applications.
And I do not think `[0]` will work after replacement either, you need to compare tracks by their `id` to make sure you're looking at the correct one.

You can use `peer.getStats()` method instead to find necessary information using public API (which is not documented in readme for some reason, but you can rely on it).

**Comment by thedavidscherer** [comment]
@nazar-pc seems readme is missing a bunch of stuff like documentation for addTrack(), probably a bunch of stuff. Is there an un-mini-ed version of simple-peer? I don't see one in the release zip.

I actually keep a reference to the stream returned by getUserMedia() to compare track IDs and do replacements because I learned rather quickly that after the camera/microphone was switched the first time I have to keep track of which devices are being used myself without relying on stream metadata. 

How would I get the current device ID being streamed using getStats()? The callback returns a massive array with 134 items in it and I'm not sure where to begin.

Can you tell me how to get the current audio/video track with the public API? Or should I continue to rely on the reference I store from getUserMedia? This is working, but doesn't necessarily seem "correct".

**Comment by nazar-pc** [comment]
Release on NPM only includes what you need to run it. Repository has `index.js` file with unminified source code.

Well, I'm not really sure why you want to extract info about device ID from simple-peer, I'd keep it somewhere in app state instead since you have full control over track relacement and know when device ID changes.

**Comment by t-mullen** [comment]
The `replaceTrack` documentation is indeed missing. I'll add it.

There's no official way to retrieve local tracks. I recommend tracking this state in your application. The very outdated (and private) `peer.streams` property only contains streams added via the peer constructor.
