### ISSUE TITLE
New projects using simple-peer

### ISSUE THREAD

**Issue by holtwick** [feross/simple-peer#624]
I created two Open Source projects that are using simple-peer that might be interesting to be added to https://github.com/feross/simple-peer#who-is-using-simple-peer

1. [Briefing](https://brie.fi/ng) - Secure group video conferencing https://github.com/holtwick/briefing
2. [Peer.School](https://peer.school/) - Virtual class room with video chat and whiteboard https://github.com/holtwick/peer2school

Thanks again for the great simple-peer project! It really helped a lot to get these projects realized quickly.

**Comment by athina635** [comment]
@holtwick HEllo and good job congratulation for this work. I'm really interested on your work cuz I want to do similar work ( i already did ^^) to make multiple students connect to one teacher. I used peer to peer communication webRTC and WebSocket to do that. 

did you use those technologies?

**Comment by holtwick** [comment]
@athina635 Indeed, I used WebRTC and signaling via Websockets. The code is available at https://github.com/holtwick/peer2school

**Comment by vj-abishek** [comment]
I'm also created a website known as `airdrop`  to transfer files between two peers. The code is available here [https://github.com/vj-abishek/airdrop](https://github.com/vj-abishek/airdrop). And the demo is available here [https://airdrop.netlify.app](https://airdrop.nerlify.app). I'm happy to use this great and simple library. I like `simple-peer`. 
Thanks

**Comment by t-mullen** [comment]
Hey guys! Awesome projects!

Do you mind opening a PR adding them to the README? 👍

**Comment by holtwick** [comment]
Thanks, this is the PR https://github.com/feross/simple-peer/pull/659/

**Comment by vj-abishek** [comment]
Could any say, what is PR? I'm new to Github.
