### ISSUE TITLE
Failed to execute 'send' on 'RTCDataChannel'

### ISSUE THREAD

**Issue by arushgupta2007** [feross/simple-peer#626]
Hi, 
I am trying out WebRTC using simple-peer
I am using the Opera Browser (which supports WebRTC) and following the tutorial linked [here](https://www.youtube.com/watch?v=ieBtXwHvoNk)
Here is the error I am facing when I try to send the string "Hello":
`
Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
    at Peer.send (http://127.0.0.1:9966/bundle.js:7011:19)
    at HTMLButtonElement.<anonymous> (http://127.0.0.1:9966/bundle.js:22:14)
send @ index.js:241
(anonymous) @ index.js:21
`

Here is index.js:
```javascript
var Peer = require('simple-peer')

if (Peer.WEBRTC_SUPPORT) {
    console.log("Support");
    peer = new Peer({
        initiator: location.hash === '#1',
        trickle:true
    })
    peer.on('signal', function (data) {
        document.getElementById('yourId').value = JSON.stringify(data)
    })
    document.getElementById("connect").addEventListener('click', function () {
        var otherId = JSON.parse(document.getElementById('otherId').value)
        peer.signal(otherId)
    })
    peer.on('connect', function () {
        console.log("CONNECTED");
    })
    document.getElementById("send").addEventListener('click', function () {
        var message = document.getElementById("message_to_send").value
        peer.write(message)
    })
    peer.on("data", function (data) {
        console.log(data)
        document.getElementById("messages").textContent += data + "\n"
    })

} else {
    console.log("No Support, Sorry");
}
```

Changing
`
peer.send(data)
`
to 
`
peer.write(data)
`

does not give error but nor does it send the data

What am I doing wrong?
Thanks in advance

**Comment by arushgupta2007** [comment]
I tried to debug this problem using breakpoints, and I found that RTCDataChannel.readystate is 'connecting', if that was helpful

**Comment by nazar-pc** [comment]
Looks like you click a button before connection is even established. You need to wait for connection to be ready to accept data.

**Comment by arushgupta2007** [comment]
Hi,
Thanks for the response
But I waited for 5 mins for the connection to establish, and then send the message, which did not work either

**Comment by nazar-pc** [comment]
Was the connection established though? If not you need to fix that first.

**Comment by arushgupta2007** [comment]
Putting a break point and trying again, I see that in the peer object, connected is false and readyState is at 'connecting'

**Comment by vladyslava-p** [comment]
Hi
I have the same issue. readyState is 'connecting'
Any updates?

**Comment by nazar-pc** [comment]
There is something wrong with the app or networking, which causes WebRTC connection not to be established.

Since there doesn't seem to be anything to do in simple-peer. I'm closing this issue, but feel free to continue conversation.

**Comment by arushgupta2007** [comment]
HI, 
I got it to work. If useful to anybody else:
I was using opera browser, which is blocking my ip address from "leaking". Using Chrome worked like a charm
You can use this link to see if your browser is blocking the connection: [https://diafygi.github.io/webrtc-ips/](https://diafygi.github.io/webrtc-ips/)
