### ISSUE TITLE
Store Media Stream in array and use it later for peer.addStream

### ISSUE THREAD

**Issue by arushgupta2007** [feross/simple-peer#631]
Hi,
I am making a video chat application for multiple users. As a mesh network does not scale pretty well, I am putting my server (my desktop) for centralized communication. I am able to store peer objects in an array, and also access the peer objects later on. But when I somebody joins the video chat, I need to be able to give the client the media stream of every other person. To do that I am trying to store the media stream object as well, so that when the client joins, I can call `peer.addStream(stream)` on the connection from the client (who joined) and the server. But when I store the media stream, I see a empty object. 
How should I go about this?
Thanks in advance

**Comment by t-mullen** [comment]
How are you "storing" the media stream objects?

**Comment by arushgupta2007** [comment]
Hi,
Sorry for the late response.
I am appending the stream to an array.
Does that answer your question?
Thanks

**Comment by arushgupta2007** [comment]
Anyway, I am currently using an aldready made media server to continue with my project. But it would be intresting to know how to store a stream object in an array!
