### ISSUE TITLE
Maybe-ready PC True channel False : Getting black or empty screen in video stream 

### ISSUE THREAD

**Issue by surya-vamsi2310** [feross/simple-peer#633]
Hello i used simple-peer for video streaming, but getting a black or blank (somtimes)while streaming code looks fine in every snippet. could you please help me 
![image](https://user-images.githubusercontent.com/59705196/80674801-848ec080-8ad0-11ea-8bf5-c7819d3231da.png)
<img width="781" alt="Screenshot 2020-04-30 at 10 51 45 AM" src="https://user-images.githubusercontent.com/59705196/80674844-9c664480-8ad0-11ea-9353-e8045bb9ee77.png">

**Comment by nazar-pc** [comment]
I do not understand what issue with simple-peer do you have specifically and why do you think it is simple-peer's issue in particular? Can you clarify, please?

**Comment by rajpurohityogesh** [comment]
Did you find the solution @surya-vamsi2310  because I am facing the same error !!!
