### ISSUE TITLE
Getting error when connect via mobile phone

### ISSUE THREAD

**Issue by JanithaKalshan** [feross/simple-peer#635]
I have created video chat and it is working with two browsers in two laps but when I connect with a lap and mobile phone it is not working error is showing 

simplepeer.min.js:6 Uncaught Error: Connection failed.
    at a (simplepeer.min.js:6)
    at p._onConnectionStateChange (simplepeer.min.js:6)
    at RTCPeerConnection._pc.onconnectionstatechange (simplepeer.min.js:6)

when I connect with two phones it is working. Can any one help me to solve this

**Comment by nazar-pc** [comment]
There is likely no way to establish direct connection. So if you have STUN servers already, you should consider adding TURN server too. There have been many questions about this during last month alone, just browse closed ones and you should be able to find additional information there.

This is not something simple-peer can or should solve, this is a generic WebRTC error, so I'm closing this issue, but feel free to continue converstation.

**Comment by JanithaKalshan** [comment]
But before this work but suddenly this was stop working and can you share a link that have the answer for this.

**Comment by nazar-pc** [comment]
Just search, there are plenty: https://github.com/feross/simple-peer/issues?q=is%3Aissue+Connection+failed+is%3Aclosed

To make it work reliably you need to know at least basics of WebRTC, like what STUN and TURN are. Otherwise there is no one-click universal solution.

**Comment by JanithaKalshan** [comment]
I have make direct connections and it works earlier. I didn't used any turn severs. But now it is not working is there any reason. theses questions would be some what silly and it would be much grateful if you can explain me.

**Comment by nazar-pc** [comment]
There is definitely a reason, but without having access to the network and devices it is hard to say why exactly and this is not a generic WebRTC support forum, but rather issue tracker about simple-peer library.

I can suggest you to look at chrome://webrtc-internals if your desktop browser is Chromium-based or about:webrtc if it is Firefox and trying to make sense of it.
