### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by athina635** [feross/simple-peer#636]
Hello,

I'm using simple peer to make my own webRTC application and that work fine except for some perturbation in connexion I don't know if that's come from the bad network or no (I'm using a STUN/TURN servers so its not the case).

I would like to share screens between the two browsers! 

is that possible?

@t-mullen 
@nazar-pc 

Thank you.

**Comment by EricEisaman** [comment]
You can use the [MediaDevices.getDisplayMedia() API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia).

**Comment by athina635** [comment]
Hello, thank you yes i used that to share the desktop but why the volume is always mute even if a pass it as  ```
let constraintObj = {
                video: true,
                audio: true
            }
```

**Comment by nazar-pc** [comment]
Network quality is not improved by using TURN, is just makes it work at all. If network is bad, connection can lag or drop.

Sharing audio is not supported in most browsers, but there may be additional audio input devices you can add on top of microphone on some platforms and you can share audio from Chromium tab, but that is about it.

Please try to limit question here to simple-peer itself. This is not a generic WebRTC support forum and we have limited capacity as maintainers in answering random questions.
