### ISSUE TITLE
Change timeout on signaling phase

### ISSUE THREAD

**Issue by mkhan45** [feross/simple-peer#639]
Well if I'm going to be honest, I don't understand WebRTC very well, so I'm not sure if this is something that this library can fix.

I want to make a connection between two browsers without a signaling server (this is just for my me and my friends), so we're just doing what the example says and copy pasting the json signaling data over messenger. It works fine if we speedrun it finish everything within ~15 seconds, but otherwise it times out. Is there a way to set the timeout to much longer?

**Comment by nazar-pc** [comment]
No there is no way. Signaling information generally times out under 30 seconds and is one-time use.
There is no way around it.
