### ISSUE TITLE
Ringing/alerting to remote party

### ISSUE THREAD

**Issue by nikpakar** [feross/simple-peer#641]
has any one done one to one calling app with simple-peer ?

Im trying to see how to implement alerting/ringing signalling to the B party ?

**Comment by nazar-pc** [comment]
Someone definitely did, but how is it related to simple-peer itself? Simple-peer is just a library on top of WebRTC.

**Comment by nikpakar** [comment]
Sorry for the unrelated question. Since i saw simple-peer as the best library so far for my app (react-native), just trying to find out further development related to my project.

Any links to such project which use simple-peer would be highly appreciated.

**Comment by t-mullen** [comment]
Try "Who is using simple-peer?" in the README, or look at dependents on NPM.

Github issues isn't really meant as an open forum - it's not the user community who will see this, but a small group of volunteer maintainers. It's mostly for bugs with the library, feature requests, or constructive feedback.

Best of luck with your project!
