### ISSUE TITLE
Is it possible to record peer1 audio and peer2 audio in one file?

### ISSUE THREAD

**Issue by DylanJu** [feross/simple-peer#642]
Hi. I'm thankfully using this project for 1:1 video/audio communication.

My node.js server is connecting peer1 signal and peer2 signal.

But when I save the conversation with mp3 file, It only is recorded peer1 voice.

How can I record both of peer1 and peer2 voice in one file? is it impossible?

**Comment by nazar-pc** [comment]
You should be able to combine your own and remote audio tracks into one with https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by DylanJu** [comment]
> You should be able to combine your own and remote audio tracks into one with https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

Thanks for your quick response.
I tried some way but can not figure out the correct way to merge peer1 audio and peer2 audio.

````
let combined = new MediaStream([...peerOneStrem.getTracks(), ...peerTwoStream.getTracks()]);
let recorder = new MediaRecorder(combined);
````

It is recorded only peerOneStream. Could you tell me more detail about the way two audio streams can be recorded at the same time?

**Comment by nazar-pc** [comment]
I you'll need to build audio processing pipeline in the browser such that you have one track at the output, not media stream with 2 tracks.
The page I have referenced contains links to all necessary parts of what you need. You can search for examples too.

There is nothing to be done in simple-peer here, so I'm closing this issue. But feel free to continue conversation.
