### ISSUE TITLE
connected type is undefined in SimplePeer.Instance.

### ISSUE THREAD

**Issue by sungwoo91** [feross/simple-peer#644]
```ts
      if (this.peers[id].connected) {
        ...
      }
```
* Message
**Property 'connected' does not exist on type 'Instance'**

I want to use **connected** field in peer, but it is not defined in type definition file.
Could you add this type?

Or let me know if there is a way I can contribute to type definition file.

**Comment by nazar-pc** [comment]
You need to contribute a change here: https://github.com/DefinitelyTyped/DefinitelyTyped
We are not maintaining those typings.
You can also follow #605 for updates when someone contributes them here.
