### ISSUE TITLE
Unable to create a Peer

### ISSUE THREAD

**Issue by efizzy** [feross/simple-peer#645]
I am currently unable to create a peer. I keep getting the error message below. 

![image](https://user-images.githubusercontent.com/25567173/81281553-e5c70e80-9051-11ea-8af1-a9c4c3514ecb.png)

This is after I have installed simple-peer via npm using 

```
npm install simple-peer
npm install @types/simple-peer
```

Then I am doing this in my service

```
import { Injectable } from "@angular/core";
import * as SimplePeer from "simple-peer";

@Injectable({
  providedIn: "root",
})
export class StreamRService {
  constructor() {}

  async initiateConnection() {
    const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });

    const peer = new SimplePeer({ initiator: true, trickle: false, stream });

    peer.on("signal", (data) => {
      console.log(data);
    });
  }
}
```

What could I be doing wrong?

**Comment by nazar-pc** [comment]
Does `const SimplePeer = require("simple-peer");` work?

But generally we don't maintain those typings, so this is not an issue in simple-peer itsef, hence closing, but feel free to continue conversation.
