### ISSUE TITLE
Best way to connect up to 15 peers together ?

### ISSUE THREAD

**Issue by athina635** [feross/simple-peer#646]
I'm used to connecting more than 15 peers together using simple-peer as **one to many broadcasting**, my architecture was as follow :

- we have a leader peer and the children's peers that will demand to connect with the leader and just the leader peer will communicate with all other peers and the children's peers couldn't communicate with each other.  **( PS: leader script is separate from child script and not the same one)**

- The leader peer globe all other peers, as following:
         1. child peer sends the signal to the leader peer with `peer.on('signal')`. 
 ```
peer = new Peer({
                                        initiator: true,
                                        wrtc: wrtc,
                                        stream: stream,
                                        trickle: false,
                                        config{"iceServers"}
```
         2. the leader peer receive signal and create a new peer for this child with no init peer.
```
peer[ID] = new Peer({
                            initiator: false,
                            stream: stream,
                            wrtc: wrtc,
                            trickle: false,
                            config: {"iceServers"}
```
         3. the leader peer sends back the signal to the child and connect as well.
         4. the two peers exchange the streaming as well with `peer.on('stream')`.
         5. id any new child signal the leader peer for new connexion the leader peer will repeat the 
             steps 2,3,4  for each new peer.

I reach my goal with this, but, The question here is:

is what i did right or no for the best performance ?
is that assure a good connexion between peers?
on this architecture, i have sometimes peers didn't connect how can i know if that's for the bad network?
is this architecture let the server work well cuz the communication is going throw WebSockets? 
is that required a very big server performance?

**Comment by nazar-pc** [comment]
The best performance can be achieved with SFU.
You can either get a basically complete solution with Janus or use lower-level tools like mediasoup or medooze.

I'd like to ask limiting questions to simple-peer itself though. This is not a support forum and we have limited resources answering random questions not related to simple-peer itself. Thanks for understanding.
