### ISSUE TITLE
Cannot set remote answer in state stable

### ISSUE THREAD

**Issue by BoazKG93** [feross/simple-peer#648]
I'm using `simple-peer` to develop a one-on-one video chat in my ReactJS App.

I do the handshake P2P using `socket.io` on my server - so peer 1 is calling peer 2, peer 2 answers, and then the chat starts. The problem begins when peer 2 closes his browser (peer connection closes) and then goes back again in the chat room. Now when peer 1 calls him and he answers, I get `Cannot set remote answer in state stable` error.

I made sure that when the socket of peer 2 closes, peer 1 is being notified and in return removes the `signal` and `stream` events, and use the `destroy()` method, so on the next call it will be created again.

This `callPeer()` function is being called on a press of the call button as peer 1:

```

callPeer() {
    this.peer = new Peer({
      initiator: true,
      trickle: false,
      config: { iceServers: [
        { urls: 'MY.STUN.SERVER' },
        {
          urls: 'MY.TURN.SERVER',
          credential: "PASS",
          username: "USER"
        }
      ]},
      stream: this.state.stream
    });

    this.peer.on("signal", this.listenSignalsHost);
    this.peer.on("stream", this.listenStreamHost);

    this.io.on("callAccepted", (signal: any) => { //peer 2 accepted the call
      this.setState({callAccepted: true})
      this.peer.signal(signal);
    });

    this.io.on("bye", () => { //peer 2 disconnected
      this.peer.off("signal", this.listenSignalsHost)
      this.peer.off("stream", this.listenStreamHost)
      this.peer.destroy()
      this.setState({callAccepted: false, receivingCall: false})
    });


  }


listenSignalsHost(data: any) {
//We call peer 2
    this.io.emit("callUser", { userToCall: this.state.guestId, signalData: data, from: this.state.id });
}

listenStreamHost(stream: any) {
    if (this.partnerVideo) {
      this.partnerVideo.srcObject = stream;
    }
}


```

And this is the `aceeptCall()` function is being called on the press of the answer button as peer 2.

```
  acceptCall() {
    this.peer = new Peer({
      initiator: false,
      trickle: false,
      config: { iceServers: [
        { urls: 'MY.STUN.SERVER' },
        {
          urls: 'MY.TURN.SERVER',
          credential: "PASS",
          username: "USER"
        }
      ]},
      stream: this.state.stream
    });


    this.peer.on("signal", (data: any) => {
      //we notify peer 1 that we answered the call
      this.io.emit("acceptCall", { signal: data, to: this.state.caller });
    });

    this.peer.on("stream", (stream: any) => {
      if (this.partnerVideo) this.partnerVideo.srcObject = stream;
    });

    this.peer.signal(this.state.callerSignal);

    this.setState({callAccepted: true, receivingCall: false})
  }

```

So to make a long story short - the first connection works great. Then when the guest leaves the website and returns, the connection between the peers fails with the error mentioned.

Here is the debug log for the second time peer 2 tries to connect (the log is taken from peer 1):

```
starting batched negotiation index.js:448
start negotiation index.js:464
signalingStateChange have-local-offer index.js:1045
createOffer success index.js:705
iceStateChange (connection: new) (gathering: gathering) index.js:791
started iceComplete timeout index.js:666
iceStateChange (connection: new) (gathering: complete) index.js:791
signal index.js:696
signal() index.js:218
got request to renegotiate index.js:221
_needsNegotiation index.js:440
signal() index.js:218
got request to renegotiate index.js:221
_needsNegotiation index.js:440
starting batched negotiation index.js:448
already negotiating, queueing index.js:462
signal() 2 index.js:218
flushing sender queue Array [] index.js:1019
flushing negotiation queue index.js:1030
_needsNegotiation index.js:440
negotiate index.js:1038
signalingStateChange stable index.js:1045
starting batched negotiation index.js:448
start negotiation index.js:464
on track 2 index.js:1118
destroy (error: Cannot set remote answer in state stable)

```

What am I doing wrong?

**Comment by AlessandroAnnini** [comment]
I am experiencing the same error with a specific host.. did you solve it?

**Comment by nazar-pc** [comment]
@AlessandroAnnini there is almost definitely a signaling issue. Make sure to send messages in correct order and to not duplicate them.

**Comment by AlessandroAnnini** [comment]
thanks @nazar-pc, I will debug more.. but it is normal that it happens only when I try the connection with a specific computer? it works for everybody else
(tried to make him use private navigation window, still nothing)

**Comment by nazar-pc** [comment]
Specific computer can be caused by some race condition or setup, it is impossible to guess without code and even if I had access to code I really have no time to debug it anyway.

**Comment by AlessandroAnnini** [comment]
I understand, thanks for pointing me to signaling direction!

**Comment by AlessandroAnnini** [comment]
@nazar-pc just to give closure :) my problem was that I needed to set STUN/TURN servers, I used Twilio and worked at the first try.

Thanks anyway because checking the signaling process I made it better
