### ISSUE TITLE
Implementing peer to peer connection from RaspberryPi to web-browser

### ISSUE THREAD

**Issue by SourceCodeZone** [feross/simple-peer#655]
I am planning to implement peer to peer connection  from RaspbarryPi to web-browser, where the webserver is accessed publicly and implemented using https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API.

Basically I need to stream video from RaspberryPi  to a client browser, and the RaspberryPi  is in local network and need to start the stream automatically, also I have to use a custom signaling server like peerjs-server https://github.com/peers/peerjs-server. 

Please let me know whether simple-peer suit my requirement.

**Comment by razvanphp** [comment]
it does, you can implement your own signalling server or implement peerjs-server API.

But the problem will be to get your video stream in nodejs in MediaStream format, since this is only implemented in browsers currently.

**Comment by SourceCodeZone** [comment]
Thanks for the replay, probably I have to look for other solution.

**Comment by t-mullen** [comment]
`wrtc` supports MediaStreams! https://github.com/node-webrtc/node-webrtc
