### ISSUE TITLE
peer.destroy() throws RTCErrorEvent

### ISSUE THREAD

**Issue by techlover1** [feross/simple-peer#657]
Occasionally when the second party calls `peer.destroy()` the first party will receive an RTCErrorEvent. Not really sure where to start with debugging this since I'm not very familiar with JS, so any help would be greatly appreciated
![image](https://user-images.githubusercontent.com/17421974/81688664-b7697a80-9427-11ea-85f7-6a33e0ad5e2c.png)

**Comment by techlover1** [comment]
It figures I make progress right after I open an issue.
Seems like calling `peer.destroy()` inside `peer.on('close')` helps with this. It doesn't solve the error, but it at least leaves me in a state where I can re-establish a connection.

Still would love some input from anyone with more knowledge than me

**Comment by feross** [comment]
I've seen this issue as well but it's unclear what causes it.

**Comment by junaid-A-khan** [comment]
I was having the same problem. 
I have a viewer and broadcaster setup with multi peer support. 

I solved it by unsubscribing peer(viewer) client event channel when ever the broadcaster disconnected/upon receiving error at viewer's end. As @techlover1 has mentioned that the other peer(viewer) receives `{code:"ERR_DATA_CHANNEL"} `. After this if I make a call to broadcaster, I first subscribe to self client event channel and then signal the other peer(broadcaster) which is the correct sequence of signalling I suppose. 

It is also related to closed issue #24 where you get this error `Error: InvalidStateError: Failed to set remote answer sdp: Called in wrong state: kStable`

And it is also good to unsubscribing the peer(viewer) client event channel at other peer's  (broadcaster) end.

This really fixed it for me after days of debugging.
Sorry for bad English. Hope this helps someone.

**Comment by feross** [comment]
@techlover1 So, I've improved the error message logging so it should show something more useful than "[object RTCErrorEvent]". Can you try to reproduce this and see what the error message is?

I have a suspicion that this is the same issue as https://github.com/feross/simple-peer/issues/627

**Comment by t-mullen** [comment]
#627 was about the local peer firing `onerror` on `channel.close()`. This issue is about the remote peer receiving an error.

It seems like they may have both been fixed in latest Chromium. Can you confirm if this issue is solved @techlover1 ?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
