### ISSUE TITLE
Debug npm module throws an error in IE11

### ISSUE THREAD

**Issue by chocnut** [feross/simple-peer#658]
Is it possible that we don't use debug module in IE11? Because it throws an error. Please refer to this ticket.

https://github.com/visionmedia/debug/issues/701

**Comment by nazar-pc** [comment]
IE11 wouldn't work either way since it doesn't support data channels at very least. So you run it you'll need to hack simple-peer and who knows what other issues you'll get afterwards.

**Comment by chocnut** [comment]
Thanks for the reply @nazar-pc. Yeah looks like I need to fork it. I'm wondering why webpack requires it on my bundle? Is it because it's a dependency?

**Comment by chocnut** [comment]
I ended up using the minified version.
