### ISSUE TITLE
How do I run the test code?

### ISSUE THREAD

**Issue by flx413** [feross/simple-peer#663]
I'm trying to run the test/basic.js in cmd node env, like `node basic.js`, but I got the error `No WebRTC support: Specify opts.wrtc option in this environment`. Should I run it in Chrome?

**Comment by nazar-pc** [comment]
`npm test` as usual in Node.js. Or check package.json for instructions how to run it manually: https://github.com/feross/simple-peer/blob/143c6284074772be316779b860e3ad53aebe7d10/package.json#L58-L66
