### ISSUE TITLE
peer.signal() slow when using wrtc and trickle: false

### ISSUE THREAD

**Issue by dandevs** [feross/simple-peer#667]
It seems to always take 5 seconds exact to get a signal.

```js
const SimplePeer = require("simple-peer"),
      wrtc       = require("wrtc");

const peer  = new SimplePeer({ wrtc, initiator: true, trickle: false }),
      start = Date.now()

peer.on("signal", data => {
  console.log(data);
  console.log(Date.now() - start);
});
```

**Comment by t-mullen** [comment]
Disabling trickle means you must wait for all ice candidates to be gathered before sending an offer/answer. This is why it's slow.

Use trickle for faster signalling - that's what it's for!

**Comment by dandevs** [comment]
Sorry, I should have elaborated more. In the browser it only takes me 250ms~ with trickle disabled to get the initial signal, but with node+wrtc it takes 5 seconds. Is this normal?

**Comment by t-mullen** [comment]
I would expect them to take about the same length of time. You should open this issue in https://github.com/node-webrtc/node-webrtc
