### ISSUE TITLE
Connection failed when behind university network or VPN

### ISSUE THREAD

**Issue by napdivad** [feross/simple-peer#668]
My company is using simple-peer for a video chat web app and it has been working great (even with trickle = true), but I found that people behind a university network (e.g. "eduroam" / WiFi on college campus) or VPN get "connection failed" with error code "ERR_CONNECTION_FAILURE", and I'm not sure why. I see the signaling data passed between the browsers (via our servers), but the connection failure keeps happening.

Has anyone run into this issue / have some idea why this is happening? We're using Xirsys for STUN/TURN and it's been working fine, except for this case of behind university network or VPN.

**Comment by nazar-pc** [comment]
There is no universal answer. External UDP traffic can be blocked, try to use TURN with TCP on port 443, that is a good fallback in restrictive networks.

I'll close this issue since it is not an problem in simple-peer and this is not a generic WebRTC support forum, but feel free to continue conversation.

**Comment by napdivad** [comment]
Thanks for the info, makes sense, we are using TURN TCP with 443 (e.g. "turns:us-turn4.xirsys.com:443?transport=tcp" ) among a list with other URLs, but hmmm need to debug more.

**Comment by napdivad** [comment]
Fixed it! Thanks Xirsys support team! Problem was I was setting the credentials expiration token incorrectly, which caused the TURN servers to reject the credentials because they are expired.
