### ISSUE TITLE
ability to remove event listeners

### ISSUE THREAD

**Issue by Dealerpriest** [feross/simple-peer#673]
Can't figure out a way to remove event listeners.
By experimentation I've figured out that doing several calls to `on('close', blabla)` will add to the collection of event handlers, rather than replace the already existing one.
For example I'd like to remove all event listeners for `close` events. 

As of now the following code will trigger all the console logs on a close event:
```
this.peerConnection.on('close', () => {
  console.log('close event 1');
});
this.peerConnection.on('close', () => {
  console.log('close event 2');
});
this.peerConnection.on('close', () => {
  console.log('close event 3');
});
```

Is there a way to remove an event handler after it has been added?

**Comment by Dealerpriest** [comment]
Aha. I was not aware of event emitters. Isn't that a nodejs specific thing? And I guess then that it's introduced through the `require` of **readable-stream** which implements Event Emitter?

Perhaps it would be useful with a reference to the [nodejs events documentation](https://nodejs.org/api/events.html) in the README.md?

Anyways. I tried with `this.peerConnection.removeAllListeners('close');` and it seems to work fine 👍

**Comment by subins2000** [comment]
I had to look into code that it's `EventEmitter`, but I can't seem to call `.off()` on the `Peer` object. Instead, had to use `.removeListener()`. Shouldn't `.off()` be available ?

**Comment by jarretttaylor** [comment]
@subins2000 I believe `off()` is a [jQuery-specific method](https://api.jquery.com/off/). simple-peer does not utilize jQuery, so `removeListener()` is the correct approach.
