### ISSUE TITLE
Please add more information about how the `opts.wrtc` option works.

### ISSUE THREAD

**Issue by fresheneesz** [feross/simple-peer#676]
It says you need to pass a web rtc implementation for node, however it doesn't say what kind of API it requires. Does this only support the wrtc module? Some more information in the readme would be appreciated.

**Comment by nazar-pc** [comment]
It is very simple if you look at source code.
Basically it is an object with following properties:
* `RTCPeerConnection`
* `RTCSessionDescription`
* `RTCIceCandidate`

You rarely need it and if you do checking source code is not difficult.

**Comment by fresheneesz** [comment]
There are certainly very simple things you can glean from looking at the source code. However, looking at the source code very often doesn't make some important things clear. The source code certainly doesn't make it easy to understand how each of the methods on `this._pc` operate or what assumptions are made.

For a user of this library, usually you wouldn't want to implement your own, however, you might want to choose between different implementations, sometime which require connector code when the APIs (inevitably) don't match. If the API is intended to match the wrtc library's API, please mention it in the documentation. If there are other libraries that have matching APIs we could use, that would also be incredibly useful information. I don't know how I would verify that I can use another library without actually just trying it out, and when it inevitably fails, it would probably take hours to figure out how to wire another implementation up so that it works with simple-peer. Those are hours I'd rather not spend, and hours that could be saved if the documentation made it clear what API it expect, whether that API is a standard that multiple libraries implement, and other information like that. Source code is not documentation. 

This repo has pretty great looking documentation (tho I must say I haven't used it enough to be likely to have found holes in it). This is just one spot that seems under documented. So this is really less of a question and more of a request to actually add better docs here.

**Comment by t-mullen** [comment]
The structure of the `wrtc` object is documented in the README (Line 300).
```
wrtc: {}, // RTCPeerConnection/RTCSessionDescription/RTCIceCandidate
```

The interfaces of these types are defined by the WebRTC specification:
https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection
https://www.w3.org/TR/webrtc/#dom-rtcsessiondescription
https://www.w3.org/TR/webrtc/#dom-rtcicecandidate
These aren't documented in simple-peer because they aren't within scope of the project.

No specific assumptions related to the `wrtc` library are made. The implementation is only assumed to be spec-compliant.

**Comment by fresheneesz** [comment]
Thanks, that's super useful info. I created a pull request to make that more clear in the readme: https://github.com/feross/simple-peer/pull/677
