### ISSUE TITLE
Default datachannel only works in one direction in electron app

### ISSUE THREAD

**Issue by Dealerpriest** [feross/simple-peer#678]
I'm actually not sure if my problem is related to simple-peer, but I think so.
When using simple-peer inside a Quasar electron app I can only use the datachannel in one direction. Sending from the electron app to a webpage works well. The other direction, though, from a webpage to the electron app doesn't work.
When running two instances of the webpage it works correctly in both directions.

Curiously enough it works perfectly well with both directions between electron app and webpage if I create a datachannel manually like this:
```javascript
let peerConnection = new Peer(config);
channel = peerConnection._pc.createDataChannel('chat', { negotiated: true, id: 0 });
channel.onmessage = (event) => {
  console.log(event.data);
};
```

Any ideas what might cause this issue?

**Comment by nazar-pc** [comment]
Well, there is nothing special in simple-peer that would prevent data channel from working both ways.
What is you peer config?

**Comment by Dealerpriest** [comment]
My peer config is as follows:
```
//Peer A
const config = {
  initiator: true
};

//Peer B
const config = {
  initiator: false
};
```
I've also tried the following on both peers without any improvement:
```
const config = {
  initiator: true, //or false if it's Peer B
  channelName: 'chat',
  channelConfig: { negotiated: true, id: 0 },
};
```

So far the only thing I've tried that works for me is the following:
```
peerConnection = new Peer(config);
channel = peerConnection._pc.createDataChannel('chat', { negotiated: true, id: 1 });
```

**Comment by nazar-pc** [comment]
The first config is fine, make sure you handle all signaling events correctly.

Closing since I see nothing that indicates issue in simple-peer, but feel free to continue conversation.

**Comment by Dealerpriest** [comment]
I understand you want to close the issue since I can't prove it's an error on the simple-peer side (although this is indicated by it being possible to manually create a RTCDatachannel).
But the issue is not resolved.
I'm rather sure I handle all signaling correctly. I propagate them through a nodejs websocket server as is kind of common praxis.

Also the code is identical when I run it in two webpages compared to running in a webpage and an electron app. The electron app is a wrapper for the exact same codebase. So I'm rather sure there is something in simple-peer that makes it fail to create a datachannel in electron. As i can create one manually 👍 

Anyways. If someone have the same problem, the workaround for me was to create my own datachannel as described in this issue.
