### ISSUE TITLE
WebRTC: Using five or more STUN/TURN servers causes problems

### ISSUE THREAD

**Issue by BoazKG93** [feross/simple-peer#680]
I'm using XIRSYS as my STUN/TURN server provider. They provided me with 1 STUN server and 6 TURN servers (both udp and tcp, on different ports - 80, 3748, 443, 5349). When I write all of them in the options object, I get this error:

`WebRTC: Using five or more STUN/TURN servers causes problems`

This doesn't prevent me from actually establishing a connection and have my video call, but I'm afraid it won't scale or will actually cause problems. I couldn't find anything related in internet, so I thought it's simple-peer related. Any thoughts?

**Comment by nazar-pc** [comment]
There is no such message in simple-peer's source code. But it is not a very good idea to have so many STUN/TURN servers indeed, but it is not forbidden either. The message you get is most likely a warning, not an error.

Closing since there is nothing to be done in simple-peer.
