### ISSUE TITLE
Datachannel and Video example

### ISSUE THREAD

**Issue by MariasStory** [feross/simple-peer#682]
Hi,
I am trying to connect datachannel and than (on event) initiate a video stream.
So far I haven't seen a working example like this.
In my test, the datachannel disconnects as soon as the stream connections is established and works only from the initiator side.
Simple example would help.
--------- init:
p = new SimplePeer({
	initiator: initiator,
	trickle: false,
});
--------- later:
thePeer.addStream(stream)
--------- peer1:
p.on('stream', stream => {
	video.srcObject = stream;
}
--------- message peer1:
finish
disconnected
end
--------- message peer0:
No events or signals.

**Comment by nazar-pc** [comment]
From your code sample I don't see any signaling code. Please check examples in readme, they are there for you to start quickly and get something working right away.

Closing since I believe there is nothing wrong with simple-peer here.
