### ISSUE TITLE
WebRTC Signaling works only when initiator loads the webpage first

### ISSUE THREAD

**Issue by BoazKG93** [feross/simple-peer#684]
I'm having a React App using `simple-peer` with WebRTC. 
My application has 2 links for a chat room - one for host and one for guest. I'm saving on the state if it's a host or a guest.

So when a user enters the room, I emit his id and receive it by the other person in the room:

```
    this.io.on("video_users", (users: any) => {
      this.setState({ users }, () => {
        if (this.state.host) this.callPeer();
      });
    });

```

If it's the host, I'm calling the other peer using:

```

callPeer() {
   this.peer = new Peer({
      initiator: true,
      trickle: true,
      config: ....
    });

    this.peer.on("signal", (data: any) => {
      this.state.users.map((user: any) => {
        if (!user.host) {
          this.io.emit("video_call_client", {
            to: user.id,
            signal: data,
            from: this.state.id,
            name: this.state.name
          });
        }
      });
    });
}

```

In return, the guest receives the `video_host_signal` event that holds all the information that i passed on `video_call_client`:
```
    this.io.on("video_host_signal", (data: any) => {
      this.setState({
        receivingCall: true,
        partner: { id: data.from, name: data.name },
        signals: [data.signal, ...this.state.signals]
      });
      if (this.peer) this.peer.signal(data.signal);
    }); 
```

Now because `receivingCall: true` is set to true, the guest has a button to accept the incoming call, once he clicks it, I call `acceptCall()` as follows:

```
acceptCall() {
    this.peer = new Peer({
      initiator: false,
      trickle: true,
      config: ....
    });

    this.peer.on("signal", (data: any) => {
      if (this.state.partner) {
        this.io.emit("video_answer_host", {
          signal: data,
          to: this.state.partner.id,
          from: this.state.id,
          name: this.state.name
        });
      }
    });
    
//We now signal back all the ICE candidates that were collected on the state
    this.state.signals.map((signal: any) => {
      this.peer.signal(signal);
    });

}
```

The host in return gets an `video_host_signal` event that was created from the emitting of `video_answer_host` by the guest as follows:
```
    this.io.on("video_client_signal", (data: any) => {
      this.setState({
        callAccepted: true,
        partner: { id: data.from, name: data.name },
        signals: [data.signal, ...this.state.signals]
      });
      if (this.peer) this.peer.signal(data.signal);
    });
```

That's it, we have a connection.

The problem is it works ONLY if the host connects first and then the guest joins. If the guest joins first, and then the host - the host can see the guest, but the guest can't see the host. I can't figure out what's the problem though. When the host joins, we create `this.peer` and signal. The guest receives all the signals and save them for later use. Why does it matter if the guest was there before the host?

Live demo can be tried out here:
Host link: https://my.treedis.com/public/tour/wLZZpgKGxYW/video/host/test
Guest link: https://my.treedis.com/public/tour/wLZZpgKGxYW/video/guest/test

If you try to enter first as host and then as guest, all good. If you enter first as guest and then load the host link, signaling is not working correctly.

**Comment by BoazKG93** [comment]
So I checked the signaling data. It seems that if I load the host first, it signals 19 times. Then the guest joins and it signals 89 more times.

If I load the host AFTER the guest was loaded already, it signals only those 19 times and that's it. When the guest refreshes, it will signal the rest (89 times).

**Comment by t-mullen** [comment]
Closing as this doesn't seem to be an issue with simple-peer, but feel free to continue discussion.
