### ISSUE TITLE
Anyway to force h264?

### ISSUE THREAD

**Issue by rygo6-MS** [feross/simple-peer#687]
Is there any setting which would let me force SimplePeer to only use h264? Currently I am noticing the answer signal from SimplePeer doesn't even include h264 as an option. Not sure how I would even get it added to signal, let alone have that be the only option. 

My source is definitely offering h264 in it's signal that gets send to SimplePeer and I want SimplePeer to basically be a pass through for this unaltered h264 stream to many other peers. Is this possible?

**Comment by nazar-pc** [comment]
Codec support depends on environment. Simple-peer doesn't alter codec selection in any way out of the box.

Codec is usually enforced either with SDP munging or by other peer (like with special SFU configuration or when browser prefers other codec and hence only includes it in the answer).

There is nothing simple-peer does or should do about codec selection here, so I'm closing the issue, but feel free to continue conversation.
