### ISSUE TITLE
Understanding peer.signal() function

### ISSUE THREAD

**Issue by elizardi-Ceit** [feross/simple-peer#688]
Hi, 

I'm creating a WebRTC application using Simple-Peer.  I have developed a simple prototype where 2 users connect from different browsers so far, but I have an issue.  The application will be used by different type of devices.  The majority will connect using the browser (so Simple-Peer will be used) but other devices have their own WebRTC implementation.

I more or less know how to implement in plain WebRTC the same behaviour implemented using Simple-Peer. However I'm having problems understanding the **`peer.signal()`** function.  What is the equivalent counterpart in plain WebRTC of **`.signal()`** function?

Thank you and good job for this awesome project.

Regards.

**Comment by nazar-pc** [comment]
Various things depending on signal contents, just check the source code:
https://github.com/feross/simple-peer/blob/fe1b3f80e265276333bf44e7dcc51170193b9e75/index.js#L180-L237

**Comment by elizardi-Ceit** [comment]
Nice.  I didn't know exactly where was the definition of the function.  Thanks for helping!
