### ISSUE TITLE
Can't connect peers when on a different network

### ISSUE THREAD

**Issue by josdejong** [feross/simple-peer#69]
Thanks for writing simple-peer, really great to have a WebRTC library that I can use in both browser and node.js.

I'm playing around with SimplePeer but noticed that I can't connect peers when they are on a different network. I've put the [usage example](https://github.com/feross/simple-peer#usage) from the readme in a jsbin to have the simplest possible test: 

http://output.jsbin.com/tomini/ 

The initiator correctly generates an offer, and when I paste the offer in the form of the receiver, it generates an answer. When I paste the answer in the initiators form however nothing happens, and after 5 or 10 seconds the peers on both sides send a  closed (from both sides).

To verify whether the networks and devices I'm testing on don't have some issue I tested whether WebRTC by itself works using https://apprtc.appspot.com/. This indeed works just fine on all machines and phones I'm trying.

Any idea?

**Comment by josdejong** [comment]
hm, I guess the reason is that https://apprtc.appspot.com has a TURN server configured. Let me give that a try.

https://github.com/feross/simple-peer#connection-does-not-work-on-some-networks

**Comment by josdejong** [comment]
Ok it was indeed not working because I need a TURN server. WebRTC doesn't feel very p2p anymore :(

**Comment by josdejong** [comment]
Just for others having the same issue, here is a free TURN service: 

http://numb.viagenie.ca/

**Comment by feross** [comment]
@josdejong The TURN server will probably needed ~10% of the time between any two arbitrary peers (according to stats quoted by Google). It only happens when both peers are on really restrictive networks. Symmetric NATs are the most common offender. You can learn more about NATs here: https://en.wikipedia.org/wiki/Network_address_translation#Methods_of_translation

**Comment by josdejong** [comment]
Yeah, I have only limited knowledge of NAT, will dive into it more deeply. Good to know that it's only a small user percentage needing TURN in practice. Thanks again!

Just FYI, I'm working on this project: https://github.com/enmasseio/linkup (early stage, similar to peer.js)
