### ISSUE TITLE
Calling `send` before the channel is open doesn't buffer data?

### ISSUE THREAD

**Issue by lazerwalker** [feross/simple-peer#690]
The README claims that if you try to send data before a connection has been established, the `send` method will buffer that message until it's ready: https://github.com/feross/simple-peer/blob/master/README.md#peersenddata

This isn't happening for me in practice — trying to send before receiving a `connect` message gives me an error that the `RTCDataChannel.readyState` is not `'open'`.

Looking at the code, `peer.send` appears to just delegate straight to the underlying WebRTC method: https://github.com/feross/simple-peer/blob/master/index.js#L243-L245

I'm guessing the correct fix here is to just delete that sentence from the README (happy to open a PR), but curious if there's something I'm doing wrong or misunderstanding, or if you have other thoughts.

**Comment by t-mullen** [comment]
You're correct, `peer.send` does not buffer and the documentation shouldn't say this.

**Comment by feross** [comment]
Docs updated in PR: https://github.com/feross/simple-peer/pull/766
