### ISSUE TITLE
Ice connection failed after peer is killed

### ISSUE THREAD

**Issue by fresheneesz** [feross/simple-peer#696]
I have a listening peer and a connecting peer. The listening peer listens for multiple connections. When a connecting peer connects, it successfully connects and gets a message through. However, when I close the browser tab of the connecting peer, after a few seconds, the listening peer gets an "Ice connection failed" error. Is this expected? I would have hoped for a simple 'close' message or at least a clearer "peer disconnected uncleanly" error.

**Comment by nazar-pc** [comment]
This is definitely expected. Simple-peer is just a wrapper over native WebRTC API. WebRTC is a bit more complex that `open` and `close`.

**Comment by fresheneesz** [comment]
I see the list of errors in the readme includes this error (ERR_ICE_CONNECTION_FAILURE), however I don't see any description of what those errors mean or when they're thrown. Do they correspond to errors in [the spec](https://www.w3.org/TR/webrtc/)? I don't see any ICE_CONNECTION_FAILURE error in the spec. If they're not in the spec, could those errors be more fully documented as far as what they mean and what options the programmer has when they catch an error like that?

**Comment by nazar-pc** [comment]
Just open source code at `index.js`, it will become obvious what they are.

**Comment by fresheneesz** [comment]
I can see from the source that this error corresponds to the ["failed" RTCPeerConnectionState](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnectionstate), which indicates that either the [RTCIceTransportState](https://www.w3.org/TR/webrtc/#dom-rtcicetransport) is "failed" or [the RTCDtlsTransportState](https://www.w3.org/TR/webrtc/#dom-rtcdtlstransport) is "failed". 

How can I determine which of those situations it is? 
It would be nice if the error objects themselves included information that allowed the programmer to get deeper information about the error.

Its still not clear to me the situations this may happen and guidance on handling those situations would be very helpful, since it would allow a programmer to appropriately deal with these errors without a deep understanding of the webrtc spec. 

The major attributes that would be useful to know about are:

A. Whether or not the transport used for communicating has been broken or is still usable.

B. Whether the transport can be restarted or not.

C. Whether the error originated from the local peer or the remote peer. And if it originated from the remote peer, what is the likelihood that it is an unclean disconnection of the type that closing a browser window could cause?

Its clear that my situation is a fully broken connection that can't be restarted because the peer is gone, but how would I determine that programmatically in the code? If I can gain a clearer understanding, I'd like to update the readme with some guidance on it, if that's ok with you.

**Comment by nazar-pc** [comment]
Simple-peer is just a wrapper around native WebRTC functionality. So handling is about the same here as it is with native WebRTC. I think describing all of the WebRTC API surface and meaning is beyond the scope of this library.

Both A and B can be answered by specification. Not sure what you mean by error origination though.

In most cases you simply can't know why connection is dropped by remote peer and sometimes connection appears to be alive for some time even though remote peer turned their computer off already. What to do depends on use case a lot and you really need to read MDN and preferably relevant specification sections if you want to ship something to production. WebRTC is not that simple if you want to handle it properly.

For practical purposes rarely important to know who and why and where got broken connection, you just need to know it happened and show an error to the user and write message to logs.
