### ISSUE TITLE
on("Signal") called twice

### ISSUE THREAD

**Issue by ranbe1** [feross/simple-peer#702]
I'm trying to make a connection between two peers and after there's a connection i want to add their streams.
This is the main part of the code:

add a stream:

```
getMedia(peer) {
    // Get media of current client
    navigator.mediaDevices
      .getUserMedia({ video: false, audio: true })
      .then((stream) => {
        peer.addStream(stream);
      })
      .catch(() => {});
}
```
callPeer method:

```
callPeer(peer, userToCall) {
    peer.on("signal", (data) => {
      this.socket.emit("call:offer", {
        receiverId: userToCall,
        signalData: data,
      });
    });

    peer.on("connect", () => {
      this.getMedia(peer);
      console.log("peers connected");
    });

    peer.on("stream", (stream) => {
      var audio = document.getElementById(userToCall);

      audio.srcObject = stream;
      audio.onloadedmetadata = function (e) {
        audio.play();
      };
    });
 }
```
acceptCall method:
```
  acceptCall(peer, callData) {
    peer.on("signal", (data) => {
      this.socket.emit("call:accept", {
        signalData: data,
        receiverId: callData.senderId,
      });
    });

    peer.on("stream", (stream) => {
      var audio = document.getElementById(callData.senderId);

      audio.srcObject = stream;
      audio.onloadedmetadata = function (e) {
        audio.play();
      };
    });

    peer.on("connect", () => {
      this.getMedia(peer);
      console.log("peers connected");
    });

    peer.signal(callData.signalData);
  }
```

The main problem is in `acceptCall` method in this line: `peer.signal(callData.signalData);`
For some reason after i call this line, the `peer.on("signal")`(acceptCall method) is being called twice everytime i'm trying to make a call.

Also, it happens in two scenarios, because of different reasons(from what i understand):

The first time it happens is the initial call, i investigated a bit, and turns out it was related to renegotiation.
so just adding a hacky `if(!data.renegotiate)` inside the `peer.on("signal")`(acceptCall method) solved it.
like this:
```
 peer.on("signal", (data) => {
      if (!data.renegotiate) {
      this.socket.emit("call:accept", {
        signalData: data,
        receiverId: callData.senderId,
      });
     }
    });
```

The second time happens again on the same line, when it tries to re perform the call signaling *after* `addStream` called,
and i have no idea why it happens in this scenario.
but because of this, it tries to accept the call again(`this.socket.emit("call:accept"...)`) which causes errors.

not sure what to do here, tried to add logs to the library index.js, but can't find the place that calls the `on("signal")` again.

thanks.

**Comment by nazar-pc** [comment]
`signal` is expected to be called multiple times unless you specify `trickle: false` in peer configuration.
This mechanism is called Trickle ICE and is designed to make connection establishment faster.

**Comment by ranbe1** [comment]
my bad, i didn't add my peer configuration:
```
const peer = new Peer({
        initiator: isInitiator,
        trickle: false,
        renegotiate: false,
        config,
        stream: stream,
      });
```

trickle is set to false..

**Comment by nazar-pc** [comment]
Looks like the same as #670 then?

**Comment by nazar-pc** [comment]
Please read what Trickle ICE is and why it is necessary to have multiple signal messages. Also renegotiation will require additional SDP exchange, which means additional signal events.

**Comment by ranbe1** [comment]
i saw #670 , and it's probably the same issue in the first scenario.
not sure about the second, because the `renegotiate` variable is `undefined` there.

**Comment by nazar-pc** [comment]
There is no `renegotiate` option, so it doesn't impact anything, not sure why you have it.

**Comment by ranbe1** [comment]
i mean on the signaldata, it does append renegotiate property there.
in the peer configuration i will remove it.

**Comment by nazar-pc** [comment]
It appends it because of #670.

**Comment by ranbe1** [comment]
yes, true. but what i mean is that in the second scenario(after `addStream`) it doesn't append a `renegotiation` but still called twice. so it might be another issue.

**Comment by nazar-pc** [comment]
You need to check the contents. There are a few different but related things abstracted away as a `signal` event.

**Comment by ranbe1** [comment]
i printed the data, it's the same data 2 times in a row:
```
{"type":"answer","sdp":"v=0\r\no=- 4041966182180262076 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS yM0xcqLy3XXLN2qhC7sxO89IFXDet2iQ0AiF\r\nm=application 63018 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 192.168.42.49\r\nb=AS:30\r\na=candidate:557050242 1 udp 2122260223 192.168.42.49 63018 typ host generation 0 network-id 1\r\na=ice-ufrag:+bHH\r\na=ice-pwd:/4bUSQOXpU8N2Un/INNNwRq4\r\na=fingerprint:sha-256 9F:62:30:57:6C:C3:92:39:2F:BA:F5:7F:72:AF:CC:80:B5:DB:9C:6D:E7:97:DD:6C:52:AE:D0:80:DA:8B:2C:48\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:+bHH\r\na=ice-pwd:/4bUSQOXpU8N2Un/INNNwRq4\r\na=fingerprint:sha-256 9F:62:30:57:6C:C3:92:39:2F:BA:F5:7F:72:AF:CC:80:B5:DB:9C:6D:E7:97:DD:6C:52:AE:D0:80:DA:8B:2C:48\r\na=setup:active\r\na=mid:1\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:yM0xcqLy3XXLN2qhC7sxO89IFXDet2iQ0AiF 0e8e6394-f824-43f2-8786-6ee527de5522\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:170450026 cname:DpnzjMGV1ygqG4c/\r\n"}
```

**Comment by nazar-pc** [comment]
Are they exactly the same though?

**Comment by ranbe1** [comment]
yes, compared them with a tool.

**Comment by nazar-pc** [comment]
I think you can ignore second event then and wait for #670 to be resolved

**Comment by ranbe1** [comment]
it's problematic for me to ignore the second because i might have conference calls when the user needs to answer more than 1 time in a row, so how would i know which is the answer to ignore without saving the contents of the answer and compare it(which is pretty weird)

**Comment by nazar-pc** [comment]
Not sure what that means. You can try `once('signal', ...)` if you are know you only need one signal.

**Comment by ranbe1** [comment]
it actually works...it doesn't repeat this answer twice now.
but from what i understand now, it's not a good solution as multi signaling is necessary for a fast handshake on production.
and it's not that i need one signal, it's that i don't need the **same** signal twice, as it just ruins the flow of the handshake.

**Comment by nazar-pc** [comment]
Right, but then you wouldn't have `trickle: false` in the config

**Comment by ranbe1** [comment]
well, that's cause i really don't know how to use it, when i turn it on everything just gets messy and doesn't work(just nonstop accepting calls).
can you refer me to a good example on how to write the code with trickle?

**Comment by nazar-pc** [comment]
Readme has an example of this that should work. Essentially you need to send to the other side each and every message emitted with `signal` event and call `.signal()` with it. This is all that there is to it really.

**Comment by ranbe1** [comment]
anyway, i figured out what was the problem. everytime i called `acceptCall` it redefined the `.on("signal')`, that's why when `simple-peer` called `emit` it was being called twice.
thanks for the help :)

**Comment by rokit** [comment]
@ranbe1 Thanks for posting your findings as it helped me solve my own problem. I was using the same Socket.IO `peer` event to handle both my initiator and candidate signals as in this example:
https://gist.github.com/adammw/d9bf021c395835427aa0

My problem was the initiator's event listeners were getting defined twice, once when it was prompted to signal by the server, and then again when it received the answer from the candidate. So I was seeing the initiator get two connection events, send data twice, and receive data twice.

**Comment by prasanna3000** [comment]
> anyway, i figured out what was the problem. everytime i called `acceptCall` it redefined the `.on("signal')`, that's why when `simple-peer` called `emit` it was being called twice. thanks for the help :)

How did you fix this issue? I ran into the same problem. Any kind of suggestion would be really helpful.

**Comment by Mihai-github** [comment]
> anyway, i figured out what was the problem. everytime i called `acceptCall` it redefined the `.on("signal')`, that's why when `simple-peer` called `emit` it was being called twice. thanks for the help :)

Hi, I'm also facing the same issue when calling peer.addStream() or addTrack() the peer.on('signal') is called, and then because of the websocket the peer.signal(answer_signal) is also called and I an error

When I'm adding a stream the peer.signal and on('signal') should be called?
