### ISSUE TITLE
Not able to setup Peer connection for mixed mode (One user on video & audio, Other user only Audio)

### ISSUE THREAD

**Issue by sumitgupta07** [feross/simple-peer#711]
Hi,

I am using simple-peer for video/group call and screen share. One to one and many to many video call works fine along with screen share, which I am doing using replaceTrack function.

While extending my application, I got 2 issues:
1. If remote peer doesn't have access to camera. Means he is connecting via only Audio (i.e. only one Track). And current peer has both audio and video (i.e. both tracks). Connection is established if Non Camera remote user initiates the connection.  But it doesn't work when current user (video/audio) initiates the connection. 
Basically, it is trying to signal twice. And a transceiverRequest event is fired with signal = {transceiverRequest: {kind: 'video', init: undefined}. I am not sure from where it is fired and how to handle it.
I am directly creating Peers as below:
const peer = new Peer({
      initiator: true/false, // It is based on the peer if he is initiator or not
      trickle: false,
      stream: stream, // Has 1 track for remote peer and 2 tracks for current peer
    });

2. Another issue is based on above problem. If above works, I am not sure how to share screen from remote peer, who doesn't have any video track. If I try to use addTrack function, it fires renegotiation event. And I am not sure what to do after this step.

I really need help here to understand how I can solve these problems. I cannot find much in simple-peer documentation or demos. I may have missed some details, but don't know exactly what.

I can add more information if required.

Thanks a lot for the great work!!!

**Comment by sumitgupta07** [comment]
Some more details:

2 Peers:
1. Initiator: Runs with both audio and video ON.
2. Non initiator: Runs with only Audio.

Steps:
1. Initiator connects and wait for new users.
2. Non initiator connects and find an existing user in the room. It tries to add Peer with "Initiator: true" value.

Handshake info:
1. Non initiator sends offer signal and its Audio track. 
2. In return initiator sends answer signal. And additionally send **TransceiverRequest** for **kind: video**. 
3.Non initiator end sees this signal as normal signal and tries to signal back, which causes another set of handshaking, where Initiator tries to add one more non-initiator peer.

My question: How should I pass this TransceiverRequest to non-initiator peer and how to respond back. Right now I did not put any kind of signal type check before responding back. But it seems, it is needed now.

Thanks

**Comment by sumitgupta07** [comment]
On further analysis. I found that Non initiator end is offering again because it receives additional signal (transceiverRequest) from initiator which is accepted.
If I stop this offer by hack using flags. Both ends can talk. But video is not delivered to non-initiator end.

Seems some kind of signal has to go from Non-initiator to Initiator so that Initiator can send its video.

**Comment by nazar-pc** [comment]
This is not about simple-peer, but rather general WebRTC stuff.

This is not a general WebRTC support forum, but rather a tracker for simple-peer bugs and feature requests. I'll give you a few general hints though. If you want to add/remove tracks on the fly that is possible, but you need to support sending more than one signaling message back and forth (can be implemented over data channel within the same WebRTC connection). Another workaround is to create a 1 pixel video on canvas and use that as video source. Later to can replace that video track with screen sharing video track if necessary.

Closing since there is nothing to be done about this in simple-peer, but feel free to continue discussion.

**Comment by sumitgupta07** [comment]
Hey, thank you for your response.
It helped me look into more details about webrtc. I found below 2 links which are exactly what I was looking for. I will try these methods to fix my issue.
https://blog.mozilla.org/webrtc/warm-up-with-replacetrack/
https://blog.mozilla.org/webrtc/signaling-with-rtcsimpleconnection/
