### ISSUE TITLE
Peer's video not streaming

### ISSUE THREAD

**Issue by vineetisforu** [feross/simple-peer#716]
@feross  While checking out the code for the Video/Voice, I am having hard time to try out this code,

```
var Peer = require('simple-peer')

// get video/voice stream
navigator.mediaDevices.getUserMedia({
  video: true,
  audio: true
}).then(gotMedia).catch(() => {})

function gotMedia (stream) {
  var peer1 = new Peer({ initiator: true, stream: stream })
  var peer2 = new Peer()

  peer1.on('signal', data => {
    peer2.signal(data)
  })

  peer2.on('signal', data => {
    peer1.signal(data)
  })

  peer2.on('stream', stream => {
    // got remote video stream, now let's show it in a video tag
    var video = document.querySelector('video')

    if ('srcObject' in video) {
      video.srcObject = stream
    } else {
      video.src = window.URL.createObjectURL(stream) // for older browsers
    }

    video.play()
  })
}
```

When I try to run this code while deploying it in nginx server I only see my screen and audio. And not able to see the peer Audio/Video. I have also setup a STUN server and passed the configs in the needful way, however still its not working.

Thanks!
VM

**Comment by nazar-pc** [comment]
Both peers are on the same page. Also only one of the peers sends audio/video. So example works exactly the was it is intended to work.
