### ISSUE TITLE
issue with stream on broadband

### ISSUE THREAD

**Issue by kk-007** [feross/simple-peer#718]
```error
Uncaught Error: Connection failed.
    at makeError (bundle.js:6751)
    at Peer._onConnectionStateChange (bundle.js:7393)
    at RTCPeerConnection.Peer._pc.onconnectionstatechange (bundle.js:6855)
makeError @ bundle.js:6751
_onConnectionStateChange @ bundle.js:7393
Peer._pc.onconnectionstatechange @ bundle.js:6855
```
i get this error when i run my code using a broadband connection and it works perfectly fine when I use my mobile data.

**Comment by nazar-pc** [comment]
Please don't spam the same issue every day.
This was mentioned in multiple places and is not specific to simple-peer.
Please do your research and after that let me know if you still believe there is an issue in simple-peer.
