### ISSUE TITLE
Stream Event not firing for peer 1

### ISSUE THREAD

**Issue by douglasmasho** [feross/simple-peer#724]
I set up a project that uses socket.io to send signals from peer to peer. It seems that the connection happens as expected, but peer 1 does not receive a stream from peer 2. Even though peer 2 gets a stream

this is the project...the exact files where the issue occurs are specified in the readme.MD

https://github.com/douglasmasho/simple-peer-attempt/

**Comment by arpitmishra61** [comment]
Yes having same issue although for peer1 stream event also firing but not always it happens  very few time and this is bigger issue when we do streaming for multiple times.

**Comment by Ponjimon** [comment]
Any solution? having the same issue

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
