### ISSUE TITLE
Question: does sending a file incur data charges

### ISSUE THREAD

**Issue by kodejuice** [feross/simple-peer#725]
if i `peer.send( BINARY_DATA )` of over a gigabyte, do i also have to pay for the data charge, or its just the receiving peer?

sorry if the question sounds dumb, i'm kind of new to the WebRTC thing

**Comment by jarretttaylor** [comment]
There is no magic in WebRTC. The sender is still using his/her upstream data. If there are costs associated with sending data for the user, then charges would be incurred. Additionally, if the sender is utilizing a [TURN](https://webrtc.org/getting-started/turn-server) server, there may be data charges associated with the relaying of data.

**Comment by kodejuice** [comment]
Thanks, makes sense
