### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by PeadarO** [feross/simple-peer#728]
Hello all,
I am looking at this program 'simple-peer' by Feross Aboukhadijeh and it looks like a very useful piece of work.

I have created the index.html as instructed on the webpage.
I have the simplepeer.min.js in the same directory.

I have the index.html and simplepeer.min.js installed on two computers running Windows 10 and they are both behind 
the same firewall so they should be accessible to each other.

The WebPage says that "An 'offer' will be generated by the initiator".
When I enter something in the field and then click on submit, nothing happens.

Is there anywhere I can get step-by-step instructions on how to make this sample run?

I am looking at https://github.com/feross/simple-peer but it really leaves me no wiser.

Any help much appreciated.
Peadar

**Comment by jarretttaylor** [comment]
simple-peer makes the process of establishing a connection between peers easier. It doesn't make _all_ of WebRTC simple. A much deeper understanding of the concepts associated with WebRTC are necessary to be able to benefit from this project. A good place to start is webrtc.org's [Getting Started Guide](https://webrtc.org/getting-started/overview). As you read it, understand that simple-peer mainly focuses on a subset of the larger WebRTC picture (i.e. Peer connections, Remote streams, and Data channels).

**Comment by PeadarO** [comment]
Thank you Jarrett. I shall do just that but I presume that simple-peer can actually run. It's hard to imagine that it would exist at all if it can't run. I believe that I have followed the instructions and so far it does nothing. Does anyone here know if it can be made to run?

**Comment by PeadarO** [comment]
I just want to make sure that my above enquiry is clear.
This is what the web page says;

Visit index.html#1 from one browser (the initiator) and index.html from another browser (the receiver).
An "offer" will be generated by the initiator. Paste this into the receiver's form and hit submit. The receiver generates an "answer". Paste this into the initiator's form and hit submit.
Now you have a direct P2P connection between two browsers!

It seems to be indicating that simple-peer will run and I am just asking if anyone in here ever got it to run.

**Comment by nazar-pc** [comment]
Of course many people got it to run. Try to use 2 tabs of the same browser on the same machine and it will connect.
If connection doesn't work in more complex cases you need to read some more about what WebRTC is, how it works and what might cause it not to connect.

I don't see any issue with simple-peer here, hence closing, but feel free to continue discussion.
