### ISSUE TITLE
Binary messages not flowing on version 6.0.3

### ISSUE THREAD

**Issue by BrianAdams** [feross/simple-peer#73]
Just took the basic example and used the test payload from the unit tests:  http://requirebin.com/?gist=426a5e6c340fd64b73ef329cbfa94baf

When inspecting the console, I see that it attempts to send but the message is never received by the other peer.  If I switch the payload to a text string, it works no problem.

Using OS X, tested on 
* Chrome: 51.0.2700.0 canary (64-bit)
* Chrome: 49.0.2623.110 (64-bit)

```
var SimplePeer = require('simple-peer')

var peer1 = new SimplePeer({ initiator: true })
var peer2 = new SimplePeer()

peer1.on('signal', function (data) {
  // when peer1 has signaling data, give it to peer2 somehow
  peer2.signal(data)
})

peer2.on('signal', function (data) {
  // when peer2 has signaling data, give it to peer1 somehow
  peer1.signal(data)
})

peer1.on('connect', function () {
  // wait for 'connect' event before using the data channel
  peer1.send(new Uint8Array([0, 1, 2])); //example from unit tests
  console.log('sent')
}) 

peer2.on('data', function (data) {
  console.log('got') //this never fires when using binary data
  console.log(JSON.stringify(data));
})
```

I tried packages 6.0.3-6.0.0 with the same behavior.

**Comment by BrianAdams** [comment]
I am going to go ahead and close this as this is only an issue in this sandbox environment where I was trying to recreate a completely different issue.

**Comment by feross** [comment]
Okay, thanks for self-closing :)
