### ISSUE TITLE
error Error: Connection failed

### ISSUE THREAD

**Issue by Kris-84** [feross/simple-peer#732]
When I try to run the demo from the documentation it doesn't work in chrome version 84.0.4147.135, in the console I see

error Error: Connection failed.
    at a (simplepeer.min.js:6)
    at p._onConnectionStateChange (simplepeer.min.js:6)
    at RTCPeerConnection._pc.onconnectionstatechange (simplepeer.min.js:6)

**Comment by TheSalarKhan** [comment]
Same here. I'm using copy paste to exchange the sdp between me and another person. To be sure that its not because of TURN server I'm adding the turn server in the config but that does not help.

I am the initiator I don't get any error. When the other person sets the sdp and submits they get { renegotiate: true } and then they get their sdp. But after a while - even before I'm able to paste it in - their side gets a connection error and the peer dies.

**Comment by feross** [comment]
You may be taking too long to paste the signals. You don't have very much time before it will time out.

**Comment by MdJahidHasan09** [comment]
I am also facing same issue.

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion!

**Comment by shigristudy** [comment]
have you figure out what was the issue?
my connection is made successfully but after few seconds the same error pops out.. 
some times at 10 secs and some time 30 seconds

**Comment by ntngoc96** [comment]
@shigristudy bro, have you solved this problem yet?? I'm having the same problem and don't know what I'm missing.

**Comment by Mihai-github** [comment]
Also interested +1

**Comment by basedwon** [comment]
I was getting this error, I realized that it was my VPN blocking the stun server. So I set the config option to use TURN servers and no more error! 

[List of servers](https://gist.github.com/sagivo/3a4b2f2c7ac6e1b5267c2f1f59ac6c6b) 

my options:
```js
const peer = new SimplePeer({
  initiator: true,
  objectMode: true,
  config: {
    iceServers: [
      {
        url: 'turn:numb.viagenie.ca',
        credential: 'muazkh',
        username: 'webrtc@live.com'
      },
      {
        url: 'turn:192.158.29.39:3478?transport=udp',
        credential: 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
        username: '28224511:1379330808'
      },
      {
        url: 'turn:192.158.29.39:3478?transport=tcp',
        credential: 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
        username: '28224511:1379330808'
      },
      {
        url: 'turn:turn.bistri.com:80',
        credential: 'homeo',
        username: 'homeo'
      },
      {
        url: 'turn:turn.anyfirewall.com:443?transport=tcp',
        credential: 'webrtc',
        username: 'webrtc'
      }
    ]
  }
})
```

**Comment by biomousavi** [comment]
In Chrome, if you have two peers in a browser, you will get this error
so **each peer should be in a different browser(or incognito)**  :))))

**Comment by zhefciad** [comment]
I fixed it by automatically switching the initiator and reconnecting when the connection failed error shows up. Mine doesn't error most of the time, but there are times where some wifi networks are not compatible as initiator causing the error. Probably because of firewalls and stuff.

**Comment by Keanu2431** [comment]
@zhefciad Can you show me where you caught the error, my try catch block isn't picking it up

**Comment by zhefciad** [comment]
![image](https://github.com/feross/simple-peer/assets/90712250/5fb99b6d-64ac-4cf1-9c14-4c138bc89af8)

**Comment by zhefciad** [comment]
> @zhefciad Can you show me where you caught the error, my try catch block isn't picking it up
```
const handleIncomingCall = (data: any, retryCount = 0) => {
      // Check if the stream is ready
      if (!yourStream) {
        console.warn("Stream not ready yet. Retrying in 1 second...");
        setTimeout(() => handleIncomingCall(data), 1000);
        return;
      }

      console.log("Received call from", data.from);

      const peer = new Peer({
        initiator: false,
        trickle: false,
        stream: yourStream,
      });

      console.log("Peer connection being set up | non initiator");
      const callerSocketId = data.from; // Store the caller's socket ID

      peer.on("signal", (signalData) => {
        console.log(" non-initiator | Signaling data:", data);
        socket.current.emit("acceptCall", {
          signal: signalData,
          to: callerSocketId,
        });
      });

      peer.on("stream", (stream) => {
        console.log(" non-initiator | Received a remote stream");
        if (remoteVideoRef.current) {
          remoteVideoRef.current.srcObject = stream;
        }
      });

//DO IT ON THE PEER.ON("ERROR")

      peer.on("error", (err) => {
        console.log("Error occurred:", err);

        if (err.message === "Connection failed.") {
          socket.current.emit("connectionFailedToast", {
            roomId: roomId,
          });
          console.log("Connection failed. Reconnecting...");
          reconnectCleanup();
          socket.current.emit("otherUserDestroy", {
            roomId: roomId,
          });
        }
      });

      peer.signal(data.signal);
    };
```

**Comment by zhefciad** [comment]
> @zhefciad Can you show me where you caught the error, my try catch block isn't picking it up

Btw, my workaround is not consistent and is just a mess to work with. Sometimes both of the networks are just incompatible with each other making the reconnection useless.
