### ISSUE TITLE
receive stream not working

### ISSUE THREAD

**Issue by nullbro** [feross/simple-peer#733]
Peer is connected and `peer.on' ('data')` function is also executed normally.
It's got a `peer.on('stream')` function, and it's getting a stream, and I think it's getting a bug like this, so how do I fix it?

I tried to solve it, but I don't know how 😭

- **case1** desktop/chrome (initiator) => iphone/safari (ok)
- **case2** iphone/safari(initiator) => desktop/chrome(not working)..

|      | desktop/chrome |iphone/safari 
| ----------- | ----------- |----------- |
|   case1  | ![Imgur](https://i.imgur.com/lCS8e23.png#.X00ZsM9EBo8.link)   |![](https://i.imgur.com/xiimKdY.jpg#.X00ajt8xpYo.link)|
| case2|    ![Imgur](https://i.imgur.com/Kgn3Qlj.png#.X00aHNm02AY.link)    |![](https://i.imgur.com/wFhZswU.jpg#.X00ajt_-zvo.link)|

**Comment by nullbro** [comment]
Somehow it worked out.

**Comment by heykkyu** [comment]
Safari have same issue to me.
How did you fixed this?

**Comment by Karthikdb** [comment]
Yeah I to have this issue on safari
If the initiator:true in safari it is working fine 
if the initiator:false in safari its not working
