### ISSUE TITLE
Extra Bandwidth consumption issue

### ISSUE THREAD

**Issue by amoghh** [feross/simple-peer#735]
I noticed something wierd happening in my connection with 2 peers. Below are my media contraints
`  mediaConstraints: any = {
    video: {
      width: {
        min: 160,
        max: 320,
      },
      height: {
        min:120,
        max: 240,
      }
    },
    audio: true
  };`

So i manage the connection successfully between 2 peers and share their audio/video with each other. At this point when i m monitoring my netwrok its shows a downlink speed of avergae 40kbps on my 2nd device(peer).
Now i want disable video on my 1st Device(peer) so i do getVideoTracks for the stream and disable it. After doing this the downlink speed on my 2nd Device(peer) drops to about 8-10kbps which is appropriate.
Now i enable the video again on my first device by getting the video track and enabling it. After doing this the downlink speed on my 2nd Device(peer) goes up but only to 15-20 kbps and everything works fine the video audio on both the peers

why does it require more bandwidth initially and why after toggling the video track does the bandwidth required drop to almost 50% ?

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion.
