### ISSUE TITLE
react-native - No WebRTC support: Not a supported browser 

### ISSUE THREAD

**Issue by ahmetozalp** [feross/simple-peer#737]
Hello there,

I'm trying to make a peer connection with react native but I get a warning like this how can I skip it?

`[Error: No WebRTC support: Not a supported browser]`

**Comment by ahmetozalp** [comment]
fixed.

**Comment by kaissaroj** [comment]
@ahmetozalp did you resolve the WebRTC support problem  in react native??

**Comment by ahmetozalp** [comment]
Rn-hack use

**Comment by kaissaroj** [comment]
can you share the solution . I am also facing same problem

**Comment by nikita-zot-1408** [comment]
Any solutions?
