### ISSUE TITLE
Getting : Error: SessionDescription is NULL when calling peer.signal

### ISSUE THREAD

**Issue by amverma** [feross/simple-peer#74]
Hello
My basic requirement is to stream audio and video to a simple-peer running within node.js.
I have written following code for node.js app:
------
require('events').EventEmitter.prototype._maxListeners = 1000;
var WebSocketClient = require('websocket').client;
var wrtc = require('wrtc');
var client = new WebSocketClient();
var counter = 0;
var sdp;
var ice;

var peerConnectionConfig = null;
var SimplePeer = require('simple-peer');
var peerConnection = undefined;

client.on('connectFailed', function(error) {
	console.log('Connect Error: ' + error.toString());
});

client.on('connect', function(connection) {
	console.log('WebSocket Client Connected');

	connection.on('error', function(error) {
		console.log("Connection Error: " + error.toString());
	});
	connection.on('close', function() {
		console.log('echo-protocol Connection Closed');
	});

	connection.on('message', function(message) {

			if (peerConnection === undefined) {
				peerConnection = new SimplePeer({
					trickle: false,
					wrtc: wrtc
				});
				console.log('Created peer connection..');
			}
			console.log(' Started SimplePeer on node.. ');

			peerConnection.on('signal', function(data) {

				client.send(data);
				console.log(' sent sdp to server');

			});

			sdp = message.utf8Data;
			console.log("Received sdp: '" + sdp + "'");
			console.log(' Sending message to server: ');
			peerConnection.signal(JSON.parse(sdp));

	});

});

client.connect('ws://10.112.198.241:8080/webrtc');

---------------- 

And I get following error in node.js when I do : peerConnection.signal(JSON.parse(sdp));

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: SessionDescription is NULL.
    at Error (native)

Can you pls suggest where am I wrong or it it an issue with either wrtc module or simple peer.

Thanks in advance.

Amit Verma

**Comment by amverma** [comment]
I just realized my issues seems to be duplicate of #55.
I tried to print full stack trace using :
process.on('uncaughtException', function(err) {
  console.log("Stacktrace : "+err.stack);
  throw err;
});

But same error message.

Pls let me know if any other details needed.

**Comment by feross** [comment]
This is an issue with the `wrtc` library. See: https://github.com/js-platform/node-webrtc/issues/257

I would consider using `electron-webrtc` instead: https://www.npmjs.com/package/electron-webrtc
