### ISSUE TITLE
Only share “offer”, do not share “answer”

### ISSUE THREAD

**Issue by kovkev** [feross/simple-peer#740]
Hi folks!

I think this is an awesome library, thank you. I have to say, I don't understand WebRTC and STUN servers very well.

My question is. If the initiator A has an "offer", and shares it with user B, then should that be enough for B to send the answer through WebRTC to A, without having to share the "answer" back?

A visits page, browser shows "offer"
A sends "offer" to user B
B visits page, enters "offer" into page
B's browser sends a packet to A, through WebRTC, and the packet contains an "answer".

It seems to me like B has all the information needed to send some information to A?

Or, is there some question of certificates that A wants to make sure it is getting data from a trusted source?

Is there a way to remove the sharing of the "answer" step? Is there another library that does this?

Thank you!

kovkev

**Comment by nazar-pc** [comment]
Both offer and answer are critical pieces for both sides to have. It woudn't work if you don't send answer back. There is no way to skip it (just for 100% completeness actually there are some advanced capabilities that can give you that, but for very specific cases and those are not what you want in 99.9% of situations).
