### ISSUE TITLE
How this simple peer works internally

### ISSUE THREAD

**Issue by gnusiva** [feross/simple-peer#741]
Hi, I want to understand how simple peer works internally. Details like which stun server it uses? if the client is under restricted NAT, how this will work? is this using any Turn Server? Give me some document which explains the whole workflow.

**Comment by nazar-pc** [comment]
The source code is open and it is just one file. You can open it and see STUN servers.
As to work around NAT for that you need to learn what WebRTC is, simple-peer is just a convenient library on top of native browser API.
