### ISSUE TITLE
[react-native] Ice connection fail

### ISSUE THREAD

**Issue by zrg-team** [feross/simple-peer#742]
react-native: 0.63.2
react-native-webrtc: latest
simple-peer: ^9.7.2

OS: Android

```
this.peerInstance = new Peer({
      initiator: true,
      trickle: false,
      wrtc: {
        RTCPeerConnection,
        RTCSessionDescription,
        RTCIceCandidate
      }
    })

=> web version : generate answer

=> receive referenceConnectString from web
this.peerInstance.signal(JSON.parse(referenceConnectString))

```

it always response “Ice Connection Fail”

**Comment by TheSalarKhan** [comment]
I'm not sure if this will help but does wrtc have all the required fields? Works for me like:
```
{
    RTCPeerConnection,
    RTCIceCandidate,
    RTCSessionDescription,
    MediaStream,
    MediaStreamTrack
}
```

**Comment by feross** [comment]
If you search the issues, you'll see that others have had to add `adapter.js` in order to get full compatibility with `simple-peer`. This is because `react-native-webrtc` is using an out-of-date WebRTC API interface that is non-standard.
