### ISSUE TITLE
makeError function is not working in production build of electron js/vue app

### ISSUE THREAD

**Issue by junaid-A-khan** [feross/simple-peer#743]
**Scenario:**
- Peer 1 (Viewer using web app)
- Peer 2 (Broadcaster using electron app)

**Steps I followed:**

1. Create an app with [vue cli electron builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/)
2. Implement broadcaster logic in electron app.
3. Implement Viewer logic in web app.
4. Create a successful connection between peer 1 and peer 2.

When I generate build using `yarn electron:build or npm run electron:build` it runs vue cli service in modern mode i.e. `vue-cli-service build --modern` and after installing application I get the following issue:

When the webpage is reloaded after creating a successful connection. It throws `Cannot assign to read only property 'code' of object`

Image 1:
![image](https://user-images.githubusercontent.com/19288139/95730905-507f1480-0c98-11eb-873a-d5e0f5249442.png)

Image 2:
![image](https://user-images.githubusercontent.com/19288139/95731019-6d1b4c80-0c98-11eb-835e-3d2c49601b7d.png)

Image 3:
![image](https://user-images.githubusercontent.com/19288139/95731148-94721980-0c98-11eb-8773-50e6e610370b.png)

**Actual expected error:**
RTCError: Transport channel closed

Everything is fine in development build and it also works as expected when running/generating production build using legacy flag i.e. `yarn electron:build --legacy`.

**Comment by feross** [comment]
Fixed by https://github.com/feross/simple-peer/pull/686. Update your simple-peer
