### ISSUE TITLE
Uncaught Error: [object RTCErrorEvent]  at RTCDataChannel._channel.onerror (Chrome only error)

### ISSUE THREAD

**Issue by dev2919** [feross/simple-peer#747]
I made a p2p file share web app 2 months ago using simple-peer to establish the data channels and send huge files. I was using service workers to split them into array buffers. Since this week, Chrome has completely lost support for sending huge files constantly receiving this error.
```
 index.js:17 Uncaught Error: [object RTCErrorEvent]
    at makeError (index.js:17)
    at RTCDataChannel._channel.onerror
```
When checked on firefox, everything seems to be working. 

You can check out the code [here](https://github.com/veghfile/Frontend/blob/master/src/context/Maincontext.js) or pull the repo to reproduce this issue ( **Only happens on chrome browsers** )

**Comment by feross** [comment]
You need to chunk your large files up when you call `send`. There are many previous issues about this in the issue tracker.
