### ISSUE TITLE
A way to send buffer in a stream

### ISSUE THREAD

**Issue by vj-abishek** [feross/simple-peer#748]
At the sender end, I'm using a package known as `chunk-stream` to chunk the data. 

#### Sender
```js
 fileReaderStream(FileList).pipe(chunk(16000)).pipe(peer);
```
#### My question:
Is there any way to listen for `peer.on('stream')` and access the data at the receiver end?
I need to receive the data in a stream, is that possible?

I'm transferring files in this example, not video/audio.

**Comment by jarretttaylor** [comment]
@vj-abishek You likely want to send the files over a DataChannel. These two responses may help guide you to a solution.
#409 
#561

**Comment by vj-abishek** [comment]
@jarretttaylor Do you know any package which converts TypedArray into a stream. Im gonna use [streamSaver](https://www.npmjs.com/package/streamsaver), which needs stream as an input.

**Comment by jarretttaylor** [comment]
@vj-abishek Unfortunately, we are well outside of my area of expertise, so I am likely not of much help. That being said, you might look into [ReadableStream ](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream)and see if it could be of some use.

**Comment by vj-abishek** [comment]
Found a package which is used to share files.

### `Sender`
```js
import SimplePeerFiles from 'simple-peer-files'
const spf = new SimplePeerFiles()

function readyToSend () {
  // peer is the SimplePeer object connection to receiver
  spf.send(peer, 'myFileID', file).then(transfer => {
    transfer.on('progress', sentBytes => {
      console.log(sentBytes)
    })
    transfer.start()
  })
}
```

### `Reciever`
```js
import SimplePeerFiles from 'simple-peer-files'
const spf = new SimplePeerFiles()

// peer is the SimplePeer object connection to sender
spf.receive(peer, 'myFileID').then(transfer => {
  transfer.on('progress', sentBytes => {
    console.log(sentBytes)
  })

  transfer.on('done', (file) => {
     console.log(URL.createObjectURL(file))
  });
})
```

### `In Stream`
```js
spf.receive(peer, 'myFileID').then(transfer => {
 const fileStream = transfer.createReadStream()
// Do whatever you want with the stream
})
```
