### ISSUE TITLE
Audio streams don't always start in chrome

### ISSUE THREAD

**Issue by bnolan** [feross/simple-peer#75]
I'm using simple-peer to send audio streams (for positional audio in scenevr), but I'm having a case that about 70% of the time, if I don't have the javascript console open, the stream doesn't seem to have an audio in it, it's just silent. Sadly, if I run these tests with the console open, it seems to work 90% of the time. :(

Any ideas?

**Comment by contra** [comment]
Which version of chrome and what OS? Does the official WebRTC demo give you the same results?

**Comment by feross** [comment]
I'm closing this issue because it's been a while without a response from the issue opener. It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by bnolan** [comment]
Sorry I forgot about this issue. It's a chrome bug with webrtc and webaudio, nothing specific to simple-peer.
