### ISSUE TITLE
Communication issues

### ISSUE THREAD

**Issue by alfredo-baratta** [feross/simple-peer#750]
Hi all, I'm having a lot of communication problems using this library.
The problem that frequently (not always) arises is that when two people try to use my website (developed with Angular) to initiate a video call, the communication between the two peers fails. I can't really understand what the problem is having tried to consult a lot of online documentation about it. I release a part of the code on this gist:
https://gist.github.com/alfredo-baratta/f6cc995000375920028155be5fb3b89a
https://gist.github.com/alfredo-baratta/c984d653452aaa3ce872b48606fcb4da

Thanks in advance for any help!

P.S: If you want to try to run into this problem, the website link is https://musicmeet.it/

**Comment by feross** [comment]
Sorry for the issue you're facing. Unfortunately, this is not a support forum so I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
