### ISSUE TITLE
Server side example

### ISSUE THREAD

**Issue by GabrieleCicconetti** [feross/simple-peer#752]
Is it possible to have a server side example? (or a reference to an example?), i'm going crazy. I know that this is not an issue but i don't know where to ask and i cannot find anything about this "signaling server", sorry.

**Comment by jarretttaylor** [comment]
@GabrieleCicconetti  Check out [simple-signal](https://github.com/t-mullen/simple-signal) and see if that provides what you are looking for.

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
