### ISSUE TITLE
Detect write progress from sender ??

### ISSUE THREAD

**Issue by ccornen** [feross/simple-peer#755]
Hello,
thanks a lot for this very helpful library.
I'm wondering if there is a way to detect when the "write" function actually send the buffer to the receiver ?.
It make sense to detect this sending progress from sender instead of emitting an ACK from the receiver.
Thanks for your feedback.

Edit:
After checking your implementation, I found a "cb" optional parameter to the _write function, can you please confirm this call occurs when buffer is send ?

**Comment by feross** [comment]
`cb` is called once the data has been given to the data channel. As for when this data has actually gone over the wire, I think that's hard to determine since there's so many layers at work here -- data channel API, SCTP, DTLS, TCP, etc.
