### ISSUE TITLE
Cannot connect with example (feat. weird uuid hostname)

### ISSUE THREAD

**Issue by nolash** [feross/simple-peer#758]
I have tried the example browser code with current master 36d9665163b40fba6cd983fa7c12346ffe448c23 aswell as tag 9.8.0 and 9.7.2. The connection cannot be made.

Looking at the offer being produced, the only candidate is a hostname which looks like an embellished uuid:

```
v=0
o=- 6181610274092370810 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=candidate:1670720485 1 udp 2113937151 44eb5b8c-a27e-48c3-a59b-31d1ace229eb.local 54729 typ host generation 0 network-cost 999
a=ice-ufrag:Dl3W
a=ice-pwd:y4NnJLJlIf4SV8Dvy6JWwQqK
a=fingerprint:sha-256 AB:0E:C2:11:DE:91:0A:EC:A2:C3:E0:2E:35:90:5E:1C:6A:98:57:72:F7:70:64:17:8D:04:7C:26:A3:E8:61:3C
a=setup:actpass
a=mid:0
a=sctp-port:5000
a=max-message-size:262144
```

Without a STUN server, I was expecting my local ips to be offered up as candidates. I am totally new to WebRTC, but if I was to take a guess, the reason why the connection is failing is because of this weird hostname.

How can I get the backend to generate an ipv4 candidate in the sdp?

**Comment by nazar-pc** [comment]
This is expected and called mDNS, used specifically to prevent leaking of local IP addresses in WebRTC.
