### ISSUE TITLE
"stream" event not firing

### ISSUE THREAD

**Issue by Ponjimon** [feross/simple-peer#759]
Ref #724 

I made an example repo: https://github.com/Ponjimon/simple-peer-error

Steps to reproduce:

1. Create `.env` file with the content below
2. Run `yarn install`
3. Run `yarn start ui` and `yarn start server` parallely
4. Open two tabs `http://localhost:4200`
5. Click the `Connect` button in one tab, then shortly after in the second.
6. In the tab where you clicked `Connect` first, it will show the remote stream, in the other it won't

You can enable debug logs by doing `localStorage.debug = 'app*'`

`.env` content:
```
SERVER_URL=http://localhost:3333
```

**Comment by feross** [comment]
Are you assuming that `signal` is only fired once?

**Comment by Ponjimon** [comment]
What do you mean? I'm sending it to the signaling server every time it fires

**Comment by feross** [comment]
>I'm sending it to the signaling server every time it fires

That sounds right.

**Comment by Ponjimon** [comment]
So, what am I doing wrong? Or, how can I debug this to find it out?

**Comment by innocenzi** [comment]
Just got that issue when trying to implement video streaming. I can connect peers, they can send data to each other. I use `addStream` at some point when the connection is already done, but the `stream` event never fire.

**Comment by innocenzi** [comment]
Update: it works properly and I receive the stream when I use the `stream` key directly when instantiating `new Peer`.

**Comment by Ponjimon** [comment]
@innocenzi On both clients? Because that's exactly the issue here that it only fires it on one side

**Comment by vj-abishek** [comment]
I also have a similar issue https://github.com/feross/simple-peer/issues/703#issuecomment-719321983 

For me, the peers are connected, can able to send data. Only getting an error when I add the stream later.

But it is working as excepted when the peer is initialized with a stream.

**Comment by Ponjimon** [comment]
Hm, seems like I needed to add the stream to BOTH peers, initiator or not in the constructor of Peer.

**Comment by Mihai-github** [comment]
any updates? So the issue is that when adding a stream both peers have to emit it right?

**Comment by jdpartin** [comment]
How can you add the stream in the constructor of both peers if you need the peers to be connected before you can send the stream
