### ISSUE TITLE
DIsconnection happens frequently

### ISSUE THREAD

**Issue by Steelze** [feross/simple-peer#760]
Hello guys, I've implemented this library on a project which is currently live but I've noticed there are frequent disconnection even on stable networks. I've added a reconnection script in the on error event but that doesn't seem to help. Any thoughts about this?

**Comment by feross** [comment]
This is how WebRTC works. You can try ICE renegotiation – see https://github.com/feross/simple-peer/issues/756 for our progress on building in support for it here. But disconnects happening is a network issue – likely nothing to do with simple-peer.

**Comment by feross** [comment]
Sorry – just fixed a typo in my comment. Meant to say "ice restarts" not "ice renegotiation".
