### ISSUE TITLE
destroy method not working

### ISSUE THREAD

**Issue by tebaly** [feross/simple-peer#764]
Hello.
```
console.log("peer destroyed");
peer.removeAllListeners("signal");
peer.destroy();
```
This does not work. The event from is triggered after "destruction". Even when it's a different page in the app. He continues to listen to the "signal" and gives an error.

```
peer destroyed
Error: cannot signal after peer is destroyed
```

**Comment by c4b4d4** [comment]
@tebaly Did you find out what was happening? I'm experiencing the same thing

**Comment by tebaly** [comment]
It was a long time ago I don't remember what I did
