### ISSUE TITLE
Provide ability to initiate signal after class instantiation

### ISSUE THREAD

**Issue by jahtalab** [feross/simple-peer#765]
**What version of this package are you using?**
9.9.3
**What problem do you want to solve?**
Currently the only way to initiate signal is by passing `initiator: true` to the constructor. However, in some cases it's desirable to create a generic instance of SimplePeer (with the default event listeners) and initiate the signal later on.

**What do you think is the correct solution to this problem?**
Provide a method on SimplePeer, such as `SimplePeer.initiate()`

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by feross** [comment]
> However, in some cases it's desirable to create a generic instance of SimplePeer

What are you trying to accomplish? Is it possible to wait to create the `simple-peer` instance until you're ready to connect?

**Comment by jahtalab** [comment]
Thanks for the reply @feross. 

What I'm trying to achieve is already possible with the current version (I already have implemented it), however, IMHO the proposed API in this issue is a better solution. The problem is partly exposed by the documentation which mentions `Be sure to listen to this event (signal) immediately to avoid missing it. For initiator: true peers, it fires right away.`. Having the ability to create the instance and initiate the signal separately would resolve this.

Although, I do understand wanting to keep it similar to the `net` package.
