### ISSUE TITLE
Not working on different network

### ISSUE THREAD

**Issue by shigristudy** [feross/simple-peer#770]
I have implement simple peer and on localhost and on same network both sre working fine... When i try to connect from one network to another network it showing error connection failed... 

If anyone have figure out the solution then please help...

**Comment by jarretttaylor** [comment]
You likely need a [TURN ](https://github.com/feross/simple-peer#connection-does-not-work-on-some-networks)server.

**Comment by shigristudy** [comment]
I have added free stun and turn server both... Is there any website from where i can get stun and turn server??? 
Or i have to configure stun and turn on my server using coturn???

**Comment by nazar-pc** [comment]
This question was asked here many times already, please do a bit of research yourself.

It is very unlikely that you have added a working and free TURN server, they are usually paid.
