### ISSUE TITLE
How to get stats

### ISSUE THREAD

**Issue by t104360088** [feross/simple-peer#795]
Hi, could you make a sample about getStats?
I need to get some information, but I do not know how to do it
This is my code and report's value is null, Does anyone can help me?

```
setInterval(() => {
    peer.getStats((report) => {
        console.log('report', report)
    });
}, 1000);
```

**Comment by wbobeirne** [comment]
`getStats`'s callback is an "errback", meaning the first arg is if there was an error. Changing your code to:
```js
peer.getStats((err, report) => {
  console.log('report', report)
});
```
should get you what you want

**Comment by t104360088** [comment]
Oh, thank you so much, this helped me solve the problem.
