### ISSUE TITLE
Connection failed when connecting outside of the local network

### ISSUE THREAD

**Issue by ivomirtolev** [feross/simple-peer#797]
Hi all,

I'm developing a Video Conferencing app with Angular , Simple-Peer(9.9.3) and signalR. The app is deployed and works fine on local networks. When a user tries to connect to a peer on a different network, the following error is returned:

Uncaught Error: Connection failed.     at c._onConnectionStateChange (scripts.js:1)     at RTCPeerConnection._pc.onconnectionstatechange (scripts.js:1)

When i go to webrtc-internals i see that my iceServers config is ignored and it uses the default 2 stun servers :
({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:global.stun.twilio.com:3478?transport=udp' }] }) 
instead of the servers that i've setted. 

This is my peer object configuration: 

const peer = new SimplePeer({
      initiator: isInitiator,
      trickle: true,
      stream,
      config: {
        iceServers: [
          { urls: "stun:numb.viagenie.ca:3478" },
          {
            urls: "turn:numb.viagenie.ca:3478",
            username: <username>,
            credential:<pass>,
          },
        ],
      },
    });

Both servers are tested in Trickle-Ice and they seem to work fine , returning host ,srflx and relay candidates.
Any suggestions ?

**Comment by jarretttaylor** [comment]
@ivomirtolev In your example configuration, the **stream** property doesn't have a value. Was this just overzealous cleanup when you were removing other sensitive information (e.g. username & password) or does your configuration not pass a value for stream?

const peer = new SimplePeer({
initiator: isInitiator,
trickle: true,
**stream,**
config: {
iceServers: [
{ urls: "stun:numb.viagenie.ca:3478" },
{
urls: "turn:numb.viagenie.ca:3478",
username: ,
credential:,
},
],
},
});

**Comment by ivomirtolev** [comment]
@jarretttaylor thanks for the quick response, the peer object is wrapped in a function which has the stream as a parameter so i'm getting the value from there. The application works fine without any problems when i connect two machines on a same network, audio and video streams are correctly generated. The problem occurs when trying to connect users on different networks.

**Comment by Dealerpriest** [comment]
You probably need a TURN server if the peers are on symmetrical NAT networks.

**Comment by ivomirtolev** [comment]
@Dealerpriest I've tried with several TURN servers, i've also configured my own one, i think that the problem is that for some reason i can't override the default iceServers property, when i try to establish a connection, i see in chrome://webrtc-internals/ that the app is using the default two STUN servers (not the servers that i've setted in the config prop) and no TURN server.

**Comment by jarretttaylor** [comment]
@ivomirtolev simple-peer's user of the supplied configuration is minimal and is worth reviewing.

The default configuration is defined [here](https://github.com/feross/simple-peer/blob/9ea1805d992a8164a42b750160ed3425f2a494f1/index.js#L1038).

The configuration is initialized [here](https://github.com/feross/simple-peer/blob/9ea1805d992a8164a42b750160ed3425f2a494f1/index.js#L46).

Finally, the configuration is passed to the constructor of the underlying [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection) implementation (the web browser's in your case) [here](https://github.com/feross/simple-peer/blob/9ea1805d992a8164a42b750160ed3425f2a494f1/index.js#L101).

From reviewing that code, it is unclear to me why your configuration would seem to not be utilized.

**Comment by ivomirtolev** [comment]
@jarretttaylor  It seems to be a deployment problem, i've cloned the project in 2 different machines using different networks and it works fine. After deployment we don't get the correct config so we will look there. Thanks for the help, i'm closing the issue.
