### ISSUE TITLE
When is the 'ready' event fired?

### ISSUE THREAD

**Issue by jatins** [feross/simple-peer#8]
I create two `Peer` objects in the same browser window and tried to send message from one to other. The code is almost same as that given in `simple-peer` readme:

```js
var Peer = require('simple-peer');
var peer1 = new Peer({ initiator: true })
var peer2 = new Peer();

peer1.on('signal', function (data) {
  // when peer1 has signaling data, give it to peer2
  console.log('peer1 on signal')
  peer2.signal(data)
})

peer2.on('signal', function (data) {
  // same as above, but in reverse
  console.log('peer2 on signal')
  peer1.signal(data)
})

peer1.on('ready', function () {
  // wait for 'ready' event before using the data channel
  console.log('peer1 ready');                         
  peer1.send('hey peer2, how is it going?')
})

peer2.on('message', function (data) {
  // got a data channel message
  console.log('got a message from peer1: ' + data)   
})
```

I get these logs:
```
peer1 on signal
peer2 on signal
peer1 on signal
peer2 on signal
peer1 on signal
peer2 on signal
```

The `ready` event never seems to fired, and no message gets sent.

**Comment by jatins** [comment]
I tried looking at `about:webrtc` in Firefox. Not sure what to interpret from it. 
You can see the logs here: https://paste.ee/r/aISjr .

**Comment by feross** [comment]
Are you connected to a VPN or proxy?

**Comment by jatins** [comment]
Nope.

**Comment by jatins** [comment]
I tried it on a different machine and it works. So, it is probably due to some network settings on my laptop (it's my work laptop, and the company makes some configurations before giving it to employees, so because of that maybe?). 

Any idea where I should look into for specific settings, or how to get it working on my machine?

**Comment by feross** [comment]
WebRTC uses UDP, so I would check or ask if that is blocked. It selects a random port each time, and there's no way to get it to use a specific port. Spec mandates this for security reasons.

**Comment by feross** [comment]
We can continue to debug in this issue, but I'm going to close it since it's not an issue with this module.
