### ISSUE TITLE
stream only works from initiator 

### ISSUE THREAD

**Issue by m0ose** [feross/simple-peer#80]
I was playing with the stream example, and it seems that the initiator must have a stream or it doesn't work for either side. For example ...
```   
var peer1 = new SimplePeer({ initiator: true });
var peer2 = new SimplePeer({ stream: stream }); 
peer1.on('stream', function (stream) {
    // got remote video stream, now let's show it in a video tag
    var video = document.querySelector('video')
    video.src = window.URL.createObjectURL(stream)
    video.play()
  })
```
... does not work

But, 
 ```   
var peer1 = new SimplePeer({ initiator: true, stream: stream });
var peer2 = new SimplePeer({ stream: stream });
...
```
works fine

**Comment by contra** [comment]
@m0ose What browser?

**Comment by m0ose** [comment]
I am using chrome 51.

**Comment by feross** [comment]
@m0ose Have you tried the case where neither peer has a stream? What happens then?

**Comment by feross** [comment]
Closing due to lack of response. If this is still an issue for you, please leave a comment with additional info.
