### ISSUE TITLE
`signal` event does not fire in Safari 14.1 for macOS

### ISSUE THREAD

**Issue by a-dpq** [feross/simple-peer#808]
I think there may be a bug with the latest version of Safari for macOS (Version 14.1 – 16611.1.21.161.6). Recently, after upgrading macOS, I noticed my Simple Peer connections are getting stuck on `iceStateChange (connection: checking) (gathering: gathering)`. The `signal` event only fires once on both peers, and the connection is not established, although the stream comes through (but doesn't play). This only happens in the latest version of Safari for macOS, as far as I can tell. Safari for iOS as well as other desktop browsers still work as expected. Can anyone else replicate this behavior?

**Comment by a-dpq** [comment]
More information on the latest Safari release, which included a security fix for WebRTC: [https://support.apple.com/en-us/HT212318](https://support.apple.com/en-us/HT212318)

**Comment by a-dpq** [comment]
I've been able to replicate this issue with the first example from the Simple Peer readme. The `signal` event does not fire in Safari 14.1 for macOS, but it does in Chrome 90.0.4430.93 and in Firefox 88.0.1.

**Comment by jzombie** [comment]
I've done a lot of debugging with Safari 14 in my fork and it seems to be really stable w/ Safari 14 on both Mac and iOS:  https://github.com/zenOSmosis/webrtc-peer

It's not published on npm but you can install it like:

```bash
$ npm install github:zenosmosis/webrtc-peer
```

Then update your import / require to "webrtc-peer"

**Comment by jzombie** [comment]
Assuming it works, could open a PR, sure.

**Comment by jzombie** [comment]
If you get a chance to try it, let me know if it works for you.

**Comment by a-dpq** [comment]
I don't see the client library (simplepeer.min.js from this repository) in your fork. But if you try the first example in the readme with Safari 14.1 and the signal event fires on both ends, then you've likely solved the issue.

**Comment by a-dpq** [comment]
I'm surprised that this issue isn't getting more attention. Simple Peer appears to be broken in the latest version of Safari for macOS.

**Comment by jzombie** [comment]
This repository seems to be in a maintenance mode and is not really maintained, judging from the stacked up issues and pull requests, hence why I started my own fork.

I'll add the built version to my own fork as I'm pretty sure it works... haven't had any issues w/ latest Safari.

I don't foresee them merging it in, however, as the changes are somewhat significant due to having also added webrtc-adapter repository as well, and I think that itself irons a lot of issues out.

Apologies, however, am feeling a bit of burnout at the moment, and don't have the built version tested and ready.  I feel someone should fork this repo and make a separate "official" implementation as this repo, with all due respect, is more or less, "dead."

**Comment by feross** [comment]
This repository is maintained – but we're all volunteers.

@jzombie You point people to your own repo while also saying that you feel "burnt out and won't be able to merge in people's changes". Do you see the irony of this? How do you think comments like "this repo is dead" affect the burnout of me and the other maintainers who are under a huge load of issues and PRs?

This is open source – you're not entitled to free support, guaranteed bug fixes, or anything at all really.

With all that said, we'd love to get this issue fixed, and I would happily review a PR that fixes the problem. :)

**Comment by a-dpq** [comment]
@feross thanks for maintaining this repository! I just tested this issue again, and Simple Peer is now working for me in Safari 14.1. I don't know what was causing this problem for me before, but I'll close this issue.

**Comment by feross** [comment]
That's great to hear. There has been a new macOS Big Sur (11.13.1) and iOS release (14.5.1) release since Safari 14.1 was released, so perhaps this bug was fixed as part of that release?

**Comment by a-dpq** [comment]
It looks like those versions haven't changed on my system since I first noticed this issue, so it may have been due to some other factor.
