### ISSUE TITLE
Can i send a stream other then video & voice?

### ISSUE THREAD

**Issue by jimmywarting** [feross/simple-peer#81]
Chrome v52 brings ReadableStream constructor to the table. It would be cool if it would be possible to send a blob/file as a readableStream. I have written a [blob stream reader](https://github.com/jimmywarting/blob2web-stream) recently. And now i want to send it over webrtc. (from browser to the server - using [electron-webrtc](https://github.com/mappum/electron-webrtc))

There is also this alternative [blob reader](https://www.npmjs.com/package/readable-blob-stream) but it uses node's stream

```javascript
var blobStream = new ReadableStream({...}); // read blob as chunks
var peer2 = new SimplePeer({ stream: blobStream })
```

**Comment by contra** [comment]
Have you tried sending the chunks over an RTC data stream?

**Comment by jimmywarting** [comment]
@contra no, i haven't tried that yet, not sure how i would handle back pressure & queuing. 

I want to have the RTC data stream more as a communication layer and be able to send a blob in a separate stream that can handle backpressure and is also send it in order. 
I think the blobStream should also close when the file has sent everything.

**Comment by contra** [comment]
@jimmywarting simple-peer exposes data channels as a duplex stream so it should handle your case (back pressure). You can open as many data channels as you want, one for files and one for communication.

**Comment by contra** [comment]
On second look the API for creating multiple data channels seems a little tricky to use.

@feross How do you feel about making multiple data channels part of the API?

**Comment by feross** [comment]
@jimmywarting The `stream` option is for media streams, like from a microphone or webcam. What you want is the data channel. As @contra said, `simple-peer` instances are node.js style duplex streams, so you should not pass a `stream` option.

@contra I'm open to supporting multiple data channels as part of the API if we can do it in a backwards-compatible way. There was discussion about this before in #19.
