### ISSUE TITLE
memory usage questions around peer.send(buf)

### ISSUE THREAD

**Issue by mreinstein** [feross/simple-peer#88]
Let's say I want to send some data over a peer:

```javascript

let buf = new Uint8Array(1024);

// buf gets filled up with uint8 values here

peer.send(buf);
```
I'm wondering how is `buf` handled. For example, right after I call `.send(buf)`, can I re-use `buf` and start filling it with more data? Or maybe it's unsafe to do this, as the datachannel might still be sending this, which overwrites the data before it goes over the wire?

Restated, I'm not sure if webrtc internally copies this data to it's own memory or if it's being read directly.

I'm building an app that will send a *lot* of this data per second in a pretty tight loop so I'm trying to prevent crazy gc churn and keep the memory pressure to a minimum. Any insights would be much appreciated. Would be happy to add these useful bits to the readme as well.

**Comment by zetxx** [comment]
https://github.com/feross/simple-peer/blob/master/index.js#L221
https://github.com/feross/simple-peer/blob/master/index.js#L296
i think it is not save to use approach that you mention.

**Comment by mreinstein** [comment]
> i think it is not save to use approach that you mention.

I don't have an approach. I want to understand how the array passed to simple-peer/ the underlying data channel is used so I can come up with a memory efficient way to transfer bytes to peers.

**Comment by contra** [comment]
@mreinstein I think after you pass something to `.send()` (which passes to `.write()`) you can start mutating the reference (loading in new bytes)

**Comment by xuset** [comment]
Looking at the spec, I can't find anything on how the user's buffer is handled. It seems to me that this is grey area that is implementation specific.

https://www.w3.org/TR/webrtc/#dfn-send
https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.6

**Comment by zetxx** [comment]
> I don't have an approach
i meant that its better to be sure what is sent over the wire .. so better don't overwrite byte chunk .. just in case .

**Comment by feross** [comment]
If you call `peer.send(buf)` you can be sure that `simple-peer` is not keeping a reference to `buf` and sending the buffer at some later point in time. We immediately call `channel.send()` on the data channel. So it should be fine to mutate the buffer right afterward.

However, beware that `peer.write(buf)` (a writable stream method) does not have the same contract. It will potentially buffer the data and call `channel.send()` at a future point in time, so definitely don't assume it's safe to mutate the buffer.

**Comment by mreinstein** [comment]
@feross that's really valuable information, thanks! This should probably go into the readme. If you'd like I can send a PR.

**Comment by feross** [comment]
@mreinstein Sure -- if you think it's valuable please send a PR. Happy to merge it!

**Comment by mreinstein** [comment]
I think it's probably valuable for people writing javascript that has to be particularly careful about mem pressure/gc churn in a tight loop (games, simulations, etc.) 

PR forthcoming...

**Comment by feross** [comment]
@mreinstein Cheers :)
