### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by MiGu3X** [feross/simple-peer#91]
So I want to make a p2p real-time chat like hangouts but I can't, even though documentation is great, i can't get it to work since it's difficult to understand correctly how peers work with this model.

Maybe if someone could make an example it'd be great since I couldn't find anyone on the internet (by example I mean an example that can be run from different computers and not creating peers directly on the same window object)

**Comment by feross** [comment]
I would read about how WebRTC works and ensure you understand the part about signaling: https://www.html5rocks.com/en/tutorials/webrtc/basics/

Sorry, this isn't an issue with `simple-peer` so I'm going to have to close this. Feel free to continue discussion in this issue.
