### ISSUE TITLE
Fixing addStream() deprecation

### ISSUE THREAD

**Issue by abelRoland** [feross/simple-peer#912]
**What version of this package are you using?**
9.11.1
**What problem do you want to solve?**
I am having some 'Connection Failed' issues.

**What do you think is the correct solution to this problem?**
I believe that what can cause this problem is that the addStream() method is deprecated. The method is present here:

https://github.com/feross/simple-peer/blob/f1a492d1999ce727fa87193ebdea20ac89c1fc6d/index.js#L152

The deprecation is on the documentation of Mozilla.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream

**Are you willing to submit a pull request to implement this change?**

I could try to do it, but should be assisted with it.

**Comment by jzombie** [comment]
It's not calling addStream directly on the peer connection.

https://github.com/feross/simple-peer/blob/f1a492d1999ce727fa87193ebdea20ac89c1fc6d/index.js#L281-L289

**Comment by abelRoland** [comment]
Thanks @jzombie , I haven't seen that.

So I believe that what I am experiencing is more a bug with specific browsers. I will gather more information and create another issue if needed here.

For now I believe that this conversation is done, so closing the issue.

Thanks

**Comment by NisargDeveloper** [comment]
Hey what is the resolution for this issue. How to overcome this issue in simple peer library. I'm trying to implement addStream. it seems it is deprecated.
