### ISSUE TITLE
Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11

### ISSUE THREAD

**Issue by gateremark** [feross/simple-peer#925]
**What version of this package are you using?**
Version 9.11.1

**What operating system, Node.js, and npm version?**
Using Linux (Ubuntu), pnpm package manager

**What happened?**
I am using the Chrome browser and on clicking 'Call' button on my web app, I get the error logged on the Chrome browser console.

![Screenshot from 2023-12-29 21-05-53](https://github.com/feross/simple-peer/assets/91592218/53e5c5c5-6c7f-4d2b-a742-80fe222cb46b)

```javascript
<button
    className="bg-[#ffffff] text-[#000000] p-2 m-2 rounded-md"
// Options.jsx:47 (Line below)
    onClick={() => callUser(idToCall)}
>
    Call
</button>
```

```javascript
    const callUser = (id) => {
        if (!stream) {
            console.log("Stream is undefined");
            return;
        }
// SocketContext.jsx:67 (Line below)
        const peer = new Peer({ initiator: true, trickle: false, stream });

        peer.on("signal", (data) => {
            socket.emit("callUser", {
                userToCall: id,
                signalData: data,
                from: me,
                name,
            });
        });

        peer.on("stream", (currentStream) => {
            if (userVideo.current) {
                userVideo.current.srcObject = currentStream;
            }
        });

        socket.on("callAccepted", (signal) => {
            setCallAccepted(true);

            peer.signal(signal);
        });

        connectionRef.current = peer;
    };
```

**Comment by AleemIlyas** [comment]
Did you found the solution ?

**Comment by AleemIlyas** [comment]
I found the solution of this you need to make a samll change in randombyte you need to change 

**const crypto = crypto || msCrypto**

with 

**const _global = typeof globalThis !== 'undefined' ? globalThis : global
const crypto = _global.crypto || _global.msCrypto**

This issue is fixed in randombyte repository but package is still not updated

**Comment by gateremark** [comment]
Awesome, lemme check it out
