### ISSUE TITLE
Support renegotiate when adding new media stream

### ISSUE THREAD

**Issue by boblund** [feross/simple-peer#926]
simple-peer 9.11.1

I dynamically add a media stream on a existing connection from p1 to p2. Now I have voice/video from p1 to p2. I want to add voice/video tracks from p2 to p1. When I try this on p2 with addStream or addTrack on the existing connection the corresponding 'stream' or 'track' events never occur on p1 and my signaling server connection on p1 gets a renegotiate message. However, I don't see any API in the documentation for acting on the renegotiate message. Could this be added?

This is needed as my app provides texting, file transfer and voice/video connections. The majority of use cases don't involve voice/video so I'd like not to have to create the voice/video tracks on app startup but rather add them when needed on the existing connection.

I would if I knew how to implement. I would be happy with any work-around short of re-establishing the initial connection.

**Comment by boblund** [comment]
I see in the code that there is a renegotiate method that causes a new offer/answer exchange so my use case is supported.

**Comment by lherman-cs** [comment]
@boblund in case you're looking for a better alternative, I'm building https://github.com/PulseBeamDev/pulsebeam-js which provides automatic renegotiation, reconnection, typescript, auth, and many others. My discord username is lherman_cs if you'd like to just chat about general WebRTC, happy to help!

**Comment by boblund** [comment]
Thanks for the link. I found that simple-peer supports renegotiate and addTransceiver in the code; just not documented as far as I can tell. This seems sufficient for dynamically adding and removing media streams.
