### ISSUE TITLE
Peer is suddenly close in mobile browser chrome/mozilla in android

### ISSUE THREAD

**Issue by techleadzdevteam** [feross/simple-peer#93]
I am using simplepeer.js with pusher api and I have developed an audio/video calling system but there is a problem that it is not working on the mobile browser chrome/firefox in android.

I have tested my system on Mozilla and chrome on laptop ,it is working fine on both but on the mobile when I call the person ,peer stream starts and then it close suddenly.

In Mozilla it also shows this error

ICE FAILED see webrtc:about

Kindly help me about this issue?

**Comment by feross** [comment]
Try specifying a TURN server to hole punch through NATs.

**Comment by techleadzdevteam** [comment]
Thanks for your reply .I have specified the google turn server in the configuration 
 var peer = new SimplePeer({ initiator: initiator, stream: currentUser.stream, trickle: false,config: { iceServers: [ { url: 'stun:stun.1.google.com:193021' } ] }  });

but still the the peer connect and after less then 5 seconds it close and the connection drops.
I am using wifi internet for testing on the mobile browsers .
I am using just mobile devices for this purpose no desktop system.
There is no firewall or proxy on the network but still the issue is same any idea?

**Comment by techleadzdevteam** [comment]
I have also tried this second configuration 

var ICE_config= {
	  'iceServers': [
		{
		  'url': 'stun:stun.l.google.com:19302'
		},
		{
		  'url': 'turn:192.158.29.39:3478?transport=udp',
		  'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
		  'username': '28224511:1379330808'
		},
		{
		  'url': 'turn:192.158.29.39:3478?transport=tcp',
		  'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
		  'username': '28224511:1379330808'
		}
	  ]
	}
      var peer = new SimplePeer({ initiator: initiator, stream: currentUser.stream, trickle: false,config:ICE_config });

but still no luck??

**Comment by techleadzdevteam** [comment]
Thanks Feross for your reply.I really appreciate your help.
I got a free turn server from a website(bit6) and use it in the system.
My code is as below

var ICE_config= {
	  'iceServers': [
		{
		  'url': 'stun:turn.bit6.com'
		},
		{
		  'url': 'turn:turn.bit6.com:3478?transport=udp',
		  'credential': 'xoMmQhdiQTJ0Yv1LoiYErxI1JBw=',
		  'username': '1476466484:5c93d210f7c19076@2bll1'
		},
		{
			'url': 'turn:turn.bit6.com:443?transport=tcp',
			'credential': 'xoMmQhdiQTJ0Yv1LoiYErxI1JBw=',
			'username': '1476466484:5c93d210f7c19076@2bll1'
		}
	  ]
	}
      var peer = new SimplePeer({ initiator: initiator, stream: currentUser.stream, trickle: false,config:ICE_config });

-I am using wifi network .
-When i connect all the devices with the same network everything works fine .
-But when Devices join different network this error again occurs
ICE failed, see about:webrtc for more details

This is the image link for ICE stats 
https://snag.gy/8sLEu3.jpg

Kindly help me in this issue .
Thanks.

**Comment by feross** [comment]
Sometimes even a TURN server can't help you connect. I'm not an expert in how this stuff works, tbh. I would do research or if you think this is a bug in Firefox, file a bug.
