### ISSUE TITLE
Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER

### ISSUE THREAD

**Issue by yasirrose** [feross/simple-peer#94]
hey there,

I have implemented simple-peer.js with pusher for audio/video chat process. It works fine for first time when two users starts audio/video conversation but when i try to call again to same user, it will connected to that peer but when on.signal() event trigger it generate above error.

Can you help me with this issue? If you need to look into script that i have implemented i will send it to your email address? 

thanks,

**Comment by feross** [comment]
You need to create a new simple-peer instance for each connection. You can't reuse the same `peer` object for a new connection.

**Comment by yasirrose** [comment]
Thanks for reply. My script is creating new instance of simple-peer when any user try to start audio/video chat. May be the issue is in the closing section of call. I have properly destroyed the peer while user ends the call on button click event. i didn't figure it out yet what else causing the issue. 

Can you tell me what is the better way to close or trigger the peer.on('close') event or any other way to close that call so when user try to make another call it works fine?

**Comment by yasirrose** [comment]
@feross Thanks for reply. My script is creating new instance of simple-peer when any user try to start audio/video chat. May be the issue is in the closing section of call. I have properly destroyed the peer while user ends the call on button click event. i didn't figure it out yet what else causing the issue.

Can you tell me what is the better way to close or trigger the peer.on('close') event or any other way to close that call so when user try to make another call it works fine?

**Comment by feross** [comment]
Calling `peer.destroy()` is enough to fully destroy the peer connection. If you're getting an error about "Called in wrong state", then you're probably re-using a destroyed or already connected peer object by accident.
