### ISSUE TITLE
stream not added if initiator set to false

### ISSUE THREAD

**Issue by dukelec** [feross/simple-peer#95]
Change the video/voice example code from:

```
  var peer1 = new SimplePeer({ initiator: true, stream: stream })
  var peer2 = new SimplePeer({ initiator: false })
```

to:

```
  var peer1 = new SimplePeer({ initiator: false, stream: stream })
  var peer2 = new SimplePeer({ initiator: true })
```

the stream callback never called.

**Comment by techleadzdevteam** [comment]
Hi,
Hope that you will be good.Can you please help me regarding the issue #96

I will be very thankfull to you.

Thanks

**Comment by RationalCoding** [comment]
There's an issue in Chrome with `pc.onaddstream` not firing when the the non-initiator is the one providing the only stream.

The workaround is to specify the offer and answer constraints.

The initiator should offer to receive.  
`new SimplePeer({initiator : true, offerConstraints:{ mandatory: { OfferToReceiveAudio: true, OfferToReceiveVideo: true } }})`

The non-initiator should not offer to receive.  
`new SimplePeer({initiator : false, stream:webcamStream, trickle:false, answerConstraints:{ mandatory: { OfferToReceiveAudio: false, OfferToReceiveVideo: false } }});`

You have to use Chrome's constraint format here, the specs one won't work.

**Comment by RationalCoding** [comment]
There's an open bug with `pc.onaddstream` not firing in Chrome.

https://groups.google.com/forum/#!topic/mozilla.dev.media/BqklQQIXx9w

This forum suggests a workaround with `pc.getRemoteStreams()[0]`, but I haven't been able to get it working.

**Comment by feross** [comment]
@RationalCoding Do you have a link to a Chrome bug? Should this workaround only be applied for Chrome? Any interest in sending a PR to add this workaround to `simple-peer`?

**Comment by RationalCoding** [comment]
[Here's the forum discussing the bug.](https://groups.google.com/forum/#!topic/mozilla.dev.media/BqklQQIXx9w) 

I seem to have lost the forum that provided the workaround, but it definitely solved the issue for me.

The workaround needs to be applied for Chrome, but specifying the constraints shouldn't affect the behaviour of other browsers.

I'm not sure if this can be added to `simple-peer`, since the constraints need to be set with knowledge of what streams will be sent *before* connection.

However, to make this easier, I will send in a PR so the new constraints format is converted to the old format, as [some browsers don't support the new standards](https://stackoverflow.com/questions/27830810/webrtc-getting-malformed-constraints-object-from-chrome-but-not-firefox).

**Comment by feross** [comment]
Alright, closing, as this cant' be fixed in `simple-peer`.

**Comment by izakgl** [comment]
For anyone coming here from google. Since version 9.3.0 the options offerConstraints and answerConstraints are now named offerOptions and answerOptions respectively.

**Comment by t-mullen** [comment]
You don't need to specify constraints as of `9.3.0` for streams to be received, it "just works" now.

Constraints options in `offerOptions` and `answerOptions` will be silently ignored since transceivers have no use for them, hence the change in name.

**Comment by izakgl** [comment]
Well I had a similar problem as the OP. Initiator only streamed audio and the other side streamed video and audio. Without specifying the `offerOptions` I only received audio track on initiator side. When I added `offerToReceiveVideo: true` it started working.

**Comment by toxaq** [comment]
> You don't need to specify constraints as of `9.3.0` for streams to be received, it "just works" now.
> 
> Constraints options in `offerOptions` and `answerOptions` will be silently ignored since transceivers have no use for them, hence the change in name.

I'm using 9.6 and requesting a video stream did not work without answerOptions and offerOptions?

**Comment by nazar-pc** [comment]
@toxaq I do not understand what exactly is your question, but it would be better if you create a separate issue if you have any problems rather than commenting in an old ticket.

**Comment by toxaq** [comment]
@nazar-pc it's a reply to @t-mullen stating that as of 9.3 "you don't need to specify constraints" - "it just works". That was not my experience and I'm running 9.6.

**Comment by ricardopolo** [comment]
Same experience from @toxaq
