### ISSUE TITLE
ICE failed even after turn server is added.

### ISSUE THREAD

**Issue by techleadzdevteam** [feross/simple-peer#96]
I have integrated the turn server in my application as I discussed this matter with you,but still the same error is showing and the peer disconnected.
This is the error that is showing in the firefox console.

ICE failed, see about:webrtc for more details
Have a look at my code.

```
 var ICE_config = {"iceServers": [{"url": "stun:turn.bit6.com"},
     {"url":"turn:turn.bit6.com:3478?transport=udp","username":"secret","credential":"secret"},
     {"url":"turn:turn.bit6.com:443?transport=tcp","username":"secret","credential":"secret"}           
                        ]};


```

ice failed:see webrtc:about for more details
this is the ice stats from the webrtc:about mozilla firefox browser

![screenshot_2](https://cloud.githubusercontent.com/assets/21102134/19531769/61266ad8-9652-11e6-98af-ffe0bdab44f1.png)

Even the turnserver is realying but still the error occurs..

Kindly help me about this issue.thanks

**Comment by gnunicorn** [comment]
hey @techleadzdevteam , could you try using `urls` instead of `url`. Looks like that might be a typo in the docs, because the keys in the [MDN spec refers to `urls`](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration) (with the `s`) – why ever ...

**Comment by techleadzdevteam** [comment]
I have try urls instead of url but the same result

![screenshot_2](https://cloud.githubusercontent.com/assets/21102134/19779333/112725f6-9c9a-11e6-9e9d-b7603e67207d.png)

**Comment by feross** [comment]
> @gnunicorn Looks like that might be a typo in the docs

The spec used to say `url` but it changed to `urls` at some point. I'll update the docs.

**Comment by feross** [comment]
@techleadzdevteam Don't spam issues with comments begging for help. This is not a support forum. You can try StackOverflow for that.
