### ISSUE TITLE
Can't receive large payloads

### ISSUE THREAD

**Issue by troq** [feross/simple-peer#97]
I'm using simple-peer to send javascript objects like so `peer.send(JSON.stringify(myObj))` and decoding them on the receiving end using `JSON.parse(data)`. The issue is when `myObj` is very large, the data is chunked and calling `JSON.parse(data)` on the chunked data fails (for obvious reasons). How can I disable chunking for large objects so `JSON.parse` works again?

**Comment by drywet** [comment]
Chunking can't be disabled. Practical maximum for the chunk size is something like 16 * 1024 bytes.
You should chunk it yourself and use framing or use some high-level streaming messaging like mux-demux.
https://github.com/tjgq/node-stream-throttle

**Comment by feross** [comment]
Yep, what @drywet said.
