### ISSUE TITLE
Remove unambiguity between a stream and a track?

### ISSUE THREAD

**Issue by vespakoen** [feross/simple-peer#98]
Hey!

I added a shim (webrtc/adapter) to try to make simple-peer work in Firefox, it seems it patched chrome to have the 'ontrack' handler, and now `.on('stream', cb)` fires twice.

I guess I now receive the seperate tracks.

Perhaps it would be nice to add a note about this to the readme? it left me confused for quite a while.

Perhaps we can change the 'change' event to becoma a 'track' event on [this line](https://github.com/feross/simple-peer/blob/master/index.js#L582)?

**Comment by techleadzdevteam** [comment]
Hi,
Hope that you will be good.Can you please help me regarding the issue #96

I will be very thankfull to you.

Thanks

**Comment by feross** [comment]
It looks like the hyperlink in your issue isn't valid anymore (the code has changed). Pro-tip: when you select a line, hit the 'Y' key to turn it into a permalink before sharing!

If I understand correctly, you're suggesting we emit a 'stream' event in some browser and a 'track' event in others. I'd rather just emit a single event for all browsers.

Also, I'm a little confused about how the original issue could happen, as [there's an if-else block here](https://github.com/feross/simple-peer/blob/c3eed3e538bb1364f9ceea619c27570d95c7c510/index.js#L92-L102), so either the `ontrack` code runs, or the `onaddstream` code, but never both.
