### ISSUE TITLE
Feature Request: include ObjectRTC browsers

### ISSUE THREAD

**Issue by smatthews1999** [feross/simple-peer#99]
Would it be possible to include ObjectRTC Browsers such as Edge?

**Comment by xuset** [comment]
As far as I know, ObjectRTC has the DataChannel defined in the spec, but Edge has not implemented support for DataChannels yet. Without DataChannels, I don't think it's possible to add support for ORTC in simple-peer.

**Comment by feross** [comment]
Edge hasn't implemented support for data channels. When they do, we should support it.

**Comment by smatthews1999** [comment]
Thank you!
